TeamNewPipe/NewPipe

- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
I have added a line saying that the Dutch XML file is UTF-8, because of the ü character, as I am not sure how Android deals with this. Please ensure the Dutch version does not crash.
Also, would you consider adding NewPipe to Weblate? It is Free of charge for Free Software projects, it is fully Free itself and F-Droid uses it as well: https://weblate.org/en/hosting/.
> Add Dutch translation

- app/src/main/java/org/schabi/newpipe/ActionBarHandler.java
This makes the external player experience nicer.
I had to set the title twice on the intent, since "Intent.EXTRA_TITLE" didn't work on MX Player. (MX Player's supported intent data is here: https://sites.google.com/site/mxvpen/api).
I think I did that correctly. Anyhow, it works. :)
> Set the title for external video players

- app/src/main/java/org/schabi/newpipe/VideoItemListFragment.java
- app/src/main/java/org/schabi/newpipe/VideoListAdapter.java
+ Remove deprecated method from app/src/main/java/org/schabi/newpipe/VideoItemListFragment.java
onAttach(Activity activity) is replaced by onAttach(Context context)
+ Remove deprecated method from pp/src/main/java/org/schabi/newpipe/VideoListAdapter.java
context.getResource().getColor(resId) is replaced by ContextCompat.getColor(context,resId)
> Remove Deprecated methods

- app/src/main/java/org/schabi/newpipe/SearchEngine.java
- app/src/main/java/org/schabi/newpipe/youtube/YoutubeSearchEngine.java
+ Added interface method in for search suggestion list in [SearchEngine.java](https://github.com/joshsoftware/NewPipe/blob/feature_search_suggestion/app/src/main/java/org/schabi/newpipe/SearchEngine.java) & implement that in [YoutubeSearchEngine.java](https://github.com/joshsoftware/NewPipe/blob/feature_search_suggestion/app/src/main/java/org/schabi/newpipe/youtube/YoutubeSearchEngine.java)
+ That method returns List of suggestion data.
+ Also Added listener for SearchView [SearchView.OnSuggestionListener](http://developer.android.com/reference/android/widget/SearchView.OnSuggestionListener.html) in VideoItemListActivity.java
+ I am only commiting 2 files as of now so that @medavox  & I can resolve merge conflict in this two file.
> Feature search suggestion (enhancement)

- app/src/main/java/org/schabi/newpipe/VideoItemDetailFragment.java
The method to parse a date with spliting a string, that was used before, was actually buggy and showed one month ahead of actual upload date in the layout, e.g. Sep 18, 2015 instead of Aug 18, 2015
SimpleDateFormat was used instead.
>  fix bug with upload date + better way to parse it

- app/src/main/res/values/strings.xml
Apart from app name, which at the moment is the same no matter what language, there are URLs here. They shouldn't reside here (URLs) but they (including app name) should be made at least "translatable=false".
> Make some strings non-translatable

- contributing.md
Contribution guidelines are a helpful way to inform new potential
contributors about the way in which they can help with the project.
It's also a helpful way to enforce some consistent coding style and
quality among the contributions.
> Add contribution guidelines

- app/src/main/java/org/schabi/newpipe/DownloadDialog.java
Added new variable *final File* **dir** with value of key
"*download_path_preference*" or *externalStorageDirectory*().
Firstly I check if directory **dir** exits, then eventually try to create it and then download file.
> Added check if directory exist and try create it

- app/src/main/java/org/schabi/newpipe/services/VideoExtractor.java
- app/src/main/java/org/schabi/newpipe/services/youtube/YoutubeVideoExtractor.java
Just noticed this today when testing the experimental audio player with Gangnam Style.
The patch plays well with view_count field of AbstractVideoInfo class as it is already of type long.
> Fix view count parsing for large numbers

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/ExitActivity.java
- app/src/main/java/org/schabi/newpipe/PanicResponderActivity.java
This is a great app, I'm very excited to see a free software youtube player, and I like the nice, simple UI!
We (Guardian Project) have been developing "panic button" features in our apps for years, and now we are working to make a more flexible and open ecosystem of apps that can both trigger other apps, or respond to triggers. Since many people search for private topics on youtube, NewPipe is a natural panic responder app. This setup allows for easy configuration of a single trigger action which can then trigger multiple apps.
This single commit wipes NewPipe from the Recent Apps then exits when it is responding to a panic trigger.  Since NewPipe does not currently save the searches or current video, that has the effect of clearing the history.  Once NewPipe does save history, this will …
> allow "panic button" apps to wipe activity

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/Downloader.java
- app/src/main/java/org/schabi/newpipe/PlayVideoActivity.java
- app/src/main/java/org/schabi/newpipe/SettingsActivity.java
- app/src/main/java/org/schabi/newpipe/VideoItemDetailActivity.java
- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings_screen.xml
I started with @gjedeer 's work and then worked on making Tor support more tightly integrated.  Since `DownloadManager` does not let you set the proxy settings, I wrote a basic, custom download manager for downloading over Tor.  This does not touch the video streaming at all, so with "Use Tor" enabled, video streaming will not go over Tor.  That'll require ExoPlayer, I think.
Ideally, NewPipe would represent the state of Tor in the UI somehow.  Orbot will broadcast out the status, and its easy to receive that with a `BroadcastReceiver`.  The open question is how to represent the state of Tor in the UX.  The states are `OFF, STARTING, ON, STOPPING`.
> Tor support for all except streaming

- app/src/main/java/org/schabi/newpipe/DownloadDialog.java
The application should ask the user for the ```WRITE_EXTERNAL_STORAGE``` permission before downloading a video in order to avoid a ```java.lang.SecurityException``` on devices running Android 6.0 (this happened in issue #143).
> Fixed #143

- app/src/main/java/org/schabi/newpipe/VideoItemDetailFragment.java
Auto playing the video depends on the ActionBar being setup before trying.
> Fix ArrayIndexOutOfBoundsException when using autoplay

- app/src/main/java/org/schabi/newpipe/Localization.java
- app/src/main/java/org/schabi/newpipe/NewPipeSettings.java
- app/src/main/java/org/schabi/newpipe/extractor/DashMpdParser.java
- app/src/main/java/org/schabi/newpipe/extractor/Parser.java
- app/src/main/java/org/schabi/newpipe/extractor/ServiceList.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java
squid:S1118 - Utility classes should not have public constructors.
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Faisal Hameed
> Code quality fix - Utility classes should not have public constructors.

- app/src/main/java/org/schabi/newpipe/VideoInfoItemViewCreator.java
- app/src/main/java/org/schabi/newpipe/VideoItemDetailFragment.java
- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
- app/src/main/java/org/schabi/newpipe/extractor/Parser.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
squid:S00117- Local variable and method parameter names should comply with a naming convention.
https://dev.eclipse.org/sonar/rules/show/squid:S00117
Faisal Hameed
> Code quality fix - Local variable and method parameter names should comply with a naming convention.

- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PlayVideoActivity.java
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Faisal Hameed
> Code quality fix - Useless parentheses around expressions should be removed to prevent any misunderstanding.

- app/src/main/java/org/schabi/newpipe/extractor/AudioStream.java
- app/src/main/java/org/schabi/newpipe/extractor/VideoStream.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
squid:S2259- Null pointers should not be dereferenced.
https://dev.eclipse.org/sonar/rules/show/squid:S2259
Faisal Hameed
> Code quality fix - Null pointers should not be dereferenced.

- app/src/androidTest/java/org/schabi/newpipe/extractor/youtube/YoutubeSearchEngineTest.java
- app/src/main/java/org/schabi/newpipe/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/extractor/StreamInfo.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S1155 - Collection.isEmpty() should be used to test for emptiness. 
squid:S2293 - The diamond operator ("<>") should be used. 
squid:S1488 - Local Variables should not be declared and then immediately returned or thrown. 
https://dev.eclipse.org/sonar/rules/show/squid:S1155
https://dev.eclipse.org/sonar/rules/show/squid:S2293
https://dev.eclipse.org/sonar/rules/show/squid:S1488
Faisal Hameed
> General code quality fix-2

- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-eu/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sr/strings.xml
- app/src/main/res/values-uk/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rHK/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
The following 4 commits fix common mistakes in the UI strings:
Periods, colons and other unnecessary punctuations should not be used in labels.
See https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation
Why? See http://english.stackexchange.com/questions/128996/how-would-one-know-when-to-choose-preferred-or-preferable
"Download path video" -> "Video download path"
"Download path audio" -> "Audio download path"
"Default Resolution" -> "Default resolution"
See https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation
> Let's tweak the UI strings a bit

- app/src/main/java/org/schabi/newpipe/VideoInfoItemViewCreator.java
Hi,
The bug will not surface itself as we have an up-loader all the times, but it indeed is a bug as we were hiding itemDurationView when itemUploaderView was empty.
> Fix to hide uploader correctly

- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sr/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rHK/strings.xml
- gradle/wrapper/gradle-wrapper.properties
https://travis-ci.org/theScrabi/NewPipe indicate gradle 2.10 is required.
FAILURE: Build failed with an exception.
Where: Build file '/home/travis/build/theScrabi/NewPipe/app/build.gradle' line: 1
What went wrong: A problem occurred evaluating project ':app'. > Failed to apply plugin [id 'com.android.application'] > Gradle version 2.10 is required. Current version is 2.4. If using the gradle wrapper, try editing the distributionUrl in /home/travis/build/theScrabi/NewPipe/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
Also fixed compile errors: AAPT: Error parsing XML: prefix must not be bound to one of the reserved namespace names
The xml namespace should be defined in root element.
> Upgrade gradle wrapper to 2.10 and fix compile errors.

- app/src/main/java/us/shandian/giga/get/DownloadManager.java
- app/src/main/java/us/shandian/giga/get/DownloadMission.java
squid:S2333 - Redundant modifiers should not be used.
https://dev.eclipse.org/sonar/rules/show/squid:S2333
Faisal Hameed
> Code quality fix - Redundant modifiers should not be used.

- app/src/main/java/us/shandian/giga/util/CrashHandler.java
squid:S1444 - "public static" fields should be constant
https://dev.eclipse.org/sonar/rules/show/squid:S1444
Faisal Hameed
> Code quality fix - "public static" fields should be constant.

- app/src/androidTest/java/org/schabi/newpipe/extractor/youtube/YoutubeSearchEngineTest.java
- app/src/main/java/org/schabi/newpipe/SuggestionListAdapter.java
- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
- app/src/main/java/org/schabi/newpipe/extractor/SearchEngine.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeSearchEngine.java
- app/src/main/java/us/shandian/giga/get/DownloadMission.java
squid:S1319 - Declarations should use Java collection interfaces such as "List" rather than specific implementation.
https://dev.eclipse.org/sonar/rules/show/squid:S1319
Faisal Hameed
> Code quality fix - Declarations should use Java collection interfaces such as "List" rather than specific implementation.

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/detail/ActionBarHandler.java
- app/src/main/java/org/schabi/newpipe/detail/VideoItemDetailActivity.java
This makes sure VideoItemDetailActivity is always started as a seperate app, and is displayed in recent apps seperately.
Changes in VideoItemDetailActivity are necessary to replace the existing video/fragment with the new one.
The change in ActionBarHandler was required to avoid a crash when opening a new video from a different app.
> Launch video player in single task mode

- app/src/main/res/values-de-rCH/strings.xml
Hello
I realized I accidental opened a new translation "de-rCH" on Weblat, but I don't think it makes sense to add it because its basically the same as German. Also it's empty. 
Otherwise I would recommend to copy the German part to Swiss German.
Regards
> Delete Swiss High German translation

- .travis.yml
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeSearchEngine.java
Fix for  #388:
Google begins with page 1 so we can add 1 to the page before creating the URL.
I've tested it on my Phone and it worked.
Examples:
https://www.youtube.com/results?search_query=test&page=0&filters=video
is the same as 
https://www.youtube.com/results?search_query=test&page=1&filters=video
but
https://www.youtube.com/results?search_query=test&page=2&filters=video
is different
> Fix dublicated results

- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeChannelExtractor.java
When opening a channel i get an error.
The error is caused by matching all characters greedy which results the next parentheses to match:
```
java.io.FileNotFoundException: https://yt3.ggpht.com/ZENp6vo0Y1Brsnshet01VoLrhwa-73XUlsyVayXHaBA6IhmabLghw4NjeJS4qAF61CQxkNJqNpU=w1060-fcrop64=1,00005a57ffffa5a8-nd-c0xffffffff-rj-k-no)%3B%20%20%7D%20%20@media%20screen%20and%20(-webkit-min-device-pixel-ratio:%201.5),%20%20%20%20%20%20%20%20%20screen%20and%20(min-resolution:%201.5dppx)%20%7B#c4-header-bg-container%20%7B%20%20%20%20%20%20%20%20background-image:%20url(//yt3.ggpht.com/ZENp6vo0Y1Brsnshet01VoLrhwa-73XUlsyVayXHaBA6IhmabLghw4NjeJS4qAF61CQxkNJqNpU=w2120-fcrop64=1,00005a57ffffa5a8-nd-c0xffffffff-rj-k-no)%3B%20%20%20%20%7D%20%20%7D#c4-header-bg-container%20.hd-banner-image%20%7B%20%20%20%20%20% …
```
> Fix banner extaction

- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
- app/src/main/java/org/schabi/newpipe/detail/StreamInfoWorker.java
- app/src/main/java/org/schabi/newpipe/detail/VideoItemDetailFragment.java
- app/src/main/java/org/schabi/newpipe/search_fragment/SearchInfoItemFragment.java
- app/src/main/res/values/strings.xml
This pull request fixes the following issues from first reCaptcha integration ( #387 ).
> After exiting the reCaptcha activity, I need to re-click on the search field to refresh the query.
Fixed.
> If I click from outside Newpipe Application on a Youtube link the reCaptcha exception is thrown but the activity is not started.
Fixed.
I change the way of starting reCaptchaActivity, using startActivityForResult() and onActivityResult().
> Improve reCaptcha integration

- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
on my android-4.2 (api-17) NewPipe-0.8.8 and 0.8.9 crashes with nullpointer-exception when openinge the "Downloads"
reason: in api < 23 Fragment.onAttach(Context)  is never called by android  so mActivity is null
fix: re add deprecated Fragment.onAttach(Activity) which exist since api-11 that will set mActivity instead.
> fix NullPointerExcpeption when opening "Downloads" with android-api < 23

- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamUrlIdHandler.java
- app/src/test/java/org/schabi/newpipe/extractor/services/youtube/youtube/YoutubeStreamUrlIdHandlerTest.java
Just discovered that some of the links `https://www.youtube.com/shared?ci=` works and others don't, like:
https://www.youtube.com/shared?ci=FM7MFYoylVs
https://www.youtube.com/shared?ci=8A940MXKFmQ
So I changed the test to the working one.
And the bug in the `YoutubeStreamUrlIdHandler`, was that it was passing a lowercase URL to the checking method, which obviously failed.
> Fix travis and YoutubeStreamUrlIdHandler

- app/src/main/java/org/schabi/newpipe/settings/SettingsFragment.java
- app/src/main/res/values/strings.xml
Hey,
This pull request implements a dialog asking if the user want to restart the application when the theme changes.
- Added necessary strings on resource file
- Remove some unused imports
- Only show the dialog when the selected theme it's not the current theme
> Add restart dialog on theme change

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- Fix #482
- When opening a invalid/deleted/unavailable video, the popup was just printing the error, now it shows a message to the user and exits
> Fix bug when fetching unavailable content

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/res/layout/player_popup.xml
- app/src/main/res/values-sw600dp/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
- Resizable popup
- You can enter in resize-mode when you longpress one of the sides of the popup
- Remember/save the popup position and size 
- Fix bug occurring after screen rotation
- Check if position is greater than the bounds of the (new sized) screen
> Implement resizable popup

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
After closing a player (popup in this case), and the image loader was still loading, `onLoadingComplete` is still being called and the notification control was being created after the popup was destroyed (getting stuck, user cannot close it) as the `loadImage` task is not cancelled, and we cannot cancel these with the current imageloader.
And that's one more reason that we **still** need to change it, the one that we are using (UIL) is discontinued since 2015.
> Fix image loading bug

- app/src/main/java/org/schabi/newpipe/fragments/detail/ActionBarHandler.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Live settings changes (Show Higher Resolutions and such) are already available, but this PR implement an update to the visibility of some toolbar/menu items (like the Play on Kodi) that I forgot to add originally.
> Update menu items after change in settings

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/res/layout/activity_main_player.xml
When a video was finished or paused, the screen wouldn't turn off, then if a user forgot that is paused or the video is finished, the screen would stay on and drain up the battery.
- Fixes #511
> Fix keep screen on

- app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
The settings wasn't saving the state on screen rotation.
- Fixes #419, fixes #418
> Fix settings on screen rotation

- app/src/main/res/values/settings_keys.xml
Set the popup default resolution as the normal player default.
- Fix #558
> Change popup default resolution

- app/src/main/java/org/schabi/newpipe/settings/SettingsFragment.java
This fixes the URL encoding artifacts encountered when selecting folders with non-url characters.
Instead of stripping the trailing 'file:/' just call the getPath method.
> Fix download path handling (#580)

- app/src/main/AndroidManifest.xml
- app/src/main/assets/apache2.html
- app/src/main/assets/gpl_2.html
- app/src/main/assets/gpl_3.html
- app/src/main/assets/mit.html
- app/src/main/assets/mpl2.html
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/about/License.java
- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- app/src/main/java/org/schabi/newpipe/about/SoftwareComponent.java
- app/src/main/java/org/schabi/newpipe/about/StandardLicenses.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/layout/fragment_about.xml
- app/src/main/res/layout/fragment_licenses.xml
- app/src/main/res/layout/item_software_component.xml
- app/src/main/res/menu/main_menu.xml
- app/src/main/res/menu/menu_about.xml
- app/src/main/res/menu/software_component.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
I have created a about activity which includes the following information:
* NewPipe's License
Maybe this should include something like `(c) 2017 by ...` or similar. 
* Note on how to contribute and a link to GitHub
* Copyright of the software components used including full license texts
**Additional ideas**
* Donate button
* Tab containing the "privacy policy":
* What data is sent to YouTube
* What data is included in the crash reports
**Implementation Notes**
The software components list is created by inflating the layout and adding it to the `LinearLayout` because I couldn't get it working otherwise. `ListView` doesn't support the `NestedScrollingView` scroll behavior and I didn't get the `RecyclerView` to handle the context menu correctly (+ the scrolling needs to be disabled). …
> Add about activity

- app/src/main/res/values/strings.xml
Realized that I made the GitHub-URL translatable.
> Make github_url not translatable

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Added a line to only link web URLs. Before this the links for time were linked and created an Intent with the data "#" which caused an `ActivityNotFoundException` (Fixes #632). 
I think it would be nice to implement support for times but with the current links it wont work.
> Prevent "time links" from beeing clicked

- app/build.gradle
- app/src/main/java/us/shandian/giga/ui/common/ToolbarActivity.java
- build.gradle
This change bumps the target version to Android O and changes the deprecated ActionBarActivity (now removed) to AppCompatActivity.
Because support libraries 26+ are now hosted on 'maven.google.com', as seen [here](https://developer.android.com/topic/libraries/support-library/setup.html) and [here](https://stackoverflow.com/questions/45103230/failed-to-resolve-com-android-supportcardview-v726-0-0-android), this endpoint is added as part of our dependency repository. 
Support library version 26+ is also needed for later versions of Room Persistence used in #620.
Note: Currently the CI test is failing because it uses build tool version 25.
> Upgrade target sdk and support library version to 26

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Ignoring non-transient audio focus loss, so multiple streams can play at the same time.
Also added the option to resume background audio on audio focus regain (say, after a phone call interruption). However, this option only works on background audio and popup/main video player will not resume.
Perhaps I should categorize these settings under experimental rather than video and audio.
Let me know what you guys think.
> Added option to ignore permanent audio focus loss

- .travis.yml
- build.gradle
Hey there, 
Using `google()` in the buildscript block is going to become needed for Android Studio 3.0, so might as well add it now!
> Use google() in buildscript

- app/src/main/java/us/shandian/giga/get/DownloadManagerImpl.java
- app/src/test/java/us/shandian/giga/get/DownloadManagerImplTest.java
The line `(int) (o1.timestamp - o2.timestamp)` causes errors. Replacing this with the Java default comparison should fix this issue.
PS: Is this how I should create fixes for sentry entries?
> Use correct long comparison (fixes #726)

- app/src/main/res/values/strings.xml
The rationale being audio-files can currently also be "viewed".
> Spelling: View → Play

- app/src/main/res/xml/provider_paths.xml
Use undocumented root-path element to the file providers paths. See https://stackoverflow.com/a/37807813/7026879 for why this solution might work.
To do:
> [WIP] Add root-path /storage (fixes #707)

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
In #784 I corrected a typo: 
`<string name="service_kosk_string">%1$s/%2$s</string>` => `<string name="service_kiosk_string" translatable="false">%1$s/%2$s</string>`
While I did this some more users translated the false string on wablate. They got merged later and now cause a warning: `Warning:string 'service_kosk_string' has no default translation.` This PR removes them.
> Remove unused "service_kosk_string" strings

- app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
Since AdaptiveIcon is used, the Drawable for notification got in DownloadManagerService is no loger `BitmapDrawable`. This PR fixes the crash when user hit download page on Android 8.0+ devices.
> Fixes ClassCastException when getting Bitmap from AdaptiveIcon

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/res/values/settings_keys.xml
This makes NewPipePlayer remember its last screen orientation when locking the screen orientation globally, like I suggested here:https://github.com/TeamNewPipe/NewPipe/issues/894
> remember last screen orientation

- .travis.yml
- app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
The update of the extractor changed the signature of the `VideoStream` and `VideoStream`. I've changed the test accordingly.
**Update**: Also fixes installation of Android components in Travis CI
> Fix failing test

- CheckTranslations.java
- fixplurals.sh
@theScrabi Here is the update for the script, so you don't have to do it manually. You just could have waited a little longer and you'd have saved some time ;)
> Fix crash due to no "other" item in plurals

- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
I've added a subject argument to the `shareUrl` method.
Here some examples screenshots for when the playlist/channel/video is shared with firefox:
> Add subject to shared URL's (fixes #975)

- app/src/main/java/org/schabi/newpipe/MainActivity.java
Control media volume with the hardware buttons in the MainActivity. This is how the YouTube app works. Closes #1072.
> Control media volume with the hardware buttons.

- app/build.gradle
- app/src/debug/java/org/schabi/newpipe/DebugApp.java
- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/BaseFragment.java
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/res/menu/debug_menu.xml
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
This PR adds LeakCanary for detecting memory leaks.
As you can see, we have many things that needs patching up. Even though these leaks are small, they can quickly add up on older devices. The only downside to this is the dependency dumps the heap from time to time and will hog the app for a few seconds, hence why it is debug build only.
> Leak Canary

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/Downloader.java
- app/src/main/java/org/schabi/newpipe/ImageDownloader.java
This makes it easier to implement proxy support later.
> Use OkHttp with UIL

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
I've just added a MediaButtonReceiver which handles Play/Pause Next and Previous actions in the background player.
So basically now you can control the player from headset buttons which I found really conveniant.
> Media Button Play/Pause, Previous and Next in Background Player

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/playlist/PlayQueueItem.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Issue #861 
This fixes the starting time for videos opened in the video player. This wasn't working before because:
1. The url was cleaned immediately upon opening, removing the time info. This isn't necessary because NewPipeExtractor should clean urls on its own anyways
2. PlayQueueItem used a transient Single to store the StreamInfo, and it regenerated the Single with only the url, not all of the information.
I fixed these issues by not cleaning the url initially, and storing StreamInfo with PlayQueueItems. This solution works for links opened with the Background, Video, and Popup players.
I've tested this change with a variety of link types and it works with youtube and soundcloud links
> Handle links with time specified (ex. &t=xxx)

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/appearance_settings.xml
Follow-up to #1286. This PR changes the caption view to use styles set in the captioning manager (i.e. Android Settings -> Accessibility -> Captions, or Newpipe Settings -> Appearance -> Caption). Here are some sample with transparent text background:
> Caption Style Management

- app/src/main/res/values/settings_keys.xml
Fix #1345 Gradle build fails with "error: unescaped apostrophe in string"
> Fix #1345 Gradle build fails 

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
This PR changes how double-tap for the main player works:
Now, double-tapping the middle third of the screen will pause the video, while rewind / fast forward are on the left third / right third of the screen, respectively.
The reason is, that currently there is no practical way to pause the video fast: When you want to pause playback, you need to tap the screen, wait for the controls to fade in, and then finally press pause. But if you tap the center (where the pause button fades in) too fast, it will be recognized as a double-tap gesture, which will trigger a **seek**, although you tapped the center of the screen and actually wanted to pause the video. This is probably not what you expect, so this PR attempts to change this behaviour to something more natural.
Another idea, which I did …
> Double-tap the middle of the player screen to pause the video

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/ZipHelper.java
- app/src/main/res/values/strings.xml
Alright, this actually seems to work now! I haven't encountered any issues with this yet, but I will continue testing it because exports feel quite important. I hope someone else can also confirm there are no issues.
Anyways, I had to change how ZipHelper.extractFileFromZip works because it was broken and always returned true and also didn't work for the same ZipInputStream more than once. It now uses the filepath, but as the function isn't used outside of ContentSettingsFragment.java this won't be an issue. 
The exports now contain a new file called newpipe.settings. If while importing it is detected, it will trigger a second dialog asking if to import settings too. If you press Ok it will import the settings from there.
#849
> Settings export

- app/src/main/java/us/shandian/giga/get/DownloadMission.java
- app/src/main/java/us/shandian/giga/util/Utility.java
#1355 introduced a bug, which results in a crash, when you open the "Downloads" Activity with paused, unfinished items:
When a DownloadMission gets written to a file via the Serialization API, the member mListeners is not serialized, because it is marked as _transient_. After restoring, mListeners is null, resulting in a NullPointerException in DownloadMission.java:234.
This Pull Request also improves the performance of downloads by wrapping the FileOutputStream in Utility.writeToFile in a BufferedOutputStream, resulting in less system calls.
> Downloader: Fix crash on loading unfinished downloads from .giga files

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/util/ListHelper.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/video_audio_settings.xml
- app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
Fixes #1259 
This limits the user's default video resolution when not connected to WiFi. The user can choose "No Limit"(default) or a specified resolution ("144p" for example). When active the audio stream with the lowest bitrate is also chosen. This differs from the proposed design due to complexity concerns. For example, supporting a "No Video" option would have required a lot of changes to be implemented cleanly.
- Changes to Settings video & audio settings
- Added mobile data resolution limit drop down
- Changes to ListHelper:
- Automatically limits the *default* resolution based on user's resolution limit settings. Direct changes to video resolution (from within the player) will not be limited.
- Automatically limits the *default* audio bitrate to the lowest available stream if …
> Added the ability to limit video quality if using mobile data.

- app/proguard-rules.pro
This is a fixup for #1407 , which fixes the crash in release builds, too. It keeps Proguard from removing the new method "private void readObject(java.io.ObjectInputStream)", which is only called by the VM, but not from the code, and therefore considered useless by Proguard in release (minify) mode.
This PR adds some new Proguard rules to keep class members related to serialization for Serializable classes like DownloadMission.
> Downloader: Fix crash on loading unfinished downloads from .giga files (Fixup for release builds)

- app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
This improves downloading performance dramatically when the download is cpu bound:
For example, a Galaxy S4 with its 2013 high-end CPU only reaches around 1MB/s, with all cores running at its maximum (and overheating).
By inreasing the chunk size, at which download threads notify its progress (and persist its current state) from only 512 Bytes to 64 KiB, the S4 can easily saturate a 50 MBit/s connection (the maximum I could test).
> Downloader: Improve performance for weaker CPUs

- app/src/main/res/layout/fragment_video_detail.xml
This fixes bug #1440 Broken Video Info Layout and partially reverts pull request #1371 Reduce Overdraw in doing so.
> Fix #1440 Broken Video Info Layout

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/video_audio_settings.xml
Here is a quick implementation for request #1334, added as toggleable in Settings -> Video & Audio.
However, I'm not particularly fond of this implementation as it performs the switch based on the `onStop` lifecycle event, which will occur on:
- back button pressed -- expected behavior
- home button pressed -- expected behavior
- screen turned off -- expected behavior
- other activity starts (open up settings) -- expected behavior
- navigation/overview button pressed -- maybe unexpected behavior
- entering multiwindow mode (long press overview button) -- unexpected behavior
- (many more possibilities, but mostly when the player activity is actively killed by the user)
Since this implementation uses the existing player switching method, the switching is just going to be as slow …
> Minimize main player on exit

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- [#1412] Fixed repeat mode causing player NPE when new intent is received while player activity is in background.
- Fixed minimizing player to popup does not destroy player when popup permission is not granted.
> Main video player fix

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
This updates bumps the version of a few libraries and was part of #1392, but since it is isolated enough, I've decided to pull it out.
Starting from version 1.1.0, Room db changes its journal file into two separate accessory files, namely db-wal and db-shm. These files do not store any important data after a checkpoint or db connection closes. However, when importing new databases, if any of the accessory files do not match, the existing core database will be wiped. So, in order to provide backward compatibility, I've decided to remove all accessory files when a database is imported. 
The only problem is that, if the database of a newer version needs to be imported to a version before this PR, then the user needs to manually clear the app data from the system settings. @theScrabi What do …
> Library version update and database backup fix

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PlayerState.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/FailedMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSourcePlaylist.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/PlaceholderMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
- app/src/main/java/org/schabi/newpipe/player/playback/PlaybackListener.java
- app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java
- app/src/main/java/org/schabi/newpipe/player/resolver/MediaSourceTag.java
- app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
- app/src/main/java/org/schabi/newpipe/player/resolver/Resolver.java
- app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/res/layout/activity_main_player.xml
- app/src/main/res/layout/dialog_playback_parameter.xml
- app/src/main/res/layout/player_popup.xml
- app/src/main/res/layout/statistic_playlist_control.xml
- app/src/main/res/values/strings.xml
This update bumps the player library version and:
- Reworked the playback speed control dialog to support different step sizes for faster speed change.
- Added a toggle to fast-forward during silences in playback speed control. This should be helpful for audiobooks and certain music genres, and can bring a true seamless experience (and can break a song with lots of silences =\\).  
- Refactored media source resolution to allow passing metadata alongside media internally in the player, rather than doing so manually. Now we have a single source of metadata and is directly available when playback starts.
- Fixed remote playlist metadata not updating when new metadata is available when playlist fragment is opened.
- Various UI fixes: #1383, background player notification controls now always …
> ExoPlayer 2.8.2 Update

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/res/layout/player_popup.xml
- app/src/main/res/layout/player_popup_close_overlay.xml
- Add an overlay at the bottom of the screen that the user can drag the popup to, closing it.
A little demo showing how it works:
- Do not show the player controllers when moving, since the user have to click in the popup
anyway now (#1342).
---
Closes #658
Related #979, #1306
> New way to close the popup player

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/res/drawable/background_oval_black_transparent.xml
- app/src/main/res/drawable/ic_brightness_high_white_72dp.xml
- app/src/main/res/drawable/ic_brightness_low_white_72dp.xml
- app/src/main/res/drawable/ic_brightness_medium_white_72dp.xml
- app/src/main/res/drawable/ic_volume_down_white_72dp.xml
- app/src/main/res/drawable/ic_volume_mute_white_72dp.xml
- app/src/main/res/drawable/ic_volume_off_white_72dp.xml
- app/src/main/res/drawable/ic_volume_up_white_72dp.xml
- app/src/main/res/drawable/progress_circular_white.xml
- app/src/main/res/layout/activity_main_player.xml
Current gesture controls work but look like an afterthought. This PR introduces circular design with progress bar and material icons that changes depending on current value.
Demo:
Changed version seems to work without any problems.
> Gesture controls

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/download/ExtSDDownloadFailedActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
- app/src/main/java/org/schabi/newpipe/report/UserAction.java
- app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/us/shandian/giga/get/DownloadManagerImpl.java
- app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- app/src/main/res/values/strings.xml
- build.gradle
This PR covers:
- Fix Cyclic search result  #1562
- Fix Seek bar not statically lay outed
- Fix YT Premium video are not blocked correctly
- Fix Videos sometimes not loading (due to DASH parsing)
- Fix links in video description
- Show warning when someone tries to download to external sdcard
- fix nothing shown exception triggers report
-  thumbnail not shown in background player for android 8.1 [see here](https://github.com/TeamNewPipe/NewPipe/issues/943)
> Refactor and bugfix

- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- app/src/main/res/layout/mission_item_linear.xml
- app/src/main/res/menu/download_menu.xml
- app/src/main/res/values/strings.xml
Hey NewPipe team, thanks for the great app. As an expat living in China, I really value the ability to download YT videos then play them later without having to stream them over a VPN. One issue I've had though is that the Downloads activity is pretty bareboned, and oftentimes I can't even read the full video title. I've enabled a toolbar item in the Downloads menu (most of the code was already there) to allow the user to switch between the grid and linear views. In the linear layout, the full video title should be displayed.
Do let me know if there are any issues - I'm certainly interested in continuing to contribute to NewPipe dev in the future.
> Enable linear layout in Downloads activity with full video names

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
> Enqueuing now triggers video playing if the play queue has already ended

- app/src/main/res/values/strings.xml
This change makes the heading of the "Bookmarks" tab more intuitive to the user by renaming it to "Bookmarked Playlists".  This addresses https://github.com/TeamNewPipe/NewPipe/issues/1772
Here is an example image of what this change looks like on an emulated Pixel XL:
> [Closes #1772] change 'tab_bookmarks' string to 'Bookmarked Playlists' for UI clarity

- app/src/main/AndroidManifest.xml
As discussed here https://developer.android.com/about/versions/pie/android-9.0-changes-28
Apps which target API 28+ must include foreground permission in the manifest. I first noted this issue today after trying NewPipe master on the Pixel 3 device. Confirmed exists also with API 28 in emulator.
- Fix foreground playback in android Pie API 28. Tested in emulator & Pixel 3 device.
- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
> Add foreground service permission for API 28+ devices

- app/src/main/java/org/schabi/newpipe/util/ListHelper.java
Fixes #1829.
When default resolution is set to best. The value of `resolution` is set to `best_resolution` here:
https://github.com/TeamNewPipe/NewPipe/blob/6fe3fdce112a617ed94d6b113146df8747ad74bb/app/src/main/java/org/schabi/newpipe/util/ListHelper.java#L108-L116
In the `if` branch however, `compareVideoStreamResolution` function expects values like `144p`, `480p`, etc. (but instead, the string `best_resolution` gets passed in `resolution`) and it is unable to parse it to an integer:
https://github.com/TeamNewPipe/NewPipe/blob/6fe3fdce112a617ed94d6b113146df8747ad74bb/app/src/main/java/org/schabi/newpipe/util/ListHelper.java#L393-L399
This PR workarounds it by checking whether the value of `resolution` is set to `best_resolution` before calling `compareVideoStreamResolution` in the `if` …
> Fix crash with default resolution set to best and limited mobile data resolution

- .github/CONTRIBUTING.md
Minor spelling correction of 'description'
> Correct 'description' spelling

- README.md
This will help cull the number of "how to update?" Issues whenever we need to push out a fix, like how recently NewPipe got completely broken.
This attempts to be an all-inclusive guide to updating NewPipe. If there are any (clean/official) links to additional info, please comment them and I will add it.
Also let me know if this section should be relocated within the README. I figured it would be best to keep it up top, so people see it right away, and then don't make a new Issue.
> Add updating section to README

- app/src/main/res/xml/appearance_settings.xml
- app/src/main/res/xml/content_settings.xml
- app/src/main/res/xml/debug_settings.xml
- app/src/main/res/xml/download_settings.xml
- app/src/main/res/xml/history_settings.xml
- app/src/main/res/xml/main_settings.xml
- app/src/main/res/xml/update_settings.xml
- app/src/main/res/xml/video_audio_settings.xml
There was previously a gap before every setting option (#1866).
Here's how it looks now:
> Fix padding in settings layout (Fixes #1866)

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
This happens while switching from pop-up to full-screen player. The reason is the thumbnail was loaded while the pop-up player is closed
> Fix random Popup player crash

- app/src/main/AndroidManifest.xml
The old player has been removed some time ago, but it was still in the manifest.
See https://github.com/TeamNewPipe/NewPipe/pull/1884 for more info on dropping support for Android 4.1 - 4.3.
CC @friendlyanon I guess you need to revert this commit in the legacy repo
> Remove old player from the manifest

- app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
Scenario: listening to a video on NewPipe over Bluetooth and a Notification Sound causes audio focus event AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK.
Problem: With the current implementation animateAudio does cause the audio to reach the DUCK_AUDIO_TO volume AFTER the notification sound is played, which is irritating and annoying.
Solution: animateAudio should just be used on focusGain where it is sensible to increase audio gradually. On ducking event the reaction should be immediate.
This very simple fix does this. Please approve.
> Fix delayed ducking of Audio

- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersionTask.java
1. check if cancel was called in onPrepare
2. if we currently don't have a Connection, don't show crash report dialogue to user
> Fixed CheckForNewAppVersionTask being executed when it shouldn't

- app/src/main/java/org/schabi/newpipe/fragments/EmptyFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/fragment_comments.xml
- app/src/main/res/layout/fragment_empty.xml
- app/src/main/res/layout/fragment_related_streams.xml
- app/src/main/res/layout/fragment_video_detail.xml
closes https://github.com/TeamNewPipe/NewPipe/issues/2174
> fixed scroll w/ comments and related streams disabled

- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
This pull requests complements pull request  #2178 by reducing general computational time for the method getTimeString.
On my local machine (Desktop PC with Java) my tests with a sample size of 10000 calls to the method with param 86400001 showed an average performance improvement of about 50%.
See sample code below to reproduce:
private static final StringBuilder stringBuilder = new StringBuilder();
private static final Formatter stringFormatter = new Formatter(stringBuilder, Locale.getDefault());
public static String getTimeString(int milliSeconds) {
int seconds = (milliSeconds % 60000) / 1000;
int minutes = (milliSeconds % 3600000) / 60000;
int hours = (milliSeconds % 86400000) / 3600000;
int days = (milliSeconds % (86400000 * 7)) / 86400000;
stringBuilder.setLength(0);
return days > 0 …
> Improve performance of getTimeString

- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
This pull requests intents to improve performance on Backgroundplayer while the screen is on.
In VideoPlayer the Duration String is cached effectively with the help of the playbackSeekBar(getMax() and setMax(). As the playbackSeekBar doesn't exist in BackgroundPlayer, using two additional variables will reduce performance impact of notification updates by almost 50% and thus perform similar to VideoPlayer.
This addresses issue #2170 and issue #1941.
> Cache duration String to improve performance

- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/SinglePlayQueue.java
- app/src/main/java/org/schabi/newpipe/util/CommentTextOnTouchListener.java
Fixes https://github.com/TeamNewPipe/NewPipe/pull/1968#pullrequestreview-212928929
> There are some problems with the popup player:
> 
> 1. start a video in popup mode by clicking on a timestep-link in a video description or comment
> 2. Notice the video repeating the first miliseconds again and again until some more of the video stream is buffered.
> 3. Let the video play for some seconds
> 4. Pause the video. Notice the current playback position is reset back to the point from where we started in 1.
> 
> In some cases this problem is even bigger.
> 
>  1. start a video in popup mode by clicking on a timestep-link in a video description or comment
>  2. start another video in popup mode by clicking on a timestep-link in a video description or comment
>  3. let the first video finish or …
> seek on clicking timestamp links in comments

- app/src/main/res/values/strings.xml
The wording for the Play/Enqueue commands is currently a little odd (introduced in commit 6167d5dbfc6de63c50d24fdbfa524ada48432c05):
```diff
-    <string name="enqueue_on_background">Enqueue on Background</string>
+    <string name="enqueue_on_background">Enqueue when backgrounded</string>
-    <string name="enqueue_on_popup">Enqueue on Popup</string>
+    <string name="enqueue_on_popup">Enqueue on new popup</string>
-    <string name="start_here_on_background">Start Here on Background</string>
+    <string name="start_here_on_background">Start here when backgrounded</string>
-    <string name="start_here_on_popup">Start Here on Popup</string>
+    <string name="start_here_on_popup">Start here on new popup</string>
```
This commit fixes them (eg: "Enqueue when backgrounded" is changed to …
> Fixed English translations for Play/Enqueue commands

- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
- app/src/main/res/layout-large-land/activity_main_player.xml
- app/src/main/res/layout/activity_main_player.xml
The button is placed in the upper right corner, under "more settings". No changes has been made to the popup video player (as for other things, there is no space for a share button).
The share button generates this text (for the video above at the current time):
```
TEST VIDEO
https://www.youtube.com/watch?v=C0DPdy98e4c&t=3
```
This implements #2000, but it does not give a chance of choosing whether to share the url normally or to at the current time. But as discussed in #2000 this is not a problem because there are already many other ways to do that.
The share utilities (i.e. `shareUrl()` and `openUrlInBrowser()`) were placed under the BaseStateFragment class. But since they have nothing to do with fragments, I moved them to a separate utilities class: `utils.ShareUtils`. This way they …
> Add "share at current time" button to the main video player

- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
closes #2393
this amends my obviously incomplete fix in PR #2311.
This is just an UI issue. Subtitle track selection and display of subtitle works. It just shows "No Captions" instead of the actual selected subtitle track name.
Sorry.
> Fixed selected subtitle track name not being shown

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
> Handle (auto)rotation changes during activity lifecycle

- app/src/main/java/us/shandian/giga/get/DownloadInitializer.java
- app/src/main/java/us/shandian/giga/get/DownloadMission.java
- app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
- app/src/main/java/us/shandian/giga/get/DownloadRunnableFallback.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
This PR re-write the download segmenting logic and makes the thread handling coherent,  fixes #2360 
> fix downloads stuck at 99.9%

- app/src/main/java/org/schabi/newpipe/player/playback/BasePlayerMediaSession.java
This PR includes
* Bug fix for the duration metadata field. `item.getDuration()` returns the duration in seconds, while the metadata object expects this to be in milliseconds.
* Add the current track number and total number of tracks in the playlist to the metadata. Some Bluetooth players prefer this information be present.
These metadata changes have been tested using a Pioneer car stereo over Bluetooth.
Fixes #2240
> Update play queue metadata

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java
- app/src/main/java/us/shandian/giga/get/DownloadInitializer.java
- app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
- app/src/main/java/us/shandian/giga/get/DownloadRunnableFallback.java
- app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
this fixes socket leak in `DownloadRunnable`
* In `DownloadInitializer` close the HTTP body after doing range-request checks
* In `DownloadDialog` fix regression, using one thread for audios instead of subtitles
resolves #2470
if the speed change is not noticied, restart the device
> Fix slow download speed

- app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
- app/src/main/java/us/shandian/giga/service/DownloadManager.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- app/src/main/res/menu/download_menu.xml
some buttons on the download page dissapears when the screen goes off or the app is switched
> fixup for #2149 (missing buttons)

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/Downloader.java
- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/res/layout/activity_recaptcha.xml
- [y] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
This pr fixes two problems with the ReCaptchaActivity:
- it crashes on activity startup due to a hidden EditText, see #2484
- it always shows youtube's main page ("https://www.youtube.com"), even though the ReCaptchaException was thrown while loading a different page. The main page sometimes contains the ReCaptcha (so there is no problem), but other times it does not since YouTube only blocks a specific page. The specific page that requested a ReCaptcha challenge is now loaded instead, so that the ReCaptcha is always shown.
Fixes #2484
Corresponding extractor pr: TeamNewPipe/NewPipeExtractor#186
Testing apk: …
> Fix ReCaptchaActivity

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
- app/src/main/java/org/schabi/newpipe/util/FilePickerActivityHelper.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java
- app/src/main/java/us/shandian/giga/service/DownloadManager.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/download_settings.xml
Some ROMs are not [CTS](https://source.android.com/compatibility/cts/) compliant, in these cases the Storage Access Framework is not fully implemented or functional.
This PR checks whatever is SAF available, otherwise, the legacy API (Java I/O) will be used
changes:
* restore request permissions popups
* use legacy file/folder picker if necessary
fixes #2498 and fixes #2504 
> Downloads: add switch for saf/legacy file picker

- app/src/main/java/org/schabi/newpipe/util/FilePickerActivityHelper.java
fixes https://github.com/TeamNewPipe/NewPipe/issues/2581 but allows NewPipe pick and navigate on hidden directories
> show hidden directories in the file picker

- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/us/shandian/giga/get/DownloadMission.java
- app/src/main/java/us/shandian/giga/io/StoredFileHelper.java
- app/src/main/java/us/shandian/giga/service/DownloadManager.java
- app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
[ ✔ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
This PR fixes various performance issues in Android 9 (Pie):
* Drop use of thread handler in the MissionAdapter
* Validate the file before start the download
fixes  #2576 and fixes #2560
Also a toast will be displayed after toggle the SAF switch, because the storage APIs implement different URIs. fixup for #2521
> Fix performance problem in android pie

- app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
fixes a deadlock in `DownloadRunnable` because youtube is sending in some files one byte **alone** ~~after downloading 26MiB exactly, why... i dont know.~~
possible fix for #2406
> check if last byte in the block is downloaded

- app/src/main/res/layout/toolbar_search_layout.xml
Fixes #2644 
The selectableItemBackground has been deleted to show only the circle animation on the search box.
> Clear search box has now only one animation - issue #2644 solved

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/CacheFactory.java
- app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasession/PlayQueueNavigator.java
- app/src/main/java/org/schabi/newpipe/player/mediasession/PlayQueuePlaybackController.java
- app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
As we now finally have AndroidX I was able to update ExoPlayer to the latest version.
This brings numerous of needed fixes and improvements to NewPipe. Have a look at the ReleaseNotes: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md
This might close #2257 and #2373 and possible other issues.
Debug apk for testing: https://github.com/Redirion/NewPipe/releases/download/v0.17.3-exo/app-debug.apk
Notes for Review:
- Changes to the MediaSessionManager and PlayQueueNavigator were mainly required due to this commit in ExoPlayer: https://github.com/google/ExoPlayer/commit/063f5704cd80a733bf770375d8fbf402a6c5d958
- I also had to fiddle again in CustomTrackSelector as there have been changes again. I already tried subtitles (it seems to be working fine this time :D)
- I have …
> Update to ExoPlayer 2.10.5

- app/build.gradle
Little dependency update.
ExoPlayer Changelog: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md
OkHttp Changelog: https://square.github.io/okhttp/changelog_3x/#version-3126
> Bump ExoPlayer to 2.10.6 and OkHttp to 3.12.6

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
I think it's time we introduce Kotlin to NewPipe as I consider it very nice to use. The main reasons/opinions as to why I think it'd be good to the project:
- I want to learn more about it, so why not have more contact with it
- Want to learn something new
- Relative ease to migrate _and_ interact with Java code
- Enjoyable coding overall
If you think this is not a good addition for NewPipe, please post your thoughts below.
> Update Gradle and introduce Kotlin to NewPipe

- app/src/main/res/values/strings.xml
I updated reCaptchaActivity string and made it untranslatable, because it's causing "Failed check: Unchanged translation" on Weblate.
This would fix the last paragraph of #2794 (the main reason why I created the issue is not fixed)
> Make reCAPTCHA string untranslatable

- app/src/main/java/org/schabi/newpipe/BaseFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/DefaultKioskFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
- app/src/main/java/org/schabi/newpipe/settings/tabs/TabsJsonHelper.java
- app/src/main/res/values/strings.xml
- app/src/test/java/org/schabi/newpipe/settings/tabs/TabTest.java
- app/src/test/java/org/schabi/newpipe/settings/tabs/TabsJsonHelperTest.java
Was testing some other PRs and noticed that the main fragment had some problems, the most important one being the way the view pager was being handled.
- Remove usage of hardcoded title for default kiosk.
- Some tests were simply ignored, this PR enables them again.
- Fix broken view pager tabs implementation
- Fragments were being recreated from scratch (losing their state) every time some configuration change occurred (e.g. screen rotation).
- Use `FragmentStatePagerAdapter` instead, as it is built to work with them and manage their states.
- Clear the item list when starting loading.
- Enable toolbar title visibility when setting a new one.
- Use tab position from parameters instead of relying on the view pager.
- Make the `KioskFragment` aware of changes in the preferred content …
> Fix tab handling and enable ignored tests again

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
Fixed a bug that could not move the popup player if another finger was placed while moving the popup player.
This is also a fix for #1727 (fixes #1727).
> Fix popup player gestures

- app/src/main/res/values-iw
Hebrew on android uses two locale codes (iw and he).
See details here: https://stackoverflow.com/a/8470980
For example, Nexus 7 (2013) uses iw, so it shows the English UI even when configuring the tablet to use Hebrew.
Add a symbolic link from values-iw to values-he so both use the same strings.
> Fix Hebrew translation on some devices

- app/src/main/res/values-v27/styles.xml
- app/src/main/res/values/styles.xml
As discussed in https://github.com/TeamNewPipe/NewPipe/issues/1494, this changes the software navigation bar to black with light buttons if all of the following points are fulfilled:
1. The black theme is enabled (maybe this should apply to the dark theme as well?)
2. The device supports setting a custom navigation bar color (API Level 21).
3. The device supports setting the navigation buttons color to dark mode (API Level 27).
Fixes #1494
> Black navigation bar for black theme

- app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
- app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java
release build is failing without this on android studio 3.5.3
> Migrate annotation to androidx

- app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/util/TLSSocketFactoryCompat.java
This is an attempt to fix #2777 . I already got the Downloader and the Extractor parts working. What I may need some help on is the player. I simply don't know how to approach this and where to start.
Please give me some feedback on the "finished" parts, too.
> Enabling TLS1.1/1.2 on Android 4.4 devices (API 19/KitKat)

- app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
> fix add instance dialog

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- [✓] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
I found a way to solve issue #2838  together with issue #2773 and issue #2797 . Youtube seems to freeze as the NewPipe activity is not correctly closed. I added an if statement in DownloadDialog to close the activity when ok is clicked if the activity does not come from the app itself:
As it finishes the activity, when downloading a second video, the name is reset so it also fixes issue #2797 
Fixes #2838
Fixes #2773
Fixes #2797
> Fixed issues #2838 #2797 #2773

- app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
Some code was running in a RxComputation thread (default of `Observable#interval`).
This PR fixes it by always delivering the result in the main thread, which the player was created on.
Should be the only case where this happens, checked using a watch point on the player field to compare in which thread access occurred on.
---
Fixes #2376.
> Fix for player access out of its creation thread

- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
Maybe not the cleanest solution but it seems to fix #2170 while recreating notification often enough to prevent leaks.
> Limit amount of notification thumbnail updates in background player

- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
- app/src/main/java/org/schabi/newpipe/views/ScrollableTabLayout.java
- app/src/main/res/layout/fragment_main.xml
This PR makes tabs scrollable so they don't get squeezed if there are too many of them and hides tab selector if there is only a single tab. Adds and closes #1647 
Before | After
:---:|:---:
Created separate ScrollableTabLayout class to avoid cluttering MainFragment with switching between scrollable and fixed modes.
[single-pre]: https://user-images.githubusercontent.com/10105131/70863722-e647f700-1f42-11ea-95d5-17268d883ad6.jpg "Single tab"
[single-post]: https://user-images.githubusercontent.com/10105131/70863727-efd15f00-1f42-11ea-8ef8-d1edf501fa23.jpg "Single tab"
[multi-pre]: https://user-images.githubusercontent.com/10105131/70863729-f5c74000-1f42-11ea-9064-5aa63f83ffd0.jpg "Multiple tabs"
[multi-post]: https://user-images.githubusercontent.com/10105131/70863733-f9f35d80-1f42-11ea-94 …
> make main page tabs scrollable and hide when there is only a single tab

- app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java
I propose this solution for the issue #2759.
It corrects the use-case described in this issue : 
1. Select item, Add To Playlist -> New Playlist -> test1
(Item Thumbnail will be used as Playlist Thumbnail)
2. Go to test1 playlist, Delete item.
(Playlist Thumbnail ~~will remain, but it should be removed~~ is updated with the default thumbnail url : https://i.ytimg.com/ if the playlist is empty)
3. Select item, Add To Playlist -> test1
(Playlist Thumbnail ~~will remain, but it should be updated~~ is updated with this item thumbnail if playlist was empty)
If the playlist isn't empty in step 2, we just update the playlist thumbnail with one of its item.
> Playlist thumbnail updates

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
* use *.opus extension instead of *.webm (bad change from https://github.com/TeamNewPipe/NewPipe/pull/2679/commits/844f80a5f1b0762a043afd2b4aec63b402830e53)
* show "opus" in format label instead of "WebM Opus" in the dropdown
fixes #2904
> add opus file extension

- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
This commit fixes the situation where NewPipe is set up to play in the background when minimizing its window.
1) A video is playing
2) The video is paused
3) NewPipe is minimized (of the screen is turned of)
In this situation, without this pull request, the video is incorrectly resumed in the background.
I hesitated whether I would set the default value to true of false. I chose  to pick true to be closer to the current behavior, please let me know if it would be better to use false or fill free to edit. 
[X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
> Allow a BasePlayer to start paused

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/util/KoreUtil.java
- app/src/main/res/layout-large-land/activity_main_player.xml
- app/src/main/res/layout/activity_main_player.xml
[Debug APK](https://webcloud.zaclys.com/index.php/s/drYS1oNG5xpKfKp)
> Add send to Kodi button to player next to share button

- app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
- app/src/main/res/values/strings.xml
#2922 - This issue seems to happen on any device on Android 6 and above. Specifically on Android 10, it seems like it doesn't open the Settings window for the permission when the home button is pressed. But even in cases where it does show the window, it won't open the popup window when you give it the permission. 
So i added a snackbar that lets the user go to the settings when they set the "minimise on home" option to "minimise to popup player".
> ask for display over other apps permission in settings

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- PeerTube: it's now full description (it cut at 250 characters before), and Markdown is supported.
- MediaCCC: descriptions as it should be (newlines added).
- YouTube: timestamps in descriptions are clickable and work. Fixes #1025 (Thanks to @jimbo1qaz & #2536).
+ Thumbnail is now high quality.
+ Age limit is now handled.
+ Upload date in «recently added» feed is good now (it was delayed as much hours as your are from GMT).
[Before](https://i.ibb.co/G52TGp9/Screenshot-20200208-112424-New-Pipe.png)
After: [Thumbnail](https://i.ibb.co/wKCDf3B/Screenshot-20200208-112236-New-Pipe-Debug.png) [Description (and see this beautiful Markdown 😃)](https://i.ibb.co/T8CdJXm/Screenshot-20200208-112249-New-Pipe-Debug.png) 
APK: [2020-02-08_description_and_peertube_fixes#3044.zip](https://github.com/Team …
> Description fix and some PeerTube fixes

- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
Release build is failing without this on android studio
Cheers
> Migrate annotation to androidx on ReCaptchaActivity

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/util/Constants.java
- app/src/main/res/menu/download_menu.xml
- app/src/main/res/menu/menu_about.xml
- app/src/main/res/menu/menu_channel.xml
- app/src/main/res/menu/menu_play_queue.xml
- app/src/main/res/menu/menu_playlist.xml
- app/src/main/res/menu/video_detail_menu.xml
As noted by @opusforlife2 in https://github.com/TeamNewPipe/NewPipe/issues/3114#issuecomment-589933537 it is sometimes useful to access settings from activities other than the main one. So this PR readds *some* "Settings" buttons removed in #2960.
In particular, the activities where the button is restored are:
- Queue (background and popup queue activities)
- VideoDetail (see @opusforlife2 usecase)
- Playlist (same as VideoDetail)
- Channel (same as VideoDetail)
- Download (I'm not really sure about this one, because the Download activity is only accessible via the drawer and the user could just press "back", so it would categorize as one of the activities below that do not require the button, but I feel like it would be useful anyway sometimes... **could you give some feedback?**)
Other …
> Reintroduce "Settings" button in app bar

- app/src/main/res/values/strings.xml
: smallversal is incompatible. This does away with the potential for errors.
> Spelling: Some devices are incompatible

- app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
- app/src/main/res/values/strings.xml
closes #3127 
Hides 5, 15, 25 second seek options if inexact seek is enabled. If one of those values was selected while activating inexact seek, it automatically gets set to 10 seconds.
Will the edited string resource make any problems concerning translation with weblate, since it was not a rewrite but adding additional info.
I tested it on my Android 10 and 7.1 devices.
Updated apk: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4283025/app-debug.zip)
> Hide 5, 15, 25 second seek options if inexact seek is enabled

- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
Closes #3045
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4147126/app-debug.zip)
Tested it on my android 10 and 7.1 devices.
When sharing a video to vlc media player it doesn't start playing it, but this should be related to them.
Related stackoverflow: https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed
> Fix bug causing crashes when sharing a downloaded file.

- app/src/main/res/xml/appearance_settings.xml
- app/src/main/res/xml/content_settings.xml
"Show 'Next' and 'Similar' videos" and "Content of main page" have been relocated from Appearance to Content settings.
APK for testing: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4296606/app-debug.zip)
Closes #3166. Closes #3176.
> Relocate two settings from Appearance to Content

- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
Tabs were not being destroyed/restored correctly due to a call to a method that populated the view pager before it even had a chance of restoring itself.
The solution was to null out the adapter before calling that method so the view pager will postpone the populating process.
> Fix bug in main screen tabs state management

- app/src/main/res/values-v21/styles_services.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_services.xml
This is a pretty old issue, I'm surprised nobody was annoyed enough to fix it.
It was even added by me, 2 years ago. The reason was to provide smooth transitions when changing the theme, and it worked, but in recent versions of Android it doesn't seem to make a difference other than trigger this annoying glitch.
---
Closes #1173.
> Fix visual glitch when exiting the app

- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-b+ast/strings.xml
- app/src/main/res/values-b+zh+HANS+CN/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-eu/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-he/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ku/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
Fixes #3169.
I put the already translated string into all cases where the plural is needed. Therefore, the translation may be innacurate, but I'll explain:
+ People translated for "%s seconds", in general, so it's already plural, even if it can be innacurate, it's better than blank.
+ If we don't put everywhere, sometimes it's blank. Same, innacurate is better than blank.
+ Translators will be notified that the strings has changed, and either they will confirm it's ok, or correct the string.
I also corrected the «one» plural translation for some languages I know how plural works (eg french, german, spanish…)
For Chinese, for all plurals, from IDEA: one or zero is never called, it's always other.
So with the same reasoning, I put the already translated word.
BTW, it may happen in the …
> Fix seek duration not showing

- app/build.gradle
- app/src/main/res/values/strings.xml
The share title is currently hard coded and it was missed by #3133.
I was also inclined to create another variant for this, but a simple `true` in that if statement seems to be enough to force the default behavior when needed, not worth it.
- Change share title as well to differentiate multiple builds
- Move code with lower priority to the bottom of the file
> Change share title to differentiate multiple builds

- app/src/debug/AndroidManifest.xml
One more thing that was missed.
The file was responsible for making the app use the Debug application class, which various debug tools depended on.
> Revert manifest removal from debug build variant

- app/src/main/java/androidx/fragment/app/FragmentStatePagerAdapterMenuWorkaround.java
- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
When restoring the state of the adapter, all the fragments' menu visibility were set to false, effectively disabling the menu from the user until he switched pages or another event that triggered the menu to be visible again happened.
As the bug happens deep inside the adapter restore method and the require field to fix it is private, a copy of the class was needed.
`FragmentStatePagerAdapter` is deprecated and should be replaced with its `ViewPager2` counterpart, until then, this should do it.
[fix-main-screen-menu-creation.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4394064/fix-main-screen-menu-creation.apk.zip)
> Temporary fix for main screen menu visibility

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
See https://stackoverflow.com/questions/35819290/invalid-drawable-tag-vector
There was no need to change other ImageButtons because the image was set programmatically only in the mute button
> Fix mute button inflation problems on API<21

- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
Some fragments were not handling these types of exceptions.
We should improve the display of `ContentNotAvailableException` exceptions in the future by showing more specific details, like not found.
For now, a "Content unavailable" is better than a crash.
- #3277
> Handle content not available exception more comprehensively

- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
Fixes crashes when instantiating the background and popup queues, due to a problem in obtaining and setting the drawable to the menu icon on API 19.
Note: using rootView.getContext() because getApplicationContext() didn't work (it was probably missing information about theme)
- Fixes #3320
I tested this fix on Android 4.4 (API 19, emulator) and Android 7.1 (phone). @AnotherLife could you test this apk?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4414294/app-debug.zip)
> Fix mute button causing crashes on API 19

- app/src/main/res/layout/drawer_header.xml
- app/src/main/res/values-v21/dimens.xml
- app/src/main/res/values/dimens.xml
The padding and height for the drawer layout were being hardcoded, and when the drawer was shown in phones with non-standard status bar sizes, it would not be positioned correctly.
This improves the drawer specifically for phones that have a notch.
[improve-drawer-height-handling.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4421610/improve-drawer-height-handling.apk.zip)
> Make the drawer layout adapt to any status bar size

- app/build.gradle
Debug APKs are now named after their branch name as suggested by @opusforlife2  e.g. the debug APK for this branch is named `NewPipe_apk_base_name-debug.apk`
Release builds are not touched, as well as debug builds on dev and master branch.
not needed
> Change APK base name depending on the branch name for debug builds

- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersionTask.java
This way we only have to change code in DownloadImpl and the ExoPlayer stuff when we want to add support for e.g. setting a SOCKS proxy in the settings. I tested that this works successfully.
> Use DownloaderImpl in CheckForNewAppVersionTask

- app/src/main/java/org/schabi/newpipe/database/stream/dao/StreamDAO.kt
The upload date was being updated regardless if the new one had more precision or not, this caused items on the feed to jump around when the user opened one of them.
This changes it to only update when the existent upload date is null or the new one has a higher precision (i.e. is not an approximation).
> Avoid unnecessary changes to the upload date of saved streams

- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderWithMenuItem.kt
The visibility of the group sort button in the subscriptions fragment was not the right one when a rebind happened (e.g. return from another fragment that destroyed its host's views).
> Fix visibility of group sort button in the subscriptions fragment

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/res/values/settings_keys.xml
- Playback parameters are speed, pitch and skip silence
- Save playback parameters into shared preferences whenever they are set
- Retrieve playback parameters from shared preferences when starting any player
- Remove playback parameters from being passed from one player to another through intents. Instead they can be retrieved from the shared preferences.
- solves #735
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4398458/app-debug.zip)
I noticed that changing the playback parameters while the video is paused gets ignored. At first I thought i broke something, until I noticed that it was like this before too.
> Save and restore playback parameters into/from preferences

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
See https://github.com/TeamNewPipe/NewPipeExtractor/pull/300 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/250
Copy paste from https://github.com/TeamNewPipe/NewPipeExtractor/pull/300
> Follows the discussion we had in https://github.com/TeamNewPipe/NewPipeExtractor/pull/250
It will greatly improve SoundCloud usability, because instead of randomly crashing, it will show the error with an appropriated UI, not a crash report, then the average user will understand why, and he can go back to play another track.
Before, the user was confused, and it went back to main kiosk each time, so it was really annoying.
How to Test: use debug apk below, search for "Dua Lipa" in SoundCloud, go to her channel page, and play the newest track, or go to youtube music.
Screenshots: …
> handle ContentNotSupportedException

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/PlaylistMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistItemHolder.java
- app/src/main/java/org/schabi/newpipe/util/Localization.java
- app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
See TeamNewPipe/NewPipeExtractor#291.
> YouTube Music search stuff

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/res/layout/drawer_header.xml
- app/src/main/res/values/dimens.xml
Some devices, specially with custom fonts that changed the font width, weren't being correctly adjusted before.
- Fix #3381
[improve-drawer-title-size-handling.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4461735/improve-drawer-title-size-handling.apk.zip)
> Improve size handling of the drawer header title

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
The current popup window does resize with pinch gestures, but it's a bit weird. It resizes to the distance between the 2 fingers, and changes its position to one of the fingers. I changed it so that the window size scales to the pinch-in/out gesture and stays in the same position.
Fixes #515 fixes #2880 fixes #2918
APK:
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4184242/app-debug.zip)
> Better popup resizing with pinch gestures

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/services/BaseImportExportService.java
- app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
- app/src/main/java/org/schabi/newpipe/util/ExceptionUtils.kt
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
- app/src/test/java/org/schabi/newpipe/util/ExceptionUtilsTest.kt
I saw a few of these in some reports lately, because when a network exception occurs, some other method will sometimes wrap that exception and cause it not to be detected by the simple `instanceof` checks.
This adds a class that checks whether some exception in the chain is of some network issue related type.
- Fix #2418
- Fix #2582
- Closes #2600
- Closes #2765
[fix-network-issues-detection.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4398023/fix-network-issues-detection.apk.zip)
> Fix detection of network related exceptions

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/res/values/strings.xml
Now it will show an error for videos with an age limit when the option to view age restricted videos is disabled in the settings:
Apparently there already was a bug in NewPipe that it will still show the tabs when an error occured, and this PR doesn't fix that yet, though it makes it much more noticable.
This PR will fix #776.
> Show error when video has age limit and setting is disabled

- app/build.gradle
Fixes the behaviour described in https://github.com/TeamNewPipe/NewPipe/pull/3265#issuecomment-612102349
@Bubu told us:
> when doing a release build the apk is now called:
`NewPipe_head-release-unsigned.apk`. Also a file in the `META-INF` dir now ends up being called `NewPipe_head_release.kotlin_module` instead of `app_release.kotlin_module`.
For some reason the `archivesBaseName` Gradle property from debug builds was used in release builds. Forcing it to be `app` and changing the order of build flavors fixed the problem for me
- https://github.com/TeamNewPipe/NewPipe/pull/3265#issuecomment-612102349
@Bubu With the changes I could not reproduce the behaviour you mentioned. Can you verify this by running a build on your machine, please? …
> Fix F-Droid build

- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
Make background and popup buttons in the channel header long clickable, and trigger an enqueue action in that case, just like in local and remote playlist activities. This is a very small change copied directly from [PlaylistFragment.java](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java#L327-L335).
Fixes #3450 
@minsk21 test this :-D
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4498645/app-debug.zip)
> Enqueue on long click on background/popup in channel

- app/src/debug/java/org/schabi/newpipe/DebugApp.java
- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
- app/src/main/res/values/settings_keys.xml
- Try to get cookies from pages even when they start loading, because non-html pages like ones with `pbj=1` never stop loading.
- Try to extract the cookie directly from the redirection url, by looking at the field `google_abuse=`.
- Add `GOOGLE_ABUSE_EXEMPTION=` to the youtube recaptcha cookies.
- Store cookies into shared preferences so that the user does not have to solve a recaptcha every time he opens the app
Fixes #3134 fixes #3272 fixes #3418 fixes #3310
@mehedihasanziku @baraa272 @LargePrime @tusch001 could you test this, if recaptchas still pop up for you? Also, @Ristovski, even though I didn't change anything about webviews, could you test, too?
[NewPipe_recaptcha-debug_1.zip](https://github.com/TeamNewPipe/NewPipe/files/4464377/NewPipe_recaptcha-debug_1.zip)
> Fix ReCaptcha Activity for another type of recaptcha page

- app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
This is a fix for #3261 (App loops in null pointer with bookmarks exception).
A fix for a bug that prevented the Bookmarked Playlists screen from being displayed because the playlist name had changed to null for some reason.
When Bookmarked Playlists is displayed, sorting is done against the playlist names. This PR prevents crashes by allowing you to sort playlist names that contain a null.
The fundamental solution is to prevent null in playlist names, but I think this fix is necessary to open a database that is already in an unopenable state.
- Fixes #3261
apk: [errorwithbookmarks.zip](https://github.com/TeamNewPipe/NewPipe/files/4428531/errorwithbookmarks.zip)
database: [NewPipeData-Test.zip](https://github.com/TeamNewPipe/NewPipe/files/4428532/NewPipeData-Test.zip)
Steps to reproduce …
> Fix repeated exceptions in Bookmarked Playlists

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
- app/src/main/java/org/schabi/newpipe/util/AndroidTvUtils.java
- have a better detection of TV devices, so that everyone with a TV can have a great experience on NewPipe.
Because some boxes — including mine — are just boxes shipped with Android with a TV interface / remote-friendly interface, but they aren't shipped with [_official_ Android TV system](https://www.android.com/tv/), i.e. with Google Assistant, Chromecast… , or Fire TV (I've seen Fire TV detection in `AndroidTvUtils.isTv()`).
Please include this PR in 0.19.3, this way https://github.com/TeamNewPipe/NewPipe/pull/3478 will ship all TV fixes.
- Some android boxes aren't detected as TV (because not Fire TV / Android TV), and it created many issues mainly related with navigation.
[NewPipe_tv_detection.zip](https://github.com/TeamNewPipe/NewPipe/files/4532762/NewPipe_tv_detection.zip)
> Better detection of TV devices

- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
Fix the many rotation issues reported in #3479. The crash was caused by `itemsList` being `null` in `BaseListFragment`. I didn't understand how that could happen (maybe a leak of some sort?), but I could fix it simply by adding a null check.
- See issues in #3479
@androidSwDev099 @Domiuns could you confirm this fixes the issue in every one of the situations you reported? I tried them all after the fix and could not find any crash, but who knows ;-)
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4536343/app-debug.zip)
> Fix rotation

- app/src/main/res/values/strings.xml
Other debug settings are translatable as well, so why not allow translation for these? Thanks to @AnXh3L0 for pointing that out.
> Allow time ago debug setting translation

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/util/KoreUtil.java
- app/src/main/res/layout-large-land/activity_main_player.xml
- app/src/main/res/layout/activity_main_player.xml
This PR disables the share to Kodi button when the current service is not supported (see the Kore  [AndroidManifest.xml](https://github.com/xbmc/Kore/blob/master/app/src/main/AndroidManifest.xml)). Supported services are Youtube and Soundcloud. From that manifest I could also deduce that replacing `https` with `http` is not needed anymore.
- fixes #1166
- closes #1930
I tested if the urls correctly matched Kore's manifest, by installing the app (even without connecting it to anything) and sharing urls. Before this fix sharing MediaCCC urls would have generated an error (thus leading to a "Missing Kore app, install it?" dialog), so this method of testing is good. 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4588833/app-debug.zip)
>  Fix Kodi button showing up with unsupported services

- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/channel_header.xml
- app/src/main/res/layout/error_retry.xml
- app/src/main/res/layout/fragment_video_detail.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles_misc.xml
- change retry (when there is a network error) button color, to follow service's color
- fixes #1134
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4605400/app-debug.zip)
> Change retry & subscribe buttons background color based on service color

- app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
Send e-mails like https://developer.android.com/guide/components/intents-common#Email. I tested that it works with Gmail and Outlook.
Fix #3383
> Fix sending e-mail from crash reporter

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSourcePlaylist.java
- app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
This PR updates ExoPlater to 2.11.4, which should hopefully fix some player issues like slowdowns. On my phone and on emulators I noticed that stream loading is (roughly speaking) twice as fast with regards to the old player, but I can't provide a proof ;-)
This PR also includes the changes made by @Redirion in #2859, i.e. making use of two new features: `setHandleWakeLock` and `setHandleAudioBecomingNoisy`.
I fixed the bug faced by @Redirion with `MaskingMediaSource`s: the issue was that the new version wraps around `MediaSource`s being fed to it with a `MaskingMediaSource`, preventing direct access to the original media source. NewPipe made use of this feature in the `ManagedMediaSource` interface to keep track of whether streams were pre-buffered (probably among other things), by …
> Update to ExoPlayer 2.11.4

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/util/ListHelper.java
- checkstyle-suppressions.xml
I also forgot to remove some Checkstyle hack that's not needed anymore now that they handle it properly with Gradle when upgrading its version, so I removed that as well.
Fixes #3609
> Fix download dialog freeze

- app/src/main/res/values/strings.xml
According to a user on IRC "the menu is confusingly worded, [...], it seems to correctly enqueue in the miniplayer and in the background, it just calls it "a new" miniplayer even if there is already a miniplayer, which obscures the fact that the action will enqueue a song". So I removed the `new` word from the long-press menu strings
> Improve long-press menu strings

- app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
- Open in browser buttons open in default browser for android 6+ (otherwise no change).
- Open in browser button not opening in browser, but either showing a chooser, or worse: opening in NewPipe if NewPipe is set as default for youtube links. I just wanna open in browser
It will only work for android 6+ since it uses default apps, available from settings -> apps -> more -> default apps -> browser app, [a new feature in android 6](https://www.tomsguide.com/us/change-default-apps-in-android,review-3309.html), otherwise it will not change. It will also not change if you have no browser set as default. It's a rare case, because if you have only one browser that does not happen, if you have two, as soon as you choose one browser as default for opening a link, it will be set default in that …
> Open in browser button now really opens in browser

- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
I don't know the cause of the IndexOutOfBounds exception, it could have something to do with the adapter not having finished to update itself after the last call to `notifyDataSetChanged()`. Anyway, a simple check should fix it.
Fixes #3575 
@ltomes @test2a could you test this apk and see if it fixes the issue?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4742764/app-debug.zip)
> Fix search crash: adapter array index out of bounds

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
- Allows user to long-press on the video title in the detail screen to copy it to the clipboard
- Brief "Copied to clipboard" toast appears
closes #3768 
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4761426/app-debug.apk.zip)
> Copy video title

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/res/layout-land/activity_player_queue_control.xml
- app/src/main/res/layout/activity_player_queue_control.xml
- app/src/main/res/menu/menu_play_queue.xml
- Add fast rewind / fast forward in BackgroundPlayerActivity (activity where you manage videos playing in background)
Honestly, 9 icons in one row is maybe too much? We could move shuffle and repeat upward. And we could remove (one of) playbackSpeedButton/playbackPitchButton, since they both do the same.
fixes #2722
> Fast rewind forward in background activity

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueAdapter.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/events/ErrorEvent.java
<table>
<tr>
<td><img width="3000px" src="https://user-images.githubusercontent.com/36421898/83352146-e8afd900-a349-11ea-9892-17c381aa98a7.gif" /></td>
<td>When an item in the play queue failed to load, only some kind of errors were previously considered as "skippable" (i.e. go to the next stream without removing the current one). But other errors were not (e.g. network errors), so it was annoying in case of a temporary internet instability, because many streams would be removed from a possibly carefully handcrafted queue. This PR keeps the old behaviour when a stream cannot be played, except that every item is considered as "skippable". So if an erroring stream is encountered, the queue index is incremented without removing the old item. If the end of the queue is reached, the index …
> Do not remove items generating errors form queue

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
- Update ExoPlayer dependency to the newest version
- fixed a deprecation regarding ExoPlayer
This hopefully addresses #2397 as the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md) contain this promising fix:
> Only set the playback state to BUFFERING if playWhenReady is true
https://github.com/Redirion/NewPipe/releases/download/exoupdate/app-debug.apk
> Update to ExoPlayer 2.11.6

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- Fixes an issue where having a paused video in the popup player then enqueuing another video would cause the paused video to start playing again.
- Does not break expected behavior, clicking the popup button will still immediately play the video that it was clicked on.
- fixes #3760 
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4796122/app-debug.apk.zip)
> Fixes enqueue resuming paused videos

- app/build.gradle
Currently unnecessary Checkstyle stuff is included in debug APKs. I changed `build.gradle` to not include that stuff in the debug APKs, while it still runs Checkstyle. This causes debug APKs to be like 8 MB smaller.
> Do not include Checkstyle in any APK

- app/src/main/res/layout/activity_player_queue_control.xml
For some reason a strange `style` attribute was used for title and channel in background/popup queues. This caused some problems on some devices. So I removed the `style` attributes from the `TextView`s and added `textAppearance`, with the same values used in `fragment_video_detail` for, respectively, title and description.
- fixes #2586
@xxkfqz @primarto please test if this fixes the issue, thank you in advance ;-)
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4840662/app-debug.zip)
> Fix queue channel name color for some devices

- app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt
- app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionEntity.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/EmptyPlaceholderItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
- app/src/main/res/layout/dialog_feed_group_create.xml
- app/src/main/res/layout/toolbar_search_layout.xml
- app/src/main/res/menu/menu_feed_group_dialog.xml
Let the user search for subscriptions in the feed group dialog.
[feed-add-search-sub-list.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4840678/feed-add-search-sub-list.apk.zip)
> Add search for subscription picker in the feed group dialog

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/res/values-v21/styles_services.xml
- app/src/main/res/values/colors_services.xml
- app/src/main/res/values/styles.xml
- Remove translucent status bar
- Change status bar color to match toolbar color across services
- Implements: (Feature request) Status bar color #3013
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4768501/app-debug.apk.zip)
> Update status color to match toolbar color

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
After doing a `git bisect` I found out which commit caused the desync to appear: 3855e488cb78959dbf6327ff187fda8867e42b43
The problem was that the value of playback speed, even though displayed as `1.0x`, was instead `1.00267911`. This was probably caused by cumulative floating point errors after saving and restoring the value many times from shared preferences. This PR rounds speed and pitch to 2 decimal places before saving them or feeding them to the player, so that any floating point error is eliminated and the issue is not there anymore.
- fixes #3550
*The reason as to why having a playback speed very near 1.0 caused desync is still unknown to me*, but I tested this PR with the settings provided at https://github.com/TeamNewPipe/NewPipe/issues/3550#issuecomment-626040706 and the …
> Fix audio/video desync caused by floating point cumulative errors

- app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt
- app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionEntity.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/EmptyPlaceholderItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
- app/src/main/res/layout/dialog_feed_group_create.xml
- app/src/main/res/layout/toolbar_search_layout.xml
- app/src/main/res/menu/menu_feed_group_dialog.xml
- app/src/main/res/values/strings.xml
Add a way to let user hide subscriptions from the subscription picker that are already included in any other group .
- Closes #3377
- #3373
[feed-add-filter-sub-list.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4840740/feed-add-filter-sub-list.apk.zip)
> Add filter to the feed group dialog to show only ungrouped subscriptions

- app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
- app/src/main/res/layout/activity_error.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
Add content country as additional debug information to reports
Adds button to error screen to copy markdown crash report and button to open our GitHub issue page.
Part of #1816
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4620341/app-debug.apk.zip)
> Add Markdown export of crash logs

- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/values-land/dimens.xml
- app/src/main/res/values-sw600dp/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Display search suggestions: "did you mean" and "showing result for" (in YouTube & YouTube Music).
<table><tr><td><img src="https://user-images.githubusercontent.com/21021560/79996735-71249980-84c1-11ea-95bd-6d8928609b08.png"></td><td><img src="https://user-images.githubusercontent.com/21021560/79996922-aa5d0980-84c1-11ea-8a60-1d97bf45ef94.png"></td></tr></table>
- https://github.com/TeamNewPipe/NewPipe/issues/3419
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/311
[NewPipe_gisplaysearchsuggestion-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4517507/NewPipe_gisplaysearchsuggestion-debug.zip)
> Display search suggestion: did you mean & showing result for

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/DefaultKioskFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/ChannelPlayQueue.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlaylistPlayQueue.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
TeamNewPipe/NewPipeExtractor#314
> Next page stuff

- app/src/main/res/values-bn-rIN/strings.xml
- app/src/main/res/values/settings_keys.xml
add languages
- fixes #3858  
i can't upload it…
> add the new languages translated in NewPipe

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueAdapter.java
Apparently we were using ReactiveX' `NonNull` annotations at certain places, while we're using AndroidX' `NonNull` annotations everywhere else.
> Use androidx.annotation.NonNull instead of io.reactivex.annotations.NonNull

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
I just found this issue while trying to debug the the age restricted videos issue. This shouldn't be able to happen with any service currently though.
> Check for description == null

- app/build.gradle
- app/src/debug/java/org/schabi/newpipe/DebugApp.kt
- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/report/AcraReportSenderFactory.java
This PR fixes blank reports not containing the stack trace (as seen in #3930). This was caused by `MultiDex.install` not being called before ACRA initialization, so ACRA could not load some of its classes and failed to initialize the stack trace collector (among others). See ACRA/acra#619 and [ACRA wiki](https://github.com/ACRA/acra/wiki/Troubleshooting-Guide#legacy-multidex).
This PR also contains two other improvements to ACRA's initialization code:
- Skip ACRA initialization if the current process ends with `:acra` (i.e. is created by ACRA): https://github.com/ACRA/acra/wiki/Troubleshooting-Guide#applicationoncreate
- Remove deprecated calls to set the `ReportSender` class in the configuration: `setReportSenderFactoryClasses()` is deprecated, now extensions (`ReportSenderFactory` is an …
> Fix ACRA bug reports not containing stack trace

- app/src/main/res/layout/local_playlist_header.xml
- app/src/main/res/layout/playlist_header.xml
This PR changes paddings and margins for elements in the header of local and remote playlists. ~~I noticed the title for local playlists has a different behaviour from that of remote ones, should I make it more consistent?~~ The local playlist title is now consistent with the remote's one.
<table><tr><td><img width="400px" src="https://user-images.githubusercontent.com/36421898/88659512-76533f00-d0d5-11ea-8f71-794744269114.png"></td><td><img width="400px" src="https://user-images.githubusercontent.com/36421898/88476449-a9140080-cf38-11ea-9641-46f611627eba.png"></td></tr></table>
Fixes #3937
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4987950/app-debug.zip)
> Improve playlist header layout: align with info items

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
For some reason supported calls in API 19 (https://developer.android.com/reference/java/util/Objects#requireNonNull(T)) actually unsupported in API 19 (see #4060) even when the same code works on other devices with API 19 :). So I just deleted these calls.
fixes #4060
> Removed java.util.Objects calls

- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
> Fix crash when opening video in local playlist tab

- app/src/main/res/values/strings.xml
Make title and summary of "Remeber popup size and position" setting less redundant.
Before:
not needed
> Reduce redundancy in "Remeber popup size and position" setting

- app/src/main/AndroidManifest.xml
Allow resizing of app when OS + device support it.
Closes #3947
See https://codeberg.org/gitnex/GitNex/commit/9e352df1ed7d1d285fde61632822e2db5d128f16
See https://developer.samsung.com/samsung-dex/modify-optimizing.html#Enabling-Multi-Window-support
[NewPipe_basic_resize_APK.zip](https://github.com/TeamNewPipe/NewPipe/files/5017065/app-debug-1.zip)
@mqus @Domiuns @MD77MD Can you please test if the app works properly when changing the orientation of your device, opening the keyboard when typing something in the searchbar and in dialogs (e.g. when creating a new feed group)?
> Add basic resize functionality

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
See #4129. Since this is such a simple change I think it should be merged asap, as to make testing #3178 simpler
@avently is this ok?
Fixes #4129 
@opusforlife2 you were encountering this problem in #3178, could you check if it is fixed in this apk?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5078760/app-debug.zip)
> [regression] Close player in onPlaybackShutdown()

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Makes more space underneath the mini player when it's visible or expanded into main player. So the last items in recyclerView from main fragment will be visible in both cases: opened or closed player. Works in multiWindow mode too.
closes #4047
[app-release.zip](https://github.com/TeamNewPipe/NewPipe/files/5079228/app-release.zip)
@XiangRongLin check this one, should be ok.
> Set bottom padding of the main fragment when the mini player is visible

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
After reading this comment https://github.com/TeamNewPipe/NewPipe/pull/3948#issuecomment-668241710  
> this new unified player ... drains the bettery twice as much
I checked how much CPU the player uses. And found out that @MD77MD said incorrect information but even if it's not true (about double difference) the new player definitely uses more CPU than 0.19.8. Difference is about 15%. So I started seaching for the cause and found that this line https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L1774
adds 7-10% of CPU load. Actually there is no need to animate the progress bar when it's hidden under the video but it should be updated anyway (without animation) to reflect playing position changes. 
Next. After this …
> Reduced CPU usage when playing a video by 7-10%

- app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
- app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
Prevents interception of a swipe on seekbar by top level parent (BottomSheet). 
Was:
- please, take a look at the description of the issue: #4121. I just don't even want to describe this .... non-issue.
Now: 
- no such (non-)issue 
- no another (non-)issue related to tapping and swiping on fullscreen button (see the linked (non-)issue too).
- closes #4121
[app-release.zip](https://github.com/TeamNewPipe/NewPipe/files/5085969/app-release.zip)
> Skipping interception of some gestures

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/res/values/settings_keys.xml
- NewPipe now remembers which media type was downloaded last and will select that option the next time the user wants to download something.
- Closes #3490. This implementation follows the suggestion (2): remember last choice.
- Replaces PR #3901.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5010087/debug.zip)
> Remember last selected media type for downloads.

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
Just fixes for issues linked below + one thing that allows to play previous video from queue using previously viewed position (start playing queue, play next stream, tap back button, position will be restored). 
Regarding this thing: https://github.com/TeamNewPipe/NewPipe/compare/dev...avently:small-fixes?expand=1#diff-5f76198512a7674ea2f085d5c554be97R187  it means that the app will be shut down only when video player is playing. Popup and background players will continue to play in background even if a user swiped the app away from recents. So the only way to kill the app is to use notification `close` button or popup player's close button from the bottom of the screen.
- closes https://github.com/TeamNewPipe/NewPipe/issues/4043
- closes https://github.com/TeamNewPipe/NewPipe/issues/4159 …
> Small fixes of issues with brightness, background playback, gestures

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
On devices with cutout there is a "jump" when you are in multiWindow mode or when you're watching vertical video in fullscreen. This PR fixes that jump (the first commit).
On the same devices there is a problem related to top padding on vertical videos in portrait in fullscreen. This is more interesting because a couple hours ago I thought I will not be able to fix it. This problem makes situation when the center of the player is not in the center of the screen. After hours trying I installed the app on my phone and the issue is fixed actually (same Android version but different result). So I have no idea will my method (from the second commit) work on user's devices or not. I think the issue is still here but on devices with non-standard screen ratio. But I don't know how to fix it. You …
> Prevent jumping of the player and wrong padding on devices with cutout

- app/src/main/java/us/shandian/giga/io/StoredFileHelper.java
- Adds a null check before a String comparison on the equals method
- Fixes bug where downloading the same deleted file would cause the app to crash on a NullPointerException
- fixes #3782
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4802345/debug.zip)
> Fixes crash when a file is deleted then redownloaded

- app/src/main/res/layout/related_streams_header.xml
- app/src/main/res/values/strings.xml
- The toggle which appends related streams is called Autoplay. Now that there is an actual Autoplay setting, this can cause confusion for users.
- Confusion
> Change Autoplay to Autoqueue to reduce ambiguity

- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- Do not show anything in case of network error (it can simply be ignored, see #3923 for more info). I had to add a `suggestionsPanelVisible` variable to check if the suggestions panel is visible, because checking visibility on `suggestionsPanel` itself was unreliable due to animations.
- Show a snackbar if the search suggestions generated an (e.g.) extractor error, which still allows writing things into the search box.
- Fix deprecations, warnings and useless null checks in SearchFragment (as reported by Android Studio)
- fixes #3923
I tested the snackbar by manually throwing an exception on every network search suggestion request, and the snackbar is shown correctly.
@opusforlife2 does this behaviour suit you?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5006308/app-debug …
>  Improve search suggestion experience when remote ones can't be fetched

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
When you play one video and then select another the player will stop loading the first stream. Which theoretically saves some megabytes while next video is loading.  So the first video will NOT stop playing but will stop loading more parts that will never be viewed because the second video shows up.
closes #4232 
[disabled-preloading.zip](https://github.com/TeamNewPipe/NewPipe/files/5184067/disabled-preloading.zip)
> Disabled preloading when switching streams

- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/report/UserAction.java
- app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
- app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
- app/src/main/res/values/settings_keys.xml
The difference between "detail page" and the video player is only the phone's orientation. Therefore, we decided to remove the open "Detail Page" option from the share menu. To handle entries from older versions, I added a migration system for the settings / shared preferences which is quite similar to the one used in for the DB.
With the new app workflow introduced by the unified player PR, it is possible to minimize the video player to the bottom while doing other stuff in the app. However, this does only apply to the main fragment. When a user opens the settings or the about screen, the player stops. That's bad UX. For this reason, I set the "Minimize on app switch" setting to "background" instead of "None" to allow seamless transitions within the app as well as when closing NewPipe. …
> Add settings migration, remove "Detail page" option from share dialog and minimize to background by default

- app/build.gradle
When I work on PRs from other people I am used to calling the local branches `prNUMBER`, i.e. `pr3178`. But all such names resulted the same app package id, since numbers were stripped completely, leading to conflicting APKs (e.g. https://github.com/TeamNewPipe/NewPipe/pull/4259#issuecomment-699543016 ). This PR fixes the issue by only stripping the numbers at the beginning of the git branch, [as required by Android](https://stackoverflow.com/questions/12041857/what-is-the-rule-of-the-name-of-the-packages-that-start-with-number#12042111), but not all of the others. While I was at it I also removed `toLowercase()` since package ids needn't be only lowercase, according to [the same SO](https://stackoverflow.com/questions/12041857/what-is-the-rule-of-the-name-of-the-packages-that-start-with-n …
> Allow numbers and uppercase letters in app package id

- app/src/main/res/values/strings.xml
- Spelling
Not sure what "Change the download folders to take effect" means…
> String improvements

- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
> Fix auto-queue with no next videos

- app/src/main/res/layout-large-land/player.xml
- app/src/main/res/layout/player.xml
- Now the user cannot interact with the controls behind the video queue in the main player
- https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-699863945 - "open a playlist in full-screen mode. while playing, tab the top-right button to show the queue. the bug: although the queue window is on top, you can still accidentally press the player ui buttons such as the video quality menu . I think the queue window should block player buttons until dismissed."
[tap-behind-queue.zip](https://github.com/TeamNewPipe/NewPipe/files/5302041/tap-behind-queue.zip)
> Prevent tapping behind queue in main player

- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- app/src/main/res/layout/list_comments_item.xml
- app/src/main/res/values/dimens.xml
- #4205 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5300447/app-debug.zip)
> Disabled commenter image view on LoadThumbnail set to false

- app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
- app/src/main/res/layout-large-land/player.xml
- app/src/main/res/layout/play_queue_item.xml
- app/src/main/res/layout/player.xml
Overlays were off-centered before this PR. By overlays I mean volume slider, brightness slider, loading icon, etc. Now it's fixed.
Also excluded play/prev/next buttons from swipe interception so now it's not possible to drag them up/down with expectation to drag the whole player.
If you'll find any issue, please, fix it yourself or just drop the PR because waiting of the fix from my side will take months. Thank you for understanding.
P.s. so many changes in player.xml in diff view but actually it's just the overlays were included into top level relativelayout to be able to position them via one assigment of paddings. For review it's easier to open previous player.xml and new player.xml side-by-side.
https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-701459044 …
> Player overlays now centered

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout-large-land/player.xml
- app/src/main/res/layout/fragment_video_detail.xml
- app/src/main/res/layout/player.xml
- ~~Fix invisible play queue item drag button: https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-701379310~~ reverted this, as it is already covered by #4360
- Fix play queue close button always being white regardless of theme.
- Prevent touches behind minimized player: https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-700726544
- Make player close button always white regardless of theme, like all other player controls.
- Make thumbnail in `large-land` minimized player a little bit bigger, since there is plenty of horizontal space.
- Fix `Context.startForegroundService() did not then call Service.startForeground()` crash, happening when the foreground service is started too late on really slow devices. So now I start the foreground service directly in …
> Random fixes and improvements

- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- Use `DisplayCutoutCompat` instead of `DisplayCutout` in `VideoPlayerImpl`.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5289781/debug.zip)
> Use DisplayCutoutCompat in VideoPlayerImpl.

- app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
- Fixes #4390 by just adding a null check.
- Prevents Android from showing how much time ago a notification was created or updated: seeing when a notification was last updated is mostly useless, since it is distracting and does not really provide a useful information due to it being changed every time the notification is updated; also other players hide it. The freed space could be used to show other useful information in the future (or now, if you have any suggestion)
@baraa272 @opusforlife2 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5327845/app-debug.zip)
> Notification fixes

- app/src/main/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
- app/src/main/res/values/bools.xml
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/debug_settings.xml
Don't show the Leaks launcher icon. Now there's a button in the debug settings to open it. Btw it was already possible to open it in new Android versions by long pressing NewPipe's launcher icon and then tapping on Leaks.
> Hide Leaks launcher icon

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Some users don't know how to properly tick the check boxes. So I've modified the issue templates to give an example each.
> Added an example of how to use Markdown checkbox

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersionTask.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
- app/src/main/java/org/schabi/newpipe/player/helper/LockManager.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
- app/src/main/java/org/schabi/newpipe/util/ListHelper.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
- app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/java/us/shandian/giga/util/Utility.java
- checkstyle-suppressions.xml
- Use `ContextCompat`'s `getSystemService` and `startForegroundService` methods.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5338521/debug.zip)
> Use ContextCompat methods.

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- Removed the condition that there must be more than one video in the queue for the confirmation dialogue to be shown.
- closes #4459
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5356348/app-debug.zip)
> Ask for confirmation before clearing queue even if only 1 video in it

- app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/settings/HistorySettingsFragment.java
This PR fixes an inconsistent behaviour when deleting a stream from history: the stream state was not being deleted, thus potentially leaving trace of the fact that that specific video was watched. Also see #4393. This PR just adds a line to also delete the stream state when deleting a single stream from the history fragment.
Fixes #4393 
@e-edgren
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5328446/app-debug.zip)
> Also delete stream state when deleting stream history

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/content_settings.xml
This PR changes the titles for "Show age restricted content" and "Enable YouTube's Restricted Mode" and adds a summary to them, since they have been confused by many users lately. In order to reduce redundancy in translations, I also changed the restricted-video-error string to include a `%1$s` instead of the duplicate "Show age restricted content" string. If the latter change causes prolems with translation syncing I can revert it. @wb9688 @opusforlife2 @comradekingu what do you think of these strings?
I also tested whether the latter change cause problems with languages different than English, where `%1$s` is not there yet, but it isn't creating problems.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5301355/app-debug.zip)
> Improve age restriction and yt restricted content strings

- app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
This PR adds a 2-finger-touch gesture to the `CustomBottomSheetBehavior` to dismiss/close the player when the player is pulled down with two fingers.
- closes #4469 
[app-debug-two-finger-close-player.zip](https://github.com/TeamNewPipe/NewPipe/files/5358993/app-debug-two-finger-close-player.zip)
> Two finger to close player gesture

- .github/PULL_REQUEST_TEMPLATE.md
> Pull request template reworked

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/content_settings.xml
Add button in settings to clear reCAPTCHA cookies
Fixes #4279
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5378041/app-debug.apk.zip)
> Add button in settings to clear reCAPTCHA cookies

- app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItemBuilder.java
This PR removes touch listeners from thumbnails in playlists and queues, making the latter reorderable only using the handle on the right. Though I think the drag-by-thumbnail was introduced for some reason, so I'd be ok if this PR gets rejected because of a real-life use of the drag-by-thumbnail.
Closes #4523
@nbmrjuhneibkr @opusforlife2 @Swyter what do you think of this?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5395830/app-debug.zip)
> Don't rearrange lists by dragging the thumbnails

- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderWithMenuItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
- Use some functions in the Core KTX library.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5395811/debug.zip)
> Use Core KTX functions.

- app/build.gradle
- app/src/debug/java/org/schabi/newpipe/DebugApp.kt
- app/src/main/java/org/schabi/newpipe/App.java
- Use multidex for all build types instead of only debug builds.
- 
debug.zip
> Use multidex for all build types.

- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/res/layout/activity_about.xml
- Migrates AboutActivity to viewpager2, the first (and hands-down the easiest) of the viewpager trio (the others being MainFragment and VideoDetailFragment (oh god no), respectively). Whoever dares migrate the next two, may the odds be ever in your favor.
- Nothing, and if we're lucky, doesn't create any either
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5396845/app-debug.zip)
> Migrate AboutActivity to ViewPager2

- app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistDAO.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java
- app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistCreationDialog.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
- Added methods to `PlaylistDAO` and `LocalPlaylistManager` to get an observable for checking if there is a playlist
- Added method `checkPlaylists` to `PlaylistAppendDialog` which gives the opportunity to react on existing playlists
- Inserted the check into the three corresponding places (menus + background player)
- fixes #4339 
[app-debug-fix-createplaylist.zip](https://github.com/TeamNewPipe/NewPipe/files/5295452/app-debug-fix-createplaylist.zip)
> Fix PlaylistAppendDialog showing when no local playlists exist

- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
This PR fixes a random crash happening sometimes when messing with the miniplayer while it's still starting. According to [this SO](https://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit) the solution is just to replace `commit()` with `commitAllowingStateLoss()`, which may not be a real solution (state loss should never happen in theory) but is surely better than making the app crash completely.
This was the stack trace:
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1691)
at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1731)
at …
```
> Fix IllegalStateException after onSaveInstanceState

- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/settings/NotificationSettingsFragment.java
- Use `TextViewCompat`'s `setCompoundDrawablesRelativeWithIntrinsicBounds()` method to support displaying drawables properly with RTL layouts on API level 17 and higher while allowing this change to be used in NewPipe Legacy.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5419339/debug.zip)
> Use TextViewCompat.setCompoundDrawablesRelativeWithIntrinsicBounds().

- app/src/main/java/org/schabi/newpipe/settings/NotificationSettingsFragment.java
- Use `DrawableCompat` to tint the retrieved notification icon in `NotificationSettingsFragment`.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5419320/debug.zip)
> Use DrawableCompat.

- app/src/main/java/org/schabi/newpipe/settings/NotificationSettingsFragment.kt
- app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
- app/src/main/res/layout/settings_notification.xml
- app/src/main/res/xml/notification_settings.xml
- Convert `NotificationSettingsFragment` into a custom `Preference`
- extract scale switch out of this
- Create "standard" preference with scale switch and custom preference above
- closes  #4646
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5443584/app-debug.zip) (updated with Stypox suggestions)
- `Preference.onDetached()` seems to equivalent to `Fragment.onPause()` for the purpose of saving the preference and recreating the notification.
- From the doc on the 4 constructors of `Preference`, only modifying the one that i did should be enogh (I think).
> Convert notification actions to a custom preference

- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/local/feed/FeedDatabaseManager.kt
- app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/util/Localization.java
- app/src/main/java/org/schabi/newpipe/views/ExpandableSurfaceView.java
- app/src/main/java/org/schabi/newpipe/views/FocusOverlayView.java
- app/src/main/java/us/shandian/giga/io/StoredDirectoryHelper.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- app/src/main/res/xml/content_settings.xml
- app/src/main/res/xml/notification_settings.xml
- app/src/main/res/xml/video_audio_settings.xml
- Don't use dumb loser numbers when checking the Android OS version
- Replace a getSystemService(LayoutInflater) with LayoutInflater.from
- Updates the viewpager2 to use the preferred version of the state adapter
- Add missing app:iconSpaceReserved settings
- Some miscellaneous code improvements
- None that I'm aware of
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5469751/app-debug.zip)
> More miscellaneous little fixes and improvements

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistLocalItem.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/util/ListHelper.java
- app/src/main/java/us/shandian/giga/get/Mission.java
- app/src/main/java/us/shandian/giga/service/DownloadManager.java
- build.gradle
- checkstyle-suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
* Add support for [Java 8 API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).
* Make use of APIs introduced in Java 8, such as the `Comparator.comparing` methods (using the [the Java 8 Date/Time API](https://developer.android.com/reference/java/time/package-summary) has been moved to [a separate PR](https://github.com/TeamNewPipe/NewPipe/pull/4556)).
* Using Java 8 API desugaring also incorporates [bug fixes](https://bugs.openjdk.java.net/browse/JDK-8028564) for `ConcurrentHashMap` on Android Lollipop.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5470477/debug.zip)
> Use Java 8 APIs.

- app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
- app/src/main/java/org/schabi/newpipe/settings/NotificationSettingsFragment.kt
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/notification_settings.xml
- Add option to not colorize notifications
- Setting is located under notifcation
- closes #4488
updated after rebase
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5471377/app-debug.zip)
> Add option to not colorize notification

- app/src/main/java/org/schabi/newpipe/player/event/BasePlayerGestureListener.kt
- app/src/main/java/org/schabi/newpipe/player/event/DisplayPortion.kt
- app/src/main/java/org/schabi/newpipe/player/event/DoubleTapListener.kt
- app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
This PR separates the logic behind the player gestures (for example popup position observation) and the UI (for example show/hide controls and adjusting the brightness during scrolling) This way it is more readable.
- Created `BasePlayerGestureListener` which handles the logic and provides abstract methods for listening
- Now `PlayerGestureListener` contains only visual code
- Added `DisplayPortion` enum class (`LEFT`,`MIDDLE`,`RIGHT` for double tap, `LEFT_HALF`, `RIGHT_HALF` for scrolling)
- Added multi-double-tap-logic (will be used by #4264 soon)
[app-debug-0.20.2-fix.zip](https://github.com/TeamNewPipe/NewPipe/files/5458220/app-debug-0.20.2-fix.zip)
> Separate player gesture logic and UI

- app/build.gradle
- app/src/main/res/values/strings.xml
This are the new steps:
1. Go to this URL: https://takeout.google.com/takeout/custom/youtube
2. Log in when asked
3. Click on \"All data included\", then on \"Deselect all\", then select only \"subscriptions\" and click \"OK\"
5. Click on \"Next step\" and then on \"Create export\"
6. Click on the \"Download\" button after it appears and 
7. From the downloaded takeout zip extract the .json file (usually under \"YouTube and YouTube Music/subscriptions/subscriptions.json\") and import it here
Point 7, i.e. extracting things from the archive, can't be done automatically, due to the different structure for different localizations.
Fixes #4720
TeamNewPipe/NewPipeExtractor#452
@simula67 @inigosola @Djay86 @IvanProgramming @Saecki 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/547 …
> Change YouTube subscription import instructions to Google takeout

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.java
- app/src/main/java/org/schabi/newpipe/settings/MainSettingsFragment.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- Use RxJava instead of `AsyncTask` to execute asynchronous code, as `AsyncTask` has been deprecated starting with API level 30.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5492430/debug.zip)
> Use RxJava instead of AsyncTask.

- app/src/main/java/org/schabi/newpipe/database/Converters.java
- app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt
- app/src/main/java/org/schabi/newpipe/database/feed/model/FeedLastUpdatedEntity.kt
- app/src/main/java/org/schabi/newpipe/database/history/model/SearchHistoryEntry.java
- app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntity.java
- app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntry.kt
- app/src/main/java/org/schabi/newpipe/database/stream/StreamStatisticsEntry.kt
- app/src/main/java/org/schabi/newpipe/database/stream/dao/StreamDAO.kt
- app/src/main/java/org/schabi/newpipe/database/stream/model/StreamEntity.kt
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/ktx/OffsetDateTime.kt
- app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
- app/src/main/java/org/schabi/newpipe/local/feed/FeedDatabaseManager.kt
- app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
- app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
- app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
- app/src/main/java/org/schabi/newpipe/local/holder/LocalItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/PlaylistItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistItemHolder.java
- app/src/main/java/org/schabi/newpipe/util/Localization.java
- checkstyle-suppressions.xml
- Use the Java 8 Date/Time API in both NewPipe and the NewPipe extractor.
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/417
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5468440/debug.zip)
> Switch to the Java 8 Date/Time API.

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
This fixes a NullPointerException caused by repeated `getItem()` calls on a queue which could possibly change in the meantime. So even though the result of `getItem()` was checked for nullity even before, its nullity state could change throughout time, and therefore a NPE was possible (still, really rare, and this is the best explanation I could give). Anyway, this simple fix only calls `getItem()` once, which should solve this problem and also possibly improving performance
Fixes part of #4546 (not linking though)
@yashpalgoyal1304 if you are able to reproduce your issue, could you test this?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5397189/app-debug.zip)
> Fix NullPointerException in queue handling

- app/src/main/java/us/shandian/giga/ui/common/ProgressDrawable.java
Codacy found issues "Don't use floating point for loop indices. If you must use floating-point, use double."
- 
- 
debug.zip
> Change loop index from float to int

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/player/event/BasePlayerGestureListener.kt
- app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
- app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/res/values/settings_keys.xml
- Unify all ways of opening the VideoDetailFragment into two methods: `openVideoDetailFragment()` which sends the new data directly to the fragment manager, `openVideoDetail()` which sends an `Intent` received by `MainActivity` which in turn calls `openVideoDetailFragment()`.
- The arguments taken by `openVideoDetailFragment()` have changed: `autoPlay` is not there anymore, and `switchingPlayers` was added to be able to always determine correctly if the function was called as a way to switch players. `autoPlay` is now calculated based on the user's preference, on `switchingPlayers` and on whether there is already a background/popup player running. For more info see [these lines](https://github.com/TeamNewPipe/NewPipe/pull/4562/files#diff-7c684dc26bc21808937b0cd7c85de9810279b15b2ba4fdd2e31a …
> Fix opening VideoDetailFragment and much more

- app/src/main/java/org/schabi/newpipe/settings/SelectPlaylistFragment.java
This PR fixes a bug where some UI code was not being run on the main thread due to a missing `.observeOn(AndroidSchedulers.mainThread())`. I also did some refactoring of code inside `SelectPlaylistFragment.java`, since there were some unused things and some things were messy.
Fixes #4769
@RaveZero could you test if this fixes your issue?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5475307/app-debug.zip)
> Fix playlist select dialog and do some refactoring

- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/util/Localization.java
- Fixes an issue [mentioned](https://github.com/TeamNewPipe/NewPipe/issues/4851#issuecomment-730120966) by @opusforlife2.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5570398/app-debug.zip)
> Call DateWrapper's offsetDateTime() instead of date().

- app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/notification_settings.xml
- Readd option to not show thumbnail on the lock screen
- Setting is located under appearance
- closes #4489
- closes #4651
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5540406/app-debug.zip)
> Add option to hide thumbnail on lock screen

- app/src/main/java/org/schabi/newpipe/database/history/dao/StreamHistoryDAO.java
- app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistStreamEntry.kt
- app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
- app/src/main/java/org/schabi/newpipe/database/stream/StreamStatisticsEntry.kt
- app/src/main/java/org/schabi/newpipe/database/stream/model/StreamStateEntity.java
- app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java
This PR improves the binding for local list items (in playlist details and history) which require the progress time from streams (red indicator) by adding the field `progressTime` to some classes. The field is retrieved directly from the database and doesn't need to be fetched later (which blocked the UI by calling `blockingGet`).
With this change it is also easier to compare the items for changes more efficient when the lists are calculated asynchronously sometime in the future (e.g. through `ListAdapter` or Groupie).
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5542397/app-debug.zip)
> Improve performance for some updateState calls (local lists)

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
- app/src/main/res/layout/fragment_feed.xml
added pull to refresh to what's new section of app
- fixes #3329
- 
debug.zip
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5542783/app-debug.zip)
> Pull to Refresh Feed

- app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
This PR fixes the issue that the player didn't respected the brightness/volume gesture setting. When disabling one of them while the other is enabled should change the value for the whole screen instead of just disable the display portion. I didn't know of this behavior :`)
I also moved the `isBrightnessEnabled` and `isVolumeEnabled` to the actual `onScroll`-callback. If a stream is opened or playing and you'll change one or both toggle states the setting won't be applied for this opened `Fragment` (checked on 0.20.2).
- fixes #4926 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5575851/app-debug.zip)
> Fix respecting brightness-volume-gesture settings

- app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/StateSaver.java
- app/src/main/java/org/schabi/newpipe/util/ZipHelper.java
- app/src/main/java/us/shandian/giga/get/DownloadInitializer.java
- app/src/main/java/us/shandian/giga/postprocessing/Postprocessing.java
- app/src/main/java/us/shandian/giga/util/Utility.java
- checkstyle-suppressions.xml
- Use the [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) feature, as enabling Java 8 support backports the functionality to API levels lower than 19, allowing it to be used in NewPipe Legacy.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5498684/debug.zip)
> Use try-with-resources.

- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- Dispose of the `Disposable` created by `RxView.clicks()` in `BaseStateFragment`.
debug.zip
> Dispose of RxViews disposable in BaseStateFragment.

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
The crash was caused by an `Observable`'s `Callable` returning `null` when fetching the latest available app version without internet connection, but RxJava's `Observable`s do not accept `null` results. So I used a `Maybe` instead, and removed a `null` check inside the subscriber since nullity is already taken care of by the `Maybe`. I also did some refactoring in the `CheckForNewAppVersion` file.
A further crash was caused by the `onError()` interface not being implemented. That produced a crash instead of handling the connectivity error.
Fixes #4920
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5577476/app-debug.zip)
> Fix crash on startup when there is no internet connection

- app/src/main/java/org/schabi/newpipe/report/ErrorInfo.kt
-  closes #4980
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5591852/app-debug.zip)
Note that loading comments always throws an error in this apk, since i changed the extractor for easier manual testing
@TobiGr @Stypox
> Make ErrorInfo contructor public

- .github/CONTRIBUTING.md
Readable text in the guidelines.
- Easier contributions
debug.zip
> Contributing guidelines reworked

- app/src/main/java/org/schabi/newpipe/ktx/OffsetDateTime.kt
- app/src/main/java/org/schabi/newpipe/util/Localization.java
- app/src/test/java/org/schabi/newpipe/ktx/OffsetDateTimeToCalendarTest.kt
- Works around an issue reported by @opusforlife2 in which the ID of the UTC `ZoneOffset` might be null (even though its documentation explicitly says that a `ZoneId`'s ID value is not null).
[app-release.zip](https://github.com/TeamNewPipe/NewPipe/files/5671795/app-release.zip)
> Add a workaround for a possible null offset ID.

- app/src/main/AndroidManifest.xml
- Update list of Invidious URLs that work in the app.
- New Invidious URLs don't work in Newpipe.
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/463
> Update Invidious URL list in the manifest

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/test/java/org/schabi/newpipe/ktx/OffsetDateTimeToCalendarTest.kt
~~Shows "100+ videos" when the stream count of a playlist is `ListExtractor.ITEM_COUNT_MORE_THAN_100` and shows "∞ videos" when the stream count of a playlist is `ListExtractor.ITEM_COUNT_INFINITE`.
Uses the global `utils.Localization.localizeStreamCount()` function everywhere, i.e. in `PlaylistFragment`, `PlaylistInfoItem` and `ChannelMiniInfoItem` to correctly localize the item count (before it was not used in Playlist-related classes).~~
Now only does as described in the title. As discussed below using YouTube's logo is too risky, so we are using a radio icon instead.
Depends on TeamNewPipe/NewPipeExtractor#280 @XiangRongLin
> Show radio icon as uploader avatar in Youtube mixes 

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- Use `ContextCompat.getDataDir()` to retrieve the app data directory.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5692947/debug.zip)
> Use ContextCompat.getDataDir().

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/res/values/strings.xml
- Display the progress of the hash calculation in `MissionAdapter` using a notification instead of a `ProgressDialog`, as the latter has been deprecated in favor of either a `ProgressBar` or a progress notification.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5676788/app-debug.zip)
> Use a notification instead of a ProgressDialog in MissionAdapter.

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
- Use `ActivityCompat.recreate()` to work around bugs in the platform `recreate` method on API levels below 28.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5693775/debug.zip)
> Use ActivityCompat.recreate().

- app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistStreamEntry.kt
- Method equals has been overridden in the PlaylistStreamEntry class so that the index (in the method 'removeItem' in the Class LocalItemListAdapter) does not return '-1' if the memory address is not the same. In this method, I compare all the different attributes to make sure it's the same object. The hashCode method was generated by Android Studio.
-  fixes #4874
app-deleting-video-refreshing-crashfix.zip
> Fix crash deleting video refreshing

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
- app/src/test/java/org/schabi/newpipe/settings/ContentSettingsManagerTest.kt
- app/src/test/resources/settings/newpipe.db
- checkstyle-suppressions.xml
- Separate database/settings generation logic from the UI.
- Add happy path unit test.
With this seperation, unit tests can be introduced. I just added one as proof of concept for now.
If this style is ok i would work on extracting more stuff out.
This also allows cheap unit tests instead of comparatively expensive androidTests.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5624885/app-debug.zip)
> Extract export database logic into own class

- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
- app/src/main/res/values/strings.xml
This PR changes all NewPipe's URLs to its new website domain name ([newpipe.net](https://newpipe.net)), in order to prevent redirects from the old domain ([newpipe.schabi.org](https://newpipe.schabi.org)) to the new domain, in AboutActivity and in CheckNewAppVersion.
Not really needed, because the changes doesn't impact code (?)
> Update NewPipe's website domain name in the app

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
#5176 changed `homeDir` from type `String` to `File`. #5059 was based on `homeDir` being a `String`. It was incorrectly auto-resolved by git.
@TobiGr @Stypox
> Fix compile error caused by auto merging

- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
- app/src/test/java/org/schabi/newpipe/ReCaptchaActivityTest.kt
- app/src/test/java/org/schabi/newpipe/ktx/OffsetDateTimeToCalendarTest.kt
This PR removes the `pbj=1` parameter from the URLs loaded in the reCAPTCHA webview, so that an actual HTML page is loaded instead of the ajax json requested by the extractor, which would render as a blank page.
Hopefully fixes #3714
This apk throws a `ReCaptchaException` on every request, with the first request being the "test" search, always run on app opening.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5710472/app-debug.zip)
> Remove pbj=1 parameter from YouYube urls in recaptcha activity

- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
Does not contain device info and should also fix some issues about recaptchas not showing up
This fixes the issue about the user agent containing device info and should also fix some issues about recaptchas not showing up.
This PR also improves code style and fixes an Android Studio lint.
Note: the desktop page is now loaded, which is good in my opinion since it is more likely the correct ReCaptcha is served
Fixes #4313
Probably a little bit useless, but here is an apk which throws a ReCaptchaException on every request: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5717230/app-debug.zip)
> Use user agent of DownloaderImpl also in ReCapthaActivity

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
- app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/activity_downloader.xml
- app/src/main/res/layout/activity_error.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/settings_layout.xml
- Use [view binding](https://developer.android.com/topic/libraries/view-binding) in the activities, as Kotlin synthetics have been [deprecated](https://proandroiddev.com/migrating-the-deprecated-kotlin-android-extensions-compiler-plugin-to-viewbinding-d234c691dec7) in favor of view binding.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5611546/debug.zip)
> Use view binding in activities.

- app/src/test/java/org/schabi/newpipe/settings/ContentSettingsManagerTest.kt
Make initialization of `File`s in `ContentSettingsManagerTest.ExportTest` only run once per class and not before each test. They are only read from.
- followup to https://github.com/TeamNewPipe/NewPipe/pull/5059#discussion_r543297621
> Use @BeforeClass for ContentSettingsManagerTest.beforeClass

- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
Remove timestamp from share url unless it's youtube.
It produced not found error for PeerTube, media.ccc.de, SoundCloud.
Ideally we should implement this
https://github.com/TeamNewPipe/NewPipe/issues/4316#issuecomment-698948468
> we also shouldn't even use URL there client-side, but add an extractor-side API for getting an URL with timestamp.
but it has been three months and no one is willing to work on this, then I'd like to get this PR merged for the next release.
- fixes https://github.com/TeamNewPipe/NewPipe/issues/4316
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5720264/app-debug.zip)
> Remove timestamp from share url for all services except youtube

- README.ko.md
- README.md
This PR changes NewPipe's website domain to the new domain in readmes.
#5109
> Change website domain of NewPipe in readmes

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
- app/src/main/java/org/schabi/newpipe/util/Localization.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/fragment_video_detail.xml
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/content_settings.xml
Add support for displaying stream and search query meta info. Can be disabled in the content settings.
Closes #4614
TeamNewPipe/NewPipeExtractor#451
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5698843/app-debug.zip)
> Display meta info about search query, stream creator or topic

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/res/values-v21/styles_services.xml
- app/src/main/res/values/colors_services.xml
- app/src/main/res/values/styles_services.xml
Caused by changing service name in TeamNewPipe/NewPipeExtractor#472
Fixed `media.ccc.de` service color not used (NewPipe used the default color theme (YouTube) instead).
This was caused by changing the service's name in TeamNewPipe/NewPipeExtractor#472
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5735782/app-debug.zip)
> [media.ccc.de] Fix service color

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
- app/src/main/res/drawable/ic_live_tv_black_24dp.xml
- app/src/main/res/drawable/ic_live_tv_white_24dp.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Add support for listing media.ccc.de live streams (Kiosk for streaming.media.ccc.de) [works!]
Viewing streams is not yet possible. I have had no chance the test the current implementation, but I believe it is not going to work,
Adresses #5271 
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/500
- #5251 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5744545/app-debug.zip)
> [media.ccc.de] Add "live" kiosk

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
- app/src/main/res/values/strings.xml
Adds media.ccc.de's "recent" page (https://media.ccc.de/recent)
CC @yoshimo
- Closes #5206
- TeamNewPipe/NewPipeExtractor#494
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5732334/app-debug.zip)
> [media.ccc.de] Add "recent" kiosk

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- disable restoring brightness if user has disabled brightness gesture
- #4481
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5743481/debug.zip)
> disable restoring brightness if brightness gesture is disabled

- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
First time looking into the source for NewPipe, if anything needs to be updated or done in a different way let me know and I will be happy to update.
When the play queue was null, and this method was called a null pointer exception would be thrown. This change adds an additional check to see if the play queue is not null before making additional changes.
I didn't open an issue, because this seemed like a such a small straightforward issue. I did search and didn't see any other related issues.
This is the error I got from the app, where I can see a NPE being thrown in the animatePlayButtons method, when getting the index of the play queue.
```json
{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "en-CA",
"content_country": "CA",
"app_language": "en_CA", …
```
> Fix null pointer exception in play button method

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
- Updates AndroidX Media from a transitive version of 1.0.1 to a declared version of 1.2.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/media))
- Simplifies some methods, as the compat classes use the appropriate code automatically
[app-debug-androidx-media-audioreactor.zip](https://github.com/TeamNewPipe/NewPipe/files/5626506/app-debug-androidx-media-audioreactor.zip)
> Use AndroidX Media compat in AudioReactor

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- Else path is now executed, when a timestamp (item.getRecoveryPosition) is present
- Caused by incorrect changes compared to 0.19.8 code. see
https://github.com/TeamNewPipe/NewPipe/blob/v0.19.8/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L305-L327
- it certainly can be written better, but i don't understand half of what that monstrosity of method does
- https://youtu.be/ut3n8-9JM5o?list=PLbQ-gSLYQEc4mnWapHJd0K-sPvLcEwOSS&t=274'
- https://www.youtube.com/watch?v=nSNQ_Qh9Pss&t=203
- closes #5224
see CI 
https://github.com/TeamNewPipe/NewPipe/actions/runs/453310328
> Fix urls with timestamps not being played

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsExportService.java
- app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- remove usage of harcoded package name `org.schabi.newpipe`
- it fixes issues with forks or debug builds, e.g. when you open two newpipe apps (with debug or fork apps), close one notification, it closes all newpipe notifications
- fixes https://github.com/TeamNewPipe/NewPipe/issues/4653
- https://github.com/TeamNewPipe/NewPipe/issues/4653#issuecomment-717509756
- When you pause a video, it resumes on the other newpipe instance
- https://github.com/polymorphicshade/NewPipe/issues/18
- other related bugs
> Dynamically get package name

- README.ko.md
- Both the middle and last steps said to "export database". Changed the latter to "import".
- Possible confusion in Korean users.
> Change "Export" to "Import" in Korean Readme instructions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- See title.
- People assuming the checklist is optional.
> Make it clear that checklist in templates is mandatory

- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/us/shandian/giga/get/DownloadMission.java
- app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
- app/src/main/java/us/shandian/giga/get/sqlite/FinishedMissionStore.java
- app/src/main/java/us/shandian/giga/io/CircularFileWriter.java
- Use `Objects.requireNonNull()` to ensure null safety instead of throwing `NullPointerException`s manually.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5732929/debug.zip)
> Use Objects.requireNonNull().

- app/src/main/AndroidManifest.xml
This PR disable sending metrics to Google when using Android System WebView in NewPipe by adding `<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />` in the manifest of the app, inside the `<application>` tag.
Fixes #5335
[app.zip](https://github.com/TeamNewPipe/NewPipe/suites/1755326542/artifacts/33399585) (from CI)
> Disable sending metrics to Google when using Android System WebView

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
… Space button.
- While in Fullscreen mode, support hardware space button to play/pause the video.
> In Fullscreen playback, toggle play/pause with hardware space button

- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/util/KoreUtil.java
- app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
this allows the user to long press on a video in any list (search, history, playlist, etc) and send it directly to Kodi. this change honors the existing `Show "Play with Kodi" option` setting and only displays on streams supported by Kore.
there is opportunity to reduce duplication in this part of the code base generally.
closes: #5157
- add list context menu item to "Play on Kodi"
- #5157
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5752846/app-debug.zip)
> add list item to play video on kodi

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/player/event/BasePlayerGestureListener.kt
- app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
- Use view binding in `VideoPlayer` and `VideoPlayerImpl`.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5732811/debug.zip)
> Use view binding in VideoPlayer.

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/util/Localization.java
- app/src/test/java/org/schabi/newpipe/util/LocalizationTest.kt
- Make Localization.relativeTime testable.
- Add some simple tests
- Problem is global state in static variable `prettyTime`. But for performance reasons on Android that is preferred.
- At first i wanted to make a manager class which would then not be static. similiar how i did #5059 and #5225. But this would come with a performance loss, because every call to `relativeTime` would then create a manager object, create `prettyTime`, determine the app language, etc. https://developer.android.com/training/articles/perf-tips#ObjectCreation
- This solution allows injecting `prettyTime` for tests while only adding a method call when initializing `prettyTime` and otherwise keeping the performance fo `relativeTime`
https://github.com/TeamNewPipe/NewPipe/actions/runs/466273618
> Make Localization.relativeTime testable

- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedVideosFragment.java
- app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupReorderDialog.kt
- app/src/main/res/layout/channel_header.xml
- app/src/main/res/layout/local_playlist_header.xml
- app/src/main/res/layout/playlist_header.xml
- app/src/main/res/layout/statistic_playlist_control.xml
- Use view binding in the fragments, as Kotlin synthetics have been [deprecated](https://proandroiddev.com/migrating-the-deprecated-kotlin-android-extensions-compiler-plugin-to-viewbinding-d234c691dec7) in favor of view binding.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5737560/debug.zip)
> Use view binding in fragments.

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Going from portrait to landscape doesn't toggle fullscreen in tablet mode, so
the reverse action shouldn't do it either.
- https://github.com/TeamNewPipe/NewPipe/issues/4936
~~(Upload doesn't work, gets stuck :/)~~
€: It was localCDN
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5578022/app-debug.apk.zip)
> VideoDetailFragment: Don't exit fullscreen on rotation in tablet UI

- app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- Move setting the pager adapter and view binding to `null` to `onDestroy` from `onDestroyView`.
- #5414 
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5817874/debug.zip)
> Fix the crash that occurs on navigating back to the main fragment.

- app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentAdapter.kt
- app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentItem.kt
- app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
- app/src/main/res/drawable/ic_format_list_numbered_white_24.xml
- app/src/main/res/layout-large-land/player.xml
- app/src/main/res/layout/item_stream_segment.xml
- app/src/main/res/layout/player.xml
- app/src/main/res/values/strings.xml
This PR adds stream segments for the YouTube service to player controls. The feature provides the following behaviors:
- Highlights the current segment depending on the current position of the video (see Preview) / by click
- Scrolls automatically to the current playing segment when the list is opened
- Segments list is visible and the video is changed: if the new video has also segments then the new segments are loaded and it scrolls to the correct position, otherwise the list closes.
Code changes:
- Adds a new button near to the top controls bar
- Uses same layout elements like the play queue => they've been renamed to more generic id/field names, for example `queueLayout` to `itemsListLayout`
- closes #5098 
Check the build artifact page for the debug apk.
Demo (dynamically changing at …
> Add stream segments to player controls

- .github/workflows/ci.yml
- Checkout branch in CI process for pull request. CI process for push already checks out branch correctly https://github.com/XiangRongLin/NewPipe/runs/1703962796?check_suite_focus=true#step:2:456
- This way the debug build app id contains the branch name again. Currently the app id is "NewPipe HEAD"
- `github.head_ref & github.event_name` https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
- `git checkout -B` https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt--Bltnewbranchgt
- PR job force switches the branch: https://github.com/XiangRongLin/NewPipe/pull/9/checks?check_run_id=1703963185#step:3:4
- Push jobs stays unchaged, since it gets skipped: …
> Checkout branch in CI process

- .github/PULL_REQUEST_TEMPLATE.md
Removed the APK testing section from the PR template because debug APKs are built by the automatically-run workflows now.
-_-
> Remove APK testing section from PR template

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupReorderDialog.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/ChannelItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/EmptyPlaceholderItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupAddItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupCardItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupCarouselItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupReorderItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedImportExportItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderWithMenuItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerIconItem.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
- Replace Groupie's Kotlin synthetics module with its view binding module, as synthetics have been deprecated starting with Kotlin 1.4.20.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5823859/debug.zip)
> Switch to Groupie's view binding module.

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
- app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/fragment_video_detail.xml
- Make use of view binding in `VideoDetailFragment`.
**Note:** Android Studio may indicate that some of the binding fields are unavailable, but they are actually generated correctly in the binding class:
> Use view binding in VideoDetailFragment.

- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
- app/src/main/java/org/schabi/newpipe/player/Player.java
This PR fixes a random crash when closing the popup player. I could reproduce it consistently on `dev` by closing the popup player via the `X` in the notification, but it also happens on `0.20.8` at random times.
<details><summary><b>Crash log</b></summary><p>
```
java.lang.RuntimeException: Unable to stop service org.schabi.newpipe.player.MainPlayer@56760fc: java.lang.IllegalArgumentException: View=android.widget.FrameLayout{759337c V.E...... ........ 0,0-1080,1965} not attached to window manager
at android.app.ActivityThread.handleStopService(ActivityThread.java:4136)
at android.app.ActivityThread.access$1900(ActivityThread.java:219)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1896)
at android.os.Handler.dispatchMessage(Handler.java:107)
at …
```
> Prevent IllegalArgumentException when closing popup

- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
This was caused by view binding PR. initListeners was being called before the bindings were assigned, and therefore the click listener was never setup. @Isira-Seneviratne
> Fix reload feed button does nothing

- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
- app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
Show a Toast when no app is present on user's device to open a content in an app and in a browser and use an ACTION_CHOOSER intent with the ACTION_VIEW intent put as an extra intent in the update notification.
https://github.com/TeamNewPipe/NewPipe/pull/5187#issuecomment-761558752
> Fix crash when no browser is present and use an ACTION_CHOOSER intent in the app update notification

- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
Fixes 2131755371 appearing when the feed finishes loading due to an int string resource not being converted using `getString()`
> Fix number being shown instead of corresponding string resorce in feed

- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
This fixes the animation of the X button (which is now always shown while the popup is drag aroung) and the animation of the red overlay above the player.
https://github.com/TeamNewPipe/NewPipe/issues/5455#issuecomment-762604619
> Fix popup closing x button animation

- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
`break;`s were missing from a switch statement :man_facepalming: 
While I was at it I also fixed some warnings and did other consistency improvements.
Fixes the comment https://github.com/TeamNewPipe/NewPipe/issues/5455#issuecomment-768879330
> Fix minimize on app switch always opens popup

- app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
I noticed NewPipe does not call [`PreferenceManager.setDefaultValues()`](https://developer.android.com/reference/androidx/preference/PreferenceManager#setDefaultValues(android.content.Context,%20int,%20boolean)) for all settings screens. This PR fixes this, by adding `notification_settings` and `update_settings`.
Probably not doing this didn't cause any issue, since there are always fallbacks when getting preferences, but it surely does not hurt.
> Set all default settings at the beginning

- .github/PULL_REQUEST_TEMPLATE.md
- Re-add APK testing section to PR template
- Add instructions on how to navigate to the APK created by the CI pipeline
- basically reverts #5284
- Here i asked a user to test the bug fix, but he did not know where to install the apk from https://github.com/TeamNewPipe/NewPipe/pull/5464#issuecomment-763735114
fyi @mhmdanas 
@brnwlshubh Would you find the description under the APK testing section sufficient for someone who hasn't used github beforehand?
> Re-add APK testing section to PR template

- app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
This PR fixes a bug that prevents NewPipe to fall back to Google Play Store URL when using InstallApp method. I also updated some JavaDocs and did little improvements. See commit for more details.
> Fix some things in ShareUtils file and do little improvements

- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
- app/src/main/java/org/schabi/newpipe/NewVersionManager.kt
- app/src/main/res/values/settings_keys.xml
- app/src/test/java/org/schabi/newpipe/NewVersionManagerTest.kt
- Save expires header into preferences on version check
- Coerce it between 6 and 72 hours 
- Check expires date before making network request to check for new versions
- #5467
I'd to do some refactoring and add some test if time permitts.
https://github.com/XiangRongLin/NewPipe/actions/runs/501846770
https://github.com/XiangRongLin/NewPipe/pull/10
this apk ignores usual checks for when to run the request
> Respect expires header when checking for new versions

- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
This was probably caused by the binding being set to null since the activity was closing, but the async channel subscription disposable being run just after that. https://github.com/TeamNewPipe/NewPipe/issues/5455#issuecomment-763024066
> Fix channel subscribe button causing crash on closing

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
This fixes the tab layout visibility in video detail fragment when showing age restricted videos:
- never show tab layout if view pager is hidden
- always show view pager and tab layout again when a new stream info has to be shown in video detail fragment 
- https://github.com/TeamNewPipe/NewPipe/issues/5455#issuecomment-774741197
> Fix tab layout visibility with age restricted videos

- app/src/main/java/org/schabi/newpipe/about/License.kt
Remove `License#contentUri`.
I grepped the codebase and found nothing; I also built the project successfully, so I'm almost certain that it can be safely removed.
[app.zip](https://github.com/TeamNewPipe/NewPipe/files/5945398/app.zip)
> Remove License#contentUri

- app/src/main/java/org/schabi/newpipe/ktx/View.kt
Just removed a concatenation to an empty string.
Unnecessary.
> Remove unnecessary concat with empty string

- app/src/debug/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/debug_settings.xml
This PR just adds a "Crash the app" button to the Debug settings, which are only visible in debug builds. This could come in handy sooner or later to debug ACRA.
> Add crash button to debug settings

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
This PR add new error messages (strings added in English and French), on SoundCloud and YouTube services, when a user tries to play:
- a SoundCloud Go+ track
- a SoundCloud track which is blocked in his/her/its country
- a YouTube Music Premium video
- a YouTube paid video (a YouTube movie or a YouTube video which requires a subscription to the video channel)
- a YouTube video which is blocked in his/her/its country (doesn't work for YouTube Music georestricted tracks because of the error message returned by YouTube)
- a YouTube age-restricted video which could not be played, due to YouTube changes for age-restricted videos
| Screenshot of the error message | Content type of error message   |
|---------------------------------|-----------------------------|
| …
> Better error messages for SoundCloud and YouTube unavailable contents

- app/src/main/res/layout/fragment_video_detail.xml
When there are small thumbnails, e.g. with SoundCloud, and one is playing streams in background, the thumbnail was very small in the video detail fragment. This is fixed by setting a min height of `200dp` which is equivalent to the dummy thumbnail's height. 
| -------- | ------- |
| ![screenshot](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/XKMygPfkWvCFXHTSQePEYqqo) | ![Screenshot_1615656123](https://user-images.githubusercontent.com/17365767/111038416-078ae200-8429-11eb-9dcf-619881e6485b.png) |
- no related issues found yet
> [background player] Fix very small thumbnails

- README.md
- Re-add the F-Droid badge
- Remove outdated note about NewPipe being outdated on the official F-Droid repo
Unnecessary.
> Re-add F-Droid badge and remove outdated note

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Fixes empty stream title in mini player info when a stream is started through background player and title of previous stream shown instead of title of the current stream.
| --------- | ------ |
| ![Screenshot_1615662903](https://user-images.githubusercontent.com/17365767/111041552-fa75ef00-8438-11eb-90b7-f51856bdb276.png) | ![Screenshot_1615663038](https://user-images.githubusercontent.com/17365767/111041585-24c7ac80-8439-11eb-8a89-b413ffa24f16.png) |
Closes #5475
> Fix empty stream title in minimized player

- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
The player's resize mode / aspect ratio handling was not stored correctly. For this reason, the resize mode needed to be changed every time the player was started on devices with aspect ratios different to 16:9.
I think the settings key "last_resize_mode" is ambiguous. While it is used to get the recently used resize mode, someone working on the resize mode switcher thought, that the old (to be replaced) resize mode should be stored. 
I did not create a settings migration for this change, because we do not know which preferences were affected by this bug, and which were not.
Fixes #5613
> Fix last resize mode not being restored correctly

- app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
- app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/appearance_settings.xml
Added two device theme settings:
+ Device theme (Dark)
+ Device theme (Black)
Device theme (Dark) and Device theme (Black) will set the theme to light if device's theme is light or unknown, otherwise it will set dark or black.
Available for Android 10+ only, LineageOS 16+ and other ROMs providing dark theme.
Here is a GIF:
- Fixes https://github.com/TeamNewPipe/NewPipe/issues/3420
- Fixes #687
- Fixes **partially** #1535 : fixes for people who can set Automatic (time of the day) theme in Android settings.
[NewPipe_theme.zip](https://github.com/TeamNewPipe/NewPipe/files/5360974/NewPipe_theme.zip)
> Add settings to match device's theme (dark & black)

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/FailedMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/PlaceholderMediaSource.java
Updates ExoPlayer from 2.11 to 2.12
Note that we will have to do another PR to migrate from deprecated mediasession to media2.
However this will most likely require to also rework everything to the new MediaItems instead of working with MediaSources.
For now however this can stay and if ExoPlayer stays being compatible with mediasession we aren't in a rush.
> Update to ExoPlayer 2.12.3

- .github/workflows/ci.yml
- app/build.gradle
- checkstyle.xml
- Add sonar plugin and github actions file for sonar analysis
- Copied from sonarcloud.io setup page with minor adjustments. Adjusted branch to 'dev' and updated versions
- closes #5825 
- #5822 This needs to be done beforehand
> Sonar workflow

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/res/values/strings.xml
- Add toast to inform the user that download started
- Add the right string in values folder
- fixes #5428
> Add toast to inform the user that download started.

- app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
- app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
Reverts part of 731c65cd59e72921389c114f5f5ba4da8374336c, while rebasing I didn't notice that different themes were being used for settings.
Fixes color switches in settings being white instead of red.
> Fix settings switches are not red anymore

- app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
The error panel is now destroyed in `onDestroyView()` and is checked for nullity just in case.
https://github.com/TeamNewPipe/NewPipe/issues/5872#issuecomment-804194124 @B0pol 
> Fix error panel created in onViewCreated() but disposed in onDestroy()

- app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/activity_downloader.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/settings_layout.xml
- Replaces FrameLayout with FragmentContainerView where applicable (go [here](https://developer.android.com/jetpack/androidx/releases/fragment), do Ctrl + F, and put "FragmentContainerView" in the box to see related info and changes, as well as the [reasons for its creation](https://developer.android.com/jetpack/androidx/releases/fragment#1.2.0-alpha02))
- A related post (a bit outdated, but they address the main stuff): https://proandroiddev.com/android-fragments-fragmentcontainerview-292f393f9ccf
- This fixes internal issues related to using FrameLayout; however, I don't know if there's any open NewPipe issues related to this that would be fixed by this change, other than the more dev-facing:
- [Fixes animation z-ordering issues and window insets dispatching to …
> Replace FrameLayout with FragmentContainerView where applicable

- app/src/debug/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/HistorySettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/UpdateSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
- As far as I'm aware, we don't need onCreate in the settings fragments when using PreferenceFragmentCompat, as it calls its own base method (which subsequently calls onCreatePreferences at its end). Please correct me if I have forgotten something.
https://github.com/TeamNewPipe/NewPipe/suites/2318767009/artifacts/48743154
> Clean up unnecessary onCreate in settings fragments

- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
- app/src/main/res/values/strings.xml
Add option to open channel details page when long-pressing items.
- Fixes #5447.
> Add channel details option to long-press menu

- app/src/main/java/org/schabi/newpipe/player/Player.java
- Allow the user to pause/unpause while a video is buffering
- Check whether the `playWhenReady` is true instead of `isPlaying`: `isPlaying` returns false if the video is buffering
- fixes #5263 
> #5263: Allow the user to pause while a video is buffering

- .github/workflows/ci.yml
- expand ci.yml to run instrumeted test
- only run ci pipeline on push/pr against dev and master.
- uses https://github.com/marketplace/actions/android-emulator-runner
- showcase: XiangRongLin/NewPipe#8
- adds 7-8 min to CI pipeline, part of which is parallelized
- #5359 needs to be adresses which i just did by updating kotlin here.
- There currently are only 2 instrumentet tests, which means this doesn't really add much value yet. But i think having this already in place for when it is needed is good.
- At first i wanted it to run it on API level 19 and 29 (min and max SDK) but it fails on 19 with it not being able to find the test (https://github.com/XiangRongLin/NewPipe/runs/1657271924?check_suite_focus=true#step:5:247). I assume its because of some problem with multidex and API < 21 …
> Run Instrumented tests in CI pipeline

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
- app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
- app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
- app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
- app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
Updates ExoPlayer and fixes related deprecations where applicable.
@TacoTheDank I have also changed the setPlayWhenReady calls to play() and pause() where appropriate
the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.
> Update to ExoPlayer 2.13.2

- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
I got a random NullPointerException when clicking fast on the search button, this PR should prevent it, even though it should never happen. 
While I was at it I also fixed two other random NPEs.
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
at org.schabi.newpipe.fragments.list.search.SearchFragment.onOptionsItemSelected(SearchFragment.java:460)
at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2830)
...
```
- Fixes #5587
- Fixes #5812
> Fix some random NullPointerExceptions

- app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- assert statments were used in the code which lead to crash and thus replaced with if clause
- Fixes #5968
> App Crashes when no videos in last played and user interacts with playlistController  fix

- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Disabled media tunneling on affected devices.
In this PR: Formuler Z8 Pro, Z8, CC, Z Alpha, Z+ Neo
- Fixes #3927
- Fixes #5911
This workaround was already tested, now it was just implemented in a more meaningful way.
APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.
> Disable media tunneling on Hi3798MV200

- app/src/main/res/layout/settings_notification_action.xml
Even though the `ConstraintLayout` code seemed right, for some reason the icon to left of the five notification actions under "Settings -> Notification" has width `0dp` and were thus invisible. I don't know when this happened, they were working when the PR about notifications was merged, but nevermind. This fixes it by setting a constant width instead of a constant height, and for some reason only this way `layout_constraintDimensionRatio="1"` does its job forcing the image into a square.
> Fix hidden icon to the left of notification actions in settings

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- check  if the binding is null before attempting to retrieve its objects. 
- Fixes #5973
- Could not reproduce the bug even after several attempts to do so thus had to rely on crash report provided with the issue which clearly shows  _Attempt to read from field 'androidx.viewpager.widget.ViewPager org.schabi.newpipe.databinding.FragmentVideoDetailBinding.viewPager' on a null object reference_ thus we add a check for null value for binding before accessing its objects  
> NullPointerException on screen rotation during exit fix

- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/res/menu/menu_local_playlist.xml
- Functionality to rename Playlist Name from playlist interface
- Fixes #5570
> Add functionality to rename Playlist Name from playlist interface

- app/src/release/res/xml/main_settings.xml
Was changed in DayNight Theme, but only in debug resource and not release resource.
-  Caused by #5927
- `gradle assempleRelease` now works again
- For the future this means that reviewers need to look out for changes in build flavor specific files and make sure that they are made in all flavours (debug and release). But even if it is missed, it will be caught by my nightly builds.
- https://github.com/XiangRongLin/NewPipe-nightly/runs/2261992423?check_suite_focus=true
> Fix release build by updating icon reference

- app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
- app/src/main/java/org/schabi/newpipe/info_list/InfoItemDialog.java
- app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
- app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistCreationDialog.java
- app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/tabs/AddTabDialog.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- Migrates the remaining platform AlertDialogs to AppCompat
- None.
> Migrate rest of AlertDialogs to AppCompat

- app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Disabled broken media tunneling for a single device.
https://github.com/TeamNewPipe/NewPipe/issues/3927#issuecomment-674350079
The workaround (https://github.com/TeamNewPipe/NewPipe/issues/3927#issuecomment-806571342) was tested, this pull request simply adds the affected device to the check implemented in #5969.
> Disable media tunneling on cvt_mt5886_eu_1g

- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- in ChannelFragment.java do not throw emptyStateView error if no videos are present as there will be header in list which shows channel metadata and thus should be visible to user as expected by issue fix, also when there is no video the playlistController is hidden to prevent the app crash
- showEmptySpace() hides all the views in list including header when there is some error so it should be not called when there is header in the list, so changes are done accordingly in BaseListInfoFragment.java
- Fixes #5959
> Fix display of channel details when it has no videos

- app/src/main/AndroidManifest.xml
Allow installation on external storage.
Unfortunately, I'm not in possession of an external SD card, so I can't test this. Those who have SD cards, could you please test this?
Note that NewPipe uses [`Service`s](https://developer.android.com/reference/android/app/Service), which Android's docs state as one of [the features that if present in an app, would mean that it shouldn't be allowed to be installed on external storage](https://developer.android.com/guide/topics/data/install-location). I'm not sure if this means we shouldn't merge this PR, but I figured it would at least be relevant.
- Fixes #251.
https://github.com/TeamNewPipe/NewPipe/suites/2463929014/artifacts/52944489
> Allow installation on external storage

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
> Replaced if/else with switch in ErrorActivity

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
Only show the 'download has started' toast when a download has started. ~~Note, I haven't compiled and tested this.~~
- Fixes #6138 
https://github.com/TeamNewPipe/NewPipe/suites/2554180297/artifacts/55556817
> Only show 'download has started' toast when download is started

- app/src/main/java/org/schabi/newpipe/player/Player.java
Make `loadingPanel` visible when buffering.
- Fixes (2) from https://github.com/TeamNewPipe/NewPipe/issues/6052#issuecomment-825981037
> Fix invisible buffering / loading indicator in player

- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/res/drawable-night/ic_headset.xml
- app/src/main/res/drawable-night/ic_info_outline.xml
- app/src/main/res/drawable-night/ic_picture_in_picture.xml
- app/src/main/res/drawable-night/ic_play_arrow.xml
- use themed context in share dialog when getting the dialog drawables
- use white fill color in night theme for a few drawables
- Fixes Black icons in night theme in share dialog
- fixes (4) in https://github.com/TeamNewPipe/NewPipe/issues/6052#issuecomment-824722284
> Fix black drawables in night themes in share dialog (RouterActivity)

- app/src/main/java/org/schabi/newpipe/App.java
choose the correct default value when getting the reChaptcha cookie from the preferences.
In DownloaderImpl#getCookies(String url) the reChaptcha cookie is set if it is not null. For this reason, the cookie was set in every request.
> Do not set reCaptcha cookie when there is no cookie stored

- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerIconItem.kt
- app/src/main/res/values-kmr/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-sr/strings.xml
> Fix some warnings

- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
noticed logs " CacheDataSink: fragmentSize is below the minimum recommended value of 2097152. This may cause poor cache performance.
this fixes the issue by using ExoPlayers MIN_RECOMMENDED_FRAGMENT_SIZE. Unfortunately that field is private:
https://github.com/google/ExoPlayer/blob/aeb306a164911aa1491b46c2db4da0d329c83c65/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSink.java#L123
Discovered in https://github.com/TeamNewPipe/NewPipe/issues/6207
> Fix: fragmentSize is below the minimum

- README.md
- Fixes #
- Need to make appropriate changes in other translations of README
> Add NoLoginRequired in Readme file

- app/src/main/java/us/shandian/giga/ui/common/Deleter.java
When running `append()`, trigger the `commit()` action immediately and cancel all delayed callbacks for `commit()`.
Snackbars no longer pile up. For previous behaviour, see https://github.com/TeamNewPipe/NewPipe/issues/5660
(Checking if there are any tasks running via [hasCallbacks()](https://developer.android.com/reference/android/os/Handler#hasCallbacks(java.lang.Runnable)) would be nice, but that method is only available in API 29+.)
For a visual comparison:
The current behaviour in NewPipe 0.20.10
[Screencast](https://ix5.org/files/newpipe.mp4) (note: Snackbars keep piling up)
With this PR applied:
[Screencast](https://ix5.org/files/newpipe-dismiss.mp4) (note: No piling up, but users can still undo actions)
https://github.com/TeamNewPipe/NewPipe/issues/5660
[My …
> Downloader: Deleter: Dismiss previous Snackbars

- app/src/main/java/org/schabi/newpipe/player/Player.java
- reverted changes of https://github.com/TeamNewPipe/NewPipe/pull/5929/commits/749c937b8e72758b5b59a2590d717cf5945689b0 to fix #6179
- also checkout https://github.com/TeamNewPipe/NewPipe/issues/6179#issuecomment-837278251 for more details
- Fixes #6179
- Note: The problem only occurs, when the option "History and cache>Resume playback" is set to off
> Fixed player not automatically playing

- app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
- checkstyle-suppressions.xml
-When the removeItem() is called it might happen somehow that object is not in list , in this case indexOf() will return -1 and in this case we should not try to delete object by it's index (i.e is -1)
-Coming to "somehow" this may happen when  
1)the removeItem() is called on duplicate of item in list , in this case we need to implement a way to remove item by it's duplicate as duplicate is not in list
2)the object is already deleted and the UI is not updated (handled this in this PR)
- Fixes #3891
- 
> Fix trying to delete object not in list

- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/debug_settings.xml
Added an option for DEBUG builds only to help users to check if their issues with video (blackscreen or stuttering) are a cause of not working media tunneling on their device / custom os.
> Add debug option to disable media tunneling

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
- app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
Downgrade to fix performance issues with LineageOS
- Fixes #6207 
> Downgrade ExoPlayer to 2.12

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/FilePathUtils.java
- app/src/main/res/values/settings_keys.xml
- app/src/test/java/org/schabi/newpipe/util/FilePathHelperTest.java
To save location of import/export, I add a new preference key for `import_export_path` and save this preference on result of file chooser activity and send it on intent of file chooser on later tries.
So as a user, If a export data on folder `foo`, when I want to import this data, file chooser show `foo` as start path.
- Fixes #6039 
> Save backup import/export location for future import/exports

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/Player.java
Get the duration form the currrent play queue item instead of the player itself if possible. HLS streams do not always come with info on the stream length, so this info get be retrieved from the current play queue item.
- Fixes #5964
- TeamNewPipe/NewPipeExtractor#603
> Add support for PeerTube HLS streams

- .github/workflows/ci.yml
* Follow-up of #6079
* Using adoptopenjdk instead of zulu
* AdoptOpenJDK is unbranded (Zulu is branded)
* AdoptOpenJDK is very close related to OpenJDK / less modified than zulu
* There seem to be no specific commitments regarding the availability of Zulu's free constructions
* Android studio is shipped with OpenJDK:
* See also: https://github.com/actions/setup-java/issues/13, https://dzone.com/articles/java-and-the-jdks-which-one-to-use
* See also: https://github.com/TeamNewPipe/NewPipeExtractor/pull/635
none
> Use AdoptOpenJDK instead of Zulu in GitHub actions

- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
- app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java
- Unit test PlayQueue class
- Clean up and refactor class as necessary (no major changes)
- Fix edge cases in `setIndex(int): void`
On the website, the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.
> Test and clean up PlayQueue

- .github/ISSUE_TEMPLATE/config.yml
Change the IRC link for Matrix users from Freenode to [Libera](https://libera.chat).
> Update Matrix link of NewPipe IRC from Freenode to Libera.chat

- app/src/main/AndroidManifest.xml
Removes requirement for Bandcamp links to end with a `/` (see linked issue).
Additionally, I split the intent filter up into two filters into one for each of these two:
* `*.bandcamp.com`
* `bandcamp.com/?show=*`
This means that links like `https://bandcamp.com/`, `https://bandcamp.com/redeem`, …, are no longer falsely accepted.
- Fixes #6335
- Includes fix from @yashpalgoyal1304 in https://github.com/TeamNewPipe/NewPipe/issues/6335#issuecomment-845302865, which is working ;)
- [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/6544495/app-debug.apk.zip)
> Improve Bandcamp intent filters

- app/src/main/res/layout/main_bg.xml
When the text on the empty fragment was too long (larger font size or longer translation), the text was not centred anymore.
Fixed that and also added a bit more margin to the "NewPip" title.
|  Before  |  After  |
| ---------- | --------- |
| ![Screenshot_20210528-124155_NewPipe](https://user-images.githubusercontent.com/17365767/119973092-53beda80-bfb3-11eb-913a-d5128c6c2c29.png)  |  ![Screenshot_20210528-124856_NewPipe_Debug](https://user-images.githubusercontent.com/17365767/119973091-53264400-bfb3-11eb-93e8-8a3e19edcbee.png)  |
> Fix empty fragment text not centered when text longer than one line

- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- Use `getSpans` and `removeSpan` to remove text styling when pasting
- Fixes #5912 
On the website, the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.
> Fix unwanted rich text formatting when pasting

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- The result output in subscribe may throw error and thus need to be handled, so I did it :)
- Fixes #6107
> Error handling in subscribe() in DownloadDialog

- app/build.gradle
Upgrade PrettyTime to 5.0.1, which [fixes a minor mistake in the Romanian translations](https://github.com/ocpsoft/prettytime/commit/f6789675d6efff4c772ec4c136a9c602ec75c921) and [adds the Somali language](https://github.com/ocpsoft/prettytime/commit/8f374c56d6edfc4eaa0eb5647f25acac444db674), among other things.
They also [updated the README to state that PrettyTime 5 requires Java 8](https://github.com/ocpsoft/prettytime/commit/acd14391b7a94a42cae21088ef8f0f8562a1c1d4). I'm not sure if this affects NewPipe (as everything has been working fine before), but I thought I'd point it out.
- Fixes #6404
- Fixes #5805 (yes, I know this is closed)
https://github.com/TeamNewPipe/NewPipe/suites/2886740373/artifacts/64612759
@nadiration @iamthesenate1 can you test this?
> Upgrade PrettyTime to 5.0.1

- app/src/main/java/org/schabi/newpipe/fragments/EmptyFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- The EmptyFragment should not have a constructor at all.
- Now a static methods creates the Fragment and arguments are handled via a Bundle.
- Fixes #5941
> fix Rotation crash on „Video not available“ page (#5941)

- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
In #6280, @TiA4f8R notes that they had to add the "open in browser" button in more places. I was not aware of that when I made #5851 though, so this PR does it instead.
- Fixes part of #6155 (I confirmed that it works in non-local playlists now, but it still doesn't work in local playlists and the "What's New" feed)
@SameenAhnaf @opusforlife2 can you both try this?
> Add "Show channel details" option in remote (non-local) playlists

- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
This PR adds the `Open in browser` option to long-press menu when long pressing a stream and a subscription.
Screenshots:
- Long pressing a subscription:
- Long pressing a stream:
> Add Open in browser option to long-press menu

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- Set ImportExportDataPath only on successful export
- Set ImportExportDataPath only on successful import
- Commit path immediately when import backup 
- Fixes #6397
https://github.com/TeamNewPipe/NewPipe/suites/2872990922/artifacts/64206682
> Fix and improve setting import and export paths

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- Applies the changes of https://github.com/TeamNewPipe/NewPipeExtractor/pull/628 to fix #6323
Demo:
⚠️ Note: The string is currently not localized and always in "en-GB"
- Fixes #6323 
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/628
> [YouTube] Fix broken likes in comments

- app/src/main/java/org/schabi/newpipe/player/Player.java
- When displaying the segment panel hide the queue duration text
- Fixes #6441
> Hide queue duration when displaying segment panel

- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/res/layout/item_metadata.xml
- app/src/main/res/layout/item_metadata_tags.xml
Increase width of metadata text view.
Some translations come with longer words causing them to wrap at strange positions
| -------- | -------- |
| ![Screenshot_1623003898](https://user-images.githubusercontent.com/17365767/120935917-4e753480-c705-11eb-8838-b0d8ab698877.png) | ![Screenshot_1623003780](https://user-images.githubusercontent.com/17365767/120935892-2e457580-c705-11eb-9e92-5346c15efc07.png) |
> Increase width of metadata text view

- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueAdapter.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItemHolder.java
- app/src/main/res/layout/play_queue_item.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/dimens.xml
This PR uses the contraint layout in play queue item to improve how it looks, in particular on small devices (see screenshots below). The item became a little bit bigger, but that's just because the thumbnail now is really `16:9` (its height was squished, before). I also removed the "selected" indicator that was present to the left of the item a few versions ago (added in b0948cf9fc40c4fb8ea7b7445ad8b7bd9e422f3b): its icon did not exist so it was invisible, and anyway I don't think it was any useful, since changing the color of the playing item is already enough to distinguish it from the others.
Before:
After:
I tested both on API 19 and on Android 10 and everything …
> Use constraint layout for play queue item

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt
- app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
- app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
- app/src/main/res/layout/error_panel.xml
- app/src/main/res/values/strings.xml
- give a reason, why a feed could not be loaded when possible
- allow to unsubscribe from the dedicated channel
- show that an account has been terminated and (if provided) the reason for the termination in ChannelFragment
- Fixes #3313 
- Closes #5452
- TeamNewPipe/NewPipeExtractor#580
<details><summary>Screenshots</summary>
</details>
I manipulated the subscription export to contain only URls to termianted or not available channels. Extract the json and import it for testing:
[newpipe_termianted.json.zip](https://github.com/TeamNewPipe/NewPipeExtractor/files/6239718/newpipe_termianted.json.zip)
> Better error handling of terminated channels

- app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistDAO.java
- app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistRemoteDAO.java
- app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
- app/src/main/java/org/schabi/newpipe/database/stream/dao/StreamStateDAO.java
- Convert the Java abstract class DAOs to interfaces.
> Convert the abstract class DAOs to interfaces.

- app/src/main/java/org/schabi/newpipe/player/Player.java
This pull request adds a button beside the share button and open in browser button, that copies the URL of the video to clipboard. This is very useful in many situations.
> Add copy url function to share button

- app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
- Clean up equals methods
- Add hashCode methods matching respective equals to resolve style check warnings
On the website, the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.
> Resolve Tabs style checks

- app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
NewPipe used a very small/short buffer of just 500ms to fill after a buffer depletion. Some devices seem to have issues with that and get in a loop of draining this buffer and having to refill it again leading to a short buffering every 500ms.
From ExoPlayer doc:
`The default duration of media that must be buffered for playback to resume after a rebuffer, in milliseconds. A rebuffer is defined to be caused by buffer depletion rather than a user action`
We are using ExoPlayer's default value now which is 5000ms.
- Fixes #6425 
> Increase buffer for playback after rebuffer

- app/src/main/res/layout-large-land/player.xml
- The ``temsListHeaderDuration`` element was missing in the ``large-hand`` player which caused crashes on larger devices like TVs or tablets to crash
Problem was caused by #6441 / https://github.com/TeamNewPipe/NewPipe/commit/d921e2e61b3577469b26e361bd05483343f7b864
- Fixes #6467
> Added itemsListHeaderDuration to large-hand player

- app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt
- app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
- app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/util/CommentTextOnTouchListener.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
- app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
- app/src/main/java/org/schabi/newpipe/util/TextLinkifier.java
- app/src/main/java/org/schabi/newpipe/util/URLHandler.java
- app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
- app/src/main/java/org/schabi/newpipe/util/external_communication/KoreUtils.java
- app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
- app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
This PR:
- removes a toast which is shown when no app is able to handle the maket scheme on user's device (a toast is only shown if no browser is installed).
- opens the popup player for timestamps in the description of contents.
- fixes action of open with Kodi button in the player
- adds title of the shared content in Android Share Sheet (only for Android 10+ users)
- does some other improvements.
- adds support for hashtags in descriptions, which open for each a search for the hastag in the current service of the content
~~**TO DO**: add a proper support of disposables (I can't do it myself)~~ done
Fixes #5507, fixes https://github.com/TeamNewPipe/NewPipe/issues/5455#issuecomment-770903090, fixes #5695
On the website the APK can be found by going to the "Checks" tab below the title and …
> Recognize timestamps and hashtags in descriptions and do some sharing fixes and improvements

- app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/appearance_settings.xml
- Adds a setting to manually force tablet mode to be on or off under Appearance settings
- Works as a work-around for tablet-mode related issues like #5967
- Also helps all users who increase the minimum width to fit more stuff on their screen, but prefer the better-fitting phone mode for NewPipe
- Fixes #6044 
https://github.com/TeamNewPipe/NewPipe/suites/2474591406/artifacts/53233850
> Adds manual tablet mode setting

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
- app/src/main/res/layout-large-land/player.xml
- fastlane/metadata/android/en-US/changelogs/971.txt
- Increase buffer for playback after rebuffer #6444 
- Fixed crash on tablets and TVs when clicking on the play-queue icon in the player #6480 
- disable desugaring
- 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6658963/app-debug.zip)
Please report new bugs in #6494
> Hotfix release 0.21.5

- app/src/main/java/org/schabi/newpipe/ExitActivity.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Replaced System.exit call with finishAffinity() and start MainActivity call, tested by changing some settings values, exporting my configuration, reversing the changes, and then reimporting the settings, once the MainActivity was restarted I could then see my chosen settings imported.
Also updated ExitActivity.java to remove System.Exit call and replace with start MainActivity
Replaced System.Exit calls with  getActivity.finishAffinity() in the below 2 files
> NewPipe/app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
> src/main/java/org/schabi/newpipe/ExitActivity.java
- Fixes #6428 
I ran the APK on an emulator and went through the settings flow and ensured that my changes persisted after the importing task had finished and the app was restarted.
> Replace the System.exit calls with getActivity.finishAffinity()

- app/src/main/java/org/schabi/newpipe/RouterActivity.java
E/WindowManager: android.view.WindowLeaked: Activity org.schabi.newpipe.RouterActivity has leaked window DecorView@d99fe3b[] that was originally added here
at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
- dismiss the dialog correctly so no leaks might occur
> dismiss choice dialog in onStop() to avoid a leaked window Exception:

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionsImportFragment.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
- app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
- Updated AndroidX Fragment to 1.3.4 ([changelog](https://developer.android.com/jetpack/androidx/releases/fragment))
- Fix most deprecations from pre-1.3.0 Fragment versions
- Fix some of the onActivityResult deprecations
- Comes with whatever bugfixes were made between 1.2.4 and 1.3.4 (which are quite a lot). I highly recommend thoroughly reading the changelog.
There are other deprecations that come with this upgrade that will need fixing at some point:
- ViewPager1 is now officially deprecated (YEAH BOIIIIII)
I didn't do other deprecations like onRequestPermissionsResult and the other onActivityResult ones because I'm not too confident and I want to keep this one …
> Update AndroidX Fragment to 1.3.4

- app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
- app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
- app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
- app/src/main/java/org/schabi/newpipe/settings/SelectKioskFragment.java
- app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
- Fixes some `Not annotated [parameter/method] overrides @NonNull parameter` lints.
- Probably nothing but it's just for safety.
> Annotate some overridden methods and parameters as NonNull

- app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
- app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
- app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Don't enable SAF when on Fire TV.
- Fixes #6455
> Don't enable SAF on Fire TV

- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- Fixes null pointer exception when starting SearchFragment
It seems due to #6394 updating the FragmentX library there was a
change to the order of lifecycle calls, as such onResume() was no longer
before onCreateOptionsMenu() creating a null pointer exception when
using service in onCreateOptionsMenu() as it is only set in onResume().
By moving the initialization of service to onStart() which still happens
before onCreateOptionsMenu() this crash can be avoided. This commit also
adds a check for a null service to prevent future crashes for similar
issues.
- Fixes #6522
> Fix null pointer exception when displaying SearchFragment

- .github/CONTRIBUTING.md
- app/build.gradle
This PR adds a "Build instructions" section to the `.github/CONTRIBUTING.md` file with Android Studio, checkStyle and ktlint setup. It also improves the rest of the file by adding more subtitles, changing the order of points and highlighting important words with bold. I added a link to the Element Matrix client, too. What do you think @TobiGr @B0pol @XiangRongLin @opusforlife2 @mhmdanas @litetex?
Fixes #6220
> Build instructions

- .github/PULL_REQUEST_TEMPLATE.md
- Added a screenshots/screen record section to the PR template to encourage PR authors who make UI changes to provide visual feedback of what exactly changed with their PR.
> Ask for screenshots/video of UI changes in PR template
