TeamNewPipe/NewPipe

- app/src/main/res/layout/video_item.xml
- app/src/main/res/values/dimentxt.xml
Latest version of the list design, as the text is in different lines has more space and shouldn't get broken.
> 3 Line Search List

- app/src/main/res/values-sw600dp-land/dimens.xml
Before:
After:
Before push, it would be nice to test it out first. (My computer doesn't have enough memory for tablet emulator)
> fix sw600dp-land layout problem (#120)

- app/src/main/java/org/schabi/newpipe/Localization.java
- app/src/main/java/org/schabi/newpipe/VideoInfoItemViewCreator.java
- app/src/main/java/org/schabi/newpipe/VideoItemDetailFragment.java
- app/src/main/java/org/schabi/newpipe/VideoListAdapter.java
- created `Localization` class so it's now accessible not only in `VideoItemDetailFragment`
- added missing view count localization in 'next video' and 'related videos' video items
> refactor localization

- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-pt/strings.xml
Changes:
* Different settings for audio and video download dir
* User feedback if downlowd dir has just been created or cannot be created
* Fixed some download problems with illegal filenames (#143 #44 #42 #22).
> Improved download

- app/src/main/java/org/schabi/newpipe/VideoItemDetailFragment.java
- app/src/main/java/org/schabi/newpipe/VideoItemListFragment.java
Currently, when we search incase of network failure, then progress bar not stopping , added same to fix this one. Same problem occur in VideoDetail page.
> ProgressBar must stop incase of network failure 

- app/src/main/java/org/schabi/newpipe/PanicResponderActivity.java
- app/src/main/java/org/schabi/newpipe/PlayVideoActivity.java
- app/src/main/java/org/schabi/newpipe/SettingsActivity.java
- app/src/main/java/org/schabi/newpipe/VideoItemDetailActivity.java
- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
volume controls are applied on music and not phone volume
> to solve issue 38

- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeSearchEngine.java
more info at issue ticket #198
> used regex to delete spaces inside parseLong() argument

- app/src/androidTest/java/org/schabi/newpipe/extractor/youtube/YoutubeStreamExtractorRestrictedTest.java
- app/src/main/java/org/schabi/newpipe/VideoItemDetailFragment.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
Work in progress for implementing age restricted videos. It doesn't fully work and is not ready for merging yet, but I opened the pull request for feedback on this issue.
The unit test succeeds (on my device at least), but fetching the next video thumbnails fails for some reason.
> Fix Age restriction videos

- app/src/androidTest/java/org/schabi/newpipe/extractor/youtube/YoutubeSearchEngineTest.java
- app/src/main/java/org/schabi/newpipe/SuggestionListAdapter.java
- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
- app/src/main/java/org/schabi/newpipe/extractor/SearchEngine.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeSearchEngine.java
Implemented searchview suggestion feature
> Suggestion list in searching

- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
Restoring query text in SearchView after orientation change.
> Restoring search query after orientation change

- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
What do you mean by fixes? Can you please describe your request a bit futher?
> Added media volume control on main screen Fixes #38

- app/src/main/java/org/schabi/newpipe/ActionBarHandler.java
- app/src/main/java/org/schabi/newpipe/ActivityCommunicator.java
- app/src/main/java/org/schabi/newpipe/ErrorActivity.java
- app/src/main/java/org/schabi/newpipe/SettingsActivity.java
- app/src/main/java/org/schabi/newpipe/VideoItemDetailFragment.java
- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
- app/src/main/java/org/schabi/newpipe/VideoItemListFragment.java
- app/src/main/java/org/schabi/newpipe/extractor/AbstractVideoInfo.java
- app/src/main/java/org/schabi/newpipe/extractor/StreamPreviewInfo.java
- app/src/main/java/org/schabi/newpipe/extractor/StreamPreviewInfoCollector.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PlayVideoActivity.java
- app/src/main/java/us/shandian/giga/get/DownloadMission.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/java/us/shandian/giga/ui/common/ProgressDrawable.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
pmd:RedundantFieldInitializer - Redundant Field Initializer. 
https://dev.eclipse.org/sonar/rules/show/pmd:RedundantFieldInitializer
Faisal Hameed
> Code quality fix - Redundant Field Initializer. 

- app/src/androidTest/java/org/schabi/newpipe/extractor/youtube/YoutubeStreamExtractorDefaultTest.java
- app/src/androidTest/java/org/schabi/newpipe/extractor/youtube/YoutubeStreamExtractorRestrictedTest.java
- app/src/main/java/org/schabi/newpipe/VideoItemListFragment.java
- app/src/main/java/org/schabi/newpipe/download/MainActivity.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeSearchEngine.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
squid:S1192 - String literals should not be duplicated. 
https://dev.eclipse.org/sonar/rules/show/squid:S1192
Faisal Hameed
> Code quality fix - String literals should not be duplicated.

- app/src/androidTest/java/org/schabi/newpipe/extractor/youtube/YoutubeSearchEngineTest.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamUrlIdHandler.java
- app/src/main/res/values-es/strings.xml
This pull request should get the build back to normal.
> fix build. remove wrong xliff namespaces from spanish translation.

- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
@scde submitted #330, along with a couple proposed fixes.
This is the second proposed fix, which allows for arbitrarily large
timestamps. All credit to @scde for this.
> Allow for large times stamps fixing #330

- app/src/main/res/values/strings.xml
> Change "click" to "tap".

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/VideoItemListActivity.java
- app/src/main/res/drawable/splash_screen.xml
- app/src/main/res/values/styles.xml
This will just bypass the blank screen and "physically" removes startup time.
> Added Splash Screen to bypass blank screen on start up.

- app/src/main/java/org/schabi/newpipe/PlaylistExternalActivity.java
- app/src/main/java/org/schabi/newpipe/PlaylistLocalActivity.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubePlayListExtractor.java
- app/src/main/res/layout/floating_menu.xml
Hi,
I added a background when an user press on the Floating Action Button.
Now, it's provide an black opacity background on current layout behind the Floating Action Menu like google inbox. (Thanks to these [stackoverflow](http://stackoverflow.com/questions/27992058/floating-action-button-and-white-background) threads).
And now when user's click on the background it's automatically close the menu. 
Refer to [Pull Request #377 ](https://github.com/TeamNewPipe/NewPipe/pull/377)
> Playlist (#377) - Improve the Floating Action Button Menu

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/download/DownloadListener.java
add media scanner notification after successful download
* added DownloadListener
* on finished download send broadcast intent to media scanner
> auto detect downloaded files as new media files

- .gitignore
- app/src/main/java/org/schabi/newpipe/extractor/stream_info/AudioStream.java
- app/src/main/java/org/schabi/newpipe/extractor/stream_info/StreamExtractor.java
- app/src/main/java/org/schabi/newpipe/extractor/stream_info/StreamInfo.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/res/layout/player_notification_expanded.xml
Hi
I've added a progress bar to the custom expanded notification view. And change the following things:
- Add progress bar to the expanded layout
- Create a subclass of NotificationBuilder to update the progress, title, artist and playing state more easily 
- Add the Parcelable "PlaybackState" which contains information about the current playback state 
- Add action "PLAYBACK_STATE" which is broadcasted by PlayerThread
- Uncomment the while loop at the end of PlayerThread.run() to update the playback state 
- Update notification on a received broadcast message in the broadcast receiver
- Fix some typos 
I think the broadcast message could also be used by activities to show controls when a stream is played in the background.
I hope you find this useful
Regards
> Feature: Background progress bar

- app/src/main/java/org/schabi/newpipe/detail/VideoItemDetailFragment.java
Seems to me like a quick and dirty fix but it's working for me.
> Fix for  video not playable

- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeService.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamExtractor.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamUrlIdHandler.java
- app/src/main/java/org/schabi/newpipe/extractor/stream_info/StreamPreviewInfoCollector.java
- app/src/test/java/org/schabi/newpipe/extractor/services/youtube/youtube/YoutubeStreamUrlIdHandlerTest.java
I have something new: :joy:
**Improve the YoutubeStreamUrlIdHandler**
* making it a singelton
* handling embed links
* handling shared links  #362 -- needs to download the page!
* adding  tests
* accept case insensititve hosts
Please let me know if I should change something or stop creating pull requests!
> Improve YoutubeStreamUrlIdHandler

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/detail/VideoItemDetailActivity.java
- app/src/main/java/org/schabi/newpipe/detail/VideoItemDetailFragment.java
- app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
- app/src/main/java/org/schabi/newpipe/extractor/search/SearchEngine.java
- app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeSearchEngine.java
- app/src/main/java/org/schabi/newpipe/info_list/InfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
- app/src/main/java/org/schabi/newpipe/search_fragment/SearchInfoItemFragment.java
- app/src/main/java/org/schabi/newpipe/search_fragment/SearchSuggestionListener.java
- app/src/main/java/org/schabi/newpipe/search_fragment/SearchWorker.java
- app/src/main/java/org/schabi/newpipe/search_fragment/SuggestionListAdapter.java
- app/src/main/java/org/schabi/newpipe/search_fragment/SuggestionSearchRunnable.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_searchinfoitem.xml
Hi I've noticed that the search results (and the query) disappear when the screen is rotated so I made a fix.
* Keep search query when fragment is restored
* Simplify SuggestionListAdapter
* Use ResourceCursorAdapter for view creation
* Remove ViewHolder class
* Fix deprecation warning
* Some clean code
Regards
> Keep search query

- app/src/main/java/org/schabi/newpipe/ChannelActivity.java
- app/src/main/java/org/schabi/newpipe/ThemableActivity.java
- app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
- app/src/main/res/layout/activity_error.xml
> Made changes for ICS and JB

- app/src/main/AndroidManifest.xml
- Fix #480
- Add /embed/ to intent filter, as the app already handles these type of links internally
> Handle embed links

- app/src/main/java/org/schabi/newpipe/fragments/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/ActionBarHandler.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/AbstractPlayer.java
- app/src/main/java/org/schabi/newpipe/player/ExoPlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
- app/src/main/java/org/schabi/newpipe/settings/SettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/org/schabi/newpipe/util/Utils.java
- app/src/main/java/org/schabi/newpipe/workers/ChannelExtractorWorker.java
- app/src/main/java/org/schabi/newpipe/workers/ExtractorWorker.java
- app/src/main/java/org/schabi/newpipe/workers/StreamExtractorWorker.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
- app/src/test/java/org/schabi/newpipe/util/UtilsTest.java
- Up to 4k with 60 fps
- Not every device can play in that resolution and bitrate
- Add option to hide the high resolutions greater than 1080p (2k, 4k) for not clutter the menus, for those who don't need it
- Add a preference to set the default resolution of the popup, will be used when opening in popup mode from another app
- Resolves #291 
Related pull request (for the core part) > https://github.com/TeamNewPipe/NewPipeExtractor/pull/3
> Add resolution support up to 4k and 60 fps

- app/src/main/res/values-bn-rBD/strings.xml
added translation for [Bangla](https://en.wikipedia.org/wiki/Bengali_language) for Bangladesh.
> Add Bangla translation (for Bangladesh)

- app/src/main/res/menu/video_detail_menu.xml
Closes #471 
The new order is: Share, Kodi, Download, Browser
> Change order of buttons in the title bar

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
Before it was playing again on `audio focus gain`, this PR remove it.
- Fix #519
> Improve behavior on audio focus gain

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Add an option to enable/disable the gestures controls of the player.
- Fix #566
> Add option to disable the gesture controls of the player

- app/src/main/java/org/schabi/newpipe/fragments/search/SearchFragment.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Add an option to enable/disable the search suggestions.
- Fix #527
> Add option to disable the search suggestions

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/res/layout/activity_main_player.xml
- app/src/main/res/layout/player_popup.xml
- app/src/main/res/values-sw600dp/dimens.xml
- app/src/main/res/values/dimens.xml
ExoPlayer was updated to 2.4.2, which supports playback speed change.
A speed selector was also added in the MainPlayer and PlayerPopup.
Fixes #153.
> Adds support for adjustable playback speed

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Fixes the NullpointerException described in #588
> Check if view still exists in UICallback

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/util/FilenameUtils.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Added the option to specify the replacement character and the allowed file characters in the preferences.
Another option would be to test the filename (like the old method's for-loop) but with actual checks in between the replacements.
> Add renaming filename preferences

- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
I've added the licenses for RxJava and the bindings library.
> Add licenses for RxJava

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/res/values/strings.xml
Fixes background and popup player on Android O.
Maybe it is a good time to go over other things that are becoming deprecated?
> Android O Notification Building Fix

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
This update allows for DynamicConcatenatingMediaSource, which provides a good basis for playlist support (WIP).
@mauriciocolli 
What's the ETA on the big refactor? Is there any major changes I should keep in mind?
> Updated ExoPlayer to r2.5.1

- app/build.gradle
- app/proguard-rules.pro
Try to enable minify like @coffeemakr  suggested it [here](https://github.com/TeamNewPipe/NewPipe/pull/686#issuecomment-328460527).
I'm testing it right now, so please __don't merge yet__.
> enable minify

- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Pretty straightforward, the regex should match all URLs like `www.youtube.com`, `m.youtube.com` and `youtu.be`. It might also open some things like playlists or channels that aren't supported, not sure about that. Also I'm not sure what do when `NavigationHelper.openByLink()` throws an exception.
> Open youtube links directly from search (fixes #35)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/FilePickerActivityHelper.java
- app/src/main/res/values/styles.xml
The title says, what this PR does. This was the fastest way of doing this. If you have a better/cleaner solution, I can implement this too.
Addresses #646
> Support dark theme in file picker

- app/src/main/res/values/settings_keys.xml
As per
https://en.wikipedia.org/wiki/MPEG-4_Part_14#.MP4_versus_.M4A
https://en.wikipedia.org/wiki/WebM
https://en.wikipedia.org/wiki/3GP_and_3G2
> Spelling of file formats

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/Downloader.java
- app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionItem.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java
- app/src/main/java/org/schabi/newpipe/util/AnimationUtils.java
- app/src/main/java/org/schabi/newpipe/util/LayoutManagerSmoothScroller.java
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/item_search_suggestion.xml
- app/src/main/res/layout/toolbar_search_layout.xml
- app/src/main/res/values/strings.xml
- Use a nice `RecyclerView` list instead of a popup (aesthetics and space constraints)
- Show search history entries
- Delete entries using a long click
> Improve search

- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/SelectKioskFragment.java
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values/strings.xml
> Fix kiosk typo 

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
As you can see, I failed my flinging horribly the first time because my fling is too weak. So please check it out and see if you think the fling velocity needed to close popup player should be lower.
> Popup player fling to close, multitouch resize and fill screen

- app/src/main/assets/gpl_2.html
- app/src/main/assets/mpl2.html
- app/src/main/java/org/schabi/newpipe/about/License.java
- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.java
- app/src/main/res/values/colors.xml
This PR enables themes for the license dialogs.
Addresses #646
> Add themes to license dialog

- app/src/main/java/org/schabi/newpipe/history/HistoryFragment.java
> Fix history showing even when disabled

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/history/HistoryListener.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/res/values/strings.xml
Add a call to history listener when playing with Kodi.
I've also changed the installation procedure for Kore a bit:
* Because the F-Droid URL has changed.
* Because I think the user should choose whether he wants to install from Google or from F-Droid.
> Fature log kodi videos

- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
Sorry about this, I should've tested more thoroughly.
> Fixes Open Control intent exception between SDK 21 and 24

- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
The share and open in browser menu items are not linked in channel view.
To do:
> Implement channel menu (closes #759)

- .github/PULL_REQUEST_TEMPLATE.md
- app/src/main/res/values-cs/strings.xml
This fixes #811 and a typo in the pull request template.
> Fix Czech plurals

- .travis.yml
- app/build.gradle
- app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
I've upgraded everything, except the tests, ACRA and the file picker, so don't merge it yet.
> Upgrade to Studio 3

- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- app/src/main/res/layout/fragment_about.xml
- app/src/main/res/layout/fragment_licenses.xml
- app/src/main/res/values/strings.xml
Some small changes which
- add donation and website hint to the about view
- move NewPipe' license to the licenses tab
I'm quite sure this was requested somewhere, but can't find the ticket...
> Add donation and website hint to about view

- README.md
> Add website, blog and press kit to README.MD

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/RouterPopupActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java
- app/src/main/res/layout/dialog_title.xml
- app/src/main/res/menu/menu_play_queue.xml
- app/src/main/res/menu/menu_play_queue_bg.xml
- app/src/main/res/menu/menu_play_queue_popup.xml
- app/src/main/res/menu/menu_videooptions.xml
- app/src/main/res/values/strings.xml
- Added player conversion to background and popup players.
- [#919] Fixed custom notification does not trigger unlocking on lockscreen.
- [#947] Fixes player crashing on internet outage, issue partially addressed.
- Fixed main player losing state after destroy while in background.
- Fixed main player controls not hiding automatically after orientation change.
- Fixed dialog uploader not marqueeing when too long.
- Fixed popup permission throwing NPE on BaseList.
- Refactored popup permissions to start in NavigationHelper.
- Extracted hardcoded string for player menus.
- Bump Java version to 1.8.
> Usability Improvements and bugfixes

- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values/strings.xml
Thanks to @comradekingu who saw this on [Weblate](https://hosted.weblate.org/translate/newpipe/strings/nb_NO/?type=all&offset=259#comments).
@theScrabi I hope Weblate won't cause any trouble 😅
> Make preferred string not translatable

- app/src/main/java/org/schabi/newpipe/App.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/ZipHelper.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/content_settings.xml
Added function to import / export the database. However the database might not be consistent because I just export the file.
> Added function to import/export the database

- app/src/main/java/org/schabi/newpipe/MainActivity.java
Reverts TeamNewPipe/NewPipe#1076
Is not compiling.
> Revert "Control media volume with the hardware buttons."

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
@theScrabi: It should be OK now. I accidentally pushed it to TeamNewPipe instead of wb9688 though.
> Fix opening SoundCloud links

- app/src/main/java/org/schabi/newpipe/fragments/detail/ActionBarHandler.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/res/layout/fragment_video_detail.xml
- app/src/main/res/menu/video_detail_menu.xml
- app/src/main/res/values/strings.xml
> move download menu item into detail controls menu

- app/src/main/java/org/schabi/newpipe/settings/SelectKioskFragment.java
> Enable SoundCloud kiosks as main page fragment for debug and beta

- app/build.gradle
- app/proguard-rules.pro
- app/src/debug/java/org/schabi/newpipe/DebugApp.java
- app/src/main/java/org/schabi/newpipe/Downloader.java
I've implemented OkHttp in NewPipe.
> Use OkHttp

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/database/stream/model/StreamEntity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/feed/FeedFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/subscription/SubscriptionFragment.java
- app/src/main/java/org/schabi/newpipe/info_list/InfoItemBuilder.java
- app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/PlaylistMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
- app/src/main/java/org/schabi/newpipe/playlist/AbstractInfoPlayQueue.java
- app/src/main/java/org/schabi/newpipe/playlist/ChannelPlayQueue.java
- app/src/main/java/org/schabi/newpipe/playlist/PlaylistPlayQueue.java
- app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
Made the frontend compatible to latest extractor changes.
> made frontend combatible to latest extractor refactorings

- app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
This would close #1148. I haven't tested it myself yet. @TheAssassin: Could you update the Sentry part?
> Remove IP range

- app/src/main/java/org/schabi/newpipe/fragments/local/bookmark/BookmarkFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/subscription/SubscriptionFragment.java
> Subscription Front Page Crash Fix

- README.md
> Fix broken Librepay link in README.md

- fastlane/metadata/android/de/full_description.txt
- fastlane/metadata/android/de/short_description.txt
> Add German translation of the description for fastlane

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/fragments/local/bookmark/BookmarkFragment.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PlayerState.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/FailedMediaSource.java
- app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSourcePlaylist.java
- app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
- app/src/main/java/org/schabi/newpipe/player/playback/PlaybackListener.java
- app/src/main/res/drawable/player_controls_bg.xml
- app/src/main/res/drawable/player_top_controls_bg.xml
- app/src/main/res/layout-land/activity_player_queue_control.xml
- app/src/main/res/layout/activity_main_player.xml
- app/src/main/res/layout/activity_player_queue_control.xml
- app/src/main/res/layout/dialog_playback_parameter.xml
- app/src/main/res/layout/player_popup.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- Added "Add to playlist" menu item to service player play queue.
- [#1204] Fixed LIVE button to use untranslatable string.
- Fixed service player play queue not refreshed when existing play queue is replaced.
- Fixed potential ArrayOutOfBound exception when checking if player window is live.
- Fixed strange pausing behavior when main video player goes into multiwindow mode.
> Usability Update Follow-up

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
> Add to Playlist feature to Related and Channel lists

- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/res/layout/player_popup.xml
#1307 
Right now, pressing on the popupplayer paused the video and showed a play button. This was very annoying when you just tried to look at the time or something. Now it works more like the normal youtube app, tapping brings up the progress bar, some settings and a pause button. When you press it it pauses the video and becomes a play button. Also, thanks to this you can look at a paused video without all the clutter around.
Additionally, this didn't break the MainPlayer, even though VideoPlayer is used in the PopUpPlayer and the MainPlayer. 
The little issue is that the play/pause/repeat button gets slightly off scale, but only about 10%. I tried fixing this, but I really can't figure out how rescaling works. Maybe someone can help. But in my opinion the fluidity this brings is worth …
> PopUpPlayer now also has a Play and Pause button

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/res/layout/activity_main_player.xml
- app/src/main/res/layout/dialog_playlists.xml
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/layout/fragment_kiosk.xml
- app/src/main/res/layout/fragment_playlist.xml
- app/src/main/res/layout/fragment_video_detail.xml
[ True color: No overdraw
Blue: Overdrawn 1 time
Green: Overdrawn 2 times
Pink: Overdrawn 3 times
Red: Overdrawn 4 or more times](https://developer.android.com/studio/profile/inspect-gpu-rendering)
> Reduce overdraw

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/res/values/settings_keys.xml
I am on the fence if most users need a setting to customize the brightness behavior.
> Remember brightness for the session #1416

- app/src/main/java/org/schabi/newpipe/MainActivity.java
(except for “Check if your submission can be build with the current fdroid build server setup.”, I don’t know how :)
This is a simple snippet to disable animation of the main button because it’s hidden anyway by the navigation.
(+ a simplified version of a method)
> Disable animation (hidden anyway by navigation)

- app/src/main/java/org/schabi/newpipe/download/DeleteDownloadManager.java
- app/src/main/java/org/schabi/newpipe/download/DeleteManager.java
- app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
> undo delete

- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/res/values/settings_keys.xml
This addresses #1485 and adds an option to download within the share menu.
> Download option in share menu

- fastlane/metadata/android/en-US/changelogs/66.txt
> Fix typo in v0.13.7 changelog

- app/src/main/java/org/schabi/newpipe/util/ListHelper.java
Double check for null
**✔** I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
> Additional checks to obtain WiFi status

- README.md
Apologies for these small readme commits, but for some reason the \*\*bold effect\*\* didn't work, so i just changed it to \<b\> instead.
Also removed the multiple "\\" that was deprecated in html5 because well why not, I need something to do :+1: 
- [ yes ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
> Fix broken bold

- app/src/main/res/values/settings_keys.xml
Closes TeamNewPipe/NewPipe#1504
> Fix spelling of country names in settings

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
@theScrabi I have fixed the pop-up player crash and here is the PR for this one plz review it and let me know if anything is needed.
Thanks
> pop-up player crash fixed

- app/src/main/res/values-ru/strings.xml
Hi guys!
I want said that partial translation looks awful.
HostedWeblate does not contains this strings to translate.
Please add this strings to Hosted Weblate template or merge PR, at your choice.
> Missed strings

- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- app/src/main/res/menu/mission.xml
re:[Issue 1870](https://github.com/TeamNewPipe/NewPipe/issues/1870)
For consistency, I removed the view file option from the overflow menu as well
> downloaded files can now be opened with one click

- .github/stale.yml
This will add stalebot config to newpipe.
> add stalebot confic

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItemTouchCallback.java
Issue 1505: Delete on right swipe
> Issue 1505: Delete on right swipe

- app/build.gradle
This will fix the decrypt issue of NewPipe that occurred lately.
> fix decrypt error once again

- .github/CONTRIBUTING.md
- app/build.gradle
> Release v0.15.0

- fastlane/metadata/android/en-US/changelogs/70.txt
> add changelog for version v0.15.0

- app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
Add checks for null, this happens after rotating the screen while is turned off.
> Downloads: add null checks

- app/src/main/AndroidManifest.xml
This PR adds "youtube-nocookie.com" as a valid link to the manifest and updates the extractor version.
> support for youtube-nocookie.com

- app/build.gradle
add fix for invalid channel url when selecting channes from commends.
> fix invalid channel url for commends

- app/src/main/java/org/schabi/newpipe/player/AudioServiceLeakFix.java
- app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
> Fix AudioManager memory leak

- app/src/main/res/layout/fragment_comments.xml
- app/src/main/res/layout/fragment_related_streams.xml
closes https://github.com/TeamNewPipe/NewPipe/issues/2146 ?
> added top padding for comments and related videos

- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
fixes https://sentry.schabi.org/sentry/newpipe/issues/3153
> fix empty author endpoint

- app/src/main/java/org/schabi/newpipe/fragments/detail/TabAdaptor.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/res/values/settings_keys.xml
> preferred tab based on selected state, fixes #2238

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
ExoPlayer just can't handle the subtitle texts..
closes #2280
> Readd CustomTrackSelector

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
See https://github.com/TeamNewPipe/NewPipe/issues/2483#issuecomment-520257277
> Fix player resume

- app/src/main/java/org/schabi/newpipe/settings/HistorySettingsFragment.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/history_settings.xml
> Clear playback states

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/770.txt
> add fixed extractor and move on to version 0.17.2

- app/src/main/res/values/strings.xml
> Make language of download folder setting more consistent and less ambiguous

- app/build.gradle
- app/src/main/java/android/support/design/widget/FlingBehavior.java
- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/fragment_video_detail.xml
Fixes #2627 
Fixes #2437
Also, ParalaxScrollView is removed from dependencies and credits since it is not being used any more.
> fix scrolling in video detail fragment. fixes #2627

- app/build.gradle
Little dependency update.
ExoPlayer Changelog: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md
> Bump ExoPlayer to 2.10.7

- app/build.gradle
Here we go again.
Minor update.
ExoPlayer Changelog: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md
> Bump ExoPlayer to 2.10.8

- README.md
Add PeerTube to the list of supported services in the README.
> Add PeerTube to README

- app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
- app/src/main/res/values/settings_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/video_audio_settings.xml
Added an option in the settings for user to set the duration which gets fast forwarded/rewinded when they double-tap in a video or press the corresponding buttons in background mode.
Related issue: #1401
> Adjustable seek duration

- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
Guten Abend,
just a follow-up on my previous PR (https://github.com/TeamNewPipe/NewPipe/pull/2023).
Same functionality, but this time for local playlists.
> Add local playlist to queue when long clicking on 'Background/Popup'

- app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values/strings.xml
> made instance list url non translatable

- app/build.gradle
- app/src/main/AndroidManifest.xml
> /c/ channel links support & update extractor version

- app/src/main/java/us/shandian/giga/get/DownloadMission.java
Thanks to @blackbox87 for the hint! (see also https://github.com/TeamNewPipe/NewPipe-legacy/pull/21)
> Fixes #3021

- app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
i missed a commit in #2959 resulting in corrupt files (mp4 files only), this pr adds a missing check.
fixes #3081
[✔] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
> fixup for #3081

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/res/values-v28/styles.xml
- app/src/main/res/values/styles.xml
Fixes #2682, #1973 
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4081805/app-debug.apk.zip)
> Support display cutout

- app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java
- app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
I have tested on android P. Please test on other android versions before merging.
Related [stackoverflow answer](https://stackoverflow.com/questions/54051322/database-import-and-export-not-working-in-android-pie/54056779#54056779)
Closes #2508, closes #2699
> checkpoint db before export

- app/src/main/res/layout-large-land/activity_main_player.xml
- app/src/main/res/layout/activity_main_player.xml
This was introduced by #3165 
Screenshot, you'll be able to see what's the old behaviour: <img src="https://user-images.githubusercontent.com/58657617/76651106-d056cc00-655b-11ea-9130-71a1e52690b6.png" width="550">
> Fix captions overtaking mute button

- app/src/main/AndroidManifest.xml
This will also need some proper handling in NewPipeExtractor, as videos on YouTube Music will always be in a playlist or mix.
> Accept music.youtube.com in manifest

- app/build.gradle
- app/src/main/AndroidManifest.xml
Relies on TeamNewPipe/NewPipeExtractor#256
Fixes #3079 
Fixes #3080 
APK:  [2020-02-12_links#3090.zip](https://github.com/TeamNewPipe/NewPipe/files/4194117/2020-02-12_links.3090.zip)
Links: 
+ https://media.ccc.de/v/oscal19-12-the_hairy_issue_of_end_to_end_encrypted_instant_messaging
+ https://media.ccc.de/b/oscal19
+ https://media.ccc.de/c/oc
+ https://invidio.us/-cdveCh1kQk
> Links support for mediaccc and shortened invidious

- app/src/main/java/org/schabi/newpipe/streams/WebMReader.java
- app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java
fixes https://github.com/TeamNewPipe/NewPipe/issues/3204
There was a division (using floating point) that was not precise, consequently some offstets was wrong written on the file. I had to refactor several things until I spot the bug.
> fix for #3204

- app/src/main/res/layout/toolbar_search_layout.xml
This is a preview of the changes that match the requested change in issue #3183
> Remove search icon in search mode. Issue: #3183

- app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- app/src/main/res/drawable/ic_volume_up_black_24dp.xml
- app/src/main/res/drawable/ic_volume_up_white_24dp.xml
- app/src/main/res/layout-large-land/activity_main_player.xml
- app/src/main/res/layout/activity_main_player.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles.xml
The recently introduced mute button #3165 is not really visible the sound is unmuted, it's in gray. I made it white everytime, therefore it's more visible.
Screenshots:
Before: 
After:
When it's muted, it stays the same icon, same color (it's the icon on the first screenshot but in white).
> Change mute button color for more visibility

- app/src/main/res/values-b+zh+HANS+CN/strings.xml
- Fix UI crash in Settings, Content (chinese language)
> Fix UI crash in Settings, Content (chinese language)

- app/src/main/java/org/schabi/newpipe/info_list/holder/StreamGridInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
- app/src/main/res/layout/list_stream_grid_item.xml
Before | After
-------- | ------
(I didn't edit the width to make two items fit in the screen, it just depends on phones, the first screenshot is taken from #3175).
Fixes #3175
> add upload date on stream grid items

- app/src/androidTest/java/org/schabi/newpipe/database/AppDatabaseTest.kt
- app/src/main/java/org/schabi/newpipe/database/Migrations.java
Fix an oversight in the database migration to version 3.
- Fixes #3303
> Hotfix for the latest database migration

- app/src/main/java/org/schabi/newpipe/streams/DataReader.java
- app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java
- app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
- app/src/main/java/us/shandian/giga/io/ChunkFileInputStream.java
- app/src/main/java/us/shandian/giga/io/CircularFileWriter.java
fix two integers overflow cases
- [✔] Bug fix
- [✖] Feature
fixes #3296
_no needed_
- [✔] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
> Integer overflow fixes in downloader

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- Minor alterations to the PR template
- Made the Feature Request template easier to fill out
> Update Feature Request and PR templates

- fastlane/metadata/android/en-US/changelogs/920.txt
Mention the view count added on grid view by #3289 in changelog
- no issue opened for that
- no depedency
no need
> mention view count added in 0.19.2 in changelog

- .github/ISSUE_TEMPLATE/bug_report.md
- The biggest problem was that the reporter needed to delete a lot of text to be able to give a clean report. Now most of that is comments.
- Some other grammatical improvements.
- Scary template being ignored by reporters. See: https://github.com/TeamNewPipe/NewPipe/issues/3354#issuecomment-608964546
> Made the bug report template less daunting

- gradle.properties
@XiangRongLin: Could you test whether this works for your Checkstyle issue?
> Force UTF-8 encoding for Gradle

- app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
- use nanojson instead of org.json
- hopefully fixes #2903 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4502397/app-debug.zip)
> use nanojson instead of org.json

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelper.java
- app/src/main/java/org/schabi/newpipe/settings/tabs/TabsJsonHelper.java
@TobiGr: ~~Changing anything in the code wasn't needed.~~ I was wrong and ~~I'm fixing it right now~~ I just fixed it.
> Use our nanojson fork

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsInfoItemHolder.java
- app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- adapt TeamNewPipe/NewPipeExtractor#310 (some methods in CommentsInfoExtractor were renamed)
- Teamnewpipe/NewPipeExtractor#310
I will edit with it later
> adapt CommentsInfoItemExtractorRefactoring

- .gitignore
- Same as https://github.com/TeamNewPipe/NewPipeExtractor/pull/330
- Files that keep getting created, and as they are indiviual files we don't want people to commit them, so we should add them to gitignore
not needed
> Add vscode / eclipse files to gitignore

- app/src/main/java/org/schabi/newpipe/MainActivity.java
> Open the correct kiosk

- app/src/main/AndroidManifest.xml
Temporary fix. I'll come with a proper fix (i.e. use SAF by default and everywhere on Android 5+) later.
Fixes #3673
> Enable requestLegacyExternalStorage

- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
> avoid duplicate: use openUrlInBrowser instead of openWebsite

- app/build.gradle
- app/src/main/AndroidManifest.xml
- update invidious instances
- fixes https://github.com/TeamNewPipe/NewPipe/issues/3654
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/365
[NewPipe_2020-07-02_update_inv_instances.zip](https://github.com/TeamNewPipe/NewPipe/files/4866384/NewPipe_2020-07-02_update_inv_instances.zip)
> update invidious instances

- app/src/main/AndroidManifest.xml
- I added ability to open peertube videos without sharing to NewPipe in #3406, but it's hardcoded as it must be in manifest. [privacytools.io](https://privacytools.io) just launched their PeerTube instance [yesterday](https://old.reddit.com/r/privacytoolsIO/comments/hkbazr/introducing_the_privacytools_peertube_instance/), and I really think we should add this instance, _in the next release_
- no issue
[newpipe_privacytoolsio.zip](https://github.com/TeamNewPipe/NewPipe/files/4872497/newpipe_privacytoolsio.zip)
> add privacytools.io peertube instance to manifest

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedVideosFragment.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/util/RelatedStreamInfo.java
Fixes #3684
TeamNewPipe/NewPipeExtractor#337
> Remove calls to getNextStream()

- app/src/main/java/org/schabi/newpipe/views/FocusOverlayView.java
> Fix lingering focus highlight overlay

- app/build.gradle
Needed for F-Droid reproducible builds. Will make the APK about 20 kB bigger.
> Disable shrinkResources

- app/src/main/res/layout/fragment_search.xml
previously, a lighter color was used. That's bad on the light theme. Now using the default text color.
Fixes TeamNewPipe/NewPipe#3973
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4987333/app-debug.zip)
> Fix color of correct / suggested search term

- app/src/main/res/values/settings_keys.xml
Fixing name for Taqbaylit language.
Closes #4065
> Fixing name for Taqbaylit language

- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- Remove timestamp from url when sharing a live stream
- https://github.com/TeamNewPipe/NewPipe/issues/4098
Verified on Pixel 1
> Remove timestamp from url when sharing a live stream

- .github/CONTRIBUTING.md
As discussed on IRC, prevent the occurrence of problems where people spend hours on a feature only for it to be rejected for miscellaneous reasons.
I did not follow the style for linebreaks since I couldn't figure out where they go. Please suggest changes to add them if they are necessary.
> Add need for contributors to discuss possible changes

- app/src/main/java/org/schabi/newpipe/about/License.java
- app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
- Keep license pop-up when screen is rotated
- Fixes #4113
> Restore license pop-up when orientation changes

- app/src/main/res/values/settings_keys.xml
change default quality
- fixes #4274 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5214038/app-debug.zip)
> change default quality

- app/src/main/res/layout/settings_notification.xml
- app/src/main/res/layout/settings_notification_action.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-b+zh+HANS+CN/strings.xml
- app/src/main/res/values-ckb/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-he/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt-rPT/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sc/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
<table>
<tr><td>Before</td><td>After</td><td>Description</td></tr>
<tr><td><img width="800px" src="https://user-images.githubusercontent.com/36421898/94438450-69b79980-019f-11eb-9f90-5eb7362aaa62.png"/></td><td><img width="800px" src="https://user-images.githubusercontent.com/36421898/94438465-6fad7a80-019f-11eb-9f88-768c0702856a.png"/></td><td>This PR contains improvements and adjustments of the notification settings layout for devices with small screens. In particular I removed line number restrictions from text views.</td></tr></table>
I thought I had tried with a small screen while testing #3178, but apparently I didn't, by looking at [this user screenshot](https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-699675761). …
> Small adjustments to notification settings layout

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- each time something starts to play in any player VideoDetailFragment will be started (if not yet started) and mini player will show up. It makes possible to see a playing stream in mini player even if the stream was started without using fragment or after player service was closed somehow
- play/next/queue buttons will be updated in realtime when stream was added/removed from queue instead of waiting for a onPlay/onPause action to happen. It needed when you have opened popup and doing something with queue in background activiry or fragment
- when popup or background players start the stream will start playing only if paused state wasn't requested. Which means, for example, if a user opens popup it will be started when START_PAUSED is false. If, for example, the stream was played in main …
> Player rebind

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/util/Localization.java
Update prettytime to 4.0.6. Remove a workaround.
- fixes #4324
- fixes https://github.com/TeamNewPipe/NewPipe/pull/3567 (incorrect use of plural in russian)
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5319352/app-debug.zip)
> Update to PrettyTime 4.0.6

- fastlane/metadata/android/fr/changelogs/954.txt
- fastlane/metadata/android/fr/full_description.fr.txt
- fastlane/metadata/android/fr/short_description.fr.txt
Translate fastlane metadata in french
> Translate fastlane metadata in french

- fastlane/metadata/android/it/changelogs/954.txt
- fastlane/metadata/android/it/full_description.txt
- fastlane/metadata/android/it/short_description.txt
Translate fastlane metadata in italian
> Add italian translation for fastlane

- fastlane/metadata/android/nb-rNO/changelogs/954.txt
- fastlane/metadata/android/nb-rNO/full_description.txt
- fastlane/metadata/android/nb-rNO/short_description.txt
- Has the short and full desc and the latest (954) changelog
- No Fastlane support for nb_NO
debug.zip
> Norwegian Bokmål fastlane support

- .github/ISSUE_TEMPLATE/bug_report.md
- Added checkboxes to compel the user into making an effort in their bug report.
- People seemed to ignore the long comments.
> Replace long comments with check boxes in the Bug Report template

- .github/ISSUE_TEMPLATE/feature_request.md
- Added check boxes to compel users into making an effort in their issues.
- Users seem to ignore instructions in the comments.
> Add check boxes to Feature Request template

- .github/ISSUE_TEMPLATE/bug_report.md
Added fields for Android version and device model to the bug report template.
Something we need to know when no logs are provided.
--------
<b>Use squash and merge</b> when merging this PR. I accidentally created to commits...
> Device info

- app/build.gradle
Snyk complaining about vulnerabilities, which need to be fixed by the upstream devs. Ktlint uses junit 4.12, first secured version is 4.13.
> Disable Ktlint for now

- app/build.gradle
- settings.gradle
Added a few lines on how to use a local extractor version for debugging and developing the extractor and testing those changes in the app.
> Add info on how to use a local NewPipe Extractor version

- README.md
While taking a look at FreeTube repo I found out they had a great-looking weblate widget, and I thought NewPipe should also have it. I took the dark "Big status badge" from [here](https://hosted.weblate.org/widgets/newpipe/), let me know if you would prefer another one.
> Add Weblate widget to README

- app/src/main/java/org/schabi/newpipe/util/Localization.java
Translates shortened notation of numbers using the ICU library bundled with Android 7.0 and later.
See also #3872 .
- #3871 (already closed by the author)
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5396980/debug.zip)
> Translates shortened notation of numbers

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Edited some instructions for clarity.
- People making mistakes when opening issues.
> Refined instructions in the issue templates

- .github/ISSUE_TEMPLATE/config.yaml
- Added a config.yaml to the issue template directory to prevent users opening blank issues, without a template.
- Users avoiding the templates.
> Create config.yaml to prevent blank issues

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/956.txt
Hotfix v0.20.2
TODO: update extractor version when TeamNewPipe/NewPipe#441 is merged
- <span id="debug-apk-hotfix">fixes</span> #4572 
- TeamNewPipe/NewPipeExtractor#441
<a href="https://github.com/TeamNewPipe/NewPipe/files/5445521/newpipe-HOTFIX.zip">newpipe-HOTFIX.zip</a>
> Release 0.20.2 (956)

- README.md
- Updated "Updates" section to be more relevant, and added custom repo info.
- Hopefully, it'll reduce the number of users complaining about slow updates.
> Update readme and add custom repo info

- app/src/main/res/values/settings_keys.xml
-Added Santali in the list and also added its local name ᱥᱟᱱᱛᱟᱲᱤ
- Added new language
> [Translation]Added Santali language

- README.ko.md
- README.md
- README_KO.md
- Added README_KO.md which is korean translation of README.md 
to active the participation of the Korean contributors or download of Korean users.
> Add korean translation of README.md

- app/src/main/AndroidManifest.xml
update peertube instances list
I did not test nor build the apk but it's minor change and the added url is correct
> [PeerTube] update instances list

- README.md
- Minor grammar fixes in README.md
- None
No changes made to the app
> Minor grammar fixes in README.md

- app/src/main/res/values/strings.xml
Clarify summary for export database.
- Fixes #5036
~~[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5616014/app-debug.apk.zip)~~
~~[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5617379/app-debug.apk.zip)~~
~~[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5623474/app-debug.apk.zip)~~
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5624820/app-debug.apk.zip)
> Improve export database summary

- app/src/main/java/org/schabi/newpipe/MainActivity.java
- app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
Just some typo fixes.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5649032/debug.zip)
> Fix some typos

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
- Use `WebViewClientCompat` in `ReCaptchaActivity`.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5719056/debug.zip)
> Use WebViewClientCompat.

- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/services/BaseImportExportService.java
- app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
- app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- Use `ServiceCompat.stopForeground()` so that the flags can be used on Android versions below Nougat.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5719288/debug.zip)
> Use ServiceCompat.stopForeground().

- app/build.gradle
Update checkstyle to resolve security vulnerability: https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415
> Affected module: com.google.guava:guava@29.0-jre
> 
> Introduced through: com.puppycrawl.tools:checkstyle@8.37
> 
> Exploit maturity: No known exploit
> 
> Fixed in: com.google.guava:guava@30.0-android, com.google.guava:guava@30.0-jre 
not needed
> Fix security vulnerability in checkstyle / guava

- app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
- Fixes [an issue](https://github.com/TeamNewPipe/NewPipe/issues/5245#issuecomment-749495460) where the player queue and controls aren't shown when accessed via the player notification.
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5735813/debug.zip)
> Fix queue display in ServicePlayerActivity.

- README.ko.md
- README.md
- Replace travic ci badge with github actions one for dev branch pushes
- pushes, so PR failing does not impact the badge
- dev branch because it's the default branch
- 
- 
debug.zip
> Replace travic ci badge with github actions one for dev branch pushes

- app/src/main/assets/epl1.html
- app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
- app/src/main/java/org/schabi/newpipe/about/StandardLicenses.java
- Put the licenses in alphabetical order
- Added missing licenses for missing libraries
- Corrected some dates, names, and links
[app-debug-displayedlicenses.zip](https://github.com/TeamNewPipe/NewPipe/files/5626644/app-debug-displayedlicenses.zip)
> Update displayed licenses

- app/src/main/res/values/settings_keys.xml
Changed the Somali language name from Af-Soomaali to Soomaali which is common and more user friendly when users are looking for Somali language in the list (since they aren't expecting it starts with A as in Af-Soomaali).
I contributed the language to the project on Weblate and I think this is name is better.
- Changes the Somali language name to the common one which is Soomaali from Af-Soomaali
- Users will be expecting Somali language to start with an S
debug.zip
> [localization] Fixes Somali language name

- README.md
> Linked Readme file with Somali Readme

- README.ko.md
> Linked (Korean Readme) with Somali Readme

- README.ko.md
- README.md
- README.pt.br.md
- README.so.md
Created Readme file Brazilian Portuguese
> Created Brazilian Portuguese Readme

- README.ja.md
- README.ko.md
- README.md
- README.pt_BR.md
- README.so.md
Translate README into Japanese
> Add Japanese translation of README

- app/build.gradle
- app/src/main/AndroidManifest.xml
- update invidious instances
- fixes #5479 (part 2/2)
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/522/
> update invidious instances list

- README.ja.md
- README.ko.md
- README.md
- README.pt_BR.md
- README.ro.md
- README.so.md
- Translate README in romanian
> Add README.ro.md

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/963.txt
- Release 0.20.9
- https://github.com/TeamNewPipe/NewPipe/issues/5550
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/539
[app.zip](https://github.com/TeamNewPipe/NewPipe/files/5972256/app.zip)
> Release 0.20.9

- app/build.gradle
Dependency update.
Changelog https://square.github.io/okhttp/changelog_3x/#version-31213
> Update okhttp from 3.12.12 to 3.12.13

- build.gradle
- Update Gradle plugin to version 4.1.2
- N/A
> Update Gradle plugin to version 4.1.2

- app/src/main/res/values/settings_keys.xml
Add Northern Kurdish to language selector.
- Fixes #5716.
> Add Northern Kurdish to language selector

- app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupReorderItem.kt
- Fix the crash that occurs when reordering channel groups.
- https://github.com/TeamNewPipe/NewPipe/issues/5596
> Fix crash when reordering channel groups.

- README.md
- Adds space after the comma
- There was no space after the comma
> Add spcace after the comma, before Romanian in Readme.md.

- .github/ISSUE_TEMPLATE/config.yml
Add links to our Matrix and IRC channels. They appear at the bottom when opening issues.
https://github.com/Chocobozzz/PeerTube/issues/new/choose
-  [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
> Add links to Matrix and IRC chat when opening new issues

- .github/workflows/ci.yml
- change workflow file to only ran on the dev branch
- running the workflow twice when creating a branch in the project.
I didn't change anything there.
I did not create an issue for it but I do not think it's needed, otherwise I can
> Fix: CI only on dev

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/res/layout-large-land/fragment_video_detail.xml
- app/src/main/res/layout/fragment_video_detail.xml
- When in full-screen video playback, hardware keyboard Space button will toggleplay/pause.
> Implement "pause/play" toggle on hardware keyboard space button.

- README.ja.md
- README.ko.md
- README.pt_BR.md
- README.ro.md
- README.so.md
Re-add localized F-Droid badges to localized README's.
Follow-up to #5830.
Unnecessary.
> Re-add badges to localized README's

- app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
- Better privacy/detectability from YouTube.
Related: https://github.com/TeamNewPipe/NewPipeExtractor/pull/551
https://nightly.link/TeamNewPipe/NewPipe/actions/artifacts/42229063.zip
> Change UA to privacy.resistFingerprinting.

- .github/workflows/ci.yml
For some reason, sonar started to analyse very old PRs. This comments out the sonar job until further investigation is done.
Additionally, sonar's access to our repositories has been suspended.
> Disable sonar job

- README.es.md
- README.md
- README.ro.md
Change in READMEs newpipe.schabi.org to newpipe.net for F-Droid custom repository installation link.
> Change the old NewPipe domain to the new domain in READMEs

- .github/PULL_REQUEST_TEMPLATE.md
> Add note about "Fixes" prefix to auto-link issues

- README.es.md
- README.ja.md
- README.ko.md
- README.md
- README.pt_BR.md
- README.ro.md
- README.so.md
This PR changes some leftover HTTP URLs to HTTPS for more security.
> Update URLs to HTTPS

- app/build.gradle
- build.gradle
I hated having to try to read through the messy and unfiltered dependencies block whenever I would fork, so finally I figured I would do this (more for my own sake than anything 😅)
- Update Android Studio to 4.1.3.
- Rearrange dependencies block to look much nicer.
- Also added little notes so people not familiar with the codebase will know what all the libraries are for without having to look them up.
None needed.
> Rearrange libraries

- app/src/main/res/layout/list_stream_item.xml
- Added elipsis to the list stream item uploader
- Fixed list stream item details overflow when there's free space
> Stream item improvements

- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/res/layout/player.xml
- Adds a text view to top of queue that displays the time viewed through the queue
- Closes #5665
> Add queue time

- .github/workflows/ci.yml
- Update actions/setup-java v1 to v2 ([migration](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md))
None.
None needed.
> Update actions/setup-java to v2

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentItem.kt
- app/src/main/res/layout/item_stream_segment.xml
Display channel / creator / artist name in stream segment list when available.
| YouTube (no channel name) | Bandcamp Radio (artist name) |
| ------------------------------------- | ------------------------------------------ |
| <img src="https://user-images.githubusercontent.com/17365767/114318549-c9f3a480-9b0d-11eb-898d-105a76750c08.png"> |  <img src="https://user-images.githubusercontent.com/17365767/114318564-d972ed80-9b0d-11eb-869d-a00796e3b543.png">|
- TeamNewPipe/NewPipeExtractor#607
> [Bandcamp] Add Radio stream segments

- README.es.md
- README.ja.md
- README.ko.md
- README.md
- README.pt_BR.md
- README.ro.md
- README.so.md
- README.tr.md
- Creates README.tr.md
- Adds a link to the new page from the already-existing READMEs
> Added Turkish README

- app/build.gradle
Just a dependency update, no impact (no new deprecations or structural changes).
Changelog: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2133-2021-04-14
next version will require a bigger changes: https://github.com/google/ExoPlayer/blob/dev-v2-r2.14.0/RELEASENOTES.md
> Update ExoPlayer to 2.13.3

- app/src/main/java/org/schabi/newpipe/ktx/TextView.kt
- app/src/main/java/org/schabi/newpipe/ktx/View.kt
- Use the `Animator.addListener()` extension function.
> Use Animator.addListener() extension.

- README.ro.md
Translation of the No Login Required in Romanian.
> Add No Login Required translation for Romanian

- app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
- change back button id from app id to android id
- Fixes #6298 
> Fix ErrorActivity actionbar back button not working

- app/src/main/java/org/schabi/newpipe/ktx/Throwable.kt
- app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderItem.kt
- app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java
Just a bunch of small, miscellaneous changes.
> Make some minor changes

- README.pt_BR.md
Excluding forgotten parts of the original raw
> Excluding forgotten parts of the original raw

- README.es.md
- README.ja.md
- README.ko.md
- README.md
- README.pt_BR.md
- README.ro.md
- README.so.md
- README.tr.md
Change IRC chat button link in READMEs from Freenode to Libera.
> Change IRC chat button link in READMEs

- app/src/main/res/layout/list_channel_item.xml
- fixed xml attributes for channel description textview
- Fixes #6409 
> Fixed channel description textView

- .github/CONTRIBUTING.md
As mentioned by @Stypox on https://github.com/TeamNewPipe/NewPipe/pull/6393#issuecomment-852967851, we forgot to change the IRC links in the contribution guidelines. This is now fixed with this PR.
Fixes https://github.com/TeamNewPipe/NewPipe/pull/6393#issuecomment-852967851
> Change NewPipe IRC links in the contribution guidelines

- app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
Update playback speed when changing it in the PlayQueueAcitvity
Fixes #6419
> Fix playback speed not being updated in PlayQueueAcitvity

- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Because #5523 will be not merged soon and because #5599 can be easily fixed, I prefered to open a separate PR to implement the fix provided in the issue and include this fix in the next version.
- Fixes #5599
> Fix Play with Kodi button in Player always prompts to install Kore

- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- AS automatically refactors like this so I commit the changes. 
> Refactoring by Android Studio

- .github/workflows/ci.yml
- Comment out test-android CI job
- Until it is properly fixed with #6560, which may take a while.
- Add comments explaining decisions in test-android ci job
> Comment out test-android CI job

- app/build.gradle
- app/src/main/AndroidManifest.xml
Update invidious instances
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/668 
> Update Invidious instances and support Piped links

- .github/ISSUE_TEMPLATE/bug_report.md
- Fixed a typo / makes the wording consistent in the bug_report.md file
> Fixed a typo / make the wording consistent in the bug_report.md file

- app/src/main/res/layout-large-land/player.xml
Fixes ClassCastException when using the repeatButton with the tablet layout
- Fixes crash reported in the 0.21.6 RC, see https://github.com/TeamNewPipe/NewPipe/issues/6577#issuecomment-876095378 for more info on the crash.
> Fix crash when using repeatButtonin tablet layout

- app/src/main/res/layout/related_items_header.xml
- app/src/main/res/values-v21/styles_services.xml
- app/src/main/res/values/styles.xml
- Added v21 theme for Bandcamp fixing some night theme related color issues
- Applied `primaryColor` as active color to switches
- Fixes #3254
- Replaces / Closes #4162 
> Apply theme to switches

- app/build.gradle
- Update the AppCompat library to 1.3.0.
> Update AppCompat to 1.3.0.

- app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt
- app/src/androidTest/java/org/schabi/newpipe/testUtil/TrampolineSchedulerRule.kt
- Fixes malformed files from #5531
not applicable
- Fixes #5531
not applicable
> Fix format of some kotlin files

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/RouterActivity.java
- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
- app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
- app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
- app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
- app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
- app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- fastlane/metadata/android/en-US/changelogs/973.txt
Here is a hotfix release containing these PRs, as requested:
- Dismiss download dialog correctly #6701 
- Fix grid span count calculation #6705 
- More onActivityResult deprecation fixes #6536 
Testing apk: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6849984/app-debug.zip)
> Hotfix release 0.21.7

- app/src/main/res/layout/activity_error.xml
- app/src/main/res/layout/fragment_main.xml
- app/src/main/res/layout/missions.xml
- [Notes](https://developer.android.com/reference/android/view/ViewGroup.LayoutParams#FILL_PARENT)
> Fix deprecated fill_parent attributes

- app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
With SoundCloud selected:
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/79245641/128166790-3cd93303-b61b-4973-88f9-4bb51c1090c8.jpg" height="400px"/></td>
<td><img src="https://user-images.githubusercontent.com/36421898/128213057-7cfb0b5d-810c-4b14-bb1a-dbbd3c409e34.png" height="400px"/></td>
</tr>
</table>
> Play queue theme

- app/src/main/res/xml/appearance_settings.xml
- app/src/main/res/xml/content_settings.xml
- app/src/main/res/xml/debug_settings.xml
- app/src/main/res/xml/download_settings.xml
- app/src/main/res/xml/history_settings.xml
- app/src/main/res/xml/notification_settings.xml
- app/src/main/res/xml/update_settings.xml
- app/src/main/res/xml/video_audio_settings.xml
- added wrapping text to all SwitchPreferencesCompat
- Before:
- After:
- Fixes #6951 
> Added wrapping settings titles to the next line

- app/src/main/res/values/styles.xml
- Remove deprecated preferenceTheme style attribute (see [here](https://developer.android.com/jetpack/androidx/releases/archive/androidx#:~:text=PreferenceThemeOverlay.v14.Material))
- preferenceTheme, if not specified, uses PreferenceThemeOverlay by default
> Remove deprecated preferenceTheme style attribute

- app/build.gradle
- app/src/main/AndroidManifest.xml
Add support for https://y2u.be links.
- Fixes #6525
- TeamNewPipe/NewPipeExtractor#741
> Add support for y2u.be links

- app/build.gradle
- app/src/main/AndroidManifest.xml
Support PeerTube short links.
- Fixes https://github.com/TeamNewPipe/NewPipeExtractor/issues/678
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/743
> Support PeerTube short links

- app/build.gradle
See https://github.com/TeamNewPipe/NewPipeExtractor/pull/753
- Fixes #6669
> Use latest NewPipeExtractor to fix parsing of YT's dislikes

- .github/workflows/ci.yml
- Add sonar CI job back which was commented out
Sonar secret token still exists from before and I think no other stuff needs to be changed
This comes in result of https://github.com/TeamNewPipe/NewPipe/issues/5926
> Readd sonar CI job

- .github/workflows/ci.yml
- Run gradle command in stacktrace mode to hopefully get more information on what is going wrong.
- Related to [#7553](https://github.com/TeamNewPipe/NewPipe/issues/7553)
> Log test-android CI job in stacktrace mode

- README.ja.md
Fixed two warnings which I got while running the code inspection in Android Studio
- Fixed link to Brazil README in Japanese README
- ~~Fixed redundant character class declaration in `EMAIL_ADDRESS` regex~~
> Fix readme link

- app/build.gradle
Updates NewPipeExtractor to the latest commit.
Which among other things contains a fix for #7525.
- Fixes #7525
> Updated NewPipeExtractor

- .github/workflows/ci.yml
This should hopefully narrow down the problem from #7553
> CI: Upload test-report when an error occurs

- README.es.md
- README.ja.md
- README.ko.md
- README.md
- README.pt_BR.md
- README.ro.md
- README.so.md
- README.tr.md
- README.zh_TW.md
Add traditional Chinese translation of README.md
> Add traditional Chinese README

- app/src/main/res/values-sc/strings.xml
- app/src/main/res/values-sv/strings.xml
* Syncs weblate (try No.2 - locked weblate this time)
- Fixes #7688 
> Sync weblate v2

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/982.txt
> Release 0.21.16

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/982.txt
* Merges the master branch back into dev
* Fixes a conflict about the NewPipeExtractor version by using [the lastest commit of the dev branch](https://github.com/TeamNewPipe/NewPipeExtractor/commits/dev)
> Merge ``master`` branch back into ``dev``

- README.md
Small changes to license section of README
I'll update https://hosted.weblate.org/translate/newpipe/strings/en/?checksum=c9e11c232f6af957 after this is merged.
> Small changes to license section of README

- .github/workflows/image-minimizer.js
- .github/workflows/image-minimizer.yml
Check every created/edited issue/issue comment (on GitHub) for uploaded and not further modified images like 
``![ALT_TEXT](https://*.githubusercontent.com/<number>/<variousHexStringsAnd->.<fileExtension(jpg|gif|png)>)``
If an image is detected as too large (currently ``height > 600px``) then it's automatically cropped 
→ ``<img alt="ALT_TEXT" src="<urlFromAbove>" height=600 />``
A live demo is available at https://github.com/litetex/gh-actions-image-minimizer-demo
Example-Issue: https://github.com/litetex/gh-actions-image-minimizer-demo/issues/3
- Fixes #7612
> Added image-minimizer

- .github/workflows/image-minimizer.js
Improved image-minimizer:
* Don't minimize images that are too wide -> they will get stretched otherwise
* Don't try to modify the issue/comment when nothing changed
* Fixed typo
- Before: https://github.com/litetex/gh-actions-image-minimizer-demo/issues/5
- After: https://github.com/litetex/gh-actions-image-minimizer-demo/issues/6
> Improved image-minimizer

- app/build.gradle
- Update ConstraintLayout 2.1.2 -> 2.1.3 ([changelog](https://developer.android.com/jetpack/androidx/releases/constraintlayout#constraintlayout-2.1.3))
- Update Room 2.4.1 -> 2.4.2 ([changelog](https://developer.android.com/jetpack/androidx/releases/room#2.4.2))
These are rather inconsequential patch releases compared to the larger minor releases that other AndroidX libraries have. I'll work on getting those upgraded in other PRs of course.
> Update ConstraintLayout, Room libraries

- LICENSE
Updates the license to the latest version of https://www.gnu.org/licenses/gpl-3.0.txt
This way also GitHub recognizes the License correctly:
It should look like this after merging this PR:
> Update license to latest version

- app/build.gradle
Updated extractor to latest version of the dev-branch.
Might fix (#8183 - for the dev branch) and also helps testing the recent changes in NewPipeExtractor.
> Updated extractor to latest version of the dev-branch

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Updated AGP 7.1.2 -> 7.1.3 (doesn't have one for some reason, but whatever)
- Updated Kotlin 1.6.10 -> 1.6.20 ([changelog](https://kotlinlang.org/docs/whatsnew1620.html))
- Updated Gradle 7.4 -> 7.4.2 ([changelog](https://docs.gradle.org/7.4.2/release-notes.html))
> Update AGP, Gradle, and Kotlin

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/App.java
- Update ACRA 5.8.4 -> 5.9.1 ([changelog](https://github.com/ACRA/acra/releases))
> Update ACRA library

- app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
This PR solve the NullPointerException problem mentioned in the issue
- Fixes #8058
> Fix crash when open NewPipe from notification bar

- app/build.gradle
- Update Groupie 2.10.0 -> 2.10.1 ([changelog](https://github.com/lisawray/groupie/releases))
- Update ACRA 5.9.1 -> 5.9.3 ([changelog](https://github.com/ACRA/acra/releases))
> Update Groupie and ACRA libraries

- doc/README.es.md
- [ X ] Bugfix (user facing)
Fix documentation error (_corrige un error de la documentación_)
- [ x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
> Spanish Readme fix [Corrige frase de README]

- .github/workflows/ci.yml
We don't seem to agree on which character to use as a separator between `release` and `X.X.X` in release branch names (e.g. `release-0.23.1` or `release/0.23.0`). All those names start with `release`, though, so let's use that to identify releases.
> Run CI on all release branches

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/datasource/YoutubeHttpDataSource.java
- Update ExoPlayer 2.18.0 -> 2.18.1 ([changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md))
This contains the fix for https://github.com/google/ExoPlayer/issues/10381 that we need.
> Update ExoPlayer to 2.18.1

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
- Update AndroidX Fragment 1.3.6 -> 1.4.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/fragment)) (1.5.0 will come later)
I tested around, didn't experience anything out of the ordinary. Feel free to test it yourselves.
> Update AndroidX Fragment to 1.4.1

- app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
- Sort video tags case-insensitively.
- Before:
- After:
- Fixes #
> Sort tags case-insensitively.

- app/build.gradle
- Update AppCompat from 1.3.1 to 1.4.2. [Changelog](https://developer.android.com/jetpack/androidx/releases/appcompat)
- Fixes #
> Update AppCompat to 1.4.2.

- app/build.gradle
- Update AndroidX Room 2.4.2 -> 2.4.3 ([changelog](https://developer.android.com/jetpack/androidx/releases/room#2.4.3))
> Update AndroidX Room to 2.4.3

- app/src/main/java/androidx/fragment/app/FragmentStatePagerAdapterMenuWorkaround.java
- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- app/src/main/java/org/schabi/newpipe/player/notification/NotificationConstants.java
- app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
- app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
- app/src/main/java/org/schabi/newpipe/streams/WebMReader.java
- Use `toArray()` methods with zero-length arrays, as they automatically create arrays of the appropriate length.
- Fixes #
> Use toArray() with zero-length arrays.

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/util/FilePickerActivityHelper.java
- gradle.properties
- Use our custom fork: please acknowledge the changes found [here](https://github.com/TeamNewPipe/NoNonsense-FilePicker/compare/4.2.1...5.0.0).
- Disable Jetifier.
> Update FilePicker to our custom fork and disable Jetifier

- app/build.gradle
- fastlane/metadata/android/en-US/changelogs/988.txt
- [YouTube] Fix "Could not get any stream" error when trying to play any video #8760, thanks to @Theta-Dev!
- [YouTube] Fix "The Following content is not available on this app." message shown instead of the video requested #8713
> Release v0.23.2 (988)

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/question.yml
- Added reading the FAQ to the checklist.
- Hopefully leads to fewer duplicate issues.
> Add FAQ entry to the template checklists

- README.md
Clarify that the hidden update span should not be included in translated READMEs. People commit this mistake often.
> Clarify that span shouldn't be in translated READMEs

- app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
> Fix `DownloadDialog` crash on screen rotation

- .github/ISSUE_TEMPLATE/feature_request.yml
- Edited the 'enhancement' label to 'feature request'
> Update issue template label to 'feature request'

- .github/CONTRIBUTING.md
Dates and times are localized using prettytime. Added a note to guide translators to also localize that library to create a fully localized experience.
#9134 
> Add info on date + time localization to contribution guidelines

- app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceFuzzySearchFunction.java
- In the preference search, calculate the preference score using the Streams API.
- Fixes #
> Calculate search score using streams.

- app/build.gradle
- Update the AppCompat version to 1.5.1.
- Update the compile SDK to 32.
- Fixes #
> Update AppCompat to 1.5.1 and compile SDK to 32

- app/build.gradle
Update PrettyTime to 5.0.6
New localizations added: az and pb
<table>
<thead><tr><td>Azerbaijani (az)</td><td>Punjabi (pb)</td></tr></thead>
<tbody>
<tr>
<td><img src="https://user-images.githubusercontent.com/17365767/199311142-1d0f2d08-338d-45e3-a273-c156d6be587b.png"/></td>
<td><img src="https://user-images.githubusercontent.com/17365767/199311979-2dae0d08-c643-4cf5-b8be-ee403ffd8e5f.png" /></td>
</tr>
</tbody>
</table>
Closes #9134
> Update PrettyTime from 5.0.3 to 5.0.6 to include new localizations

- app/build.gradle
- app/src/main/AndroidManifest.xml
Support opening YouTube handles from external apps and update NewPipe Extractor to support parsing them, and include all the latest fixes and improvements of the extractor.
- Fixes #9243
> Support YouTube handles and update NewPipe Extractor

- app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHelper.java
- app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
- app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java
Refer to #8686. I don't know why GitHub suddenly closed that PR after I force pushed 1 commit (not 0 as the UI says!) and wouldn't allow me to push commits or reopen it.
> Use smoother bitmap downscaling for thumbnails

- .github/workflows/ci.yml
- app/build.gradle
- Update Sonarqube 3.3 -> 3.5 ([compare releases for changelog](https://github.com/SonarSource/sonar-scanner-gradle/releases))
> Update Sonarqube to 3.5

- app/src/main/AndroidManifest.xml
Remove dead privacytools instance, we were [unable to migrate this](https://blog.privacyguides.org/2021/09/14/welcome-to-privacy-guides/).
> [PeerTube] Remove dead Privacy Tools instance

- app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java
- app/src/main/res/menu/menu_play_queue_item.xml
- i introduced an option to download queue items in their respective long press menu
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/26669009/205511727-37a27172-fef7-496f-9929-0545cc5f2119.png" width="200px" alt="Before"/></td>
<td><img src="https://user-images.githubusercontent.com/26669009/205511736-8b18046b-17c1-4e6d-b5a7-0371a08fdafd.png" width="200px" alt="After"/></td>
</tr>
</table>
- Fixes #8585 
> Added option to download items in the queue

- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- Asks for permission when long clicking "Popup" to enqueue in a popup on channels and playlists.
- Prevents a crash when there are no videos already in the queue.
- Before:
https://user-images.githubusercontent.com/88139840/211563100-dfdb6505-196d-487a-87d9-f66c0db3c448.mp4
- After:
https://user-images.githubusercontent.com/88139840/211563117-7c013532-ecb5-42d8-b7ab-f9dbfb13466d.mp4
- Fixes #9556
> Ask for permission when enqueuing in a popup

- app/src/main/java/org/schabi/newpipe/settings/tabs/TabsJsonHelper.java
- Added the "What's New"-section to the default tabs
- Fixes #5701
> Added the "What's New"-section to the default tabs

- app/src/main/res/values/settings_keys.xml
It adds the Odia language to the language selector.
It solves the issue #9393.
- Fixes #9393 
I have downloaded and the zip file from the artifacts available in the changes section and opened the apk file inside the zip and installed it.
It works perfectly, odia language is available in the language selector in this apk file.
> Added Odia language to language selector 

- app/build.gradle
Read the [official changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md) for more info.
> Update core library desugaring from 2.0.0 to 2.0.2

- app/src/main/res/layout/list_stream_playlist_card_item.xml
Fix progress bar scaling on thumbnail in playlists card view
- Before:
- After:
- Fixes #9765 
> Fix progress bar scaling on thumbnail in playlists card view

- app/build.gradle
simple version bump to current ExoPlayer release. Checked for deprecations, there were none, so no code changes necessary.
https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md
> Bump ExoPlayer to 2.18.5

- .github/CONTRIBUTING.md
- README.md
More details will be announced soon!
> Add notice to README to not open feature PRs

- build.gradle
Just a minor version update. The changelog is [here](https://developer.android.com/build/releases/gradle-plugin#agp-8-0-1), and contains only bugfixes. The PR that updated to 8.0.0 is here, for reference: #10035. I ran a build and it worked fine.
> Update Android Gradle Plugin to 8.0.1

- app/src/main/res/values/settings_keys.xml
The translation is already done:
https://hosted.weblate.org/projects/newpipe/strings/nqo/
- Before:
- After:
- Fixes #
- 
> add language ߒߞߏ (nqo)

- app/build.gradle
- `v0.22.6` cannot be resolved for some reason. Fixed by pointing to the `v0.22.6` version commit.
> Fix unresolved extractor

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Update Sonarqube 3.5.0.2730 -> 4.0.0.2929 ([changelog](https://github.com/SonarSource/sonar-scanner-gradle/releases/tag/4.0))
- Update Checkstyle 10.3.1 -> 10.11.0 ([changelog](https://checkstyle.sourceforge.io/releasenotes.html))
- Update ExoPlayer 2.18.5 -> 2.18.7 ([changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md))
- Update desugar_jdk_libs 2.0.2 -> 2.0.3 ([changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md))
- Update jsoup 1.15.3 -> 1.16.1 ([changelog](https://jsoup.org/news/))
- Update OkHttp 4.10.0 -> 4.11.0 ([changelog](https://github.com/square/okhttp/blob/master/docs/changelogs/changelog_4x.md#version-4110))
- Update RxJava 3.1.5 -> 3.1.6 ([changelog](https://github.com/ReactiveX/RxJava/releases))
- Update Test Junit …
> Update some libraries

- app/src/main/AndroidManifest.xml
also sort the lines, because it will quickly become a mess otherwise
- sort the host lines in the “PeerTube” section of the manifest
- add the host “peertube.stream”
- Not concerned
- None
Link to the artifact: https://github.com/quarthex/NewPipe/suites/13386361596/artifacts/732718070
> handle links to the PeerTube instance “peertube.stream”

- app/src/main/res/values/strings.xml
Use the same capitalization for the "Night theme" setting as literally every other NewPipe setting.
Been a pet peeve of mine for some time.
> Make capitalization of "Night theme" setting consistent with others

- .github/workflows/image-minimizer.js
`Number.toFixed()` returns a string, `Math.floor` a number
> Image minizier: replace Number.toFixed(0) with Math.floor()

- .github/workflows/pr-labeler.yml
Use our PR labeler fork to update some libs
> Use PR labeler fork

- app/build.gradle
- app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelTabFragment.java
- fastlane/metadata/android/en-US/changelogs/996.txt
- Fix NPE when ChannelTabLHFactory not implemented for a service #10699
> Newpipe 0.26.1

- README.md
- Update the Matrix chat URL to point to the new room.
- People unknowingly joining the old room, fragmenting the conversation and possibly going unheard.
> Update Matrix chat URL to new link

- app/build.gradle
- Bump jsoup from 1.16.2 to 1.17.2 ([changelog](https://github.com/jhy/jsoup/releases))
> Update jsoup to 1.17.2

- .github/workflows/ci.yml
This updates the use of actions that still rely on Node 16.
Workflow that ran with the updated actions: https://github.com/TobiGr/NewPipe/actions/runs/8443331003
More info: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update workflows to use Node 20

- app/build.gradle
- app/src/main/res/layout/list_playlist_bookmark_item.xml
This PR fixes the bugs introduced by https://github.com/TeamNewPipe/NewPipe/pull/11024, namely:
- missing height attributes on some fields
- the thumbnail was not enforced to be ~16:9 anymore
This PR also ellipsizes the uploader, if it turns out to be too long. And it updates NewPipeExtractor, because otherwise it is impossible to find new playlists in YouTube.
Note: it works also on SoundCloud square thumbnails, which get aligned to the left, as you can see in the screenshot.
- Fixes https://github.com/TeamNewPipe/NewPipe/pull/11024#issuecomment-2478065722
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and …
> Actually fix playlist bookmark layout

- app/build.gradle
- gradle/libs.versions.toml
While #11282 removed the ViewPager2 dependency, #11684 intervened, hence this change was omitted. Just taking care of that.
- Before:
- After:
- Fixes #
> Remove ViewPager2 dependency

- .github/CONTRIBUTING.md
-  Word "bug-report" in Contributing.md is written as "bugreport". This PR simply adds a space between to write the word correctly as "bug report"
- Fixes #11783
> Correct a Typo in Contributing.md

- app/src/main/java/org/schabi/newpipe/util/Localization.java
- Include full locale info in audio track labels
| - | - |
| ![before](https://github.com/user-attachments/assets/979a4851-7fb2-498f-94cb-e9c2fd859d06) | ![after](https://github.com/user-attachments/assets/1ceb594e-d9ca-4d80-a4fc-a525f0c4b29b) |
- Fixes #12088
> Disambiguate audio track labels

- app/build.gradle
just a chore
- Before:
- After:
- Fixes #
- 
> build.gradle: Improve jitpack workaround doc & fix hash

- app/src/main/java/org/schabi/newpipe/util/Localization.java
From the discussion in
https://github.com/TeamNewPipe/NewPipe/pull/12188 it reads more natural for RTL readers.
> Comments: Put @ on the right side of right-to-left usernames

- app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- app/src/main/java/org/schabi/newpipe/player/Player.java
- app/src/main/java/org/schabi/newpipe/player/PlayerIntentType.kt
- app/src/main/java/org/schabi/newpipe/player/PlayerService.java
- app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
- app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java
- app/src/main/java/org/schabi/newpipe/player/playqueue/SinglePlayQueue.java
- app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- app/src/main/java/org/schabi/newpipe/util/text/InternalUrlsHandler.java
- app/src/main/java/org/schabi/newpipe/util/text/TextLinkifier.java
- app/src/main/java/org/schabi/newpipe/util/text/TimestampLongPressClickableSpan.java
- app/src/main/java/org/schabi/newpipe/util/text/UrlLongPressClickableSpan.java
This is a fix for #11013 
But for the fix to work, I started cleaning up the Player intent handler a little.
I could possible have hacked it into the if/if/else chain somehow, but there’s just too many different ways to call the intent that it would have broken some other case.
So instead I opted for starting to rewrite the intent into a simple tagged enum value.
This refactor is only done until the point where I could make the fix so far though, see the commit descriptions.
I also simplified the handler in the first few commits, removing intent keys that were not set in any intent calls anymore. This is in theory a breaking change to the PlayerService intent, but I don’t consider that a public API of NewPipe that people use.
- Before: …
> Fix clearing queue when tapping on timestamp
