app/src/main/java/org/schabi/newpipe/player/Player.java
The last weeks and NewPipe versions I had the issue that as soon as my phone connected via BT with my car NewPipe crashed as for some reason "onCompleted" was called.
`
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()' on a null object reference
org.schabi.newpipe.player.Player.onCompleted
org.schabi.newpipe.player.Player.changeState
org.schabi.newpipe.player.Player.onPlayerStateChanged
```
Maybe I am the only one and this is a specific issue with my current car / car software, but as we have the same null checks in other listener methods, I felt it doesn't hurt to add it here as well.
#6233
=> Fix NPE when connecting via BT

app/src/main/res/values-b+zh+HANS+CN/strings.xml
plural : one -> other
Fix #6468 #6469 
None! ( go to ci if you need )
=> [Localization]Fix Simplified Chinese Plural

.github/PULL_REQUEST_TEMPLATE.md
Correct the instructions to download a test APK
Correct the instructions to download a test APK
The instructions to get the test APK are outdated due to changes by GitHub (see below)
=> Fix APK testing section

app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Close database before restarting the app
Fixes crash when refreshing feed after importing database or subscriptions.
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.database.subscription.SubscriptionEntity.setName(java.lang.String)' on a null object reference
at org.schabi.newpipe.local.subscription.SubscriptionManager.updateFromInfo(SubscriptionManager.kt:73)
at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:324)
at …
```
=> Fix crash when refreshing feed after importing database or subscriptions

app/build.gradle
- Update AutoService 1.0-rc7 -> 1.0 ([changelog](https://github.com/google/auto/releases/tag/auto-service-1.0))
- Update Markwon 4.6.0 -> 4.6.2 ([changelog](https://github.com/noties/Markwon/releases))
- Update Stetho 1.5.1 -> 1.6.0 ([changelog](https://github.com/facebook/stetho/releases))
- Update AndroidX Media 1.2.1 -> 1.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/media))
=> Update some libraries

.github/workflows/ci.yml
- temporary fix from https://github.com/ReactiveCircus/android-emulator-runner/issues/160
All actions for instrumented tests fail due to emulator not starting properly
```
/Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
adb: no devices/emulators found
The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
Error: The operation was canceled.
```
=> Specify emulator-build version in CI job

app/src/main/res/layout/fragment_video_detail.xml
- makes the thumbnail in the minimized player visible again
- more information is available at https://github.com/TeamNewPipe/NewPipe/issues/6615
- Before: 
- After: 
- Fixes #6615
=> Made the thumbnail in the minimized player visible again

app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java, app/src/main/res/layout/chip.xml, app/src/main/res/layout/item_metadata.xml, app/src/main/res/layout/item_metadata_tags.xml
- Instead of using a percentage of the screen width, I now set the tag label width to `96dp`. I don't know why I chose a percentage in the first place, since using a constant width works better in any layout (e.g. on tablets or TVs).
- Tags are now placed at the bottom of the description tab, with a centered TAGS label and a full visible list of tags, as requested in #6459.
Fixes #6459
=> Improved metadata layout, better tags accessibility

app/src/main/java/org/schabi/newpipe/MainActivity.java, app/src/main/java/org/schabi/newpipe/RouterActivity.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/player/MainPlayer.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
- PlayerHolder: convert to Singleton, handle context within, prevent ServiceConnection leak
- VideoDetailFragment: use viewBinding correctly
- VideoDetailFragment: remove duplicated code for toggle Fullscreen
- VideoDetailFragment: move null checks for player and playerService to helper methods
- Player/MainPlayer: service.onDestroy() should only be called from the system and not manually
=> Convert PlayerHolder to Singleton; cleanup in VideoDetailFragment; Player/MainPlayer do not call onDestroy() directly

app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
Follow up to #6495. See commit messages for detailed descriptions
- Remove option to immediately commit pref changes on import 
- Resolve sonar issues in ContentSettingsFragment 
- Remove variable ContentSettingsFragment.lastImportExportDataUri
I tested it manually on API 28 emulator
1. by exporting the settings
2. moving the exported file somewhere else
3. trying to import and verify that the file explorer opens the old correct path
4. navigate to the moved file and import
5. verify that another export now opens to the new file location.
=> Remove option to immediately commit pref changes on import

.github/workflows/ci.yml
api level 29 currently times out, see https://github.com/TeamNewPipe/NewPipe/pull/6673/checks?check_run_id=3080440435.
so remove until it is resolved https://github.com/ReactiveCircus/android-emulator-runner/issues/168
=> Remove api level 29 from android ci tests

app/src/main/java/org/schabi/newpipe/player/Player.java
- Use [`GestureDetectorCompat`](https://developer.android.com/reference/androidx/core/view/GestureDetectorCompat) to backport `GestureDetector` improvements to Android versions below 4.3, allowing this change to be used in NewPipe Legacy.
=> Use GestureDetectorCompat.

app/build.gradle, app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java, app/src/main/res/layout/fragment_comments.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
Currently NewPipe shows an error when the comments are disabled → #5769 / https://github.com/TeamNewPipe/NewPipeExtractor/issues/577
<details><summary>Adds a "Comments are disabled" line under the "No comments" area when the comments are disabled <br/>(click to show demo) </summary>
</details>
For testing:
SFW Video with disabled comments: https://m.youtube.com/watch?v=MhReKn8STX8
- Fixes/Improves #5769 
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/652
=> Added comments disabled functionallity

app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt, app/src/androidTest/java/org/schabi/newpipe/testUtil/TrampolineSchedulerRule.kt
- Add instrumented tests for LocalPlaylistManager.createPlaylist
- No automated tests!
- #5360 So instrumented tests are actually run in the CI pipeline
- Besides testing the code, this should also serve as a "how-to" which can be referenced when asking contributors to add tests to classes like this one
- There are 2 weird behaviours which i commented. They should be adressed somewhere seperatly and not here.
- The manager layer and DAO layer is tested together here. Mocking the DAO with Mockito makes the tests very brittle. The example here, also does it like this. See `TaskLocalDataSource` which should be the equivalent layout to our `LocalPlaylistManager` https://github.com/android/architecture-samples
- RxJava is unpleasant to test
=> Add instrumented tests for LocalPlaylistManager.createPlaylist

app/build.gradle, app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java, app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- This is the second of what will most likely be a trilogy of PRs for fixing the onActivityResult/onRequestPermissionsResult deprecations (the stuff dealing with the ReCaptcha result stuff will be the third PR)
=> More onActivityResult deprecation fixes

app/build.gradle
- Bump the `compileSdkVersion` to 30.
=> Bump compileSdkVersion to 30.

app/build.gradle, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHelper.java, app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHolder.java, app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SyncImageLoadingListener.java, app/src/main/java/org/schabi/newpipe/util/ImageDisplayConstants.java, app/src/main/res/layout-large-land/player.xml, app/src/main/res/layout/player.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/video_audio_settings.xml
<details><summary><b>Click here to show the demo (screenshots + video) data</b><br/> (it's a lot so it's collapsed by default)</summary>
<p>
- Full demo video:
https://user-images.githubusercontent.com/40789489/120905951-e3205980-c655-11eb-8087-59f7e81c2cd6.mp4
- Screenshots:
- Settings:
- Video seekbar thumbnail preview (high quality):
- Video seekbar thumbnail preview (low quality):
- Video seekbar thumbnail preview (off):
</p>
</details>
<br/>
<details><summary><b>Implementation details (click to open)</b></summary>
<p>
These are the major parts of this implementation:
**(Meta)-Data**
The metadata of a video contains a new field (the extractor had to be modified for this → https://github.com/TeamNewPipe/NewPipeExtractor/pull/647 )
* This field consists of a list of framesets (yt …
=> Player seekbar thumbnail preview

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
This issue fixes 2 build warnings/deprecations:
The code on these parts was relatively old (>2 years).
Description of the fixes:
* ``FeedFragment``: Removed updateRelativeTimeViews when the activity is paused
We don't need to call ``updateRelativeTimeViews`` when the activity is paused, because the user likely won't notice it (because it is paused).
Despite that ``onResume`` already calls ``updateRelativeTimeViews`` so there is no need to do that twice.
* ``SubscriptionFragment``: Simplified code and adjusted the style so that it's similar to FeedFragment
The title there got set twice (no idea why). Simply copied use the same code (2 lines) from FeedFragment
not applicable
not applicable
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", …
=> Fix some build warnings

.github/CONTRIBUTING.md
Core team does not want to convert to Kotlin yet and sees Java as the easier to learn and more well adopted language.
This stance might of course change in the future. For example it could be reasonable to do a complete transition to Kotlin once it is decided that the minSdk is raised to 21 or higher, as we then could use Jetpack particularly Lifecycle and Compose.
=> Added a Kotlin section in CONTRIBUTING.md

app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt
- Make use of Kotlin methods, such as the `let` block, in `LicenseFragment`.
=> Use Kotlin methods in LicenseFragment.

app/build.gradle
- Looks like something got wrong when merging https://github.com/TeamNewPipe/NewPipe/pull/6434:
The commit https://github.com/TeamNewPipe/NewPipe/commit/253526e565a52f36191d0bb6c84a67586ab28ea4 shouldn't be on the ``dev``-Branch as it relies on changes from MY repo
- Updated the dependency to the correct repo and the latest commit so that the changes from https://github.com/TeamNewPipe/NewPipe/pull/6434 work
not applicable
not applicable
not applicable
=> Use the correct extractor dependency

app/build.gradle, app/src/main/java/org/schabi/newpipe/player/Player.java
- Use `WindowInsetsCompat`'s `getInsets` method to get the display cutout insets.
=> Use WindowInsetsCompat's getInsets() method.

app/src/main/java/org/schabi/newpipe/RouterActivity.java, app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
The first commit just reorders some methods in the `DownloadDialog` class and adds some comment section separators. 
The second commit fixes the `DownloadDialog` (which is a `DialogFragment`) dismissing according to [this thread](https://stackoverflow.com/questions/11201022/how-to-correctly-dismiss-a-dialogfragment): every reference to `getDialog().dismiss()` is replaced with just `dismiss()`. I also removed references to `getDialog().setOnDismissListener()` and replaced them with a new `onDismissListener` in `DownloadDialog`, required by `RouterActivity` to be able to `finish()` itself when the dialog dismisses. Then I removed the part of code that used to `finish()` the `RouterActivity` inside the `DownloadDialog` (it was in the wrong place), as that's now done correctly by the …
=> Dismiss download dialog correctly

app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt, app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
- Fix grid span count calculation
- Move the duplicate methods `shouldUseGridLayout()` and `getGridSpanCount()` into `ThemeHelper`. They were both duplicated in three classes: `BaseLocalListFragment`, `FeedFragment` and `SubscriptionFragment` and had a different (maybe wrong) implementation each time.
- In `getGridSpanCount()`, instead of doing `(int) Math.floor(screenWidth / ((float) minWidth))`, I just do `screenWidth / minWidth` since the default integer division already yields the floor-ed result.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36421898/126211932-5878e8bf-61de-486e-abde-b9d4194fdc0d.png"/></td>
<td><img src="https://user-images.githubusercontent.com/36421898/126211841-831e88e9-36b5-4a49-a90a-9801d6a995e9.pn …
=> Fix grid span count calculation

.github/workflows/ci.yml
- The action got fixed and released https://github.com/ReactiveCircus/android-emulator-runner/releases/tag/v2.19.1
=> Readd api level 29 to android CI tests

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java, app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueItemTest.java, app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java
This is a simple bugfix that allows having play queues with duplicate items. For some reason an `equals()` method was implemented in `PlayQueueItem` that only compared the url, and since duplicate items have the same url they were considered the exact same `PlayQueueItem`s. Using Java's default `equals()` method, that just checks if two objects are the same with `==`, solves the issue, since duplicate items were anyway created one by one and thus are never identical. Removing `equals()` should be completely fine since `PlayQueueItem`s are never `clone()`d, and therefore we never end up with two objects that should be considered the same but down in memory aren't because they were cloned.
- Fixes #4940
The APK can be found by going to the "Checks" tab below the title. On the left pane, …
=> Fix duplicate items in queue causing endless buffering

app/src/main/java/us/shandian/giga/service/DownloadManager.java
When loading pending missions from disk, sometimes an invalid mission with `storage == null` would be read (because of a corrupted file or with an outdated file format). This caused `NullPointerException`s down the line. So I added `hasInvalidStorage()` to the prelimiary checks on the mission object loaded from file, and if that's the case the related file is deleted. (each pending mission has its own file)
- Fixes #6687
@timjefferies @bew @castrik does this fix the problem for you?
=> Delete pending missions with invalid storage

app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java
After the cookies are extracted from the recaptcha webview make it load an empty page to prevent youtube being loaded unecessarily in the background.
- Load empty page in recaptcha webview after youtube is no longer needed
- Fixes #6732 
=> Prevent recaptcha webview from keeping youtube loaded in background

app/src/main/res/values/styles_misc.xml
The toolbarSearchTheme was accidently broken with https://github.com/TeamNewPipe/NewPipe/pull/6456, see https://github.com/TeamNewPipe/NewPipe/pull/6456#issuecomment-885920235 for details.
It's impossible to select text properly, because the cursor (and the enclosing brackets) have the same color as the background.
This pr fixes the issue by restoring the old behavior.
- Before: see https://github.com/TeamNewPipe/NewPipe/pull/6456#issuecomment-885920235
- After:
- Fixes https://github.com/TeamNewPipe/NewPipe/pull/6456#issuecomment-885920235
=> Fixed the ToolbarSearchTheme

app/src/main/java/org/schabi/newpipe/streams/io/StoredFileHelper.java, app/src/main/java/us/shandian/giga/get/DownloadMission.java
I just added yet another null check ;-)
I removed the ` || storage.isInvalid()` check in `DownloadMission` since that's already taken care of by ` || !storage.existsAsFile()`
Fixes https://github.com/TeamNewPipe/NewPipe/issues/6687#issuecomment-885928174
=> Fix NullPointerException when checking if storage exists

.github/workflows/ci.yml
We had quite some discussion in #6709. This PR is the successor.
Run ``ktlint`` before building on the CI.
- Fixes #6708 
=> Check formatting of kotlin files in CI

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java, app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java, app/src/main/res/values/strings.xml
- Add a method to HistoryRecordManager that adds a record to the history and sets a video to 100% watched
- Add an item to the stream dialog labeled "Mark as played" that calls the above method
- Before:
- After:
- Fixes #2642
=> Add ability to mark an item as played

app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java, app/src/main/res/drawable-night/ic_heart.xml, app/src/main/res/drawable/ic_heart.xml, app/src/main/res/layout/list_comments_item.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
- Show a heart next to the like count on comments that have `heartedByUploader` set to true.
- Before:
- After:
- Fixes #6458 
=> Show hearts in comments

app/build.gradle, app/src/main/java/org/schabi/newpipe/MainActivity.java
This PR is meant as a follow up to https://github.com/TeamNewPipe/NewPipe/pull/6702.
- https://github.com/TeamNewPipe/NewPipe/pull/6633#issuecomment-882505567
- Update AndroidX AppCompat 1.3.0 -> 1.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat#version_131_3))
- Update AndroidX Core 1.3.2 -> 1.6.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/core#core_and_core-ktx_version_160_2))
- Update AndroidX Fragment 1.3.5 -> 1.3.6 ([changelog](https://developer.android.com/jetpack/androidx/releases/fragment#version_136_3))
- Update AndroidX Lifecycle 2.2.0 -> 2.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/lifecycle#version_231_2))
- Users are basically already using these versions internally because of …
=> Update some AndroidX libraries

app/src/main/java/org/schabi/newpipe/App.java
- Use `NotificationChannelCompat`.
=> Use NotificationChannelCompat.

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
This patch changes click handlers for feed (Whats new) so that they do
nothing while the feed is refreshing and the items being clicked are not
visible.
- Prevents the user from being able to click on feed items while the refresh overlay is shown and the items themselves are hidden.
- Fixes #6081
=> Disable feed click events while refresh overlay is shown

app/build.gradle
- closes #6510
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6895581/app-debug.zip)
=> Update extractor, thus including throttling fixes

.github/workflows/ci.yml
Avoid running CI when only the only change is a README file.
=> Ignore paths unrelated to builds in CI

app/build.gradle, fastlane/metadata/android/en-US/changelogs/974.txt
Yet another hotfix release. No NewPipe-side PRs were included; instead all NewPipeExtractor PRs were included since cherry picking 55 commits possibly depending on the parent ones would not have been feasible. The PRs I had to include for this reason, but which were not essential for the hotfix, were anyway small PRs with no possible regression (https://github.com/TeamNewPipe/NewPipeExtractor/pull/661 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/647). The detailed extractor changelog is [here](https://github.com/TeamNewPipe/NewPipeExtractor/releases/tag/v0.21.8). Even though usually NewPipe's changelog do not contain NewPipeExtractor PRs references, I had to include them in this case because otherwise the changelog would have been empty. Anyway the changelog for NewPipe …
=> Hotfix release 0.21.8

.github/workflows/ci.yml
As mentioned in https://github.com/TeamNewPipe/NewPipe/pull/6709#issuecomment-888559715:
> * Is something speaking against adding [``workflow_dispatch:``](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) by default to the CI workflow? 
> If I do these kinds of PR, I always have to add it manually and change the default branch of my fork. 
> Shouldn't do any harm in theory.
> If nothing speaks against it I will open a PR.
=> Allow manual execution of ci workflow

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt, app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
In  #6705 I didn't notice that, when calculating the maximum number of grid list items that could fit horizontally, the `SubscriptionFragment` used a different `minWidth` than the other list fragments. This is because all other list fragments contain `StreamInfoItem`s, while the `SubscriptionFragment` contains `ChannelInfoItem`s. So I've created two methods to calculate the span count: one for streams (doing the same calculation as before) and one for channels.
See the screenshots in #6802. This restores the correct pre-0.21.7 behaviour.
- Fixes #6802
=> Fix channel item span count for SubscriptionFragment

.github/workflows/ci.yml, app/build.gradle
- Add gradle parameter to skip formatKtLint and use in CI
<details>
<summary>with parameter</summary>
</details>
<details>
<summary>without parameter it starts with formatKtLint</summary>
</details>
- This way `runKtlint` is not executed twice during CI
=> Add gradle parameter to skip formatKtLint and use in CI

app/src/main/java/org/schabi/newpipe/player/Player.java
this pull request replaces #6512
if a region is named android studio will show its name in the structure view.
- increase readabilty in android studio structure view
=> name the regions according to the comments

app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java, app/src/main/java/org/schabi/newpipe/util/external_communication/TimestampExtractor.java, app/src/test/java/org/schabi/newpipe/util/external_communication/TimestampExtractorTest.java
Catches errors while processing timestamp-links.
- Fixes #6842 
=> Catch errors while processing timestamp-links

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
Only display the "mark as watched" item in the feed context menu when the watch history is enabled.
=> Only show "mark as watched" when watch history is enabled

app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/res/layout/dialog_feed_group_create.xml
This PR replaces every occourrence of `android.R.string.cancel` with `R.string.cancel` (which was already being translated and used in other places). The `android.R.string.cancel` could not be used since it is missing translation in some languages, like Somali.
- Fixes #5454
=> Use custom cancel string everywhere

.github/workflows/no-response.yml
Add a workflow to help manage issues where the author hasn't responded to requests for more information. Here's an example:
1. I open an issue, but it doesn't give enough information
2. `@opusforlife` creates a comment asking me for the missing enough and labels the issue as `waiting-for-author`
3. If I reply before 14 days, the label is automatically removed. If I reply after 14 days, the label is automatically removed and the issue is re-opened.
I [opened an issue on the action's repo asking whether this works with PRs](https://github.com/lee-dohm/no-response/issues/171), but there's no reply yet. In any case, usage with PRs right now should be avoided, as 14 days is a far too short span of time. I plan to modify the action so we can have a separate `daysUntilClose` for PRs, but for …
=> Add no-response workflow

app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionItem.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java, app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java, app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/content_settings.xml
<table>
<tr>
<td><img width="1500px" src="https://user-images.githubusercontent.com/36421898/85949795-142ddf80-b959-11ea-841e-4f8193ca5bab.png"/></td>
<td>This PR replaces the switch preference to enable/disable all search suggestions with a multiselect one, so that the user can choose which types of search suggestions he likes: local, remote, both, none.
Since the previous preference stored a <code>boolean</code> while the new one stores a <code>Set&lt;String&gt;</code>, I had to create a migration function and call it in <code>NewPipeSettings.init()</code>. If the previous value was <code>true</code>, both local and remote suggestions are activated, otherwise they are both deactivated. I testes this and it works both when updating the app and when importing a database with the old …
=> Allow choosing which types of search suggestions to show

app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
ExoPlayer 2.12 noted this in the changelog:
_Set the default minimum buffer duration in DefaultLoadControl to 50 seconds (equal to the default maximum buffer), and treat audio and video the same._
Maybe there was a reason they decided to have both minimum and maximum buffer identical since 2.12. NewPipe used years old constants which are now removed in favor of ExoPlayer constants so that future versions will keep up with what changes at ExoPlayer.
Hopefully fixes some of the buffer issues we have lately like #6510 
=> Use ExoPlayer default values for buffers

app/src/main/java/org/schabi/newpipe/player/Player.java
Simpler successor to #6322.
Fixes double tapping the replay button
- Fixes #6217 
=> Fixed double tapping the replay button

app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
- Use [`PackageInfoCompat.getSignatures`](https://developer.android.com/reference/androidx/core/content/pm/PackageInfoCompat#getSignatures(android.content.pm.PackageManager,%20java.lang.String)) to get the app signatures.
=> Use PackageInfoCompat.getSignatures().

app/build.gradle, app/src/main/java/org/schabi/newpipe/about/License.kt, app/src/main/java/org/schabi/newpipe/about/SoftwareComponent.kt, app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt, app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt, app/src/main/java/org/schabi/newpipe/util/SavedState.kt, app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.kt, build.gradle
* Updated kotlin everwhere to 1.5.30 to fix version conflicts → 
* Replaced deprecated kotlin-android-extensions with ``kotlin-parcelize``
References:
* https://developer.android.com/topic/libraries/view-binding/migration#groovy
* https://developer.android.com/kotlin/parcelize#groovy
* Removed ``experimental = true`` as it doesn't work anymore in Android Studio and without it the app works fine (subscription groups, feed, etc)
* Replaced deprecated import ``kotlinx.android.parcel`` with ``kotlinx.parcelize``
* Fixed some other build problems/warnings
* ~Fixed "condition ``throwable != null`` is always ``true``"~
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which …
=> Fix build problems and updated kotlin

app/src/main/java/org/schabi/newpipe/player/Player.java
* Set ``KeyProgressIncrement`` manually to the value of the seek duration in the settings so that it works when using the DPad
* consolidated code inside a new method to avoid duplication
- Before: → https://github.com/TeamNewPipe/NewPipe/issues/6937#issuecomment-905927450
- After: 
https://user-images.githubusercontent.com/40789489/130991070-c88a7d78-407b-49ca-8572-ffb68d21d2fe.mp4
- Fixes #6937
=> Set ``KeyProgressIncrement`` manually / Fix long seekbar jumps when using a DPad

.github/workflows/ci.yml
Using integrated cache in ``actions/setup-java`` instead of specifying it.
See https://github.com/actions/setup-java#caching-gradle-dependencies for details.
Advantages:
* Results in more compact and easier readable code
* We don't need to specify/manage the cache ourselves as the action does it automatically
A test of the above can be seen in:
* https://github.com/litetex/NewPipe/runs/3450616944?check_suite_focus=true
* https://github.com/litetex/NewPipe/runs/3450662800?check_suite_focus=true
=> Using integrated cache in ``actions/setup-java``

app/build.gradle, app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java, app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/res/menu/menu_play_queue_item.xml
- Added `menu_play_queue_item.xml` as the resource to inflate the popup menu from.
- Refactored the existing popup menu code in the background/popup player queue to use the menu xml.
- Added the popup menu code to the main player queue.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><video src="https://user-images.githubusercontent.com/71804605/130356012-cfe1daf4-ddf2-4e8e-9709-92756883e72c.mp4"/></td>
<td><video src="https://user-images.githubusercontent.com/71804605/130356044-31f1da0d-6527-4b84-95ce-7f12f5a11f57.mp4"/></td>
</tr>
</table>
- Fixes #4778 
https://github.com/TeamNewPipe/NewPipe/suites/3562943169/artifacts/85514049 (Link copied from the Checks tab)
=> Show popup menu when long pressing in play queue (Full screen player)

app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
NewPipe would announce the audioSessionId once it is created for the ExoPlayer instance or when Audio gets enabled again after being disabled. However it did never announce closure of an audioSessionId. This is now done properly.
Apparently the missing closure of the audio effect control session could lead to memory leaks and cause problems with DSP / AudioFX / Equalizer apps. See also discussion in #2373 
- Fixes  #2373
=> Close audio effect control session properly

app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt, app/src/main/res/layout/error_panel.xml
I tried to fix #7003 quickly as mentioned in https://github.com/TeamNewPipe/NewPipe/issues/7003#issuecomment-907631644 however I found some major issues with the ErrorPanel that made it very poor understandable, caused #7003 in the first place and decided to fix these instead.
Summary of changes:
* All element on the error panel are now hidden by default (expect for the ``errorTextView``) as they are only optional shown - depending on the situation and type of the error
* Added a method to ensure the above (if e.g. the panel is reused)
* This deduplicates a lot of code
* Fixed format of some LoC (they were too long)
* Added new method: ``showAndSetErrorButtonAction`` (see JavaDoc for more information)
* Named buttons more logically: ``errorButtonAction`` -> ``errorActionButton``
- Before: …
=> Reworked the ErrorPanel

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/MainPlayer.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java, app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/video_audio_settings.xml
This PR adds a switch to video&audio settings that, when enabled, causes the main player to start automatically in fullscreen mode. This was rather painful to implement, but I think this finally works well.
Fixes #4152
Fixes #4387
Fixes #4682
Fixes #5845
Fixes #5594
Fixes #5299
Fixes #6785
Fixes #6784
Fixes #6131
See #4548
=> Add option to directly open fullscreen when the main player starts

app/src/main/res/drawable-night-v23/splash_background.xml, app/src/main/res/drawable-night/splash_background.xml
added night value in res for Opening Theme
added splash_background_night
- Before: Bright launch screen even when using dark mode system wide
- After: Now it's darker :)
- Fixes #7048
=> Added night variant for splash_background.xml

app/src/main/java/org/schabi/newpipe/player/Player.java
Just like in the issue #7062, this doesn't affect UI as it updates every one second anyway, but reduces very heavy android widget progress bar high cpu usage. With every 500 ms there is 6% cpu usage and with 1 s only 4%. However further changes will have to be made to disable updating of player progress bar when screen is off to further reduce power consumption. With this, total power savings would be 20% in mAh consumption in background playback. This pull request does approx 10% longer screen-off playback.
Change frequency of player progress bar update to 1s
- Fixes #7062
=> Change player progress bar update from 500 ms to 1 s

app/src/main/res/values-night-v21/styles.xml
* Fixes the navbar color when using the dark opening theme
* The problem was added with #7055
- Before:
https://user-images.githubusercontent.com/74829229/132558145-f5c930b8-ebdc-433e-af65-1b37fcd9c59e.mp4
- After:
https://user-images.githubusercontent.com/40789489/132753442-e4ce1095-f982-469c-a0af-402a56b054b5.mp4
This will fix the comment mentioned in https://github.com/TeamNewPipe/NewPipe/issues/7066#issuecomment-915441693
=> Fixed the navbar color for darkmode

app/src/main/java/org/schabi/newpipe/BaseFragment.java, app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt, app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java, app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
- Fixed updating the wrong tabs when changing settings while running the minimized player in VideoDetailFragment. The comments tab was updated although the settings for the description tab were changed.
- Fixed `OnErrorNotImplementedException` in `InternalUrlsHandler.playOnPopup` by implementing error handling. A popup is shown with a little info on the error:
- Fixed  `OnErrorNotImplementedException` in `SearchFragment.initSuggestionObserver()`. Errors are reported in the snackbar now. Not sure if I also managed to fix the cause of the original error. This needs to be investigated.
- Fixed a few warnings by SonarLint
- Fixes #6873
- Fixes #6979
- Fixes #6976
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and …
=> Fix handling exception in `playOnPopup` and toggle description tab

app/build.gradle, app/src/main/java/org/schabi/newpipe/App.java, app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
The current method https://github.com/TeamNewPipe/NewPipe/blob/6a1d81fcf311abab0a1caa8c207b9fa6f2e9cea3/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java#L602-L613 doesn't seem to work as expected. It fails to restart the app completely which causes invalid states when e.g. migrating the database and results in an appcrash.
Note: This introduces a new external library:  [``process-phoenix``](https://github.com/JakeWharton/ProcessPhoenix)
- Before:
https://user-images.githubusercontent.com/40789489/132254295-d71cc5f6-cd3d-46be-bca1-c8b6f0543376.mp4
Note: ACRA fails to open, may be an additional problem (could be https://github.com/TeamNewPipe/NewPipe/issues/5222)
Also note that it migrates the settings after the app crashes as seen in the log 😆: …
=> Fixed restarting not working properly

app/build.gradle, doc/gradle.md
- Allow passing in package suffix for release builds through CLI param
- Add documentation for the custom gradle parameters
- Fixes #6420
- Run `gradle clean assembleRelease -DpackageSuffix=nightly`
- Sign it with `apksigner` https://developer.android.com/studio/command-line/apksigner
- Install the apk and see that it has the `nightly` suffix
=> Allow passing in package suffix for release builds through CLI param

app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt
feat: it was added a string variable to avoid replication one.
=> Simple Codebase Improvement  

app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
- The "Search Suggestions" setting in Settings > Content > Search Suggestions is a `MultiSelectListPreference` and that exports as a `HashSet` of all the enabled options.
- The export was going through properly, but the import function did not have a case to handle the value if it was a `HashSet` in the key-value pair.
- Since the incoming value was not being processed, the setting was just reverting to its default values.
- I have added the case to handle when the value is a `HashSet`. 
- The `Suppress` annotation was added because value is of type `any?` and it needs to be converted to `MutableSet<String>?` which throws an `Unchecked Cast` warning. As far as I know, this warning can be suppressed without any problems, because the `HashSet` will always be convertible to …
=> Fix Settings import

app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Disables media tunneling on RealtekATV with Android 7.1.1.
Interesting to note: from what we have collected thus far, only devices that are using a Mali GPU with the old Utgard arch are affected (Mali-400, Mali-450, Mali-470).
https://en.wikipedia.org/wiki/Mali_(GPU)#Variants
- Fixes #7084
=> Disable media tunneling on RealtekATV

app/src/main/AndroidManifest.xml
Modify the intent filter in `AndroidManifest.xml` to handle URLs for YouTube shorts.
- Fixes #7130
@ravilov @shambu2k does this PR work for you?
=> Add YouTube shorts path prefix to intent filter

app/build.gradle, app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentAdapter.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt, app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupReorderDialog.kt
- Update Groupie 2.8.1 -> 2.9.0 ([changelog](https://github.com/lisawray/groupie/releases))
Do we have any `update` calls that could reasonably be replaced with `replaceAll`? I checked them all, but I'm asking just in case. [Here is context](https://github.com/lisawray/groupie/issues/365).
=> Update Groupie library to 2.9.0

app/src/main/AndroidManifest.xml, app/src/main/java/org/schabi/newpipe/App.java, app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java, app/src/main/java/org/schabi/newpipe/settings/UpdateSettingsFragment.java
check immediately for updates if user enables 'check for updates setting'
- reset the expire date on enable 'check for update setting"
- check immediately for updates if user enables 'check for updates setting'
=> resets the expire date for checking for updates

app/src/main/java/org/schabi/newpipe/player/Player.java
* Fixed progress bar not completing after video end
- Before: See #6180 
- After: <br/><img src="https://user-images.githubusercontent.com/40789489/134820621-dd9ce71a-6c30-41b6-bdbe-8058ab28a6aa.gif" width=200>
- Fixes #6180
=> Fixed seekbar not completed after video end

app/src/main/res/layout/activity_player_queue_control.xml
- reorder the Controll elements of the Play queue (putting the Title down)
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/39876427/127787876-39632423-33bb-4f4a-9fc5-272bb8e7b107.png" height="500px"/></td>
<td><img src="https://user-images.githubusercontent.com/39876427/128260601-d11f7fe6-6bb7-44ce-953a-5e7cf17dcd56.jpg" height="500px"/></td>
</tr>
</table>
- Fixes #6788 
- Fixes #2931
- Better view of the current playtime when seeking.
=> Swap seekbar position with player buttons in Queue screen

.github/ISSUE_TEMPLATE/feature_request.md
- Reduced and simplified the sections in the feature request template.
- Changed the comments to make them easier to understand.
- Poor adherence to the template.
=> Simplify the feature request template

app/src/main/AndroidManifest.xml
This adds the Invidious instance tubus.eduvid.org as well as the PeerTube instance eduvid.org.
Please note, that it's explicitly not wished to include Tubus in a "Choose an invidious instance" list, as it's configured to proxy all trafic and primarily intended for use in education.
Both services are hosted by Teckids e.V. (https://www.teckids.org)
(I think testing the APK isn't necessary here ;))
=> Add Tubus (Invidious) and EduVid (PeerTube)

app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Use the correct TAG in NavigationHelper
=> Use the correct TAG in NavigationHelper

app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java, app/src/main/java/org/schabi/newpipe/MainActivity.java, app/src/main/java/org/schabi/newpipe/settings/MainSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/UpdateSettingsFragment.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/update_settings.xml
I added a "Check for updates" button in the update settings that opens the "Releases" page of this github repo.
- Before:
- After:
https://user-images.githubusercontent.com/89147152/138511470-d96e8a69-17de-4457-a63a-081a5dd72a80.mp4
- Fixes #6049
=> Add "Check for updates" button in update settings

app/src/main/res/layout/activity_player_queue_control.xml
#7061 reverted by mistake #6824 (it was a rebase issue). This PR "unreverts" this change and uses our custom `TextView` correctly in the file changed by #6824 (`activity_player_queue_control.xml`).
Check the screenshots of #6824 to see the difference.
- Fixes https://github.com/TeamNewPipe/NewPipe/pull/7061#issuecomment-957645175
=> "Unrevert" changes from pull request 6824

app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
Parameterised shuffle state into initPlayback for potentially passing the shuffle state into the player in the future
- Fixes the shuffle mode button UI bug and parameterizes the shuffle mode in `initPlayback` (to potentially allow passing the saved shuffle state into the player in the future)
- Fixes https://github.com/TeamNewPipe/NewPipe/issues/6825
=> Fixed shuffle button opacity UI bug

settings.gradle
- Gradle: Replaced deprecated ``with`` with ``using``
The doc reads as follows:
```java
/**
* Specify the target of the substitution.
*
* @deprecated Use {@link #using(ComponentSelector)} instead. This method will be removed in Gradle 8.0.
*/
@Deprecated
void with(ComponentSelector notation);
/**
* Specify the target of the substitution. This is a replacement for the {@link #with(ComponentSelector)}
* method which supports chaining.
*
* @since 6.6
*/
Substitution using(ComponentSelector notation);
```
=> Gradle: Replaced deprecated `with` with `using`

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt, app/src/main/res/values/settings_keys.xml
default sharedpreference is used to persist and retrieve show watched menu option toggle state
- added sharedprefrences in feed ViewModel, wrote two functions to save and retrieve "show watched items" boolean state
- used the same functions in feedfragment onitemoptionselected() function of fragment
- Fixes #7362 
=> added show watched items toggle preference

build.gradle
The JCenter repository is going to be shut down. This PR tries to resolve as many dependencies as possible from other repositories.
#5837 
=> Remove JCenter when possible

app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java, app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
- Enable "Mark as Watched" in all the non-feed fragments
- Before:
- After:
- Fixes #7159
=> Enable Mark as Watched in all the other playlist fragments.

app/src/main/java/org/schabi/newpipe/player/Player.java
I missread the ExoPlayer 2.14.0 changelog
`Report information about the old and the new playback positions to Listener.onPositionDiscontinuity. Add DISCONTINUITY_REASON_SKIP and DISCONTINUITY_REASON_REMOVE as discontinuity reasons, and rename DISCONTINUITY_REASON_PERIOD_TRANSITION to DISCONTINUITY_REASON_AUTO_TRANSITION. Remove DISCONTINUITY_REASON_AD_INSERTION, for which DISCONTINUITY_REASON_AUTO_TRANSITION is used instead`
particularly as REASON_AD_INSERTION was replaced by REASON_AUTO_TRANSITION I replaced this in our code. However as PERIOD-TRANSITION was changed to AUTO_TRANSITION we lost the previous behaviour. Stupid me.
This commit fixes the ExoPlayer 2.14.2 PR #7005
~~I am a bit unsure if DISCONTINUITY_REASON_REMOVE should be at the same position, but according to the javadoc it …
=> Fixed Period Transition

app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt, app/src/main/java/org/schabi/newpipe/ktx/View.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedDatabaseManager.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt, app/src/main/java/org/schabi/newpipe/local/feed/item/StreamItem.kt, app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java, app/src/main/res/layout/fragment_feed.xml, app/src/main/res/values/strings.xml
Follow up of #6686
Changes:
* Fixed the weird duplicate FeedSuccessEvents as seen in https://github.com/TeamNewPipe/NewPipe/pull/6686#issuecomment-907840843 and https://github.com/TeamNewPipe/NewPipe/pull/6686#issuecomment-909575283 by using a ``Maybe`` instead of ``Flowable``
* New items are now highlighted with a border in the background
* If new items got fetched a "New feed items" button pops up
* Clicking the button scrolls to the top of the list and hides it
* The button automatically vanishes after 10s (when device animations are on)
* The button automatically vanishes when scrolling to the top
* The button automatically vanishes if the feed is reloaded
<details><summary>Before (click to expand)</summary>
https://user-images.githubusercontent.com/40789489/125986894-f4e7c510-f11a-4a0 …
=> Rework feed new items handling

app/src/main/java/org/schabi/newpipe/player/Player.java
See also https://github.com/TeamNewPipe/NewPipe/pull/7195#issuecomment-962624380
Successor to #7195
* If the video has completed, when the app returns from background, prevent the player from staring playback automatically 
Analysis of the problem: https://github.com/TeamNewPipe/NewPipe/pull/7195#issuecomment-962624380
Steps to reproduce the bug:
1. Play a video
2. Lock the device while the video is still playing
3. Wait until the video ends
4. Unlock the device
5. The video starts playing again automatically
- Before:
https://user-images.githubusercontent.com/4525736/140655574-733a3749-ea7c-4979-b993-3847ed2a20dc.mp4
- After:
https://user-images.githubusercontent.com/4525736/140655671-53f10945-2987-4843-a71a-95b09d5e1216.mp4
The APK can be found by going to the "Checks" tab below the …
=> Prevent automatic replay after returning from background

gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification
> The Gradle Wrapper allows for verification of the downloaded Gradle distribution via SHA-256 hash sum comparison. This increases security against targeted attacks by preventing a man-in-the-middle attacker from tampering with the downloaded Gradle distribution.
it was removed over 2 years ago https://github.com/TeamNewPipe/NewPipe/commit/e1d2c576a9989b84518b60cf358aed90ac3ee8d4
Current Android Studio does not seem to have any issue with it. So it should be added again and kept in sync with future gradle wrapper updates.
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug …
=> Add gradle wrapper Sha256

app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
The custom LoadController of NewPipe basically had two differences to the DefaultLoadcontrol of ExoPlayer: 
* the start/resume buffer was only 500ms instead of 2500ms and 
* there was a customized condition to start the playback depending on the speed. We now only use ExoPlayers behaviour / values.
- might be a fix for #7404
=> Use DefaultLoadcontrol

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java, app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt, app/src/main/java/org/schabi/newpipe/util/TLSSocketFactoryCompat.java
Code cleanup
See the commits for more detailed description.
=> Some code cleanup(s)

gradle/wrapper/gradle-wrapper.properties
Use the correct SHA-256 checksum for the Gradle distribution. @Redirion added it in a recent PR (#7418), but the checksum was the wrong one, something that I noticed while building locally (yeah, this did have me quite worried). Somehow the CI ran without any issues.
Please don't merge if you don't check this locally.
=> Fix Gradle checksum

app/src/main/java/org/schabi/newpipe/error/EnsureExceptionSerializable.java, app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailPlayerCrasher.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/playererror/PlayerErrorHandler.java, app/src/main/res/layout-large-land/fragment_video_detail.xml, app/src/main/res/layout/fragment_video_detail.xml, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/debug_settings.xml, app/src/main/res/xml/video_audio_settings.xml
This PR massively improves the handling of player errors. It consist of 2 parts:
Up to this PR player errors are always just reported as ![grafik](https://user-images.githubusercontent.com/40789489/134232359-8848b4f0-b488-424d-beeb-1b2ab4feeb04.png) (or similar)
This PR introduces an option (default=off) to report the Error directly (via acra):
https://user-images.githubusercontent.com/40789489/134233077-f92c9680-4800-47f3-a23a-65f3748c40f6.mp4
To simulate errors a debug option was introduced to crash the player.
Notes:
* This option is only available when using a Debug version of the app (the same as the ``DebugSettingsFragment``)
* To make this work in all player variants (main, mini, background, popup) it was added to``VideoDetailFragment`` - otherwise at least sometimes there is no UI …
=> Better player error handling

README.es.md, README.ja.md, README.ko.md, README.md, README.pt_BR.md, README.ro.md, README.so.md, README.tr.md
* Fixes the broken "Get it on F-Droid" button in the Readme, which is also displayed at GitHub
* Shrinks the SVGs to 80px in height so that they don't use half of the side
See also https://gitlab.com/fdroid/artwork/tree/master/badge#badge
<details><summary>Click to expand</summary>
- Before: 
- After:
</details>
=> Updated/Fixed "Get it on F-Droid"

app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
=> Disable media tunneling on Philips QM16XE

app/src/main/AndroidManifest.xml
Add [FSFE-Tube](https://media.fsfe.org) PeerTube instance.
- Fixes #7480
@yashpalgoyal1304 does this fix the issue for you?
=> Add FSFE-Tube PeerTube instance

app/build.gradle, app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt, app/src/test/java/org/schabi/newpipe/settings/ContentSettingsManagerTest.kt
- Move plugins to the DSL block because it's cool
- Compile with Java 11 (we can because we compile on SDK 30)
- Update Sonarqube 3.1.1 -> 3.3 ([changelog](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-gradle/))
- Update ktlint 0.40.0 -> 0.43.2 (and run it) ([changelog](https://github.com/pinterest/ktlint/releases))
- Update Checkstyle 8.38 -> 9.2 (and run it) ([changelog](https://checkstyle.sourceforge.io/releasenotes.html))
=> Bump ktlint, Checkstyle, Java version

app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt, app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt, app/src/androidTest/java/org/schabi/newpipe/testUtil/TestDatabase.kt, app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
Results from the local database were being fetched from the database in the correct order, but then the `DISTINCT` part of the query was not done by SQL but by Java using a `Set`, which then caused all items to be ordered alphabetically and not by creation date. This PR fixes this by having the related queries just return a list of strings that are already the correct ones and in the correct order. I just added `DISTINCT` to the queries.
Fixes #7133
=> Fix order of local search results

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
This fixes the half overlaying cutout on devices with API version 28 and higher. Currently, there are undesirable black bars.
This also respects the cutout when rotating the phone and resizes the video accordingly when in fullscreen. At the moment this leaves undesirable black bars at the top and bottom on devices that have a cutout and a screen that is nearly or exactly the resolution of the video. Maybe a setting can help here or a check for video/device resolution. Let me know what behavior you prefer.
This is my first encounter with Android in about 7 years, so please go easy on me. Let me know if there are bad behaviors or APIs that I missed.
- Before:
- After:
- Fixes #5787
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll …
=> Respect cutouts when playing in MultiWindow

app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java
* Reverts some of the changes done in #7005 as on Android 11+ the playback fails to resume after buffering.
* Removed the use of ``MediaParser``
* Further description is available here:
* https://github.com/TeamNewPipe/NewPipe/issues/7529#issuecomment-997448814
* https://github.com/TeamNewPipe/NewPipe/issues/7529#issuecomment-998013182
- Fixes #7529
=> Remove/Revert MediaParser support (Android 11+) due to bugs

app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java
Fixes hashtags that use non-English characters. Hashtags would now include any character above Unicode value U+007F . This solves problems of hashtags with accented characters as well as hashtags in other languages.
- Before:
- After:
- Fixes #7441 
=> Fixes hashtags that use non-English characters.

app/src/main/java/com/google/android/material/appbar/FlingBehavior.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/local/subscription/item/ChannelItem.kt, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java, app/src/main/java/org/schabi/newpipe/settings/BasePreferenceFragment.java, app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java, app/src/main/java/us/shandian/giga/io/FileStreamSAF.java
- Make `PlayerHolder.bound` private 
- Introduce constants for some Strings that indicate no data in `Tab` class
- Add annotations to methods and parameters.
- Replace Jetbrains' `@NotNull` with Androidx' `@NonNull` annotatiation.
- Make class variables static if possible.
- Use constants for some Strings.
- Simplify if conditions.
=> Small improvements to code quality and readability

app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsInfoItemHolder.java, app/src/main/res/drawable-night/ic_pin.xml, app/src/main/res/drawable/ic_pin.xml, app/src/main/res/layout/list_comments_item.xml, app/src/main/res/values-land/dimens.xml, app/src/main/res/values-sw600dp/dimens.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
- Show a pin icon on a comment if it has been pinned by uploader
- Before:
- After:
- Also if users use light theme, this is how it will appear:
- Fixes #7051 
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/523/
=> Added ability to see pinned comment

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Removes a blank sub-channel icon if you watch a Peertube video and then a non-PeerTube video after.
- Does not remove the icon if you watch a PeerTube video with a channel that does not have a sub-channel icon, to avoid confusion
- Before:
https://peertube.co.uk/videos/watch/8afb877a-9f14-4178-b9fb-a0e0c6bfa215
At the end in the bottom right corner of the YouTube creator icon, the app still tries to show you the sub-channel icon like it would in PeerTube. This is because whey you load up a video it only checks whether it needs to create the icon for a video and never if it needs to be hidden.
- After:
https://peertube.co.uk/videos/watch/e778dfb5-0bbf-4997-a02d-c8ccb241230b 
At the end in the bottom right corner of the YouTube creator icon, the app no longer tries to show you the …
=> Fixes view of sub-channel icon when not in use

app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/res/values/strings.xml
- Added "Already playing in background" toast when clicking "Backgound" instead of not showing anything at all.
- Before:
https://user-images.githubusercontent.com/89147152/147089684-4e7cfe6f-d071-4ede-ad33-1f384ff5b6e6.mp4
- After:
https://user-images.githubusercontent.com/89147152/147089402-ce3fec30-dda6-4a28-9f1a-3e211f1dedab.mp4
- This was suggested here : https://github.com/TeamNewPipe/NewPipe/pull/7224#issuecomment-991843605
=> Add Already playing in background toast

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Supersedes #7592
Fixes the problem by checking if the corresponding views have focus and only focuses them if that's not the case.
If this should still cause problems we can also limit the method call to Android TV devices.
- Before: 
See #7592
- After:
https://user-images.githubusercontent.com/40789489/147854501-00ebefb4-bc99-4ab4-82ee-239e2dd162be.mp4
- Fixes #7490
=> Fixed search not accepting key input after closing player overlay

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
Please feel free to criticize the code here, I am not sure if I am using workers correctly or if there is a better way to do this. I essentially copied the code from https://github.com/TeamNewPipe/NewPipe/blob/faa7a91764cf633e668d9621eb6884b5db58bfa1/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L878-L906
I decided loading the information when adding to the queue is better than loading when the video starts playing as it allows the queue progress text to be correct as well. 
This PR calls getStreamInfo causing a full network fetch of stream info (I believe only if required) when adding a stream item to the queue. This should prevent UI issues of missing metadata when queuing videos that have been fast-loaded and are missing metadata.
- Fixes #7035
The APK …
=> Load full stream info when enqueuing a stream

app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
This PR prevents a `NullPointerException` by adding a null check for `currentInfo` when trying to share a playlist which is loading. Instead of crashing, the app does now nothing when pressing the `Share` button on a playlist which is loading, like on channels.
- Fixes #6736
=> Fix crash when sharing a playlist which is loading

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/Player.java
Quick and dirty fix for #7427:
Calls ``setRecovery`` before switching the player.
See also https://github.com/TeamNewPipe/NewPipe/issues/7427#issuecomment-1014852363
- Fixes #7427 
⚠️ Please reopen the issue when merging as this is only a workaround or notify @litetex that he creates a followup issue
=> Workaround: Set recovery before switching player

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
=> Fix false warning

app/src/main/java/org/schabi/newpipe/database/history/model/SearchHistoryEntry.kt
Make SearchHistoryEntry.kt fields nullable to match java version.
I won't and don't want to question whether the nullability makes sense.
- https://github.com/TeamNewPipe/NewPipe/pull/7654#issuecomment-1018125221
=> Make SearchHistoryEntry.kt fields nullable to match java version

app/src/main/res/values/donottranslate.xml, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml
- Move untranslatable strings to a donottranslate file (the [most hip file](https://stackoverflow.com/questions/32934292/attribute-translatable-false-to-the-root-resources-element) for strings too cool for multilingualism)
- Update two of the links
- Remove redundant XML attributes in settings_keys (makes them more readable IMO)
APK probably not needed though.
=> Some untranslatable string improvements

.github/workflows/ci.yml, app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt, app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt
- Ensure order of search history entries in tests
- Fixes #7553
❗  squash merge
=> Ensure order of search history entries in tests

app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/res/values/strings.xml
@TiA4f8R noticed that #7568 contains a bug:
"the app shows Already playing in background if we switch contents by pressing the background button on the new content when it should show Playing in background"
For now I reverted the PR because better show no information instead of showing a false one 😄
=> Revert #7568

app/src/main/java/org/schabi/newpipe/player/Player.java
This PR fixes the playback of the first item in the play queue when a resolution (when switching the quality played in the quality selector) or a player type change occurs (for e.g. switching from background to main player), when playing another item than the first one of the play queue.
The issue was caused by an ExoPlayer change, which when setting a new media source, resets now the current playback position and the current window index to the first item and its default position by default (the position was then set with the first item's recovery position).
It sets now to ExoPlayer to not reset the position when setting a new media source.
- Fixes #7531
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and …
=> Fix first item always played in the play queue when reloading play queue manager

app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java, app/src/main/java/org/schabi/newpipe/util/SaveUploaderUrlHelper.java, app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
This checks if the uploaderUrl is in the database, if not it gets the
uploaderUrl and puts it in the database. This is similar to the fetching
of uploaderUrl when it doesn't exist done in #6919.
- Move the code that conditionally fetches the `uploaderUrl` and saves it to the database into a helper class + method.
- Use the `saveUploaderUrlIfNeeded` method in `QueueItemMenuUtil` when selecting `Show Channel Details` in order to load the `uploaderUrl` if it isn't available in the database.
Android Emulator screen recording seems to be broken, I'll do my best to describe the before and after in text.
- Before: When selecting `Show Channel Details` on a video that doesn't have `uploaderUrl` in the database, it will go to the channel fragment, but the `uploaderUrl` will be `null`, so it will …
=> Load uploaderUrl when showing Channel Details from Play Queue

app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt
This PR improves the `HistoryRecordManager` `getRelatedSearches` tests by shuffling items before inserting them and adding a new `getRelatedSearches_emptyQuery_manyDuplicates` test.
Nothing, but check out #7553 and #7491 for context
=> Improve HistoryRecordManager tests

app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
This PR fixes a NullPointerException in `PlayerHolder.getQueueSize()` that could happen when the player's queue is `null`, i.e. when the player is starting. It also adds `@Nullable` here and there so that Android Studio's linter reports risks of NPEs.
I think this PR should be merged before the next release as it's just adding an `if (... != null)` but solves a big issue.
- Fixes #7608
- Fixes #7528 
- Fixes #7305
- And many other duplicates
=> Fix crash when long-pressing stream while player is starting

.github/workflows/ci.yml
Add `.github/FUNDING.yml` and everything in `doc` to `paths-ignore`.
Not needed.
=> Add some stuff to `paths-ignore`

fastlane/metadata/android/en-US/changelogs/983.txt
Adds the changelog for the upcoming 0.22.0 version.
This enables the translators on Weblate to work on localizations before the new version is published
=> Add changelog for NewPipe 0.22.0 (983)

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
The workaround set with #7668 was not applied when switching to main player with content thumbnail from popup or background player. This PR fixes this by applying the workaround when switching to main player with content thumbnail from popup or background player.
- Fixes https://github.com/TeamNewPipe/NewPipe/issues/7427#issuecomment-985465982
=> Set workaround for playback position reset when switching to main player with content thumbnail

app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
* When you currently search inside the settings (introduced #7586) you end up with results that are displayed in the phone's language. This PR fixes this bug by using the app language.
* Device language is ``en`` - English
* App language is ``de`` - German
| --- | --- |
| ![grafik](https://user-images.githubusercontent.com/40789489/153661994-3bd21e23-8350-4215-93cf-d758c922ed66.png) | ![grafik](https://user-images.githubusercontent.com/40789489/153661552-9f96ca9c-92e5-428e-a16e-1e92cfce315d.png) |
=> Use the correct app language when searching in the settings

app/src/main/java/org/schabi/newpipe/player/Player.java
This PR makes sure that the fast seek overlay arcs share the same paddings as other controls (such as play-pause, brightness, volume, ...). The paddings are being set by the code and are "caused" by the system navigation bar. Play-pause, brightness, volume, ... buttons were correctly centered in the **app** UI (i.e. all of the screen excluding the navigation bar), while the fast seek overlay was centered in the **system** UI (i.e. the whole screen), causing a mismatch between the two that looked ugly, as seen in #7731. My way of fixing it might not be the best, as the arc is now not drawn under the system navigation bar anymore (see *After* screenshot below), but I just wanted to create a PR, I will try to improve it properly later today or tomorrow (though I think the current state is …
=> Fix fast seek overlay arc not correctly centered

app/build.gradle
This PR increases the `compileSdk` from 30 to 31. This will allow newer libraries to be used, see #7782 and https://github.com/TeamNewPipe/NewPipe/pull/2335#discussion_r810371632. This should have no changes on the app since the targetSdk stayed the same.
=> Change `compileSdk` from 30 to 31

app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java, app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java, checkstyle-suppressions.xml
* Supersedes #7638
* Fixes #1974 by loading enough initial data until the RecyclerView is scrollable or no more data/items can be loaded - improved behavior from PR #7638
* Fixes #3368 and fixes #4475 by not reusing the footer (and supplying the header dynamically)
- Before: See #1974
- After: 
https://user-images.githubusercontent.com/40789489/149629153-5baabecc-a24f-43d0-af16-105414fda8eb.mp4
- Fixes #1974
- Fixes #3368 
- Fixes #4475 
Tips for testing:
* The changes can be at best tested with a tablet and Grid-mode enabled
=> Load enough initial items (into BaseListFragment and descendants)

app/src/main/java/org/schabi/newpipe/player/Player.java
In #7893 I added padding (equal to the window insets) to the fast seek overlay just as it was done with the player overlays (play-pause, brightness, ...). But as you can see in the "Before" screenshot below, that caused the fast-seek arc to not go under the system ui. This PR instead applies to the fast seek overlay negative margins, for each side respectively equal to minus the window inset of the opposite side. This way the view covers all of the player (overflowing on some sides, but that's not important) and its center still coincides with the center of other controls (which is a requirement, since we don't want #7731).
| --- | --- |
| <img src="https://user-images.githubusercontent.com/36421898/154686412-402f342e-5d1e-4bc3-a9a6-e3d202f91788.png" width="500px"/> …
=> Have fast seek overlay arc go under system ui

app/src/main/java/org/schabi/newpipe/player/Player.java
Really small code refactoring. Android Studio asked for a `@NonNull` and I noticed there was a useless float division replaceable by (& equivalent to) an int division. Should be mergeable right away.
=> Small refactor in player class

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
This reverts commit c92a90749ef1188f50afe528245a54afd180613c.
#7451 causes multiple problems:
* #7915 - Fails to fill the notch correctly
* #7912 - Fails to align the system menu properly
As nearly no one benefited from #7451 (there was not even an issue), I am strongly for reverting the behavior.
See the issues
- Fixes #7915
- Fixes #7912
=> Revert "Respect cutouts when playing in MultiWindow"

fastlane/metadata/android/en-US/changelogs/984.txt
Adds the changelog for version 0.22.1, allowing translators on Weblate to translate it before releasing.
=> Add changelog for NewPipe 0.22.1 (984)

app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java, app/src/main/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelper.java, app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java, app/src/main/java/org/schabi/newpipe/player/playqueue/ChannelPlayQueue.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlaylistPlayQueue.java, app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java, app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java, app/src/main/java/org/schabi/newpipe/util/SerializedCache.java, app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
I made sure there was no **raw** use of parameterized classes. Raw means without <> when the class requires it.
- Use `<?>` for `CacheData` since the cache map `LRU_CACHE` can contain items cache data of different types
- Replace raw use of `JsonSink` with the actual classes being passed to functions. This may decrease the generality of the functions having such items as parameters, since they would work for any `JsonSynk` but are actually only called with one type of `JsonSink` each time.  Maybe just using `JsonSink<?>` is better? (btw, the definition of `JsonSink` is recursive for some reason...: `public interface JsonSink<SELF extends JsonSink<SELF>>`)
- `BaseListInfoFragment` now has two parameters: the item type to be shown in the list (`I extends InfoItem`), and the list info type …
=> Solve Java warning "Raw use of parameterized class"

app/src/main/java/org/schabi/newpipe/database/history/dao/StreamHistoryDAO.java, app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java, app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt
The warning was: "The query returns some columns [...] which are not used by ..." and the build itself suggested me to use `@RewriteQueriesToDropUnusedColumns`. Now the warnings are disappeared. This warning has been bugging me for a while, showin up in almost each build ;-)
=> Fix Room warning about unused columns during build

app/build.gradle
Fixes the build on M1 macs.
For more information see [this comment](https://github.com/TeamNewPipe/NewPipe/pull/7782#issuecomment-1034371070)
=> Fix build on Apple Silicon macs

app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
It ensures that queues are not the same. Without this check when you have multiple videos in the backstack and navigating back via Back button you'll get duplicated videos
Don't know. To hard to search for "duplicate" keyword:)
=> Better equals check

app/build.gradle, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/test/java/org/schabi/newpipe/util/urlfinder/UrlFinderTest.kt, build.gradle
- Update Kotlin 1.5.31 -> 1.6.10 ([changelog](https://kotlinlang.org/docs/releases.html#release-details) (As far as I know, there's nothing stopping us from doing this. Please correct me if this is not the case. I only know of [this](https://github.com/TeamNewPipe/NewPipe/pull/7499#issuecomment-989323578), which was fixed with #7782.)
- Update ktlint 0.43.2 -> 0.44.0 ([changelog](https://github.com/pinterest/ktlint/releases))
- Update Checkstyle 9.2.1 -> 9.3 ([changelog](https://checkstyle.sourceforge.io/releasenotes.html))
=> Update Kotlin to 1.6.10

app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java, app/src/main/res/values/settings_keys.xml
- Save `adjustmentStepSize` to shared preferences, pass it back and forth
between PlaybackParameterDialog and Player/PlayQueueActivity.
- Made `DEFAULT_STEP` in PlaybackParameterDialog public so it can be used as
the default `adjustmentStepSize` value in the Player.
|--|--|
| <video src="https://user-images.githubusercontent.com/71804605/151766501-807ca760-ad0c-494a-a1f3-9c1de85a2b05.mp4"> | <video src="https://user-images.githubusercontent.com/71804605/151766566-86420278-19d6-4bec-96c0-c5433dcca642.mp4"> |
- Fixes #7031
=> Remember adjustment step size for playback controls (speed and pitch)

app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/video_audio_settings.xml
Hi team, long time no see. 
I've long since had issue with the buffering time when starting out a new video in the built-in player. Sometimes this gets so bad, there's a 10 seconds wait before any picture would even show up. Of course, your experience might differ depending on the phones, network conditions, or luck etc. 
After digging a bit, I found a `continueLoadingCheckIntervalBytes` parameter on ExoPlayer progressive media source that controls the size of data loaded per call from the playback loader. By default, ExoPlayer will load 1MB per call. Reducing this number seems to have solved the initial buffering woes on my side, though I have no idea how it affects other users. So if you have a similar issue with buffering under fast network speed, please give this a try and test …
=> Mitigating long buffering on initial video playback

app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/playback/PlayerMediaSession.java
- Added `hideControls(0, 0)` to the Space key pressed and the `PlayerMediaSession` `play` method (only if the player is currently playing)
| -- | -- |
| <video src="https://user-images.githubusercontent.com/71804605/139620899-b62f3eb7-1d07-44d3-959e-104d46e9fbea.mp4"/> | <video src="https://user-images.githubusercontent.com/71804605/139621120-d73b284d-de60-4eb7-af34-eaae7df747d6.mp4"/> |
- ~~Fixes #7340~~ (I made that issue then only looked at how to fix it)
- Fixes #3403
=> Fix player controls not hiding if resumed from media button

app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/res/layout/player.xml
This also allows saving a remote playlist locally.
- Add an "Add to playlist" button to the queue menu in the Player.
- Move the appendAllToPlaylist functionality from PlayQueueActivity to
Player.
|--|--|
| <image alt="Before" src="https://user-images.githubusercontent.com/71804605/157583435-5bd202bf-dfec-494c-8f19-5106c4573da1.png" height="500px"> | <video alt="After" src="https://user-images.githubusercontent.com/71804605/157583561-d2b5d9e0-3281-4115-8d12-1d13a9a692d1.mp4"> |
- Fixes #8004
- This also allows for doing what #7355 implements (play the playlist then append it to a local playlist)
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which …
=> Implement appending queue to playlist in main player

app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java, app/src/main/res/values/strings.xml
Adding an confirmation button while deleting all files.
- Fixes #5419
=> Add a confirmation button when deleting all files in downloader

app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt, app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
I looked at my PR from when I converted the about package to Kotlin and found some unsatisfactory things.
- Grouped the page titles back into the state adapter because it makes more sense for it to be there.
- Removed an unneeded JvmStatic annotation.
- Extracted some duplicate code.
=> Clean up the about package a bit

app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java, app/src/main/java/org/schabi/newpipe/util/SimpleOnSeekBarChangeListener.kt, app/src/main/java/org/schabi/newpipe/views/player/SecondsView.kt
- Create a stub implementation of `SeekBar.OnSeekBarChangeListener` so we can remove unused stuff
- Utilize the Animator.addListener() KTX extension in SecondsView
=> Create stub implementation for OnSeekBarChangeListener

app/src/main/java/org/schabi/newpipe/MainActivity.java, app/src/main/java/org/schabi/newpipe/fragments/OnScrollBelowItemsListener.java, app/src/main/java/org/schabi/newpipe/fragments/detail/StackItem.java, app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java, app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java, app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistDialog.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt, app/src/main/java/org/schabi/newpipe/local/history/HistoryEntryAdapter.java, app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java, app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt, app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupReorderDialog.kt, app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java, app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java, app/src/main/java/org/schabi/newpipe/player/helper/CacheFactory.java, app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java, app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java, app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java, app/src/main/java/org/schabi/newpipe/settings/SettingsResourceRegistry.java, app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java, app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchConfiguration.java, app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchItem.java, app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java, app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
- Fixed some `Not annotated parameter overrides @NonNull parameter` lints
- Deleted a few unused parameters
- Fixed some other miscellaneous lints regarding Kotlin, unresolved documentation, etc.
=> Some lint cleaning

app/build.gradle, app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java, app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java, app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java, checkstyle/checkstyle.xml, checkstyle/suppressions.xml
- Update checkstyle from 9.3 to 10.0 ([changelog](https://checkstyle.sourceforge.io/releasenotes.html)).
- Put checkstyle files into `checkstyle/` subfolder so that the gradle task does not implicitly depend on the whole project, fixing many warnings during build and possibly increasing build performance.
- The warnings were like this: *Execution optimizations have been disabled for task ':app:runCheckstyle' to ensure correctness due to the following reasons: Gradle detected a problem with the following location: 'XXX/NewPipe'. Reason: Task ':app:runCheckstyle' uses this output of task ':app:XXX' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to …
=> Update checkstyle to 10.0 and fix various related issues

app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt
The app was crashing when trying to display an error notification on KitKat, this PR fixes that by using a non-vector-drawable on API < Lollipop. I also replaced `NotificationManager` with `NotificationManagerCompat`, just like in the player's `NotificationUtil`.
The crash was encountered while testing other thing and is about "Bad notification posted from package ... Couldn't create icon ..."
=> Fix error notification on KitKat

app/src/androidTest/java/org/schabi/newpipe/util/StreamItemAdapterTest.kt, app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
Some logic was missing in the adapter for making the no-audio icon  `GONE` instead of `INVISIBLE`. I fixed it and added some tests as well.
That reveals another problem: some icons are not themed properly, I will fix that in another pull request.
- Fixes #6677
=> Fix download dialog selector layout

app/src/main/java/org/schabi/newpipe/util/SparseItemUtil.java
Fix `SparseItemUtil` loading
* Added a missing `return` statement
* `fetchUploaderUrlIfSparse` now has a similar code-layout to `fetchItemInfoIfSparse`
In https://github.com/TeamNewPipe/NewPipe/pull/8020#pullrequestreview-926589637 I noticed that the enqueuing function enqueues streams twice.
The problem was introduced in #7981 and I didn't noticed it until now.
=> Fix `SparseItemUtil` so we don't enqueue twice

app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java, app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistCreationDialog.java, app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistDialog.java
- delete the constructors in `PlaylistDialog`
- use `newInstance()` instead
See https://stackoverflow.com/questions/51831053/could-not-find-fragment-constructor
- Fixes https://github.com/TeamNewPipe/NewPipe/issues/7825
=> Use newInstance in PlaylistDialog

.github/CONTRIBUTING.md
document improvement
`checkstyle.xml` was moved to `checkstyle` folder in this commit 710964b47df92cbdb1ab41b562c80dd9d7c28ce8, `CONTRIBUTING.md` should be updated with this change.
I think this update needn't to be recorded so I didn't open an issue, if this is not expected please point that out.
=> Update CONTRIBUTING.md with current checkstyle.xml path

.github/workflows/ci.yml, .github/workflows/image-minimizer.yml
- https://github.com/actions/checkout/releases
- https://github.com/actions/cache/releases
- https://github.com/actions/upload-artifact/releases
- https://github.com/actions/setup-java/releases
- https://github.com/actions/setup-node/releases
- https://github.com/actions/github-script/releases
=> Update action dependencies in workflows

app/src/main/java/org/schabi/newpipe/MainActivity.java
- It just does that but internally. This was introduced in DrawerLayout 1.1.x, which we had updated to when Google Material was [updated to 1.5.0](https://github.com/TeamNewPipe/NewPipe/pull/7978#:~:text=This%20includes%20an%20AndroidX%20DrawerLayout%20bump).
=> Use simpler DrawerLayout method

app/build.gradle
The release apk contains this fix, but I accidentally forgot to push the local change before merging the release PR :sweat_smile:
=> Update NewPipeExtractor again to fix throttling on age restricted videos

.github/workflows/ci.yml, app/src/main/java/org/schabi/newpipe/player/Player.java
This fixes another bug introduced by #8150 where `DefaultTrackSelector` will have text tracks automatically selected at start, where captions will be enabled for a playback session (i.e. new player instance) even if `No Caption` was selected in previous session. 
This change will disable text tracks when building the caption menu when `userPreferredLanguage` does not exist.
- https://github.com/TeamNewPipe/NewPipe/issues/8230#issuecomment-1100921774
=> Fix disabled caption to no longer automatically re-enable on new player instance

app/proguard-rules.pro
`notification_settings.xml` is the **only** file in the project that references `NotificationModeConfigFragment`. Probably there are some bugs in proguard, which didn't count the usage inside an XML as a valid usage and thus discarded the fragment when building the release apk. I don't know if this can be fixed in a more elegant way.
- https://github.com/TeamNewPipe/NewPipe/issues/8230#issuecomment-1100726643
Use this release testing apk and follow the instructions from https://github.com/TeamNewPipe/NewPipe/issues/8230#issuecomment-1100726643 : [app-release.zip](https://github.com/TeamNewPipe/NewPipe/files/8500521/app-release.zip)
=> Fix proguard for notification preference fragment

app/src/main/java/org/schabi/newpipe/settings/NotificationsSettingsFragment.kt
This PR fixes two issues with the new streams notifications preference screen:
- Check whether to enable the preference screen also in `onCreatePreferences`, since doing it only in `onResume` causes flickering as reported by @TiA4f8R on IRC
- Fix the persistent "Go to settings" snackbar not dismissed properly when exiting from the fragment
=> Fix new streams notifications preference screen

app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/util/KeyboardUtil.java
- The code block on onResume() for showing/hiding the soft keyboard failed in a specific scenario. It is because the current view of InputMethodManager is not searchEditText. This problem is handled just when searchEditText gets the focus.
- (**Update**) Fix the underlying problem as described in #7647. It just tries again to request focus and show the soft keyboard when it fails.
- Before:
https://user-images.githubusercontent.com/15650457/163761718-ba6fc388-73be-4425-9af8-2fbc86bb07bd.mp4
- After:
https://user-images.githubusercontent.com/15650457/163761735-2a86f962-7e62-4182-843b-d6ded03292cc.mp4
- Fixes #7647
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which …
=> Fix keyboard showing after the search box acquiring focus

app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
This PR sets the opacity, on Android 12 and higher, of the popup close button to [the maximum one which allows touches on other apps for these Android versions](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#maximum-obscuring-opacity).
See the documentation of the [`FLAG_NOT_TOUCHABLE`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_NOT_TOUCHABLE) flag, used in the popup close button, for more details.
These changes have been tested on an Android 12 emulator and by several users (from [the corresponding issue](https://github.com/TeamNewPipe/NewPipe/issues/6770) and from [Reddit](https://www.reddit.com/r/NewPipe/comments/u69r9c/about_non_interactivity_on_other_apps_than/)) and the changes restore the ability to interact …
=> Adapt opacity of popup close button to allow touches in other apps on Android >=12

app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
This PR updates the USER_AGENT string in DownloaderImplementation to match the latest Firefox ESR 91 release.
=> Update User-Agent in Downloader

app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
* This fixes the problem of ``PlaybackParameterDialog`` automatically resetting the speed value upon initialization
* This was caused by calling ``changePitchControlMode`` before the required values/components were initialized.
Thanks to @TiA4f8R for noticing and informing me about the bug.
=> Fixed accidental reset of ``PlaybackParameterDialog`` on initialization

app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
DefaultControlDispatcher was removed in ExoPlayer 2.16.0, so the class
extending it that handled play/pause was removed in #8020.
The new solution is to use an instance of ForwardingPlayer. Call
sessionConnector.setPlayer with an instance of ForwardingPlayer that
overrides play() and pause() and calls the callback methods.
- Fixes: N/A
- Original change: #7341 
- Breaking PR: #8020 
- Breaking commit: https://github.com/TeamNewPipe/NewPipe/pull/8020/commits/4e459b33839e428c26c5730d629ba07356ca88e3
=> Fix hiding player controls when playing from media button

app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntity.java
When watching a video that you have not seen before and going to the history.
Note that the history entry shows 2 views instead of 1 view for said video.
I then modified a function to solve the problem.
So when we go to the video history we see that he has 1 marked view.
- Before:
- After:
- Fixes https://github.com/TeamNewPipe/NewPipe/issues/8330
- Watch a video you've never seen
- Go down in history
- And you see the video shows 1 view
=> Fixed viewed counting

app/src/main/java/org/schabi/newpipe/RouterActivity.java, app/src/main/res/values/styles.xml
When the app is not running in the foreground and started via ``RouterActivity`` (e.g. clicking/sharing a link to NewPipe) incorrect things start to happens:
* The UI has incorrect colors (seen in #8179)
* The day/night mode of the app is ignored
* The language is the device language
Why does this happen?
* The RouterActivityThemes are overriding the ``color*``-attributes (``colorPrimary``, ``colorPrimaryDark``, ...). I'm not sure why this was done in the first place, however it causes the theming issues on the UI.
* RouterActivity misses some code from MainActivity, e.g. ``assureCorrectAppLanguage`` and ``ThemeHelper.setDayNightMode``. This causes further problems like the incorrect language or wrong colored theme elements.
Done via the test manual below:
- Before: 
- After: 
- Fixes …
=> Fix Routeractivity theming

app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
See https://github.com/TeamNewPipe/NewPipe/issues/6696#issuecomment-1087753680
- Fixes #6696
=> Fix crash when rotating device on unsupported channels

app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
- Bugfix (user facing)
This PR makes the volume progress bar (the slider used to change the volume) match the system volume when we start sliding. Otherwise, the slider would remember its last position, and the system volume would be ignored.
- Before:  https://www.veed.io/view/116181aa-48c0-4399-8ecd-40353c2563ad
- After:  https://www.veed.io/view/451faf5c-c952-4bdb-a0d3-4cdcbfef916f
- Fixes #8375
=> Make volume progress bar match system volume when we start sliding

app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/res/menu/menu_playlist.xml
This PR adds an option to the menu for remote/non-local playlists
that appends the playlist items to a local playlist.
- Before:
- After:
https://user-images.githubusercontent.com/88139840/140081467-e98bbecd-a052-4cae-a3bb-fa0c2df97a94.mp4
- Fixes #7294
=> Add a "Add to playlist" item to the remote playlist menu

app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java, app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
This PR adds the image preview of contents shared in the Android share sheet, for Android 10+ devices. Note that it may be not shown, depending of the customizations made by your OEM on your Android device.
Images included in the share sheet will be only the ones in the image cache used by Picasso (the image library loader), in order to not have to handle network exceptions when sharing contents. If it is not loaded or no image preview is available, no image will be shown in the share sheet (like the current behavior).
The image of the content, before sharing, is compressed in JPEG 90 and saved inside the application cache folder under the name `android_share_sheet_image_preview.jpg`. The current image shared will be, of course, always overwritten by the next one and deleted when the …
=> Add image preview of the content shared where possible in Android share sheet (for Android 10+ devices only)

app/src/main/java/org/schabi/newpipe/RouterActivity.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailPlayerCrasher.java, app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java, app/src/main/res/layout/single_choice_dialog_view.xml, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/styles.xml
Problem: Setting _Preferred 'open' action_ to "Add to playlist" does nothing when opening a video
Discovered while working on #8332 
This PR also cleans up how the choices are handled inside ``RouterActivity``. It was until now possible to e.g. download a channel (which resulted in an error/unsupported url page) due to incorrect choice-availability-checks.
Now everything is centralized in open place and should be easier to maintain.
- Before: _Nothing happens when clicking a video; Behaves like "Show info"_
- After:
https://user-images.githubusercontent.com/40789489/166318116-2016161a-d8be-4ba4-922f-0bab05bb821c.mp4
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which …
=> Fix "Add to playlist" not working and cleanup "RouterActivity" choice handling

README.md
- Edited the ReadMe to reflect the project's current status.
- I've made some opinionated changes as well. Please review those in particular.
=> Made some much needed changes to the ReadMe

app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntity.java, app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java, app/src/main/java/org/schabi/newpipe/player/Player.java
#8336 did not really fix the problem, it just made so that each item in history has 1 less view. This meant that, even though the bug appeared to be fixed the first time a video is opened (since that video's views are correctly set to 1), the second time the same video is opened the views are incorrectly set to 3. And #8336 actually introduced a regression, since e.g. enqueued videos were registered as "No views" as reported in https://github.com/TeamNewPipe/NewPipe/pull/8336#issuecomment-1149998538.
The underlying problem was an incorrect usage of Java's `==` (*same*) operator: it was used in the player's `onEvents` function to check if the media item tag in the **ExoPlayer** was equal to the one currently set in our `Player`. The problem with this is, when the player is started from …
=> Actually fix history view count

app/build.gradle, app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt, app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt, app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java, app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java, app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistItemHolder.java, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionsImportFragment.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItemBuilder.java, app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java, app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
* Updates the extractor to the latest revision
* Fixes overlooked compile errors from https://github.com/TeamNewPipe/NewPipeExtractor/pull/846
- https://github.com/TeamNewPipe/NewPipe/pull/8153
=> Updated extractor to latest revision and fix compile errors

app/proguard-rules.pro
I went down the git blame hole and found that PrettyTime was first added using 4.0.1. Meanwhile, consumer proguard rules were [added to PrettyTime in 4.0.3](https://github.com/ocpsoft/prettytime/commit/602b3a9bb6efbc9f7032fb7307f4866227aa4135). Therefore we no longer need this rule (and also ours is now [outdated](https://github.com/ocpsoft/prettytime/blob/master/core/src/main/resources/META-INF/proguard/prettytime.pro) anyway).
```-keep class org.ocpsoft.prettytime.i18n.** { *; }```
These are from before AndroidX. I don't think I need to explain these :)
```
-dontwarn android.arch.util.paging.CountedDataSource
-dontwarn android.arch.persistence.room.paging.LimitOffsetDataSource
```
The OkHttp rules are embedded into the library as of …
=> Clean up proguard file

app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java, app/src/main/java/org/schabi/newpipe/info_list/dialog/StreamDialogDefaultEntry.java, app/src/main/java/org/schabi/newpipe/util/SparseItemUtil.java
Add option to download the video when long-pressing items.
- Fixes #2171
=> Add download to longpress menu

app/build.gradle, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/datasource/YoutubeHttpDataSource.java, app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java, app/src/main/java/org/schabi/newpipe/player/playback/SurfaceHolderCallback.java, app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
- Updated ExoPlayer 2.17.1 -> 2.18.0 ([changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md))
I tested on my device and everything seemed to work fine. Feel free to test yourselves, though.
=> Update ExoPlayer to 2.18.0

app/build.gradle
I don't know how this hadn't caught my eye before, considering I've made this exact change in other apps. Anyway, I digress.
Before, when just using `exoplayer`, *every* ExoPlayer library would be added (regardless of whether they were used). This would cause some unnecessary bloat. Now after being specific, the unused libraries (like rtsp) are not being added.
This shaves off around 103KB for debug builds and 49KB for release builds.
=> Specify used ExoPlayer libraries

app/src/main/res/layout/channel_header.xml, app/src/main/res/layout/item_stream_segment.xml, app/src/main/res/layout/list_playlist_grid_item.xml, app/src/main/res/layout/list_playlist_item.xml, app/src/main/res/layout/list_playlist_mini_item.xml, app/src/main/res/layout/list_stream_grid_item.xml, app/src/main/res/layout/list_stream_item.xml, app/src/main/res/layout/list_stream_mini_item.xml, app/src/main/res/layout/list_stream_playlist_grid_item.xml, app/src/main/res/layout/list_stream_playlist_item.xml, app/src/main/res/layout/play_queue_item.xml
Since the last extractor update (which included TeamNewPipe/NewPipeExtractor#810), YouTube thumbnail urls point to thumbnails with the original aspect ratio preserved (16:9 for normal videos, 9:16 for shorts I think). Before this change, some other "legacy" urls were obtained, which instead pointed to images with pre-added black bars for shorts to make them all 16:9. This change revealed that NewPipe was not treating correctly images with aspect ratios different than 16:9, showing only their center part using the `scaleType="centerCrop"` property. Instead I used `scaleType="fitCenter"`, see the difference in the screenshots.
SoundCloud and Bandcamp square thumbnails also look better.
I also made it so that playlist thumbnails align left, so that a smaller part of the thumbnail is hidden …
=> Make thumbnails' `scaleType` `fitCenter`

.github/workflows/ci.yml, .github/workflows/image-minimizer.yml, .github/workflows/no-response.yml
Use minimum needed permissions for GitHub workflows and jobs. This reduces the attack surface if the workflows are ever compromised.
=> Use minimum required permissions for GitHub workflows

app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/res/menu/menu_local_playlist.xml
- Added ability to share a playlist using a list of video URLs
- Before:
- After:
- Fixes #1788
=> Add 'Share playlist' option to Playlist fragment

.github/workflows/no-response.yml
Use "waiting for author" label instead of "waiting-for-author".
The current labels are inconsistent with regards to usage of spaces vs. hyphens, and I ended up settling on spaces.
Immediately before this is merged, the label should be renamed from the GitHub UI too.
=> Rename "waiting-for-author" label to "waiting for author"

app/build.gradle, build.gradle
- Update Checkstyle 10.0 -> 10.3.1 ([changelog](https://checkstyle.sourceforge.io/releasenotes.html))
- Update AssertJ 3.22.0 -> 3.23.1 ([changelog](https://assertj.github.io/doc/#assertj-core-3-23-1-release-notes))
- Update desugar_jdk_libs 1.1.5 -> 1.1.6 ([changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md))
- Update Ktlint 0.44.0 -> 0.45.2 ([changelog](https://github.com/pinterest/ktlint/releases))
- Update AndroidX Constraintlayout 2.1.3 -> 2.1.4 ([changelog](https://developer.android.com/jetpack/androidx/releases/constraintlayout#constraintlayout-2.1.4))
- Update AndroidX Core 1.6.0 -> 1.8.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/core)) (please note the new interfaces in the 1.8.0 alphas, they might be useful)
- Update …
=> Update some misc libraries

app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistLocalItem.java, app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
- Use the Java 8 Stream API's sorting methods.
=> Use stream sorting.

app/src/main/java/com/google/android/material/appbar/FlingBehavior.java, app/src/main/java/org/schabi/newpipe/App.java, app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java, app/src/main/java/org/schabi/newpipe/RouterActivity.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailPlayerCrasher.java, app/src/main/java/org/schabi/newpipe/info_list/dialog/StreamDialogDefaultEntry.java, app/src/main/java/org/schabi/newpipe/player/gesture/CustomBottomSheetBehavior.java, app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java, app/src/main/java/org/schabi/newpipe/player/mediasource/FailedMediaSource.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java, app/src/main/java/org/schabi/newpipe/player/playqueue/SinglePlayQueue.java, app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchConfiguration.java, app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchItem.java, app/src/main/java/org/schabi/newpipe/settings/tabs/TabsJsonHelper.java, app/src/main/java/org/schabi/newpipe/util/CookieUtils.java, app/src/main/java/org/schabi/newpipe/util/ListHelper.java, app/src/main/java/org/schabi/newpipe/util/PeertubeHelper.java, app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java, app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
- Use Java 9's immutable collection factory methods.
=> Use Java 9 collection factories.

app/src/main/java/org/schabi/newpipe/util/ListHelper.java, app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
#8631 replaced list creation with `List.of()`, which creates an immutable list, but for this test we need a mutable list. I added a comment in the javadoc to explain this. This fixes the CI failing everywhere (my fault with merging #8631 once I saw it built fine on my PC, before waiting for the CI to finish). @Isira-Seneviratne
=> Fix ListHelperTest failure caused by immutable list being used

app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelMiniInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/local/subscription/item/ChannelItem.kt
In some places the "thumbnail" placeholder was being used instead of the "person" placeholder when loading a channel icon. Related: #8530.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36421898/180447461-5b933175-4420-4cee-8b8f-ec6cf004b366.png" height="300px"/></td>
<td><img src="https://user-images.githubusercontent.com/36421898/180447369-5d588be7-42a9-41c0-9bad-5509ecac00ff.png" height="300px"/></td>
</tr>
</table>
Could not find any.
=> Fix wrong thumbnail used as placeholder for channel

app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt, app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt, app/src/main/java/org/schabi/newpipe/util/ReleaseVersionUtil.kt
=> Use IO extensions.

app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java, app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
- Remove some unnecessary methods in the code.
- Fixes #
=> Remove unnecessary methods.

app/src/main/java/org/schabi/newpipe/views/FocusAwareCoordinator.java
- Remove calls/overrides to deprecated methods in `FocusAwareCoordinator`.
- Fixes #
=> Remove deprecated method calls in FocusAwareCoordinator.

app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedDatabaseManager.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
While merging #8545 I noticed there was much duplicated code in the feed loading. There were 4 different SQL queries based on the wanted filtering (all the combination of "filter or not by group" and "include or not played items"). Furthermore #8545 included another condition, but it wasn't implemented in SQL (as it would have meant adding 4 more queries) but rather in code. This PR removes duplicate queries by making the now-only-one query take as input the various filtering conditions. I tested and noticed no changes in the UI behavior.
=> Deduplicate SQL queries to get feed streams

app/src/main/java/org/schabi/newpipe/MainActivity.java, app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
Some time ago we removed the "beta"-tag from all services inside the Readme.
This PR adjusts the app accordingly.
I'm also not sure why there ever was a (beta) flag inside the services as all services are in theory beta (even YT) because we can't guarantee that they are stable as we don't control the remote side.
=> Removed the "(beta)"-tag from services

app/build.gradle, app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
- Update OkHttp 3.12.13 -> 4.10.0 ([changelog for the rest of 3.x](https://square.github.io/okhttp/changelogs/changelog_3x/), the [migration guide for 4.x](https://square.github.io/okhttp/changelogs/upgrading_to_okhttp_4/), and the [4.x changelog](https://square.github.io/okhttp/changelogs/changelog_4x/))
- Now that #7613 is merged, this can finally be upgraded.
It would probably be good to get this done before [a certain PR](https://github.com/TeamNewPipe/NewPipe/pull/8536#discussion_r919939386) as well.
Read through the changelogs and see if anything else needs to be done. I did so, and didn't really find anything of interest, but check for yourselves anyway.
This PR adds around 227KB to the debug APK, and 75KB to the release APK.
The APK can be found by going to the "Checks" tab below …
=> Update OkHttp to 4.10.0

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
Add a "needs triage" label to the issue templates.
This label would make it easier for issue triagers to know what they haven't triaged yet.
=> Add "needs triage" label to issue templates

app/build.gradle, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt, app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
- Update AndroidX Lifecycle from 2.3.1 to 2.5.0. [Changelog](https://developer.android.com/jetpack/androidx/releases/lifecycle)
- Fixes #
=> Update Lifecycle to 2.5.1.

app/build.gradle, app/src/main/java/org/schabi/newpipe/player/gesture/CustomBottomSheetBehavior.java
- Update Google Material 1.5.0 -> 1.6.1 ([changelog](https://github.com/material-components/material-components-android/releases))
Debug APK size increased by 37 KB.
Release APK size increased by 22 KB.
=> Update Google Material to 1.6.1

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Followup to #8170, bug reported by @opusforlife2. I don't know why the `binding` could be `null` when `getView()` returns a non-null value, unless the view is destroyed exactly in between `new Handler().post()` being called and the passed function being actually called, but anyway... 
- https://github.com/TeamNewPipe/NewPipe/pull/8170#issuecomment-1184735382 https://github.com/TeamNewPipe/NewPipe/pull/8170#issuecomment-1185762001
- https://github.com/TeamNewPipe/NewPipe/issues/8646#issuecomment-1186609499
=> Fix random NullPointerException when adding video player view

app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt
- Use the `Throwable.stackTraceToString()` extension function.
- Fixes #
=> Use Throwable.stackTraceToString().

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/ui/PopupPlayerUi.java, app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
- Use Android R's `WindowMetrics` API in `VideoDetailFragment` and `PopupPlayerUi`, as `Display#getSize()` and `Display#getMetrics()` have been deprecated in favor of it.
- Fixes #
=> Use WindowMetrics API.

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
- Remove calls to the deprecated `setBottomSheetCallback()` method.
- Fixes #
=> Remove uses of setBottomSheetCallback().

app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt, app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
- Make some improvements to `LicenseFragmentHelper`.
- Fixes #
=> Refactor LicenseFragmentHelper.

app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java, app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java, app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt, app/src/main/java/org/schabi/newpipe/util/OnClickGesture.java
- Convert `OnClickGesture` to an interface, to allow lambdas to be used.
- Fixes #
=> Make OnClickGesture an interface.

app/src/main/java/org/schabi/newpipe/ktx/View.kt
- Use nested functions in `View.kt`.
- Create reusable class which overrides `AnimatorListenerAdapter`.
- Fixes #
=> Reduce View.kt size.

app/src/main/java/org/schabi/newpipe/player/gesture/PopupPlayerGestureListener.kt
- Use [`MathUtils.clamp()`](https://developer.android.com/reference/androidx/core/math/MathUtils#clamp(float,float,float)) instead of Kotlin's `coerceIn()` in `PopupPlayerGestureListener`. This avoids an issue found by @Stypox  in #8651, as `coerceIn()` throws an exception if the maximum is less than the minimum while `MathUtils.clamp()` doesn't.
- Fixes #
=> Replace coerceIn() with MathUtils.clamp().

app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceFuzzySearchFunction.java, app/src/main/java/org/schabi/newpipe/util/ListHelper.java
- Simplify audio and video stream comparisons using the `Comparator` factory methods.
- Use `Comparator.comparingDouble()` in the preference search to avoid boxing.
- Fixes #
=> Use Comparator factory methods.

app/src/main/java/org/schabi/newpipe/database/BasicDAO.java, app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
- Remove unused methods in `HistoryRecordManager` and other locations.
- Remove `OnConflictStrategy.ABORT` for the Room `Insert` annotation, as it is now the default value.
- Before:
- After:
- Fixes #
=> Remove some unused methods.

app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java, app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java, app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchAdapter.java, app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchFragment.java, app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearcher.java
- Use [`ListAdapter`](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter) to handle displaying list data in `PeertubeInstanceListFragment`, `SuggestionListAdapter` and `PreferenceSearchAdapter`.
- Before:
- Video search:
https://user-images.githubusercontent.com/31027858/182021881-f60beea1-e880-42f8-a9d2-173b8ea8f72d.mp4
- Preference search:
https://user-images.githubusercontent.com/31027858/182053004-86985d79-852b-4dfd-a3f0-1df1b83c7c4b.mp4
- After:
- Video search:
https://user-images.githubusercontent.com/31027858/182021890-30818b27-d39d-43d5-91d0-8d041227225a.mp4
- Preference search:
https://user-images.githubusercontent.com/31027858/182053021-971da415-3bb9-491e-a986-b297d48bbc91.mp4
- Fixes #
The APK can be found by going to the "Checks" tab below the …
=> Use ListAdapter for search predictions.

app/build.gradle, fastlane/metadata/android/en-US/changelogs/989.txt
Fixes #8876
Upgrades jsoup to 0.15.3 to solve the vulnerability reported by snyk (also see https://github.com/TeamNewPipe/NewPipeExtractor/pull/911)
Release APK signed with my keys: [app-release.zip](https://github.com/TeamNewPipe/NewPipe/files/9422940/app-release.zip)
=> Hotfix release v0.23.3

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml, .github/PULL_REQUEST_TEMPLATE.md
Remove extra whitespace from issue and PR templates.
=> Remove extra whitespace from issue and PR templates

app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt, app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java
Before the Target would sometimes be garbage collected before being called with the loaded channel icon, since Picasso holds weak references to targets. This meant that sometimes a new streams notification would not be shown, because the lambda that should have shown it had already been garbage collected.
I don't know if there was a way to properly reproduce something wrong with the previous behavior, but Picasso clearly states in `RequestCreator#into(Target)`:
> This method keeps a weak reference to the `Target` instance and will be garbage collected if you do not keep a strong reference to it.
Anyway, I tested the new code by subscribing to the usual Roel Van De Paar and it works.
Note that this is also one of the causes of a missing thumbnail in the notification, that will be fixed …
=> Keep strong references to Picasso notification icon loading targets

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
The surface view is the view that contains the playing video, on which exoplayer draws. Its height was never being initialized, leaving it to 0, so the view did not have enough information to respect the video aspect ratio (which instead was being set correctly), leading to https://github.com/TeamNewPipe/NewPipe/pull/8170#issuecomment-1191217817. The height was never being set because the code tried to set it when the surface view hadn't been initialized yet. Now the height-setup is `post`ed to a `Handler`, this way the player initialization completes (creating the surface view) and then the height is initialized.
This PR should also fix https://github.com/TeamNewPipe/NewPipe/pull/8678#issuecomment-1200483145, since now all `null` checks are done inside the lambda `post`ed to the main …
=> Fix surface view not resizing video correctly + other player fixes

app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationPlayerUi.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java, app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
This PR fixes yet another issue about the notification thumbnail not changing when going to the previous or next item in the player queue (see https://github.com/TeamNewPipe/NewPipe/issues/8890#issuecomment-1229464123).
What I think the problem was (though this might need more investigation) is this:
1. when tapping on "next", NewPipe's queue implementation would go to the next item
2. then the ExoPlayer's internal media item queue gets synchronized, by telling the player to go to the next item
3. the player internally switches to the next item, and it starts loading its stream details to be able to play it, also updating the item index in the media session (a component that the system can read to get info)
4. the player switches state to `onBuffering`, which triggers a notification …
=> Fix wrong thumbnail in notification on Android 13

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/res/values/strings.xml
This PR shows the correct `tooltip`s for hide/show actions in the feed. So when watched/future items are shown, the tooltip is "Hide watched/future items", otherwise it is "Show watched/future items". This is because the tooltip should represent the action performed by clicking on the button, as requested [here](https://github.com/TeamNewPipe/NewPipe/issues/8890#issuecomment-1230466338). The item's `title`s, though, should just be a description of the button, and so stay the same (always "Show ... items"). This PR also changes "Show/hide future videos" to "Show/hide future items", in order to be consistent with "Show/hide watched videos", and also because a user's feed may not be composed of only videos.
While testing I noticed that, when pressing the buttons, sometimes the future-items …
=> Show correct tooltips for actions in feed

app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java
This PR fixes the various issues that arose after upgrading the search suggestions list code in #8719: inconsistent item icons on the left sometimes (e.g. history icon when the item is not from history), strange item movements when changing the list, strange scrolling behavior when the suggestions change (i.e. not scrolling always to the top on change). See the three commits' messages for more information. @Isira-Seneviratne could you review?
=> Fix various issues in the search suggestions list

app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- Use [`LinkifyCompat`](https://developer.android.com/reference/androidx/core/text/util/LinkifyCompat) to backport `Linkify` improvements for older API levels.
- Fixes #
=> Use LinkifyCompat.

app/src/main/res/xml/appearance_settings.xml, app/src/main/res/xml/content_settings.xml, app/src/main/res/xml/download_settings.xml, app/src/main/res/xml/notifications_settings.xml, app/src/main/res/xml/video_audio_settings.xml
- Utilize `useSimpleSummaryProvider` attribute instead of using `android:summary="%s"`
=> Utilize useSimpleSummaryProvider attribute

app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt, app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
Just a missing commit from #8683, see the equivalent for `FeedViewModel`, 404c13d4c1d5bc887a45733018a87cee26056fc2, and see https://github.com/TeamNewPipe/NewPipe/pull/8683#issuecomment-1200438229.
=> Improve `FeedGroupDialogViewModel` factory

app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
- Fixes potential exception when casting to `Spannable` in `CommentTextOnTouchListener`
- Fixes #9052
=> Fix potential cast exception in comments text

app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt, app/src/main/res/layout/fragment_about.xml, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml
According to the instruction of the maintainer, add link to FAQ in the app.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/110877395/197141982-8004ded2-d692-4691-9fdb-e1e9cb90d144.png" height="400px" alt="Before"/></td>
<td><img src="https://user-images.githubusercontent.com/110877395/197142001-244f559c-eb20-4ef3-9127-b8d816ae5f06.png" height="400px" alt="After"/></td>
</tr>
</table>
- Fixes #4447 
=> Add Link to FAQ in the app

app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- Display a Toast with the text "Hold to enqueue" when either one of the headers(background, play all, popup) in a playlist is clicked
- Before: 
https://user-images.githubusercontent.com/111133681/197704289-9b91cb74-7e78-403e-a029-dc79e00838d1.mov
- After:
https://user-images.githubusercontent.com/111133681/197704754-96f61ea1-ed58-4fb5-b7e8-7d5b88753878.mov
- Fixes  #9130
=> Added Toast Notification "Hold to enqueue"

app/build.gradle
Jitpack seems to have deleted the previous commit form their servers (5c710da160f488bb40ab2cf4469bec9bd4cefd38). This PR will be merged as soon as the CI passes.
=> Update extractor to fix Jitpack failures in CI

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/player/gesture/MainPlayerGestureListener.kt, app/src/main/java/org/schabi/newpipe/player/ui/PopupPlayerUi.java, app/src/main/java/org/schabi/newpipe/util/ReleaseVersionUtil.kt
- Use range-limiting methods such as `MathUtils.clamp()` and Kotlin's `coerceIn()` in a couple more places.
- Fixes #
=> Use range-limiting methods in more places.

app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java, app/src/main/java/us/shandian/giga/util/Utility.java
- Use Okio's `ByteString` for its digest functionality in the download checksum calculation.
- Fixes #
=> Use Okio's ByteString for download checksums.

app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
- Refactor the `removeWatchedStreams` method in `LocalPlaylistFragment`.
- Fixes #
=> Refactor removeWatchedStreams() in LocalPlaylistFragment.

app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentAdapter.kt, app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentItem.kt, app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
- Added the ability to share timestamped links starting from the beginning of a particular chapter when the user long clicks on them
- Fixes #8343 
=> Added timestamped link sharing from the start of a chapter with a long hold press

app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
In #8621 I deduplicated the queries to get feed info, but I made a mistake regarding the "All" group. The LEFT JOIN of the subscription table with the feed groups table rightfully generates multiple results for each subscription (since it is a join), but, for user-created groups, all results except for at most one are, in the end, filtered out by the first condition in the WHERE, because a subscription can appear in a group at most once. When the query was used for the "All" group, though, the first condition in the WHERE would not do anything (the reasoning behind this was to allow subscriptions independently of groups), causing duplicate subscription results to be generated (i.e. one per group the subscription belonged to). This PR fixes the problem by just making the condition on the …
=> Fix duplicate videos in feed group "All"

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Hide the play queue button in the mini player in the VideoDetailsFragment when the play queue is empty.
Related PR introducing the button: #8946
- Addresses https://github.com/TeamNewPipe/NewPipe/pull/8946#issuecomment-1273728592
=> Hide play queue button in VideoDetailsFragment when queue is empty

app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionViewModel.kt, app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupCarouselItem.kt
This PR tries to address https://github.com/TeamNewPipe/NewPipe/issues/9292#issuecomment-1303825232 ~~by making updates to the list view state happen at the same moment they are enforced, in order to prevent inconsistencies.~~ Actually that was not the problem, but rather the span count being wrongly calculated.
- https://github.com/TeamNewPipe/NewPipe/issues/9292#issuecomment-1303825232
=> Fix inconsistent channel group list and items view mode

app/src/main/java/org/schabi/newpipe/NewVersionWorker.kt, app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt, app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt, app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt, app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java, app/src/main/java/org/schabi/newpipe/util/PendingIntentCompat.java, app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- Make the `PendingIntent`s created in the app immutable on Android 6.0 and later. This prevents issues with `PendingIntent`s occurring [when targeting Android 12 and later](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability) in #9306.
- Fixes #
=> Make PendingIntents immutable on Android 6.0 and later.

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
A non-touch input device that supports hover events results in a persistent transparent overlay on top of the video player. When using an Android device in desktop mode or with a mouse, the content is obscured with said overlay. 
The bug was first reported here: https://github.com/TeamNewPipe/NewPipe/issues/4357
This PR adds an `isDesktopMode` check and removes the hover overlay for the `detailThumbnailRootLayout` only when in desktop mode (DeX, Android desktop, etc.)
- Before:
- After:
- Fixes #4357 
APK for testing: [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/8597415/app-debug.apk.zip)
=> Fix persistent hover overlay when in desktop/DeX mode or using a mouse/non-touch input

app/src/main/java/org/schabi/newpipe/util/Localization.java
- Use `Locale.forLanguageTag()`, as the minimum API level is now 21.
- Fixes #
=> Use Locale.forLanguageTag().

app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java, app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java, app/src/main/java/us/shandian/giga/util/Utility.java
This PR removes the extra toast when some text is copied using `ShareUtils.copyToClipboard`, for Android 13 and above.
The `copyToClipboard` method of the `Utility` class has been removed and its usages have been replaced by the method of `ShareUtils`.
- Before:
- After:
- Fixes #8957
=> Remove the redundant/overlapping toast "Copied to clipboard" for Android 13+

checkstyle/checkstyle.xml
- checkstyle: declare org.jetbrains and javax.annotation Nullable's and NotNull/Nonnull as illegal imports
=> Forbid wrong `@Nullable` and `@NotNull` annotation imports

app/src/main/res/layout-large-land/fragment_video_detail.xml, app/src/main/res/layout/fragment_video_detail.xml
- removed right-padding of close button LinearLayout.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/32548153/183250235-ffb7db13-884f-439f-b363-6460a9bc50cf.png" height="300px" alt="Before"/></td>
<td><img src="https://user-images.githubusercontent.com/32548153/183250262-d4dd17ba-3b5e-4565-bed2-de373bec387c.png" height="300px" alt="After"/></td>
</tr>
</table>
- fixes #8615
=> Remove padding from the end of the mini-player

app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
Add a check that the queue position is not the last in the queue before
showing "Enqueue next".
Previously the "Enqueue next" action would always be shown if the queue
length was greater than one, this meant even if you were at the end of
the queue (when "Enqueue" would have the same effect as "Enqueue next")
the action would still be shown.
=> Only show "Enqueue next" when in the middle of the queue

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/res/layout-large-land/fragment_video_detail.xml, app/src/main/res/layout/fragment_video_detail.xml
I added the subscriber count to the channel tag on the player page. It currently only shows on YouTube videos because NPE does not return the subscriber count for streams on other platforms, but that can be fixed in the extractor later.
- Fixes #2587 
=> Show subscriber count on video details page

app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java, app/src/main/res/values/strings.xml
Instead of removing it, I disabled the night theme selection when the "Automatic (device theme)" is not used.
- Before:
- After:
- Fixes #9353 
=> Disabling night theme selection if auto theme is not used

app/src/androidTest/java/org/schabi/newpipe/util/StreamItemAdapterTest.kt, app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHolder.java, app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java, app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- Use [`SparseArrayCompat`](https://developer.android.com/reference/androidx/collection/SparseArrayCompat) to reduce memory usage in the thumbnail preview, search and download functionality by avoiding integer boxing.
- Make some additional minor code improvements in `StreamItemAdapter`.
- Fixes #
=> Use SparseArrayCompat.

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/schabi/newpipe/MainActivity.java, app/src/main/java/org/schabi/newpipe/player/gesture/PopupPlayerGestureListener.kt, app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java
`android:exported` in now required in the manifest on all activities/services/receivers/providers. It was set to `true` for those that need to interact with outside apps or the OS, while others have `exported=false`. Changing the target sdk also required updating LeakCanary to the latest version as the older version being used was not using `android:exported` in `AndroidManifest.xml`.
I don't know whether problems could arise just because of this number increase, maybe @TacoTheDank can shed some light on it?
- https://github.com/TeamNewPipe/NewPipe/issues/9292#issuecomment-1304571423
- #9333
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of …
=> Set compileSdk and targetSdk to 33 (Android 13)

app/build.gradle, build.gradle
- Update desugar_jdk_libs 1.1.6 -> 1.1.8 ([changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md))
Some other things:
- Update ACRA 5.9.3 -> 5.9.7 ([changelog](https://github.com/ACRA/acra/releases))
- Update AGP 7.3.0 -> 7.3.1
=> Update Desugaring to 1.1.8

app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/PlayerService.java, app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
- the player is not paused while the user is using the seeking feature
- Before:
https://user-images.githubusercontent.com/26669009/205454341-1775c891-7340-4d52-8c09-7e98caaf4051.mp4
- After:
https://user-images.githubusercontent.com/26669009/205454288-d89b290b-3655-4071-ba9d-91774745043a.mp4
- Fixes #9437 
=> Seeking no longer pauses the played video

app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/res/values/strings.xml
- Crash fix on clicking on add to playlist.
- Added toast when clicked on share button for better UI.
<table>
<tr>
<td>
https://user-images.githubusercontent.com/76740999/206662143-ce076e98-2b9a-4e6e-9b4c-504f38d19437.mp4
</td>
<td>
https://user-images.githubusercontent.com/76740999/206662153-8c755540-44b9-463d-9819-1c76512eb04f.mp4
</td>
</tr>
</table>
- Fixes #9518
=> Fixes #9518: Crash fix when click "Add to playlist" while the current list is still loading

app/build.gradle
- Update RxJava to 3.1.5. Changelog: https://github.com/ReactiveX/RxJava/releases
This should reduce power consumption on mobile devices: https://github.com/ReactiveX/RxJava/pull/7293
=> Update RxJava to 3.1.5.

app/src/main/res/layout/playlist_control.xml
Added icon for "Play All"
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/76740999/208503684-751c867f-c895-4480-ad17-656804cd1d7e.png" width="200px" alt="Before"/></td>
<td><img src="https://user-images.githubusercontent.com/76740999/208503689-b94cedf6-9960-4a07-bac2-3a9cec72cda6.png" width="200px" alt="After"/></td>
</tr>
</table>
- Fixes #9567
=> Added icon for "Play All"

app/src/main/java/org/schabi/newpipe/settings/notifications/NotificationModeConfigAdapter.kt, app/src/main/java/org/schabi/newpipe/settings/notifications/NotificationModeConfigFragment.kt
- Use `ListAdapter` in the notification mode adapter.
- Fixes #
=> Use ListAdapter in NotificationModeConfigAdapter.

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java, app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
Some services may only have video streams and no separate audio streams available. This commit will add audio background playback support for those services. It uses the video source as audio source for background playback.
**Note** I think currently NewPipe is in no need to support this feature but maybe in the future. I use it in BraveNewPipe as some services do not support audio only streams. Would be great if it could be merged.
Thx
- audio playback for services that do not support audio streams.
- use audio from video stream for audio only background playback
=> Support audio only background for services only supporting video streams

app/build.gradle, app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java, app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- Use the new `Utils` methods added in https://github.com/TeamNewPipe/NewPipeExtractor/pull/880
- Fixes #
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/880
=> Use new NPE UTF8 Utils methods

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java, app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java, app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHelper.java, app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java, app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
- Remove `SimplifyOptionalCallChains`, as the `Optional#isEmpty()` method is now available in the Android SDK starting with version 33 and is desugared.
- Make use of `Optional` method chaining.
- Fixes #
=> Clean up Optional-related code.

app/src/main/java/org/schabi/newpipe/RouterActivity.java
Currently when sharing to NewPipe (when set to `Always ask`), the Open action menu dialog would rotate away on orientation change (since `finish()` would be called by onDismissListener during dialog cleanup thus preventing `RouterActivity` to be recreated when screen rotates).  This PR tries to improve that by making the dialogs stay across screen rotations.
~~_Known issue:_ Ongoing network requests, however, won't survive config change (which would somehow require keeping track of the `Observable`s across recreation of activity).  If user selects Add to Playlist or Download and rotates away while stream info is being fetched, the network request underway would be dropped and `RouterActivity` would start over again when recreated on orientation change.  That would (unfortunately) be …
=> Improve screen rotation handling in Open action menu

app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml
Added Language suffix for subtitle downloads.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/76740999/205491593-edec6e4a-682c-4e08-92f4-19c3e78f5542.mp4
</td>
<td>
https://user-images.githubusercontent.com/76740999/205491598-6efdbdbf-240f-440f-bc23-7fa71669b0c6.mp4
</td>
</tr>
</table>
- Fixes #9466 
- 
=> Added Language suffix for subtitle downloads

app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Samsung DeX is a feature of Samsung devices. There is no reason to assume it is on other devices. This disables the reflection calls on all devices that aren't manufactured by Samsung.
=> Check availability of Samsung DeX only on Samsung devices

app/src/main/java/org/schabi/newpipe/player/gesture/BasePlayerGestureListener.kt, app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java, app/src/main/java/us/shandian/giga/ui/common/Deleter.java
- Replace the `Runnable` variables being used in the downloader and double tap functionality with lambdas, and use String  constants to keep track of them in the Handlers.
- Fixes #
=> Remove Runnable variables for Handlers.

app/schemas/org.schabi.newpipe.database.AppDatabase/6.json, app/src/androidTest/java/org/schabi/newpipe/database/DatabaseMigrationTest.kt, app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java, app/src/main/java/org/schabi/newpipe/database/AppDatabase.java, app/src/main/java/org/schabi/newpipe/database/Migrations.java, app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java, app/src/main/java/org/schabi/newpipe/database/playlist/model/PlaylistEntity.java, app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java, app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java, app/src/main/res/values/strings.xml
- added an an option to permanently set a thumbnail with the already existing "Set Thumbnail" feature in the long press menu
- changed the long press menu of the local playlists
- Before: Rename/Delete dialog opens
- After: AlertDialog opens with 3 options: `Rename`, `Delete`, `Unset Thumbnail`. `Rename` and `Delete` open the respective dialog. `Unset Thumbnail` is only enabled if the thumbnail has been permanently set. If you press this option, the permanent playlist thumbnail is unset and a new one gets chosen automatically (first video in the playlist or a default thumbnail if there is no video in the playlist). 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/26669009/206691430-cb5d049a-08b6-4db9-9c96-7880c96caaf3.png" …
=> Allow the user to permanently set a thumbnail

app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
After a lot of troubleshooting, I found out that this bug is bigger than I initially thought, as I encountered another issue: If you manually remove videos from your playlist and then use the "Removed Watched Videos" feature, the manually deleted videos reappear. 
The reason why these bugs occur is that the streamStateTable is not up-to-date when you remove the watched videos. However, updating the playlist/streamStateTable beforehand doesn't work either, as we only save the state of an entity if it has been viewed for more than 5 seconds (maybe you want to use this feature directly after starting to watch a video). I wouldn't recommend lowering this number, as it would cause accidentally clicked videos to be counted as viewed as well.  
Therefore, I decided to slightly change the way we …
=> Fixed a bug that incorrectly removed videos from a playlist when using the "Remove Viewed" dialog

app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
- The issue was fixed by changing the faulty query `getPlaylistMetadata`:
If a playlist has no streams, there won’t be any rows in the `PLAYLIST_STREAM_JOIN_TABLE` table that have a foreign key to that playlist. Thus, the `JOIN_PLAYLIST_ID` will not have a corresponding value in any rows of the join table. So, if you group by the `JOIN_PLAYLIST_ID`, only playlists that contain videos are grouped and displayed.
- Fixes #8582 
=> Fixed a bug that prevented the display of multiple empty playlists

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
- Use [`WindowCompat`](https://developer.android.com/reference/androidx/core/view/WindowCompat) to replace the deprecated UI visibility flags.
- Fixes #
=> Use WindowCompat.

app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelMiniInfoItemHolder.java, app/src/main/res/layout/list_channel_grid_item.xml, app/src/main/res/values/dimens.xml
- Made the channel-images in the grid list bigger
- Add description to channel grid items
- Detail line: display both subscriber count and video count in all channel item instances
- Make description height either 2 lines or 3 lines based on whether the detail line actually contains something or not
<table>
<tr>
<th>Before1</th>
<th>Before2</th>
<th>After1</th>
<th>After2</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/109673982/208202962-05569fec-8b87-4888-88c3-18a824a9e1e5.png" width="200px" alt="Before1"/></td>
<td><img src="https://user-images.githubusercontent.com/109673982/208202993-88ba7a4b-66b6-47bd-b81a-9200a2ed3377.png" width="200px" alt="Before2"/></td>
<td><img src="https://user-images.githubusercontent.com/36421898/212534465-11867ea8-18b0-4a42-9f1f-065e …
=> Made the channel-images in the grid list bigger

app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java, app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java, app/src/main/java/org/schabi/newpipe/info_list/ItemViewMode.java, app/src/main/java/org/schabi/newpipe/info_list/holder/PlaylistCardInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/info_list/holder/StreamCardInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java, app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/feed/item/StreamItem.kt, app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistCardItemHolder.java, app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamCardItemHolder.java, app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamCardItemHolder.java, app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistCardItemHolder.java, app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java, app/src/main/res/layout/list_playlist_card_item.xml, app/src/main/res/layout/list_stream_card_item.xml, app/src/main/res/layout/list_stream_playlist_card_item.xml, app/src/main/res/values-w820dp/dimens.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml
Rationale behind the feature:
When user go through videos, it's not possible to get enough info from title as content creators prefer to include details in thumbnails as such.
- Spec details in tech videos
- Movie names
- News headline
- so on
PR for https://github.com/TeamNewPipe/NewPipe/issues/6087
This PR adds new List view mode called `Card`. Behavior follows,
- A full width card with thumbnail size 16:9 ratio
- Two line full width title
- Streams Feed/Trending/Channel details (list)
- Playlists in search and local playlist listing
- Streams inside local playlist
Currently we have flags for `gridLayout`, `miniLayout`. Replaced the same with enum. Unified logic to identify the list mode resides in ThemeHelper.
https://github.com/TeamNewPipe/NewPipe/issues/8412
Thumbnail size in grid is …
=> FR: Full width thumbnails aka card view mode

app/src/main/java/org/schabi/newpipe/RouterActivity.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java
Calling `getView()` is forbidden (returns `null`) on API 33. That method was used to center the text in the toast, but I think that was not useful anyway so I just removed the centering completely and now the popup enablement toast shows normally.
I also simplified some duplicate code, since each time the popup permission was checked, the toast would also be shown, so I merged those.
Related to #9306.
=> Fix popup enablement toast crash on API 33

app/build.gradle, build.gradle
Now that Android Studio Electric Eel has finally been released, we can update [AGP to 7.4.x](https://developer.android.com/studio/releases/gradle-plugin) (previously max version was 7.3.x). This also allows upgrading desugaring to [Desugaring 2.0.0](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md), which requires Java 11 at build time.
=> Update desugar_jdk_libs to 2.0.0.

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java, app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/tabs/TabsManager.java, app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
According to `OnSharedPreferenceChangeListener`'s documentation, this was caused by #9306 (even though it is not mentioned in [Android 11's upgrading page](https://developer.android.com/about/versions/11/behavior-changes-all)):
> Apps targeting API 30 on devices running OS versions Android R/11 or later, will receive a `null` value when preferences are cleared.
So I modified all of our overrides of that function to make sure to handle null values gracefully.
- Fixes #9692
=> Fix NPEs after OnSharedPreferenceChangeListener changes

app/build.gradle
We want to have reproducible builds on F-Droid so that they can ship our own APK signed with our keys, which would prevent some uninstalling and reinstalling when users switch sources.
All credits for the fix go to @obfusk, also see https://issuetracker.google.com/issues/231837768. It has been confirmed that this works [here](https://github.com/TeamNewPipe/NewPipe/issues/6486#issuecomment-1398748847).
- Closes #6486
=> Fix reproducible builds

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java, app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java
The bug was caused by an incorrect comparison between the existing `PlaylistQueue` and the new `PlaylistQueue`. In the `handleIntent` method in the `Player` class, both are compared, and if they are considered equal, the existing `PlaylistQueue` remains unchanged (because why reinitialize the same queue?). However, the overridden equality check was incorrect, as it only checks if the streams are the same, without considering the `queueIndex`. By inserting this check, the bug is fixed and only if the queues are actually identical, the existing queue is not reinitialized anymore.
I also had to change a test that tests if the equality check disregards the index. However, IMO if you do that the "equal" check doesn't make sense, since these queues cannot be considered equal.
- Fixes #9131 
The …
=> Fixed a bug that caused the background player to stop working

app/build.gradle, app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java, app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java, app/src/main/java/org/schabi/newpipe/util/text/CommentTextOnTouchListener.java, app/src/main/java/org/schabi/newpipe/util/text/HashtagLongPressClickableSpan.java, app/src/main/java/org/schabi/newpipe/util/text/TextLinkifier.java, app/src/main/java/org/schabi/newpipe/util/text/TimestampLongPressClickableSpan.java
- Update the extractor to the latest commit, with breaking changes from https://github.com/TeamNewPipe/NewPipeExtractor/pull/987: now comments have a `Description` and not a `String` anymore
- Changes in `TextLinkifier`:
- Move the method that determines how to linkify a description based on its type from `DescriptionFragment` to `TextLinkifier`
- Rename methods in `TextLinkifier` to not contain the redundant "link" word already contained in "Linkifier"
- Allow passing a callback to `TextLinkifier` methods to be notified when the text has been set to the `TextView`, needed to set ellipsis and movement method in comments
- Since `TextLinkifier` only needs stream url and service id to generate popup-timestamps and hashtags, and since comments only have that information and not a full …
=> Update NewPipeExtractor and properly linkify comments

app/build.gradle, app/src/main/AndroidManifest.xml
This pull request adds the application part of YouTube's live URLs support (the extractor part is already done and it is updated with this PR to include the required changes), which are in the form `https://www.youtube.com/live/LIVE_ID`, where `LIVE_ID` is the video ID of the livestream. This behavior applies to past, planned and running livestreams.
- Fixes #9546
=> [YouTube] Add support for live links

app/src/main/AndroidManifest.xml
See https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9 and https://github.com/TeamNewPipe/NewPipe/issues/9615. I used what @plasticanu suggested, except that I also added "http" and "market" to the used schemas.
I tried to install the Kore app and everything works well even without adding `<package android:name="org.xbmc.kore" />` to the possible queries, so I didn't add it in the end. I tested on API 33.
- Fixes #9615
=> Fix opening URLs in browser on API 30+

app/build.gradle, app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
This commit reverts #9553 / 1bb166a and downgrades ExoPlayer to 2.18.1.
There is a bug in ExoPlayer 2.18.2 which leads to crashes (e.g. see https://github.com/TeamNewPipe/NewPipe/pull/9553#issuecomment-1398217296) which is going to be fixed in an upcoming version.
- Fixes https://github.com/TeamNewPipe/NewPipe/pull/9553#issuecomment-1398217296
=> Revert PR #9553 "Update ExoPlayer to 2.18.2"

app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
This https://github.com/TeamNewPipe/NewPipe/issues/4478#issuecomment-1382828147 in the ever lasting full screen button discussion is actually valid. If a device does not feature an accelerometer (STB, Terminal, TV), the screen cannot rotate. It is more some sort of "sanity" check, as "def_accelerometer_rotation" in the SettingsProvider in AOSP is "false", which means, that after a factory reset, auto rotation of the screen should be disabled anyway. So a device manufacturer must have deliberately broken it (actually a device bug, not a bug in NewPipe) or a user must have selected screen auto rotation, even though it doesn't work. So this probably affects only a handful of users of NewPipe.
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", …
=> Orientation is locked if there is no sensor for it

app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
#9726 wasn't enough. Android 12+ seems to return null to calls to `resolveActivity`, so the previous code would have said "No app can open this". Now instead, we try to open the activity in any case, even when we don't have a resolved package to set. I will take care of removing the now unused string if this PR is considered correct.
@AudricV do you think this is ok?
- See https://github.com/TeamNewPipe/NewPipe/issues/9712#issuecomment-1400843696
=> Fix opening links on Android 12+

app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
Crash fix when click on empty comment.
After :
https://user-images.githubusercontent.com/76740999/218010404-fd579e33-560b-4f0a-999a-344cb40db0b1.mp4
- Fixes #9774
=> [Bug] Crash fix when click on empty comment

app/src/main/res/values-w820dp/dimens.xml
Reverts a small piece of #9310, which introduced bigger grid thumbnail sizes on big screens, because some users reported not being happy about having too few grid columns. See https://github.com/TeamNewPipe/NewPipe/pull/9310#discussion_r1070670806.
<table>
<tr>
<th>Before #9310</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/36421898/221361287-026f9fbd-91a7-404d-8450-fc4c5722ab7f.png" width="400px" alt="Before #9310"/></td>
<td><img src="https://user-images.githubusercontent.com/36421898/221361223-a4a0426d-be00-4768-87b5-720f4b8e828a.png" width="400px" alt="In #9310"/></td>
<td><img src="https://user-images.githubusercontent.com/36421898/221361183-ed723548-995f-444b-99df-0571e907a167.png" width="400px" alt="After"/></td>
</tr> …
=> Reduce the size of thumbnails on big screens to fit more grid columns

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java, app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java, app/src/main/java/org/schabi/newpipe/util/DependentPreferenceHelper.java, app/src/main/res/xml/history_settings.xml
- Make `Resume playback` the dependency of `Positions in lists`.
- Regain the function to control if playback information for videos in lists should display for option `Positions in lists`.
- Use `Resume playback` to control if playback information in `VideoDetailFragment` should display (`positionView` and `detailPositionView`, for UI), and remove this function for `Positions in lists`.
- Animate without delay in case that `positionView` and `detailPositionView` should disappear.
- Before:
https://user-images.githubusercontent.com/36195713/162966408-72defb1b-c1d4-4719-badf-a7eebecd8fe3.mp4
- After:
https://user-images.githubusercontent.com/36195713/162966432-8d248fc0-3044-4f7e-9f2d-41fc155505b8.mp4
- Fixes #4053 
- Fixes #8176
The APK can be found by going to the "Checks" tab below the …
=> Make UI behavior for playback information display more consistent

app/sampledata/channels.json, app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java, app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelCardInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelMiniInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionViewModel.kt, app/src/main/res/layout/list_channel_card_item.xml, app/src/main/res/values/dimens.xml
These changes take effect when card mode is selected for item view.
- This card is **NOT** applicable for subscriptions list fragment
- Thumbnail larger (100dp) than the usual (92dp) throughout the app
- More similar to List item with more description content
- Description max line count is 8 (normally 3)
| Before: UI follows the same List mode item   |  After: New Channel card will be displayed  |
|---|---|
|<img alt="image" src ="https://user-images.githubusercontent.com/6584143/215337120-6af0deac-6392-48ca-ad97-762165dfbd2e.png" width=277/> | <img alt="image" src ="https://user-images.githubusercontent.com/6584143/215336898-1f486ef9-1974-42db-9de7-27c2fbea18ec.png" width=277/>|
- Fixes #9703
- #### APK testing
The APK can be found by going to the "Checks" tab below the title. On the …
=> Larger channel cards in search results

app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/video_audio_settings.xml
- Adds an option called "Ignore hardware media button events", which disables any pause/play and the prev/next track buttons, including ones on a headset. It helps prevent accidental touches and makes the app more usable on a headset with broken buttons.
The option is inside the Video and audio category.
- Before:
- After:
- Fixes #9745
=> Add an option to Ignore hardware media button events

app/build.gradle, app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
Same as #9553 but this time with ExoPlayer 2.18.3 ([changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2183-2023-02-16))
=> Update to ExoPlayer 2.18.3

app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
The current release PR is failing the sonar lint quality quard. This PR removes the wrong annotation to make sonar lint happy:
> Do not use `@Nullable` in Kotlin; the nullability is determined by the Kotlin type `View.OnClickListener` **not** ending with `?` which declares it not nullable, contradicting the annotation
(see https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&pullRequest=9869&id=TeamNewPipe_NewPipe&open=AYacpIb_J93zs3Jn_4eI)
=> Remove wrong annotation

app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
This PR makes the app using the behavior when there is no default browser on Android 11 and lower, by opening a system chooser when there is no browser available (on all Android versions).
Also catch any exception when the system chooser cannot be opened and show the "No app on your device can open this" toast in this case, as an `ActivityNotFoundException` would be thrown if no app is available to open a web link.
These changes have been tested on an Android 14 developer preview 2 emulator and a system chooser is now displayed where there is no browser available, no default app set to open the requested link and an available app.
They also work fine on my physical device running Android 10 when there is no app available to open a web link (the "No app on your device can open this" toast …
=> Use a system chooser when opening links in browser in the case there is no browser available

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
Reverts TeamNewPipe/NewPipe#8894
Supersedes #9785
Fixes #9799 and fixes #9773
=> Revert "Use WindowCompat."

app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java, app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java, app/src/main/java/org/schabi/newpipe/util/ListHelper.java
This PR makes NewPipe compatible with the changes from https://github.com/TeamNewPipe/NewPipeExtractor/pull/488 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/706
https://github.com/TeamNewPipe/NewPipeExtractor/pull/488 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/706 can, but do not have to be merged
=> Add whitelist to only retrieve supported YouTube itags/streams

app/src/main/java/us/shandian/giga/get/DownloadInitializer.java, app/src/main/java/us/shandian/giga/util/Utility.java
- YouTube throttles all requests to their streams if they dont have either a Range header or a `&range=n-m` URL parameter
- YouTube's throttling is triggered by HEAD requests, too. Since the downloader uses HEAD requests to determine the file size, the subsequent GET requests will be throttled, too
- I modified the downloader to use HEAD requests with a range header to determine the file size. YouTube will return a Content-Range header for these requests, e.g. (`bytes 0-0/4530953`) which can be parsed to get the total size.
- The improvement is most noticeable on small audio files. Songs download almost instantly now.
- Larger audio files still get throttled at the end of a download, I am not sure how to fix this.
- Fixes #8147, fixes #8619.
The APK can be found by going to the "Checks" …
=> [YouTube] Improve download speed

app/build.gradle
When the ktlint formatter needed to make some changes to kotlin files, it failed with the following exception, see https://github.com/pinterest/ktlint/issues/1195:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.lang.Object java.lang.Throwable.backtrace accessible: module java.base does not "opens java.lang" to unnamed module @...
```
Although this should have been fixed in the latest version of ktlint, upgrading from 0.45.2 to 0.49.0, didn't really solve the issue as I then got a different error, see https://github.com/ScoopInstaller/Extras/issues/10313:
```
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ThrowableInterner
```
The solution provided in both issues was just …
=> Fix ktlint formatter after upgrade to Java 17

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/res/layout-large-land/fragment_video_detail.xml, app/src/main/res/layout/fragment_video_detail.xml
- In the XML of video details, the uploader and sub-channel images were swapped. Moreover, the code in `VideoDetailFragment` didn't really take into account the fact that when no sub-channel is present, the uploader is shown as sub-channel. So I fixed both of these things.
- When there is no *sub-channel*, now the logic is the same regardless of whether the *uploader* name is empty (which would likely be caused by an extractor error) or not. So now when there is not even an *uploader* name, the subscribers and avatar are still shown.
- I removed the error reporting snackbar that popped up when the video thumbnail failed loading: it's not really needed as if there is an issue with thumbnails not loading, we can just ask users to send us the thumbnail URL that can be found in the …
=> Fix uploader and subchannel avatars being swapped and disable loading thumbnail message failure on content details page

app/build.gradle
Update ACRA and Checkstyle libraries to fix vulnerability in their dependencies: `com.google.guava`.
See https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-5710356 for more details.
ACRA changelog : https://github.com/ACRA/acra/releases (no changes required, notable: target API for ACRA increased to 34)
Checkstyle changelog: https://github.com/checkstyle/checkstyle/releases (no changes required)
Fixes no GitHub issues, but fixes the Snyk workflow
=> Update ACRA and Checkstyle to fix a dependency vulnerability

.github/workflows/image-minimizer.js
Images are now linked to the repo and have a different URL.
Other files like .zip-files are stored under the /files/ URl and are thus not effected by the workflow change.
You can test the changes in my repo, e.g. by posting to this comment: https://github.com/TobiGr/NewPipe/issues/11
Fixes the image minimizer workflow doing nothing on new images
=> Add support for new GitHub assets URLs in image minimizer workflow

.github/PULL_REQUEST_TEMPLATE.md
I added a wiki page which contains a video demonstrating how to download an APK for a PR. Some users have had difficulties finding the APK. 
The wiki page: https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR
=> Add link to wiki page for APK download

app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt, app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/HistorySettingsFragment.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/java/org/schabi/newpipe/util/external_communication/KoreUtils.java, app/src/main/java/org/schabi/newpipe/util/text/InternalUrlsHandler.java, app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java, app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
- Cleaned up the code relating to AlertDialogs (with some reformatting)
=> Clean up AlertDialogs

app/build.gradle, app/src/debug/java/org/schabi/newpipe/DebugApp.kt, app/src/main/java/org/schabi/newpipe/BaseFragment.java
- Update LeakCanary library 2.9.1 -> 2.12 ([changelog](https://square.github.io/leakcanary/changelog/))
- Fix LeakCanary deprecations
=> Update LeakCanary library

app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
Fixed a crash after updating the feed. It doesn't seem to be a common issue, however it happens every time on my device.
Not needed
- Fixes #10142
- 
=> Fix crash after feed update

app/build.gradle, app/src/debug/java/org/schabi/newpipe/DebugApp.kt, app/src/main/java/org/schabi/newpipe/BaseFragment.java, app/src/main/java/org/schabi/newpipe/player/PlayerService.java
- According to the stacktrace provided in https://github.com/TeamNewPipe/NewPipe/pull/10085#issuecomment-1635848614, LeakCanary now takes care to install the AppWatcher by itself, so we don't need to set it up manually, so I just removed the incriminating line. Also see #10231 and [this changelog](https://square.github.io/leakcanary/changelog/#configuring-retained-object-detection).
- I have tested by enabling LeakCanary in the settings and capturing a few leaks. Among those leaks I then found a really suspicious `PlayerService`-related leak and I decided to fix it, for more info see https://stackoverflow.com/q/63787707 and the leak report below. You can verify that this was fixed by opening the player, closing it and then taking a heap dump from LeakCanary. Note that these steps did not …
=> Fix LeakCanary startup in debug builds and fix a memory leak

app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
Fixes a regression introduced by #9937 that made the DownloadDialog not respect the selected audio stream but download the initially selected stream.
Fixes #10180 
=> [Download] Fix audio stream selection

app/src/androidTest/java/org/schabi/newpipe/local/subscription/SubscriptionManagerTest.java
- A JUnit test file is added to test SubscriptionManager.kt (see #2335). However, the test result shows that either the original methods or my understanding of those methods has some problem, so I made this a draft.
- The first problem is that the `ChannelInfo` I insert doesn't equal to the one I searched. The test result shows that it's because of their difference in the uid. IDK if it is designed to operate like that. If it is, I will delete the corresponding test cases in later commit.
- The second problem is that the `updateNotificationMode()` method doesn't seems to function correctly. The `testUpdateNotificationMode()` method 2 and 4 seems to be problematic and redundant, but I will temporarily keep them until this problem is solved or clairfied.
- The third problem is that the …
=> Add database test for SubscriptionManager

app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/appearance_settings.xml
- Added the feature that the main-tabs can be set to the bottom
- Added a toggle in the apperance-settings for this feature
| Main-Page  | Appearance-Settings |
| ------------- | ------------- |
|![NewPipe2 – MainFragment java  NewPipe2 app main  25 01 2023 19_29_17](https://user-images.githubusercontent.com/109673982/214651907-20f34dbf-39f0-4d9b-919d-c6f093c004ee.png) |![NewPipe2 – MainFragment java  NewPipe2 app main  25 01 2023 19_29_33](https://user-images.githubusercontent.com/109673982/214651868-82503d0a-b84d-4bee-8869-4886c8c0e3a4.png)|
- Fixes #7658
=> Added bottom main-tabs feature

app/build.gradle, app/src/androidTest/java/org/schabi/newpipe/database/DatabaseMigrationTest.kt, app/src/main/java/org/schabi/newpipe/database/feed/model/FeedGroupSubscriptionEntity.kt
- Fix MigrationTestHelper deprecation
- Update AndroidX Room 2.4.3 -> 2.5.2 ([changelog](https://developer.android.com/jetpack/androidx/releases/room))
I had to cherry-pick my LeakCanary fix to test this, but I tested the feed, history, playlists, streams, and subscriptions, and everything works fine.
=> Update AndroidX Room library

.github/workflows/image-minimizer.js, .github/workflows/image-minimizer.yml
Images in PR descriptions are not minimized. The workflow file and JS script were altered to do so.
See https://github.com/TobiGr/NewPipe/pull/19 for a working example or create a PR to [my fork](https://github.com/TobiGr/NewPipe).
(Too) Large images in PR descriptions and comments
=> Minimize images in PR descriptions

app/build.gradle
Use okio 3.4.0 explicity to fix vulnerability introduced through okhttp3 (3.3.0).
See https://www.cve.org/CVERecord?id=CVE-2023-3635 for more details on the vulnerability.
Fixes failing snyk security check.
=> Update com.squareup.okio:okio to 3.4.0

app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt, app/src/main/java/org/schabi/newpipe/settings/ExoPlayerSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java, app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java, app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml
In #8875 a setting to disable media tunneling was added. However, the info on devices which do not support media tunneling was removed. That info is re-added and used to disable media tunneling on those devices by default.
Disabling media tunneling seems to also fix the full screen enter/exit bug on Android TVs (#9023)
- Sony Bravia VH1 (`BRAVIA_VH1`)
- Sony Bravia VH2 (`BRAVIA_VH2`), e.g. model A90J
- Sony Bravia Android TV platform 2 (`BRAVIA_ATV2`)
- Sony Bravia Android TV platform 3 4K (`BRAVIA_ATV3_4K`)
- Phillips 4K (O)LED TV (`PH7M_EU_5596`)
- Panasonic 4KTV-JUP (`TX_50JXW834`)
- Bouygtel4K (Bouygues Telecom Bbox 4K) (`HMB9213NW`)
- Added info to ExoPlayer settings explaining that media tunneling was disabled automatically.  
<details><summary>Media tunneling setting …
=> Disable media tunneling by default on known unsupported devices

app/src/main/java/org/schabi/newpipe/player/Player.java
This issue is right on the line between feature and bug, so I'm selfishly calling it a bug. Very straightforward fix, tested with no obvious problems.
- Puts checks for mute state around each call to change audio focus in player
- Makes toggling mute state request/abandon focus
- Fixes #9537
=> Fix player audio focus not respecting mute

.github/ISSUE_TEMPLATE/bug_report.yml
- Edited 1st bullet in bug template to make the clicky link more obvious.
- Hopefully fewer people will skip checking whether they actually have the latest version.
=> Make "latest release" link more obvious to bug reporters

app/src/main/java/org/schabi/newpipe/MainActivity.java
I was completely confused by the wrongly named variable `serviceName`.
Simplify `MainActivity.tabSelected(MenuItem)`: rename variables and skip iterations if kiosk was found.
=> Simplify `MainActivity.tabSelected(MenuItem)`

app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
This PR makes the play queue button visible when there is at least a stream instead of two, allowing users to access to the play queue directly from the main player and so to loop/don't loop a single stream.
This solution seems to be the easiest one to always show a loop button without using the play queue activity or the media notification (currently on Android 12 and below only) before the player is rewritten with a new UI and UX in mind.
- Fixes #6914
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR …
=> Show play queue button in main player when there is one stream

app/src/main/res/values/settings_keys.xml
Fix Language Selector Bug introduced by #10250 , by placing Uchinaguchi Language correctly in language selector settings.
Fixes:
Language Selector Bug
Description:
In App language Content Settings, when I choose Punjabi, app language actually changes to Polish after restart (that means language picker picking up the lower placed language instead). App shows selected language Punjabi, even though app is now in Polish language.
Try changing any language after ~~Italian~~ Japanese in language selector settings, bug will be noticeable except last few languages.
Tested on:
Device: Samsung Galaxy A22 5G
OS: Android 13 OneUI 5.0
App Version: 0.25.2
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to …
=> Fix language Picker Selecting Wrong Languages

app/build.gradle, build.gradle
- Get rid of outdated TODO
- Update Google AutoService 1.0.1 -> 1.1.1 ([changelog](https://github.com/google/auto/releases))
- ~~Update ViewPager2 1.1.0-beta01 -> 1.1.0-beta02 ([changelog](https://developer.android.com/jetpack/androidx/releases/viewpager2#1.1.0-beta02))~~
- Specifying Kotlin JDK8 is no longer needed: https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target
- Update Kotlin 1.8.21 -> 1.8.22 ([changelog](https://github.com/JetBrains/kotlin/releases/tag/v1.8.22))
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki …
=> Update miscellaneous libraries

app/build.gradle, app/src/main/java/org/schabi/newpipe/streams/io/StoredDirectoryHelper.java, app/src/main/java/org/schabi/newpipe/streams/io/StoredFileHelper.java
- Switch to the `desugar_jdk_libs_nio` configuration (more information on it can be found [here](https://developer.android.com/studio/write/java11-nio-support-table)).
- Use the Java 7 NIO API to improve the download helper classes. The new API offers [improved functionality](https://docs.oracle.com/javase/tutorial/essential/io/legacy.html) compared to the old `File` API, including lazy file loading on Android 8.0 and later, and more informative exceptions if something goes wrong. It should be possible to replace the `SharpStream` interface with [`SeekableByteChannel`](https://developer.android.com/reference/java/nio/channels/SeekableByteChannel) in a future PR with this change.
- The app size is increased by 33 KB with this change.
The APK can be found by going to the "Checks" tab below …
=> Improve the download helpers using the Java 7 NIO API.

app/src/main/java/org/schabi/newpipe/RouterActivity.java, app/src/main/java/org/schabi/newpipe/download/LoadingDialog.java, app/src/main/res/layout/download_loading_dialog.xml, app/src/main/res/values/strings.xml
- Added a new Dialog box which will be displayed between when a download is initiated (by sharing a youtube video with the newPipe App) and DownloadDialog is shown.
- Before:
[Screen_recording_20230910_235412.webm](https://github.com/TeamNewPipe/NewPipe/assets/47221639/8bd6df32-5b1f-4c07-93c6-5c6bd1d64f76)
- After:
[Screen_recording_20230910_234930.webm](https://github.com/TeamNewPipe/NewPipe/assets/47221639/fad0c1f7-d862-4d41-8506-63cffaa62a00)
- Fixes https://github.com/TeamNewPipe/NewPipe/issues/10378
Preventing user from dropping out of the download flow while waiting for DownloadDialog to appear.
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the …
=> Improved downloading experience

app/src/androidTest/java/org/schabi/newpipe/util/StreamItemAdapterTest.kt, app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/util/AudioTrackAdapter.java, app/src/main/java/org/schabi/newpipe/util/SecondaryStreamHelper.java, app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
- Rertrieve `MediaFormat`s for streams in case the extractor was not able to get them. Sometimes the MediaFormat can be retrieved from the HTTP response header that is fetched when getting the stream size. 
- The dialog now also displays "Unknown Quality" if the quality is unknown. Previously, the media format name was displayed as title and as quality info.
- Some code improvements simplifying castings by directly casting in if-conditions using `instanceof`
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td> 
</td>
<td> <img src="https://github.com/TeamNewPipe/NewPipe/assets/17365767/61e663d8-9d50-4e15-9f7b-fb9f483a3eb7"/> </td>
</tr>
</tbody>
</table>
- Fixes #10153 
TeamNewPipe/NewPipeExtractor#1074
The APK can be found by going to the "Checks" tab …
=> Fix downloads of streams with missing MediaFormat

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/player/gesture/MainPlayerGestureListener.kt, app/src/main/java/org/schabi/newpipe/player/gesture/PopupPlayerGestureListener.kt
- Replace 'MathUtils.clamp' with Kotlin 'coerceIn' where possible
- Also utilize the isGone extension function
=> Replace MathUtils.clamp with Kotlin coerceIn

app/build.gradle
- Update Google Material library 1.6.1 -> 1.9.0 ([changelog](https://github.com/material-components/material-components-android/releases)) (as always, release APK bloats by 193 KB, lol)
Things to notice in this update for the rewrite:
- New [Material Search Bar + Search View component](https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md): we could probably replace our custom search bar with this. Could save hundreds of lines of code, potentially.
- Has basically the same features, like the suggestion list and the menu items (like the 'x' for clearing/closing and the hamburger where the filters can be put).
- I couldn't find anything regarding displaying a "history" for searching, but I don't think this'll be a problem because I think we …
=> Update Google Material library

app/src/main/java/org/schabi/newpipe/streams/io/StoredDirectoryHelper.java, build.gradle
- Bump AGP to 8.1.1.
- Switch to [`Files.createDirectories()`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createDirectories-java.nio.file.Path-java.nio.file.attribute.FileAttribute...-), as [the issue](https://issuetracker.google.com/issues/282544786) affecting it has been fixed in AGP 8.1.
Follow up on  #10248
- Fixes #
=> Bump AGP to 8.1.1

app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java, app/src/main/java/org/schabi/newpipe/player/playqueue/SinglePlayQueue.java, app/src/main/java/us/shandian/giga/get/DownloadInitializer.java, app/src/main/java/us/shandian/giga/io/CircularFileWriter.java, app/src/main/java/us/shandian/giga/service/DownloadManager.java
- [Add comments and annotations](https://github.com/TeamNewPipe/NewPipe/commit/748c2babe9c34e533ed7fe97693d284f5d752fd1)
- [Reorder the modifiers to comply with the Java Language Specification.](https://github.com/TeamNewPipe/NewPipe/commit/8bf2d996ea681271447e115cd3d535358e453e0c)
- [Remove useless override](https://github.com/TeamNewPipe/NewPipe/commit/0acc3532c9cc29ca8b38375a65d878c095f7a376)
=> Improve codequality

app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java, app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java, app/src/main/res/layout-land/activity_player_queue_control.xml, app/src/main/res/layout/fragment_video_detail.xml, app/src/main/res/layout/play_queue_item.xml, app/src/main/res/layout/player.xml, app/src/main/res/layout/player_popup_close_overlay.xml, app/src/main/res/values/strings.xml
Add content descriptions for most player actions.
- Fixes #4303
- Fixes #10196 
Download the APK via this URL: https://github.com/TeamNewPipe/NewPipe/suites/13997135622/artifacts/780985251
This downloads a zip file (`app.zip`) which contains the debug APK of this PR.
=> Improved accessibility of player interfaces

.github/changed-lines-count-labeler.yml, .github/workflows/pr-labeler.yml
Add a workflow to label PRs based on the number of changed lines. This should help reviewers to determine which PRs to review.
Current configuration:
- small: < 50 changed lines
- medium: 50 - 249 changed lines
- large: > 250 changed lines
I was thinking about adding a two more categories for 250 - 500 and > 500 changed lines. Wdyt?
For a live demo, see https://github.com/TobiGr/NewPipe/pull/12, https://github.com/TobiGr/NewPipe/pull/13, https://github.com/TobiGr/NewPipe/pull/14
=> Add workflow "PR size labeler" to label PRs based on the number of changed lines

app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java, app/src/main/java/org/schabi/newpipe/util/ListHelper.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml
- When "Show higher resolution" option is enabled,  add 1440p and 2160p option to "Default resolution", "Default popup resolution" and "Limit resolution when using mobile data"
- switch to "Best resolution" and "No limit" when "Show higher resolution" is disabled and 1440p or 2160p is iselected
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/70268484/228861656-1da80cdc-a1c7-42e6-9757-2777b5d331ff.jpg" width="200px" alt="Before"/></td>
<td><img src="https://user-images.githubusercontent.com/70268484/228861708-f2f5879e-ac10-4f11-8351-a6b49ab980ad.jpg" width="200px" alt="After"/></td>
</tr>
</table>
- Fixes #2941
=> Include a high-resolution option in the default resolution settings.

.github/workflows/pr-labeler.yml
The write permission for the workflow was missing. From [the docs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs):
> Work with pull requests. For example, pull-requests: write permits an action to add a label to a pull request. For more information, see "[Permissions required for GitHub Apps](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests)."
The permissions on my fork are different. I fixed that to prevent such issues in the future.
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a …
=> Add write permission to PR labeler workflow

.github/workflows/pr-labeler.yml
For some reason the workflow in #10447 succeeded, but it fails on other PRs in the repo....
=> Add content: read permission to PR size labeler workflow

.github/workflows/pr-labeler.yml
Although the permission to modify PRs is granted to the entire workflow, the job still reports that it does not the permission to do so:
```
GITHUB_TOKEN Permissions
Contents: read
Metadata: read
PullRequests: read
```
This adds the permission to the job directly.
=> Fix PR labeler permissions

README.md, doc/README.asm.md, doc/README.de.md, doc/README.es.md, doc/README.fr.md, doc/README.hi.md, doc/README.it.md, doc/README.ja.md, doc/README.ko.md, doc/README.pa.md, doc/README.pl.md, doc/README.pt_BR.md, doc/README.ro.md, doc/README.ru.md, doc/README.ryu.md, doc/README.so.md, doc/README.sr.md, doc/README.tr.md, doc/README.zh_TW.md
Added translation of the README into Serbian.
=> Create Serbian README

app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
The reason for this issue is an inconsistency between user interaction and database commit order.
delete - commit (delete) - add - commit (add)
delete - add - commit (add, commit immediately) - commit (delete, commit after ~10s due to the debouncedSaveSignal)
Removes all debounced commit strategies. Sequential consistency is guaranteed by database transactions.
But I don't know why the delete operation uses the deferred commit strategy. BTW, I realize PR #8221 could have many conflicts with this solution. So I took a conservative approach to fix it.
Concurrent operations on the playlist database occur if and only if the user opens both LocalPlaylistFragment and VideoDetailFragment as described in the related issue. So I force all delete operations to be committed to the database before …
=> Fix inconsistency between user interaction and database commit order when re-adding videos to the playlist

app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java
Fix NullPointerException caused by nullable thumbnail URL String being parsed by URI.parse(). This regression was introduced in #10062 and reported in https://github.com/TeamNewPipe/NewPipe/issues/10471#issuecomment-1750226713. It occurred when disabling thumbnails and loading a stream. 
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>
```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | …
```
=> Fix crash with disabled thumbnails when trying to play a stream

app/src/main/java/org/schabi/newpipe/util/ListHelper.java
This PR removes OPUS HLS streams from playable streams. This format is not supported by ExoPlayer when returned as HLS streams, so we can't play streams using this format and this delivery method.
It also improves the Javadoc of `ListHelper.getPlayableStreams`.
- Fixes #9227
=> Remove OPUS HLS streams from playable streams

app/src/main/java/org/schabi/newpipe/player/PlayerService.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationPlayerUi.java
This PR restores the player service start handling before player UI separation, shipped with 0.24.0. This handling avoided crashes about the service service not starting in the foreground, in time or not at all (so crashes for which their exception contained `Context.startForegroundService() did not then call Service.startForeground()`). See https://github.com/TeamNewPipe/NewPipe/issues/9358#issuecomment-1722546621 for more details.
This PR also adds some player nullability checks, and the player service is now stopped when it has been started from a media button and there is nothing to play, which should avoid empty player notifications with the previous behavior.
A proper and better player code and architecture is required in order to solve this player service issue in the good way, …
=> Restore player service start handling before player UI separation and fix some issues in this service

app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
This PR fixes a crash when building the play queue audio track menu if the player is null.
It makes sure that the player is not null, by using `Optional`s on the player itself instead of its methods returning `Optional`s.
If the player is null, the play queue audio track menu will now be hidden instead of crashing the app.
- Fixes #10339, reported again on Reddit recently: https://www.reddit.com/r/NewPipe/comments/17b0vre/please_help_make_this_crash_stop_galaxy_s21/
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki …
=> Fix crash when building the play queue audio track menu if the player is null

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
This PR fixes a crash when setting the masking of the new feed items button if the feed fragment context is null (see the Javadoc of [`Fragment.getContext()`](https://developer.android.com/reference/androidx/fragment/app/Fragment?hl=en#getContext())).
It makes sure that the context is not null before calling `DeviceUtils.hasAnimationsAnimatorDurationEnabled`.
If the context is null, the button will now not be hidden automatically instead of crashing the app.
- Fixes #9031, reported again on Reddit recently: https://www.reddit.com/r/NewPipe/comments/17u8zc9/this_app_keeps_crashing_every_time_i_watch_a/
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the …
=> Fix crash when setting the masking of the new feed items button if the context is null

app/src/main/java/org/schabi/newpipe/util/FilenameUtils.java
- fixes crash by quoting replacement char in filename util
- Fixes #10346
=> Quote filename replacement characters to fix crashes when downloading streams with special characters

app/src/main/java/org/schabi/newpipe/NewVersionWorker.kt
The NewPipe API endpoint providing info on the current app version has been updated int TeamNewPipe/web-api#17
I restored backwards compatibility to enabled current versions to notify about new versions in https://github.com/TeamNewPipe/web-api/commit/0bccef026ae9c3e9ccef1bb89da3ec8a3ea61cde. Backwards compatibility will be removed after some time.
=> Update new version check to match new API structure

app/src/androidTest/java/org/schabi/newpipe/database/FeedDAOTest.kt, app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt
After fetching new streams for the feed, "old" streams are removed from the database. However, if a channel contains only streams which are considered old, they are also removed. Thus they are shown as new when refreshing the feed the next time. For a more detailed explanation, [read this comment](https://github.com/TeamNewPipe/NewPipe/issues/10237#issuecomment-1750176520) in the original issue.
- Fixes #10237
- Fixes #10553
=> Fix notifying about old "new" streams

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
The fix just involves removing some really outdated code (6 years ago) added in [33e29be](https://github.com/TeamNewPipe/NewPipe/commit/33e29be7db2e4a6fcd23e411081c871bf3c4b5c3#diff-38bd2cf1b92659b499c08e1cf6ac9ef384c7e13381b906f2f98c57cbb758756dR778) ([blame](https://github.com/TeamNewPipe/NewPipe/blame/9318bb530619898c1e1f3f8a8c866f3d2e35ab0c/app/src/main/java/org/schabi/newpipe/detail/VideoItemDetailActivity.java#L778)). What that code did was setting the 'buddy' image to the uploader avatar as a placeholder, and then setting the actual image if it existed and after it had loaded. That code remained there up until now, but now it doesn't make sense anymore, since Picasso already takes care of setting placeholders.
The problem is, starting from #10066 the actual uploader image is set …
=> Fix channel avatar not loading correctly sometimes

app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/util/ListHelper.java, app/src/main/java/org/schabi/newpipe/util/SecondaryStreamHelper.java
Instead of searching for the first audio stream compatible with a media format, this change makes the method to get audio-only streams for video-only streams in the downloader (`SecondaryStreamHelper.getAudioStreamFor`) use some methods used to get available audio streams for playback (`isLimitingDataUsage`, `getAudioFormatComparator` and `getAudioIndexByHighestRank` of `ListHelper` class).
This means that the audio stream quality selection in the downloader will now follow the setting of a default video resolution on mobile data: if a resolution is set, the lowest audio stream should be selected, otherwise the highest audio stream should be selected. This behavior should be already applied for playback.
- Fixes #8490
The APK can be found by going to the "Checks" tab below the title. On …
=> Improve audio stream selection for video-only streams in the downloader

app/src/main/java/org/schabi/newpipe/BaseFragment.java
In NewPipe the `MainFragment` is entitled to handling the fragment backstack and the collapsible player fragment. Therefore any action involving opening new fragments (e.g. when clicking on videos/playlists/...) needs to be performed on the `MainFragment`'s fragment manager. The previous implementation chose the fragment manager assuming that every fragment is at most singly nested (i.e. where the parent is directly `MainFragment`). However the new *main* page channel tab contains doubly-nested fragments (i.e. the channel tabs), so the previous method was choosing the wrong fragment manager, making the app crash. This PR fixes the issue by properly finding the root fragment.
- https://github.com/TeamNewPipe/NewPipe/issues/10471#issuecomment-1807545849
The APK can be found by going to the …
=> Fix crashes due to wrong root fragment manager

app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
A lot of time ago [a 1700-changes commit](https://github.com/TeamNewPipe/NewPipe/blame/6675d3e2cd4263b7c09f50322b27885fb1b7b5bd/app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java#L110) decided that all main page tabs would be fetched at once and stay in memory. Before customizable tabs were a feature, this made sense, but now users can add as many tabs as they want. Therefore if a user had a lot of tabs, they would all be in memory at once, making the application lag, as observed in https://github.com/TeamNewPipe/NewPipe/issues/10471#issuecomment-1749842668. This PR fixes the problem by just removing the line that tells the view pager to keep all tabs loaded at the same time, and instead rely on the default behaviour of only keeping in memory the current tab and the adjacent …
=> Fix application lagging with many main page tabs

app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt, app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt, app/src/main/java/org/schabi/newpipe/local/feed/service/FeedUpdateInfo.kt, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
This PR reduces the memory footprint of `FeedUpdateInfo` objects. [They used to contain](https://github.com/TeamNewPipe/NewPipe/blob/c076a0f77127fe6a875461dc879605405ada5ede/app/src/main/java/org/schabi/newpipe/local/feed/service/FeedUpdateInfo.kt#L14) an `originalInfo: Info` field, which in turn contained the raw json of channel tabs embedded within `ReadyChannelTabExtractor`s. This ended up using ~800KB per `FeedUpdateInfo` instance, which is not really that bad. However those objects might stay around for a while and accumulate (up to [BUFFER_COUNT_BEFORE_INSERT = 20](https://github.com/TeamNewPipe/NewPipe/blob/57eaa1bbe1c837531d5bcfe6de41e130e61b97c3/app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt#L337) at the moment), so in order not to fill up the memory …
=> Fix OutOfMemory when fetching feed

app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelTabFragment.java
This PR contains a really hacky workaround, that avoids storing useless data in the `ChannelTabFragment` state. `ChannelTabFragment` uses the corresponding tab link handler to be able to fetch data, since unlike other things in the extractor, channel tabs are not supposed to be obtained from a url (e.g. provided by the user), but rather always from a channel page internally in the app.
The problem is, `ReadyChannelTabListLinkHandler` might contain raw JSON data that uses a lot of memory (e.g. ~800KB for YouTube). While 800KB doesn't seem much, if you combine just a couple of channel tab fragments you easily go over the 1MB save&restore transaction limit, and get `TransactionTooLargeException`s.
What this PR does is to discard the `ReadyChannelTabListLinkHandler` after the first time the …
=> Fix transaction too large in channel tab fragments

app/build.gradle, app/src/main/java/androidx/fragment/app/FragmentStatePagerAdapterMenuWorkaround.java, app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt, app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt, app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java, app/src/main/java/org/schabi/newpipe/ktx/Bundle.kt, app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationWorker.kt, app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsExportService.java, app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java, app/src/main/java/org/schabi/newpipe/player/gesture/MainPlayerGestureListener.kt, app/src/main/java/org/schabi/newpipe/player/gesture/PopupPlayerGestureListener.kt, app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java, app/src/main/java/org/schabi/newpipe/util/StateSaver.java, app/src/main/java/org/schabi/newpipe/views/player/CircleClipTapView.kt, app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
- Update AppCompat 1.5.1 -> 1.6.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat))
- Update Core 1.10.0 -> 1.12.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/core#1.12.0))
- Update Fragment 1.4.1 -> 1.6.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/fragment#1.6.1))
- Update Lifecycle 2.5.1 -> 2.6.2 ([changelog](https://developer.android.com/jetpack/androidx/releases/lifecycle))
- Update Preference 1.2.0 -> 1.2.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/preference#1.2.1))
- Update RecyclerView 1.2.1 -> 1.3.2 ([changelog](https://developer.android.com/jetpack/androidx/releases/recyclerview))
- Update ViewPager2 1.1.0-beta1 -> 1.1.0-beta2 …
=> Update some AndroidX libraries and compileSdk to 34

app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/info_list/holder/CommentInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/util/text/TextEllipsizer.java, app/src/main/res/layout/playlist_header.xml, app/src/main/res/values/strings.xml
Added the playlist description to the `PlaylistFragment`.
Added new utility class `TextEllipsizer` that allows shortening and expanding text inside a TextView.
|---|---|
|  <img alt="playlist_description_before" src="https://github.com/TeamNewPipe/NewPipe/assets/17365767/bd2f3176-b427-4c80-9631-d3540c9eea21" width="400" /> |  <img src="https://github.com/TeamNewPipe/NewPipe/assets/17365767/3a2676b5-b32a-448d-a36a-9b4e24935aa1" width="400" /> |
https://github.com/TeamNewPipe/NewPipe/assets/17365767/a4aa2a10-39fa-47c3-9029-193624d9a12b
Closes #3885
TeamNewPipe/NewPipeExtractor#1061
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug …
=> Add playlist description to playlist fragment

app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java, app/src/main/java/org/schabi/newpipe/player/mediasession/SessionConnectorActionProvider.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationActionData.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationConstants.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java, app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java, app/src/main/java/org/schabi/newpipe/settings/custom/NotificationSlot.java, app/src/main/res/layout/settings_notification.xml, app/src/main/res/values/strings.xml
- Supersedes https://github.com/TeamNewPipe/NewPipe/pull/10580 and https://github.com/TeamNewPipe/NewPipe/pull/10567 because the **hacky workaround** to allow customizing 4 actions [turned out to cause problems](https://github.com/TeamNewPipe/NewPipe/pull/10580#discussion_r1435593734)
- Set notification actions only via `MediaSessionConnector` on Android 13+, and only via the notification builder on Android 12-, to save battery
- Notification actions in `MediaSessionPlayerUi` are only updated when something really changes, to avoid `setCustomActionProviders()` calling `invalidateMediaSessionPlaybackState()` more times as needed, which I figure might be costly
- Adapts the player notification settings page to allow customizing only two actions on Android 13+. The preference keys for the …
=> [Android 13+] Restore support of custom notification actions

.github/workflows/ci.yml, .github/workflows/image-minimizer.yml
=> Update GitHub action dependencies in workflows

app/build.gradle, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java, app/src/main/java/org/schabi/newpipe/util/InfoCache.java
It didn't really make sense to consider two cache keys as equal based on the type of items contained within that list. The proper way is to distinguish the actual kind of `Info` being saved/retrieved, so I created a new `enum` independent from the extractor's one
This PR includes the extractor from https://github.com/TeamNewPipe/NewPipeExtractor/pull/1148 to showcase that the problem is fixed, since there MediaCCC channels and channel tabs have the same url.
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-fo …
=> Calculate cache key based on info type instead of item type

app/src/main/java/org/schabi/newpipe/util/ListHelper.java
`AudioStream.getAudioTrackType()` is correctly marked as being `@Nullable` [in the extractor](https://github.com/TeamNewPipe/NewPipeExtractor/blob/fc67d49f59b7709ac1e61507167b0732c63a9403/extractor/src/main/java/org/schabi/newpipe/extractor/stream/AudioStream.java#L510). However, the nullability was not considered when comparing audio streams in `getAudioTrackNameComparator`. I fixed this and checked neighboring `get*Comparator` functions, but those were already correct.
To check that this is in fact working, use this video, as suggested in the issue: https://www.youtube.com/watch?v=mKdjycj-7eE
- Fixes #10883
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains …
=> Fix not considering nullability when comparing getAudioTrackType

app/src/main/res/layout-land/list_stream_card_item.xml
- changed the landscape layout of list card item
- now it is the landscape layout of list item
- Before:
- After:
- Fixes #9924
=> Changed the landscape layout of list card item

app/schemas/org.schabi.newpipe.database.AppDatabase/8.json, app/src/androidTest/java/org/schabi/newpipe/database/DatabaseMigrationTest.kt, app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java, app/src/main/java/org/schabi/newpipe/database/AppDatabase.java, app/src/main/java/org/schabi/newpipe/database/Migrations.java, app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
- Strip leading and trailing white spaces of search string before passing it into ```suggestionPublisher``` ~~after typing or pasting text~~
- Trim the search string of the search bar when the user presses search
- **Add new database migration to remove duplicate records in search history**
- Add a test for the database migration
- Before:
https://user-images.githubusercontent.com/15650457/163706467-497441a9-5213-456a-8255-64575c51acb8.mp4
- After:
https://user-images.githubusercontent.com/15650457/163706473-f08b8102-ea62-4b96-ba08-82e47a1bf645.mp4
- Fixes #8012
[Debug APK](https://github.com/TeamNewPipe/NewPipe/suites/6149649612/artifacts/214883611)
=> Trim search string and remove duplicate records from the database

app/src/main/java/org/schabi/newpipe/fragments/detail/BaseDescriptionFragment.java, app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelAboutFragment.java, app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
`streamInfo` and `channelInfo` have to be initialized, since the only way to construct the class it to pass them. So we can remove the null check boilerplate and make some of the accessors `NonNull`.
=> BaseDescriptionFragment: Assert member is initialized

app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/util/Localization.java
earlier only overall amount of videos was shown in playlist (in both searched online playlist and local playlist). Now overall duration is shown there too - as formatted by existing Localization.concatenateStrings() and Localization.getDurationString().
earlier only overall amount of videos was shown. Now overall duration is shown there too - as formatted by existing Localization.concatenateStrings() and Localization.getDurationString().
see https://github.com/TeamNewPipe/NewPipe/pull/6045/checks (artefacts) for the uptodate APK as soon as built by github - tested OK on Xiaomi Mi 9 SE
=> show overall duration of videos in playlist

app/src/main/res/xml/appearance_settings.xml, app/src/main/res/xml/notifications_settings.xml
Moved player notification setting to notification section
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/76740999/208883449-8ae038c2-409c-4939-a85d-31479dd6ee47.mp4
</td>
<td>
https://user-images.githubusercontent.com/76740999/208883465-53aa48a4-1fa9-4bd7-b0a8-451181d3a8cf.mp4
</td>
</tr>
</table>
- Fixes #8232
=> Moved player notification setting to notification section

app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentRepliesFragment.java
A `@State` annotation was missing from `CommentRepliesFragment.commentsInfoItem`, causing the value to be lost on configuration changes. This caused the NPE described [here](https://github.com/TeamNewPipe/NewPipe/issues/10930#issuecomment-2045910769). This PR just adds the `@State`. I tested and while I could reproduce consistently before, after this PR I can't reproduce the problem anymore.
- Fixes&nbsp;https://github.com/TeamNewPipe/NewPipe/issues/10930#issuecomment-2045910769
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki …
=> Fix not saving comment replies state on config change

app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionEntity.java, app/src/main/java/org/schabi/newpipe/local/feed/service/FeedUpdateInfo.kt, app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
This PR fixes a NPE by simply making sure avatarUrl is `@Nullable` everywhere, and is also treated as so.
I tested and before this fix I could reproduce the crash in 
- Fixes #10863
- Fixes&nbsp;https://github.com/TeamNewPipe/NewPipe/issues/10930#issuecomment-2042808053
=> Fix NPE if avatarUrl is null when reloading feed

app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java, app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java, app/src/main/java/org/schabi/newpipe/util/Localization.java
…and avoid the new prefix for single videos
- improvement for https://github.com/TeamNewPipe/NewPipe/pull/6045 - now a prefix is shown infront of the duration so that the meaning is more intuitive for the user
<table>
<tr>
<th>Before: </th>
<th> After: </th>
</tr>
<tr>
<th><img src="https://github.com/TeamNewPipe/NewPipe/assets/6170902/ea28487a-c2fb-4c87-be45-3d1058a9735c" width="300"></th>
<th> <img src="https://github.com/TeamNewPipe/NewPipe/assets/6170902/12d9333f-03c2-444b-9559-b5d106f8dc6d" width="300"> </th>
</tr>
</table>
- Fixes # https://github.com/TeamNewPipe/NewPipe/pull/6045#issuecomment-2035434620
- https://github.com/TeamNewPipe/NewPipe/pull/6045
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and …
=> Add an intuitive prefix for the duration of lists in the UI

app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java, app/src/main/java/org/schabi/newpipe/streams/io/StoredDirectoryHelper.java, app/src/main/java/us/shandian/giga/util/Utility.java
The previous code for obtaining free storage space was broken:
- It had some logical flaws in the checks being performed (e.g. why an `SDK_INT` check was before the function call, while another was inside it?)
- It didn't work at all for sdcard or other storages that don't have an UUID (don't ask me why the sdcard on the emulator did not have an UUID, who knows).
- It crashed with non-SAF files, see https://github.com/TeamNewPipe/NewPipe/issues/10930#issuecomment-2070180960
This PR checks for free storage according to https://stackoverflow.com/q/31171838. It uses `Os.statvfs(filePath)` on non-SAF files, and `Os.fstatvfs(fileDescriptor)` on SAF files. Note that for SAF files a file descriptor needs to be opened in read mode, but I checked and this does not seem to create a file, and works …
=> Fix free storage space check for all APIs

.github/workflows/ci.yml
- The git workflow fails when running android tests.
- The workflow is trying to launch an x86 emulator on aarch-64 (macos-latest) host.
- The macos-latest system seem to be used originally as it supports hardware acceleration.
- This is no longer recomended, and ubuntu-latest host can handle the same and be faster than macos-latest.
Doc: https://github.com/marketplace/actions/android-emulator-runner#running-hardware-accelerated-emulators-on-linux-runners
- Before: ![Screenshot_20240429_020808](https://github.com/TeamNewPipe/NewPipe/assets/87667048/e5dcce32-1bd3-4787-b4a4-99c9986059c4)
- After: ![Screenshot_20240429_022005](https://github.com/TeamNewPipe/NewPipe/assets/87667048/abbb7e0a-a04c-4424-8f52-63dc6a8924fb)
- Fixes #11015
The APK can be found by going to the "Checks" tab below the …
=> Fix github worklow for Android tests

app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt, app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java, app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationActionData.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationConstants.java, app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java, gradle.properties
- Replaces #10077.
- Switch to [non-transitive R classes](https://blog.blundellapps.co.uk/speed-up-your-build-non-transitive-r-files/), which became the default starting in Android Gradle plugin 8.0. This fixes build issues with the CI pipeline and helps speed up the build process.
- These were the cases where `R.id.*` did not exist anymore and had to be replaced by the fully-qualified path.
- `R.id.content` -> `android.R.id.content` to find the root view of an activity. I tested this manually and it works.
- `R.attr.colorSecondary` -> `android.R.attr.windowBackground` as the bottom toolbar background color. I don't know why it was `colorSecondary` before, but `windowBackground` yields the same color as before, I tested on API 33 and API 22 on all themes. Moreover `windowBackground` is …
=> Migrate to non-transitive R classes

.github/CONTRIBUTING.md
As mentioned in #11199, removes the restriction on adding kt code .
=> Remove kotlin code restriction from contribution guidelines

app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java
This PR simply fixes the NullPointerException reported in #11029 by adding a null check and by adding `@Nullable` to the involved variables.
Note that the crash happened because in [Player::destroyPlayer()](https://github.com/TeamNewPipe/NewPipe/blob/0a8f28b1c6f804de22a1ee81fdc284e7725ef8cc/app/src/main/java/org/schabi/newpipe/player/Player.java#L566), first `PlayerUi::destroyPlayer` is called on every UI, and afterwards `simpleExoPlayer.removeListener(this)` causes a call to [onEvents()](https://github.com/TeamNewPipe/NewPipe/blob/0a8f28b1c6f804de22a1ee81fdc284e7725ef8cc/app/src/main/java/org/schabi/newpipe/player/Player.java#L1262) which in turn [calls](https://github.com/TeamNewPipe/NewPipe/blob/0a8f28b1c6f804de22a1ee81fdc284e7725ef8cc/app/src/main/java/org/schabi/newpipe/player/Player. …
=> Fix crash in MediaSessionPlayerUi while destroying player

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/schabi/newpipe/App.java, app/src/main/java/org/schabi/newpipe/AppModule.kt, app/src/main/java/org/schabi/newpipe/settings/DebugScreen.kt, app/src/main/java/org/schabi/newpipe/settings/SettingsScreen.kt, app/src/main/java/org/schabi/newpipe/settings/SettingsV2Activity.kt, app/src/main/java/org/schabi/newpipe/settings/viewmodel/SettingsViewModel.kt, app/src/main/java/org/schabi/newpipe/ui/SwitchPreference.kt, app/src/main/java/org/schabi/newpipe/ui/TextPreference.kt, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/res/values/settings_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/debug_settings.xml, build.gradle
Initial Work for Settings Page with Jetpack Compose
- Implemented a new settings page using Jetpack Compose.
- Added a new settings option to enable the redesigned settings page.
- This option allows for gradual integration and testing of the new
settings page, minimizing disruptions to current functionality.
Plan for Settings Items:
- Jetpack Compose does not have a direct equivalent to the
Preference/settings library.
- We could consider using third-party libraries that offer preference
items as composables.
- However, these libraries may be incomplete or lack active development.
- Given our specific needs for only a subset of preference types,
creating custom composables would be beneficial.
- This approach allows for fine-tuning the components to our specific
use case.
Next Steps:
- …
=> Settings redesign debug page

app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
When user has not yet adjusted manually the playlists order the lists in "Bookmarked Playlists" and "add to playlist" dialog don't have the same order. Now in this phase both lists are sorted using case insensitive order. While after manual sorting from user both list keep the same order.  
- Before:
- After:
- Fixes #10993
=> Fixed playlist order

app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
- Holding an item in history and clicking "Start playing in the background" would now only add the current item in the play queue, instead of the full history which is usually massive.
N/A
- Fixes # https://github.com/TeamNewPipe/NewPipe/issues/5586
- [ x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
=> Only start playing single item in history screen

app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
Updates the user agent used by the downloader to retrieve files to a current version
See https://github.com/TeamNewPipe/NewPipeExtractor/pull/1192
=> Update user agent to Firefox ESR 128

app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java, app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
- Update NewPipe to handle the changes in https://github.com/TeamNewPipe/NewPipeExtractor/pull/1196
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/1196
=> Apply URL encode/decode changes

app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt
This PR introduces a delay between every `BATCH_SIZE=50` channel extractions while loading the feed, to avoid YouTube rate limits and hopefully solve #11661. The delay varies in range `DELAY_BETWEEN_BATCHES_MILLIS=(6000..12000)` (on average 8s). I also lowered `PARALLEL_EXTRACTIONS` from 6 to 3, as suggested by AudricV. The value of `BATCH_SIZE` was chosen because people reported problems starting from ~100 subscriptions, so 50 should be safe. 
In this video `BATCH_SIZE=10` and `DELAY_BETWEEN_BATCHES_MILLIS=(2000..8000)` for demonstration purposes.
https://github.com/user-attachments/assets/b6f8449b-c6c6-4b6c-85bc-2c1f3d91d3e5
- Workaround for / fixes https://github.com/TeamNewPipe/NewPipe/issues/11661
The APK can be found by going to the "Checks" tab below the title. On the left pane, …
=> Throttle feed loading to avoid YouTube rate limits

app/src/main/java/org/schabi/newpipe/util/ListHelper.java, app/src/main/java/org/schabi/newpipe/util/Localization.java, app/src/main/res/values/strings.xml
This PR adds support for secondary audio track type added in TeamNewPipe/NewPipeExtractor#1237.
These tracks have been given an higher priority than dubbed tracks when non-descriptive tracks are preferred, and a lower one than dubbed tracks when descriptive tracks are preferred. I don't know if that the right way to do this so the order should reviewed carefully.
Test videos are available in the extractor PR linked.
No issue found.
- TeamNewPipe/NewPipeExtractor#1237
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki …
=> Add support for secondary audio track type

app/build.gradle, app/check-dependencies.gradle, gradle/libs.versions.toml
After migrating dependencies to version catalogs in #11684, it would be nice to enforce the dependencies to be sorted. I could not find any widely used plugins for this purpose so I wrote a gradle script. 
- Fixes #10927 
=> Sort dependencies in `libs.versions.toml`

app/src/main/java/org/schabi/newpipe/settings/NotificationsSettingsFragment.kt
Since Android 13 media player notifications [are exempt](https://developer.android.com/develop/ui/views/notifications/notification-permission#exemptions-media-sessions) from the notification settings/permission, however NewPipe currently disables all preferences in the notification section preventing the user from entering the player notification page.
I have tested this on my device and neither the global notification toggle/permission, nor disabling the specific channel used for player notifications would hide it.
Since system settings don't affect the display of the player notification, this PR makes it so that only the new stream notification preferences are disabled, when notifications are blocked by the system.
(Both screenshots taken on Android 15 with notification permission …
=> Always allow changing player notification preferences on Android 13+

.github/workflows/build-release-apk.yml
This builds an unsigned APK based on the last commit on the master branch, in the hope to solve reproducibility issues (see #11754). See [here](https://github.com/Stypox/NewPipe/actions/runs/12096387804) a successful run.
=> Add build-release-apk workflow

.github/workflows/image-minimizer.js
It is legal to have multiple images on a single line in Markdown. The previous regex did not handle that correctly. This PR fixes the regex.
- (Not tracked)
```js
var exampleBody = "![image-1](https://x.githubusercontent.com/1/11111111111111111111111111111111.png) ![image-2](https://x.githubusercontent.com/2/22222222222222222222222222222222.png)";
await replaceAsync(exampleBody, REGEX_USER_CONTENT_IMAGE_LOOKUP, match => `<<${match}>>`);
// previous output (incorrect):
"<<![image-1](https://x.githubusercontent.com/1/11111111111111111111111111111111.png) ![image-2](https://x.githubusercontent.com/2/22222222222222222222222222222222.png)>>"
// output with the fix:
"<<![image-1](https://x.githubusercontent.com/1/11111111111111111111111111111111.png)>> …
```
=> Fix image-minimizer on lines containing multiple images

app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
- In the current implementation, there is nothing preventing the user from calculating the checksum of a file that was deleted from the file manager, even though it doesn't work.
- I added a condition to check if the file does exist, and if not deleting it from the list of downloaded medias as well as showing an error message to the user.
- Fixes #5038 
=> Fix the issue of getting the checksum of a removed file

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java, app/src/main/java/org/schabi/newpipe/player/PlayerService.java, app/src/main/java/org/schabi/newpipe/player/event/PlayerEventListener.java, app/src/main/java/org/schabi/newpipe/player/event/PlayerHolderLifecycleEventListener.java, app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceEventListener.java, app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceExtendedEventListener.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
This simplifies the PlayerHolder a bit.
- Before:
- After:
- Fixes #
- 
=> PlayerHolder refactor

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
While working on #11955 I realized that when `VideoDetailFragment` is first started, the video loading is initiated both by `VideoDetailFragment` and by the `NavigationHelper.openVideoDetailFragment()` function, leading to the stream info loading twice in the background. From the second time `openVideoDetailFragment()` is invoked, the `VideoDetailFragment` is already running in the background, and so its initial logic does not run.
To solve this bug I made it so that `NavigationHelper.openVideoDetailFragment()` first opens the `VideoDetailFragment` as if it were in collapsed bottom sheet state (i.e. with `url = null`, see how `VideoDetailFragment.wasCleared()` is called in `VideoDetailFragment.doInitialLoadLogic()`. I am not sure if this is just a hack or is the actual intended behavior, …
=> Fix loading StreamInfo twice on first VideoDetailFragment opening

app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
- Optimized the `execute` method to improve readability and resource management.
- Used `try-with-resources` to ensure automatic closing of the `Response` object.
- Simplified HTTP header management with a more concise approach.
- Introduced `Optional` to handle request bodies and responses, reducing null checks.
=> DownloaderImpl: Auto-close resources and simplify header setting

app/src/main/java/org/schabi/newpipe/MainActivity.java
The change
https://github.com/TeamNewPipe/NewPipe/commit/b9dd7078ad3ae2ac1c20969fdd8b97736026b7dc
accidentally moved the `return` into the `{}`, so the logic would fall
through to
```
if (fragmentManager.getBackStackEntryCount() == 1) {`
```
and close the app even though there are still items on the
`VideoFragmentDetail` stack.
To reproduce:
Start video, enqueue another video, then start a third video (which
adds one entry to the stack), and press `back` on the expanded video.
This should keep the player open and go back to the first 2-video
queue, but it actually closes the app before this fix.
=> MainActivity: Fix onBackPressed handling for open player

app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt
- It is possible for the stream uploader URL to be different from the channel URL, thus resulting in the notifications not being grouped by the channel. This change fixes that.
=> Fix stream notification grouping

app/build.gradle, app/proguard-rules.pro
This updates NewPipe Extractor to https://github.com/TeamNewPipe/NewPipeExtractor/commit/0b99100dbddeca2f27554620378f251afd66b30b.
I needed to add new Proguard rules to keep a few classes. The upgrade to Rhino 1.8.0 and the new dependency Rhino Engine 1.8.0 introduced in TeamNewPipe/NewPipeExtractor#1256 made this necessary. Otherwise `assembleRelease` would throw an error. I am unsure whether we could use stricter rules.
<details><summary>Build error</summary>
```
Missing class javax.script.AbstractScriptEngine (referenced from: void org.mozilla.javascript.engine.RhinoScriptEngine.<init>(org.mozilla.javascript.engine.RhinoScriptEngineFactory) and 1 other context)
Missing class javax.script.Bindings (referenced from: javax.script.Bindings …
```
=> Update NewPipe Extractor and add new proguard rules

app/src/main/java/org/schabi/newpipe/util/potoken/JavaScriptUtil.kt
If the challenge data array is of size one, the second element is accessed, leading to an `IndexOutOfBoundsException`. I assume, that this is a typo, as the [JS version](https://github.com/Stypox/NewPipe/blob/2b183a057651a79aa826a110e3eebf126befdd6c/app/src/main/assets/po_token.html#L100) did correctly access the first element.
=> [YouTube] Access first element if array size is one

app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java, app/src/main/res/layout/mission_item.xml, app/src/main/res/layout/mission_item_linear.xml
This patch shows the download date for downloaded videos.
=> Show download date of downloaded videos

app/build.gradle, app/src/main/java/org/schabi/newpipe/MainActivity.java, app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java, app/src/main/java/org/schabi/newpipe/util/Localization.java, app/src/main/java/org/schabi/newpipe/util/potoken/JavaScriptUtil.kt, app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java, app/src/main/res/layout/mission_item.xml, app/src/main/res/layout/mission_item_linear.xml, app/src/main/res/resources.properties, app/src/main/res/values/settings_keys.xml, app/src/main/res/xml/content_settings.xml, gradle/libs.versions.toml
- Merge latest dev changes to refactor
=> Merge dev to refactor

app/src/main/java/org/schabi/newpipe/info_list/holder/CommentInfoItemHolder.java, app/src/main/java/org/schabi/newpipe/util/Localization.java
-  Wrapped  uploader's username using BidiFormatter to fix direction issues when combining RTL usernames with timestamps  in comment headers.
- Before:
- After:
- Fixes #12141 
=> fix: support RTL usernames in comment header

README.md
Add badges in README for latest nightly builds for dev and refactor branches.
=> Add dev and refactor nightly build badges

app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt, app/src/main/java/org/schabi/newpipe/settings/SelectFeedGroupFragment.java, app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java, app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java, app/src/main/res/layout/select_feed_group_fragment.xml, app/src/main/res/layout/select_feed_group_item.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/schabi/newpipe/settings/tabs/TabsJsonHelperTest.java
Add FeedGroups as optional Tabs. With this change you can use the settings of  the main page content to add FeedGroups directly to the Main Page Tabs.
- New Fragment used in the Settings to choose the FeedGroup
- New TabClass FeedGroupTab
- Added Code for Selecting the Tab
- Added strings related to FeedGroupTab
- Added FeedGroupTab to UnitTest
New possibility:
[PR_AddingTabs_low.webm](https://github.com/user-attachments/assets/e75cdfa6-ae18-458f-9c5e-c7317aa5755d)
[PR_SavedTabs_low.webm](https://github.com/user-attachments/assets/05985dfc-d79f-4bff-b123-6a98e312fb0e)
- Fixes #3319  …
=> Feed group tab

app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
If no JSON MIME type is available on the android(old version), use "application/octet-stream" instead, which targets json files one puts on the old device.
Another solution could be to check for `Build.VERSION.SDK_INT < Build.VERSION_CODES.Q` instead of using the webkit MimeTypes
Since a file of type application/json can still be created locally(by exporting as such), the mime type for the file picker might need to be \*/\* to support both locally exported(as "application/json") and otherwise transferred .json files("application/octet-stream").
<table>
<tr>
<th>API28</th>
<th>API29</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/cd534f79-551f-4c60-917e-8881f6a9e67e" width="200px" alt="Before"/></td>
<td><img …
=> check if the JSON MimeType is supported

app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserImpl.kt, app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserPlaybackPreparer.kt
In the Android Auto PR #12044 we forgot to disable thumbnails on Android Auto when the user disabled them from settings. This PR fixes that.
<table>
<tr>
<th>With high quality images</th>
<th>Without images</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/b8ed5923-3893-47eb-9064-a5f974393729" width="400px" alt="Before"/></td>
<td><img src="https://github.com/user-attachments/assets/21e0028f-a972-4ad3-8def-083b727afa01" width="400px" alt="After"/></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/ca2f28ba-da80-40b0-98b1-a6306f6a6d90" width="400px" alt="Before"/></td>
<td><img src="https://github.com/user-attachments/assets/9cd7a6fc-5686-4297-82a1-e3811048996c" width="400px" alt="After"/></td>
</tr>
<tr>
<td><img …
=> Fix thumbnails appearing on Android Auto even if disabled

app/src/main/java/org/schabi/newpipe/settings/BackupRestoreSettingsFragment.java, app/src/main/java/org/schabi/newpipe/settings/export/BackupFileLocator.kt, app/src/main/java/org/schabi/newpipe/settings/export/ImportExportManager.kt, app/src/main/java/org/schabi/newpipe/util/ZipHelper.java, app/src/test/java/org/schabi/newpipe/settings/ImportAllCombinationsTest.kt, app/src/test/java/org/schabi/newpipe/settings/ImportExportManagerTest.kt
- Rewrite the zip import/export code to use [`Path`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html).
- Fix an issue with importing/exporting the database that occurred due to the database path being incorrect.
- Fixes #
=> Migrate zip import/export to use Path

app/src/main/java/org/schabi/newpipe/player/PlayerService.java, app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserImpl.kt, app/src/main/java/org/schabi/newpipe/player/mediabrowser/PackageValidator.kt
This PR resolves a security-related TODO from #12044: making sure only packages with the right permissions can access NewPipe's MediaBrowser through `onGetRoot()`. The `PackageValidator` file is taken from https://github.com/android/uamp/blob/329a21b63c247e9bd35f6858d4fc0e448fa38603/common/src/main/java/com/example/android/uamp/media/PackageValidator.kt, as suggested in the Android docs [here](https://developer.android.com/media/implement/surfaces/mobile#mediabrowserservice_implementation).
Furthermore, this PR fixes #12400, which was caused by an invalid media resumption notification being created by the system after closing the player. The notification was being created because the system was querying `onGetRoot()` to get information about resumption, and our code returned a …
=> Fix ghost notifications on Android 10; fix MediaBrowser exposed

app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java, app/src/main/res/values/strings.xml
The only hint (haha) which service one is searching in is currently the color of the background. This is super confusing, yesterday a friend tried to search for a video on youtube and the app was set to Bandcamp, and they were super confused why nothing turned up.
So let’s put the name of the service in the hint!
The `updateService()` thing is a little confused, but I didn’t want to refactor to improve the logic. It’s not doing anything computationally intensive anyway.
For PeerTube, the sidebar calls it FramaTube but the service name is PeerTube, I’m not sure why that is the case. Looks like the string depends on the name of the instance? Hm, can be improved later I think.
after:
https://github.com/user-attachments/assets/4e88d826-feb2-4cd1-84e6-4dcf203cd38c
The APK can be found by going …
=> SearchFragment: show service name in search hint

README.md, doc/README.ar.md, doc/README.asm.md, doc/README.de.md, doc/README.es.md, doc/README.fr.md, doc/README.hi.md, doc/README.it.md, doc/README.ja.md, doc/README.ko.md, doc/README.pa.md, doc/README.pl.md, doc/README.pt_BR.md, doc/README.ro.md, doc/README.ru.md, doc/README.ryu.md, doc/README.so.md, doc/README.sr.md, doc/README.tr.md, doc/README.zh_TW.md
Currently there is an invisible white-space that is rendered as a link:
This PR fixes this by keeping the same format as the other links.
=> Fix new badge links on Readme being rendered incorrectly

.github/workflows/ci.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/schabi/newpipe/MainActivity.java, app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt, app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/mediabrowser/PackageValidator.kt, app/src/main/res/values-v35/styles.xml
- Hello. This PR Bumps compileSdk to 36 and targetSdk to 35
- The bulk of the changes are regarding SDK 34 breakages
- Opt out of edge to edge as that is enabled by default in SDK 35
- SDK 36 shouldn't require that much work other than mandatory edge to edge... which would likely require significant code changes (perhaps it would be easier with compose?)
- I encountered a crash by downloading audio and playing it from downloads (Fresh app install, did not touch any settings) 
- Not going to address in this PR as that can be reproduced with the current dev branch
- There shouldn't have been any UI changes
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the …
=> Target SDK 35

app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
#12408 does not fix the underlying issue but tries to handle the symptoms. `nextPage` cannot be `null` when `handleNextItems()` is called, because at that point there is a page that was fetched.
#12408 made it so that is unlikely that error reports are generated. When there was an ExtractionException it is likely that there is no nextPage. The issue is that nextPage is reassigned before generating the error report.
=> Use correct fix for nextPage being null while creating error report

app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java, app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java, app/src/main/java/org/schabi/newpipe/util/Localization.java
Followup of https://github.com/TeamNewPipe/NewPipe/pull/12446
1. Contains some cleanup regarding the PlayerHelper localization and related code, removes dead code, etc.
2. If the language is changed via ContentSettingsFragment, PlayerHelper's formatters will be reset. If formatting is now requested next time it will be reinitialized and the correct format will be applied.
<details><summary>Here's an example</summary>
[Np12470Showcase1.webm](https://github.com/user-attachments/assets/9b6f3734-f192-4466-81f8-a7df6e9f4e20)
</details>
- Fixes #12441 (kind of, was already addressed mostly by https://github.com/TeamNewPipe/NewPipe/pull/12444)
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download …
=> Improve and cleanup PlayerHelper formatters/localization

app/src/main/AndroidManifest.xml, app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationWorker.kt, app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
- Fix foreground notification issue on newer versions of Android.
- Fixes #12564
- Fixes #12553
- Fixes foreground notification issue [reported in #12388](https://github.com/TeamNewPipe/NewPipe/pull/12388#issuecomment-3124021524)
=> Fix foreground service issues

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/PlayerIntentType.kt, app/src/main/java/org/schabi/newpipe/player/PlayerService.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java, app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java, app/src/main/java/org/schabi/newpipe/player/playqueue/SinglePlayQueue.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java, app/src/main/java/org/schabi/newpipe/util/text/InternalUrlsHandler.java, app/src/main/java/org/schabi/newpipe/util/text/TextLinkifier.java, app/src/main/java/org/schabi/newpipe/util/text/TimestampLongPressClickableSpan.java, app/src/main/java/org/schabi/newpipe/util/text/UrlLongPressClickableSpan.java
one extra commit on top of https://github.com/TeamNewPipe/NewPipe/pull/12252
Makes the player stay the same when a timestamp is pressed instead of always opening the popup player.
- Before:
https://github.com/user-attachments/assets/5e270c3e-f023-4219-b768-555490e9391e
- After:
https://github.com/user-attachments/assets/8f87dabb-8a33-417f-ad5a-563781048809
- Fixes #4241
https://github.com/TeamNewPipe/NewPipe/pull/12252
=> Keep current player when clicking on timestamp

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.kt, app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceEventListener.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.kt, app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java, app/src/main/java/org/schabi/newpipe/player/ui/PopupPlayerUi.java, app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java, app/src/main/res/layout/player.xml
Their names must have come from a very old version of the app, they both toggle the fullscreen mode and rotate the screen depending on circumstances.
So `fullscreenButton` -> `fullscreenToggleButtonSecondaryMenu` because it is only visible in the secondary video menu on some configurations and `screenRotationButton` -> `fullscreenToggleButton` because it is the main fullscreen button next to the video progress bar.
=> player.xml: Rename fullscreen buttons & separate enter/exit

app/src/main/java/org/schabi/newpipe/player/Player.java, app/src/main/java/org/schabi/newpipe/player/PlayerIntentType.kt, app/src/main/java/org/schabi/newpipe/player/PlayerType.java, app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
- Refactor the player intent type logic using the `IntentCompat` methods. 
=> Refactor player intent logic

build.gradle, gradle/wrapper/gradle-wrapper.properties
- Update the Android Gradle Plugin to 8.13.0. This is needed due to the compileSdk being updated to 36.
=> Update AGP to 8.13.0

app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
The code was not previously working in case no default browser is set[1] AND NewPipe is set as default handler for the link in question.
We improve it by telling the system to choose the target app as if the URI was `http://`, which makes more sense than expecting a default browser to be set and NewPipe trying to query that.
[1]: also the case if platform refuses to tell an app what the user's default browser is, which I observed on CalyxOS.
For technical reasons we do not add the behavior suggested in https://github.com/TeamNewPipe/NewPipe/issues/9403 as we still mirror the behavior as if `http://` is opened – unfortunately Android does not offer us a _proper_ way to selectively exclude a specific activity (i.e. ourselves) from the target list (see also my `Implementation note` comment …
=> Fix and simplify opening in browser (`openUrlInBrowser`)

app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java, app/src/main/java/org/schabi/newpipe/player/PlayerService.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java, app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
This PR fixes one way ghost notifications could be produced (although I don't know if there are other ways). This is the call chain that would lead to ghost notifications being created:
1. the system starts `PlayerService` to query information from it, without providing `SHOULD_START_FOREGROUND_EXTRA=true`, so NewPipe does not start the player nor show any notification, as expected
2. the `PlayerHolder::serviceConnection.onServiceConnected()` gets called by the system to inform `PlayerHolder` that the player started
3. `PlayerHolder`  notifies `MainActivity` that the player has started (although in fact only the service has started), by sending a `ACTION_PLAYER_STARTED` broadcast
4. `MainActivity` receives the `ACTION_PLAYER_STARTED` broadcast and brings up the mini-player, but then also …
=> Fix ghost notifications

app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java, app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
This one is not required. isUsingDSP is always return true.
=> Remove isUsingDSP
